import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("xmlns:ns2", "http://www.ros.org"), ("name", "eve_r3_head")] [.text "\n    ",
.element "joint" [("name", "j_neck_y"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.00646 0.00085 0.67201"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "pelvis")] [],
.text "\n        ",
.element "child" [("link", "head")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.335"), ("upper", "0.506"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "head")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.02485953 -0.00373226 0.11157957"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "1.84975554")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.01343625"), ("ixy", "-1.5664E-4"), ("ixz", "-0.00146014"), ("iyy", "0.01517256"), ("iyz", "1.7375E-4"), ("izz", "0.00763704")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/head.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [("reference", "head")] [.text "\n\n        ",
.element "sensor" [("type", "depth"), ("name", "kinect_azure")] [.text "\n\n          \n          ",
.element "always_on" [] [.text "0"],
.text "\n\n          \n          ",
.element "update_rate" [] [.text "25"],
.text "\n          ",
.element "pose" [("frame", "")] [.text "0.116669 0 0.17015 0 0.174533 0"],
.text "\n\n          ",
.element "camera" [("name", "camera_name")] [.text "\n            ",
.element "image" [] [.text "\n                ",
.element "width" [] [.text "2048"],
.text "\n                ",
.element "height" [] [.text "1536"],
.text "\n                ",
.element "format" [] [.text "R8G8B8"],
.text "\n            "],
.text "\n            ",
.element "horizontal_fov" [] [.text "1.5708"],
.text "\n            ",
.element "clip" [] [.text "\n                ",
.element "near" [] [.text "0.2"],
.text "\n                ",
.element "far" [] [.text "100"],
.text "\n            "],
.text "\n          "],
.text "\n\n          ",
.element "plugin" [("name", "camera_plugin"), ("filename", "libgazebo_ros_camera.so")] [.text "\n\n             ",
.element "frame_name" [] [.text "kinect_azure_camera_name"],
.text "\n             ",
.element "hack_baseline" [] [.text "0.07"],
.text "\n             ",
.element "min_depth" [] [.text "0.24"],
.text "\n             ",
.element "max_depth" [] [.text "2.88"],
.text "\n          "],
.text "\n        "],
.text "\n    "],
.text "\n\n    \n    \n"],
[],
[],
"2d98b1a4b0ea85250e7840c126f70f35deb1c2fd26df14f0cb770bc9d422a667"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
