import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "iiwa7"), ("xmlns:xacro", "http://www.ros.org/wiki/xacro")] [.text "\n  ",
.element "material" [("name", "Black")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.0 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Blue")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.0 0.8 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Light_blue")] [.text "\n    ",
.element "color" [("rgba", "0.2 0.4 0.8 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Green")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.8 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Grey")] [.text "\n    ",
.element "color" [("rgba", "0.7 0.7 0.7 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Orange")] [.text "\n    ",
.element "color" [("rgba", "1.0 0.4235294117647059 0.0392156862745098 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Brown")] [.text "\n    ",
.element "color" [("rgba", "0.8705882352941177 0.8117647058823529 0.7647058823529411 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "Red")] [.text "\n    ",
.element "color" [("rgba", "0.8 0.0 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "White")] [.text "\n    ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_0")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1 0 0.07")] [],
.text "\n      ",
.element "mass" [("value", "5")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.06"), ("iyz", "0"), ("izz", "0.03")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_0.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_0.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n    ",
.element "self_collision_checking" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.25"), ("radius", "0.15")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "iiwa_joint_1"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_0")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_1")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.15")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-2.9670597283903604"), ("upper", "2.9670597283903604"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-2.9321531433504737"), ("soft_upper_limit", "2.9321531433504737")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.03 0.12")] [],
.text "\n      ",
.element "mass" [("value", "3.4525")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02183"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.007703"), ("iyz", "-0.003887"), ("izz", "0.02083")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0075")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_1.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0075")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_1.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "iiwa_joint_2"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_1")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_2")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966   0 3.141592653589793"), ("xyz", "0 0 0.19")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-2.0943951023931953"), ("upper", "2.0943951023931953"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-2.0594885173533086"), ("soft_upper_limit", "2.0594885173533086")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0003 0.059 0.042")] [],
.text "\n      ",
.element "mass" [("value", "3.4821")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02076"), ("ixy", "0"), ("ixz", "-0.003626"), ("iyy", "0.02179"), ("iyz", "0"), ("izz", "0.00779")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Orange")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "iiwa_joint_3"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_2")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_3")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 3.141592653589793"), ("xyz", "0 0.21 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-2.9670597283903604"), ("upper", "2.9670597283903604"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-2.9321531433504737"), ("soft_upper_limit", "2.9321531433504737")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_3")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.03 0.13")] [],
.text "\n      ",
.element "mass" [("value", "4.05623")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.03204"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00972"), ("iyz", "0.006227"), ("izz", "0.03042")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.026")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_3.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.026")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_3.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "iiwa_joint_4"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_3")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_4")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0.19")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-2.0943951023931953"), ("upper", "2.0943951023931953"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-2.0594885173533086"), ("soft_upper_limit", "2.0594885173533086")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_4")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.067 0.034")] [],
.text "\n      ",
.element "mass" [("value", "3.4822")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02178"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.02075"), ("iyz", "-0.003625"), ("izz", "0.007785")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_4.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_4.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Orange")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "iiwa_joint_5"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_4")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_5")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0.21 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-2.9670597283903604"), ("upper", "2.9670597283903604"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-2.9321531433504737"), ("soft_upper_limit", "2.9321531433504737")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_5")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0001 0.021 0.076")] [],
.text "\n      ",
.element "mass" [("value", "2.1633")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01287"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.005708"), ("iyz", "-0.003946"), ("izz", "0.01112")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.026")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_5.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.026")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_5.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "iiwa_joint_6"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_5")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_6")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.06070 0.19")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-2.0943951023931953"), ("upper", "2.0943951023931953"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-2.0594885173533086"), ("soft_upper_limit", "2.0594885173533086")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_6")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.0006 0.0004")] [],
.text "\n      ",
.element "mass" [("value", "2.3466")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.006509"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.006259"), ("iyz", "0.00031891"), ("izz", "0.004527")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_6.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_6.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Orange")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "iiwa_joint_7"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_6")] [],
.text "\n    ",
.element "child" [("link", "iiwa_link_7")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0.081 0.06070")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-3.0543261909900763"), ("upper", "3.0543261909900763"), ("velocity", "10")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "100"), ("k_velocity", "2"), ("soft_lower_limit", "-3.01941960595019"), ("soft_upper_limit", "3.01941960595019")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.5")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "iiwa_link_7")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.02")] [],
.text "\n      ",
.element "mass" [("value", "3.129")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01464"), ("ixy", "0.0005912"), ("ixz", "0"), ("iyy", "0.01465"), ("iyz", "0"), ("izz", "0.002872")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0005")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/visual/link_7.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0005")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/iiwa7/collision/link_7.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "Grey")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "iiwa_joint_ee"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "iiwa_link_7")] [],
.text "\n    ",
.element "child" [("link", "palm_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.145")] [],
.text "\n  "],
.text "\n  \n  \n  \n  \n  \n  \n  \n  \n  ",
.element "link" [("name", "palm_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/base_link_left.STL")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "-1.5707963259 0 0"), ("xyz", "0 0 0 ")] [],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.2 0.2 0.2 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.009300 0 -0.0475")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0408 0.1130 0.095")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0475")] [],
.text "\n      ",
.element "mass" [("value", "0.4154")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-4"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-4"), ("iyz", "0.0"), ("izz", "1e-4")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  \n  \n  \n  ",
.element "link" [("name", "link_8.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_0.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0164")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0082")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0119")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.01666658333e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "6.47677333333e-07"), ("iyz", "0.0"), ("izz", "1.01666658333e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_8.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.47"), ("upper", "0.47"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "palm_link")] [],
.text "\n    ",
.element "child" [("link", "link_8.0")] [],
.text "\n    ",
.element "origin" [("rpy", "-0.08726646255 0 0"), ("xyz", "0 0.0435 -0.001542")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_9.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_1.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.054")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.027")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.065")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.95654166667e-05"), ("ixy", "1.7199e-05"), ("ixz", "8.75875e-06"), ("iyy", "2.47088833333e-05"), ("iyz", "2.413125e-05"), ("izz", "7.95654166667e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_9.0"), ("type", "revolute")] [.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.196"), ("upper", "1.61"), ("velocity", "7")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "link_8.0")] [],
.text "\n    ",
.element "child" [("link", "link_9.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0164")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "5")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_10.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_2.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0384")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0192")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0355")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.63979183333e-05"), ("ixy", "6.67968e-06"), ("ixz", "4.783625e-06"), ("iyy", "1.34948516667e-05"), ("iyz", "9.372e-06"), ("izz", "2.63979183333e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_10.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.174"), ("upper", "1.709"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_9.0")] [],
.text "\n    ",
.element "child" [("link", "link_10.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.054")] [],
.text "\n    ",
.element "dynamics" [("damping", "8"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_11.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_3.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0267")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01335")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0096")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.701248e-06"), ("ixy", "1.255968e-06"), ("ixz", "1.2936e-06"), ("iyy", "3.649312e-06"), ("iyz", "1.7622e-06"), ("izz", "4.701248e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_11.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.227"), ("upper", "1.618"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_10.0")] [],
.text "\n    ",
.element "child" [("link", "link_11.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0384")] [],
.text "\n    ",
.element "dynamics" [("damping", "10"), ("friction", "12")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_11.0_tip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_3.0_tip.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", ".9 .9 .9 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.012")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0168")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.68e-07"), ("ixy", "0"), ("ixz", "0"), ("iyy", "9.68e-07"), ("iyz", "0"), ("izz", "9.68e-07")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_11.0_tip"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "link_11.0")] [],
.text "\n    ",
.element "child" [("link", "link_11.0_tip")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0267")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_4.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_0.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0164")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0082")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0119")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.01666658333e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "6.47677333333e-07"), ("iyz", "0.0"), ("izz", "1.01666658333e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_4.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.47"), ("upper", "0.47"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "palm_link")] [],
.text "\n    ",
.element "child" [("link", "link_4.0")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0.0007")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_5.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_1.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.054")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.027")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.065")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.95654166667e-05"), ("ixy", "1.7199e-05"), ("ixz", "8.75875e-06"), ("iyy", "2.47088833333e-05"), ("iyz", "2.413125e-05"), ("izz", "7.95654166667e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_5.0"), ("type", "revolute")] [.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.196"), ("upper", "1.61"), ("velocity", "7")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "link_4.0")] [],
.text "\n    ",
.element "child" [("link", "link_5.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0164")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "5")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_6.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_2.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0384")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0192")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0355")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.63979183333e-05"), ("ixy", "6.67968e-06"), ("ixz", "4.783625e-06"), ("iyy", "1.34948516667e-05"), ("iyz", "9.372e-06"), ("izz", "2.63979183333e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_6.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.174"), ("upper", "1.709"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_5.0")] [],
.text "\n    ",
.element "child" [("link", "link_6.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.054")] [],
.text "\n    ",
.element "dynamics" [("damping", "8"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_7.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_3.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0267")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01335")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0096")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.701248e-06"), ("ixy", "1.255968e-06"), ("ixz", "1.2936e-06"), ("iyy", "3.649312e-06"), ("iyz", "1.7622e-06"), ("izz", "4.701248e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_7.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.227"), ("upper", "1.618"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_6.0")] [],
.text "\n    ",
.element "child" [("link", "link_7.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0384")] [],
.text "\n    ",
.element "dynamics" [("damping", "10"), ("friction", "12")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_7.0_tip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_3.0_tip.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", ".9 .9 .9 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.012")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0168")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.68e-07"), ("ixy", "0"), ("ixz", "0"), ("iyy", "9.68e-07"), ("iyz", "0"), ("izz", "9.68e-07")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_7.0_tip"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "link_7.0")] [],
.text "\n    ",
.element "child" [("link", "link_7.0_tip")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0267")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_0.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_0.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0164")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0082")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0119")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.01666658333e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "6.47677333333e-07"), ("iyz", "0.0"), ("izz", "1.01666658333e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_0.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.47"), ("upper", "0.47"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "palm_link")] [],
.text "\n    ",
.element "child" [("link", "link_0.0")] [],
.text "\n    ",
.element "origin" [("rpy", "0.08726646255 0 0"), ("xyz", "0 -0.0435 -0.001542")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_1.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_1.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.054")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.027")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.065")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.95654166667e-05"), ("ixy", "1.7199e-05"), ("ixz", "8.75875e-06"), ("iyy", "2.47088833333e-05"), ("iyz", "2.413125e-05"), ("izz", "7.95654166667e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_1.0"), ("type", "revolute")] [.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.196"), ("upper", "1.61"), ("velocity", "7")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "link_0.0")] [],
.text "\n    ",
.element "child" [("link", "link_1.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0164")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "5")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_2.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_2.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0384")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0192")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0355")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.63979183333e-05"), ("ixy", "6.67968e-06"), ("ixz", "4.783625e-06"), ("iyy", "1.34948516667e-05"), ("iyz", "9.372e-06"), ("izz", "2.63979183333e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_2.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.174"), ("upper", "1.709"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_1.0")] [],
.text "\n    ",
.element "child" [("link", "link_2.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.054")] [],
.text "\n    ",
.element "dynamics" [("damping", "8"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_3.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_3.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0267")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01335")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0096")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.701248e-06"), ("ixy", "1.255968e-06"), ("ixz", "1.2936e-06"), ("iyy", "3.649312e-06"), ("iyz", "1.7622e-06"), ("izz", "4.701248e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_3.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.227"), ("upper", "1.618"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_2.0")] [],
.text "\n    ",
.element "child" [("link", "link_3.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0384")] [],
.text "\n    ",
.element "dynamics" [("damping", "10"), ("friction", "12")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_3.0_tip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_3.0_tip.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", ".9 .9 .9 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.012")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0168")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.68e-07"), ("ixy", "0"), ("ixz", "0"), ("iyy", "9.68e-07"), ("iyz", "0"), ("izz", "9.68e-07")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_3.0_tip"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "link_3.0")] [],
.text "\n    ",
.element "child" [("link", "link_3.0_tip")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0267")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "link_12.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_12.0_left.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", ".2 .2 .2 1")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "3.1415926518 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0358 0.034 0.0455")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0179 -0.009 0.0145")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0176")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.89273333333e-5"), ("ixy", "7.16716e-06"), ("ixz", "5.35568e-06"), ("iyy", "1.43008213333e-05"), ("iyz", "6.8068e-06"), ("izz", "1.89273333333e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_12.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "+1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "0.263"), ("upper", "1.396"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "palm_link")] [],
.text "\n    ",
.element "child" [("link", "link_12.0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 -1.65806278845 1.5707963259"), ("xyz", "-0.0182 -0.019333 -0.045987")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_13.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_13.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", ".2 .2 .2 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0177")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.00885")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0119")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.24250866667e-06"), ("ixy", "1.032087e-06"), ("ixz", "1.603525e-06"), ("iyy", "4.52362633333e-06"), ("iyz", "1.44808125e-06"), ("izz", "4.24250866667e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_13.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.105"), ("upper", "1.163"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_12.0")] [],
.text "\n    ",
.element "child" [("link", "link_13.0")] [],
.text "\n    ",
.element "origin" [("xyz", "-0.027 -0.005 0.0399")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "5")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_14.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_14.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n                "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0514")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0257")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.038")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.30439933333e-05"), ("ixy", "9.57068e-06"), ("ixz", "5.1205e-06"), ("iyy", "1.44451933333e-05"), ("iyz", "1.342825e-05"), ("izz", "4.30439933333e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_14.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.189"), ("upper", "1.644"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_13.0")] [],
.text "\n    ",
.element "child" [("link", "link_14.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0177")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "10")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_15.0")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_15.0.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n                "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0196 0.0275 0.0423")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.02115")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0388")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.29223173333e-05"), ("ixy", "8.042076e-06"), ("ixz", "5.2283e-06"), ("iyy", "1.47493026667e-5"), ("iyz", "1.1283525e-5"), ("izz", "3.29223173333e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_15.0"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "15"), ("lower", "-0.162"), ("upper", "1.719"), ("velocity", "7")] [],
.text "\n    ",
.element "parent" [("link", "link_14.0")] [],
.text "\n    ",
.element "child" [("link", "link_15.0")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0.0514")] [],
.text "\n    ",
.element "dynamics" [("damping", "3"), ("friction", "12")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "link_15.0_tip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "../../allegro/meshes/link_15.0_tip.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", ".9 .9 .9 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.012")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0168")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.68e-07"), ("ixy", "0"), ("ixz", "0"), ("iyy", "9.68e-07"), ("iyz", "0"), ("izz", "9.68e-07")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint_15.0_tip"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "link_15.0")] [],
.text "\n    ",
.element "child" [("link", "link_15.0_tip")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0423")] [],
.text "\n  "],
.text "\n  \n  \n  \n  \n  \n  \n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_control.so"), ("name", "gazebo_ros_control")] [.text "\n      ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_0")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Grey"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_1")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_2")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_3")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_4")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_5")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_6")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "iiwa_link_7")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Grey"],
.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_1")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_2")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_2")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_2")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_3")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_3")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_3")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_4")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_4")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_4")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_5")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_5")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_5")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_6")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_6")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_6")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "iiwa_tran_7")] [.text "\n    ",
.element "robotNamespace" [] [.text "/iiwa"],
.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "iiwa_joint_7")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "iiwa_motor_7")] [.text "\n      ",
.element "hardwareInterface" [] [.text "PositionJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"d1b38837565a1c6ef8393a64ce136a81cbaf2fad492e68109c106708777f8acf"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
