import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("xmlns:ns2", "http://www.ros.org"), ("name", "eve_r3_leg")] [.text "\n    ",
.element "link" [("name", "pelvis")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.02071479 -0.00544353 0.4100644"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "10.12075049")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.2085075"), ("ixy", "8.581E-4"), ("ixz", "0.02176178"), ("iyy", "0.20882646"), ("iyz", "-0.00715583"), ("izz", "0.05515818")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/torso.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_hip_z"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "pelvis")] [],
.text "\n        ",
.element "child" [("link", "abdomen")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.0472"), ("upper", "1.0472"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "abdomen")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.055941 0.001616 0.129607"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "3.429553")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.055816"), ("ixy", "6.93E-4"), ("ixz", "-0.014517"), ("iyy", "0.054022"), ("iyz", "-0.001917"), ("izz", "0.020076")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/abdomen.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_hip_x"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "abdomen")] [],
.text "\n        ",
.element "child" [("link", "hip_x_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.523599"), ("upper", "0.523599"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "hip_x_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.01325838 -0.00134592 -2.24E-6"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "2.94819561")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.01418919"), ("ixy", "6.936E-5"), ("ixz", "-7.734E-4"), ("iyy", "0.01504315"), ("iyz", "1.297E-5"), ("izz", "0.0170189")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/hip.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_hip_y"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "hip_x_link")] [],
.text "\n        ",
.element "child" [("link", "thigh")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.57"), ("upper", "0.174533"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "thigh")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.04235221 1.7272E-4 -0.21689828"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "10.80882706")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.1632404"), ("ixy", "2.6721E-4"), ("ixz", "0.01548511"), ("iyy", "0.14491867"), ("iyz", "-0.00115905"), ("izz", "0.06656334")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/thigh.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_knee_y"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.4"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "thigh")] [],
.text "\n        ",
.element "child" [("link", "shin")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "0.0"), ("upper", "2.583"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "shin")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0177422 0.00453439 -0.17886128"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "11.06513851")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.22300589"), ("ixy", "3.9863E-4"), ("ixz", "0.00421073"), ("iyy", "0.20307232"), ("iyz", "0.00715001"), ("izz", "0.05977916")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/shin.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_ankle_y"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.38"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "shin")] [],
.text "\n        ",
.element "child" [("link", "ankle_y_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.57"), ("upper", "0.174533"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "ankle_y_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.017472 0.001483 -6.81E-4"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "2.742145")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.010787"), ("ixy", "-9.0E-5"), ("ixz", "2.71E-4"), ("iyy", "0.009295"), ("iyz", "9.0E-6"), ("izz", "0.014432")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/ankle.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_ankle_x"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "ankle_y_link")] [],
.text "\n        ",
.element "child" [("link", "base")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.523599"), ("upper", "0.523599"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "base")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.005001 0.002979 -0.007684"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "12.487535")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.330887"), ("ixy", "0.005202"), ("ixz", "-0.015354"), ("iyy", "0.233226"), ("iyz", "-3.7E-5"), ("izz", "0.532943")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/base.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.284 0.0 0.019000"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.1524")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_l_wheel_y"), ("type", "continuous")] [.text "\n        ",
.element "origin" [("xyz", "0.142 0.26983 0.019"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "l_wheel")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.0E16"), ("upper", "1.0E16"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_wheel")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "1.45E-6 -0.00487572 -1.4137E-4"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "2.17850874")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0042794"), ("ixy", "-1.22E-6"), ("ixz", "-7.84E-6"), ("iyy", "0.0074513"), ("iyz", "-5.69E-6"), ("izz", "0.00423463")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 -1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/wheel.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.03"), ("radius", "0.1524")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_r_wheel_y"), ("type", "continuous")] [.text "\n        ",
.element "origin" [("xyz", "0.142 -0.26983 0.019"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "r_wheel")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.0E16"), ("upper", "1.0E16"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_wheel")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-1.45E-6 0.00487572 -1.4137E-4"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "2.17850874")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0042794"), ("ixy", "-1.22E-6"), ("ixz", "7.84E-6"), ("iyy", "0.0074513"), ("iyz", "5.69E-6"), ("izz", "0.00423463")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/wheel.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.03"), ("radius", "0.1524")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "pelvis")] [.text "\n        ",
.element "sensor" [("name", "pelvis_imu_sensor"), ("type", "imu")] [.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n            ",
.element "update_rate" [] [.text "1000"],
.text "\n            ",
.element "imu" [] [.text "\n                ",
.element "noise" [] [.text "\n                    ",
.element "type" [] [.text "gaussian"],
.text "\n                    ",
.element "rate" [] [.text "\n                        ",
.element "mean" [] [.text "0"],
.text "\n                        ",
.element "stddev" [] [.text "0.0022"],
.text "\n                        ",
.element "bias_mean" [] [.text "0.0035"],
.text "\n                        ",
.element "bias_stddev" [] [.text "0.001"],
.text "\n\t            "],
.text "\n                    ",
.element "accel" [] [.text "\n                        ",
.element "mean" [] [.text "0"],
.text "\n                        ",
.element "stddev" [] [.text "0.031"],
.text "\n                        ",
.element "bias_mean" [] [.text "0.006"],
.text "\n                        ",
.element "bias_stddev" [] [.text "0.001"],
.text "\n\t            "],
.text "\n\t          "],
.text "\n\t        "],
.text "\n            ",
.element "pose" [("frame", "")] [.text "-0.057 0.0 0.39790 0 0.0 0"],
.text "\n\t      "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "base")] [.text "\n        ",
.element "sensor" [("name", "base_imu_left"), ("type", "imu")] [.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n            ",
.element "update_rate" [] [.text "1000"],
.text "\n            ",
.element "imu" [] [.text "\n                ",
.element "noise" [] [.text "\n                    ",
.element "type" [] [.text "gaussian"],
.text "\n                    ",
.element "rate" [] [.text "\n                        ",
.element "mean" [] [.text "0"],
.text "\n                        ",
.element "stddev" [] [.text "0.0022"],
.text "\n                        ",
.element "bias_mean" [] [.text "0.0174533"],
.text "\n                        ",
.element "bias_stddev" [] [.text "0.0001"],
.text "\n\t            "],
.text "\n                    ",
.element "accel" [] [.text "\n                        ",
.element "mean" [] [.text "0"],
.text "\n                        ",
.element "stddev" [] [.text "0.031"],
.text "\n                        ",
.element "bias_mean" [] [.text "0.012"],
.text "\n                        ",
.element "bias_stddev" [] [.text "0.001"],
.text "\n\t            "],
.text "\n\t          "],
.text "\n\t        "],
.text "\n            ",
.element "pose" [("frame", "")] [.text "0.23412 0.1925 0.013 0 0.0 0"],
.text "\n\t      "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "base")] [.text "\n        ",
.element "mu1" [] [.text "0.0"],
.text "\n        ",
.element "mu2" [] [.text "0.0"],
.text "\n    "],
.text "\n"],
[],
[],
"c6251b04c080e9520dc718e07604e07e4734a556d56ba5d3e67dbbbb1d5d86d5"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
