import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "elf2_dof25")] [.text "\n  ",
.element "link" [("name", "base_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00030047 8.28e-06 0.03546793"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "3.24038695")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02280423"), ("ixy", "3.8e-07"), ("ixz", "-1.083e-05"), ("iyy", "0.00335281"), ("iyz", "1.75e-06"), ("izz", "0.02410611")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/base_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.75294 0.75294 0.75294 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/base_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hip_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.0951743 -0.00029544 0.01157699"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.26002534")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00250858"), ("ixy", "-1.87e-05"), ("ixz", "-0.00093719"), ("iyy", "0.00299504"), ("iyz", "6.14e-06"), ("izz", "0.00188897")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_hip_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_hip_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_hip_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0.1 -0.1008"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "l_hip_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "20"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hip_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00349545 -0.05016077 0.00015601"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.75826055")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00145734"), ("ixy", "0.000276"), ("ixz", "2.571e-05"), ("iyy", "0.00183603"), ("iyz", "-4e-08"), ("izz", "0.00181117")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_hip_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_hip_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_hip_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hip_z_link")] [],
.text "\n    ",
.element "child" [("link", "l_hip_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.523"), ("upper", "0.785"), ("effort", "40"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hip_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00237237 0.02408075 -0.04874487"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2.66296335")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02678784"), ("ixy", "0.00016594"), ("ixz", "0.00075939"), ("iyy", "0.02619934"), ("iyz", "-0.00371457"), ("izz", "0.0045187")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_hip_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_hip_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_hip_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hip_x_link")] [],
.text "\n    ",
.element "child" [("link", "l_hip_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2"), ("upper", "1"), ("effort", "100"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_knee_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00711393 -0.00031499 -0.10977806"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.63072153")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01042782"), ("ixy", "1.62e-06"), ("ixz", "-0.00054999"), ("iyy", "0.01018545"), ("iyz", "-0.00015956"), ("izz", "0.00140744")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_knee_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_knee_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_knee_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hip_y_link")] [],
.text "\n    ",
.element "child" [("link", "l_knee_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "2.355"), ("effort", "120"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_ankle_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0 0.0 -0.00046563"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.01206963")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.89e-06"), ("ixy", "-0.0"), ("ixz", "-0.0"), ("iyy", "3.4e-07"), ("iyz", "-0.0"), ("izz", "3.01e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_ankle_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_ankle_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_ankle_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_knee_y_link")] [],
.text "\n    ",
.element "child" [("link", "l_ankle_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2"), ("upper", "2"), ("effort", "12"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_ankle_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00088171 0.0 -0.02245193"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.27064154")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00014549"), ("ixy", "-0.0"), ("ixz", "5.53e-06"), ("iyy", "0.00071745"), ("iyz", "-0.0"), ("izz", "0.00081666")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_ankle_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_ankle_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_ankle_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_ankle_y_link")] [],
.text "\n    ",
.element "child" [("link", "l_ankle_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.349"), ("upper", "0.349"), ("effort", "6"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hip_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.0951743 0.00029543 0.01157699"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.26002506")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00250858"), ("ixy", "1.87e-05"), ("ixz", "-0.00093719"), ("iyy", "0.00299504"), ("iyz", "-6.14e-06"), ("izz", "0.00188897")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_hip_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_hip_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_hip_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 -0.1 -0.1008"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "r_hip_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "20"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hip_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00349545 0.05016077 0.000156"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.75825984")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00145734"), ("ixy", "-0.000276"), ("ixz", "2.571e-05"), ("iyy", "0.00183603"), ("iyz", "4e-08"), ("izz", "0.00181117")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_hip_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_hip_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_hip_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hip_z_link")] [],
.text "\n    ",
.element "child" [("link", "r_hip_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.523"), ("effort", "40"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hip_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00237237 -0.02408076 -0.04874488"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2.66296401")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02678786"), ("ixy", "-0.00016594"), ("ixz", "0.00075939"), ("iyy", "0.02619935"), ("iyz", "0.00371458"), ("izz", "0.0045187")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_hip_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_hip_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_hip_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hip_x_link")] [],
.text "\n    ",
.element "child" [("link", "r_hip_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2"), ("upper", "1"), ("effort", "100"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_knee_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00711396 0.00031502 -0.109778"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.63072158")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01042781"), ("ixy", "-1.62e-06"), ("ixz", "-0.00054998"), ("iyy", "0.01018544"), ("iyz", "0.00015955"), ("izz", "0.00140744")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_knee_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_knee_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_knee_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hip_y_link")] [],
.text "\n    ",
.element "child" [("link", "r_knee_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "2.355"), ("effort", "120"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_ankle_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0 0.0 -0.00046563"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.01206963")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.89e-06"), ("ixy", "-0.0"), ("ixz", "-0.0"), ("iyy", "3.4e-07"), ("iyz", "-0.0"), ("izz", "3.01e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_ankle_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_ankle_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_ankle_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_knee_y_link")] [],
.text "\n    ",
.element "child" [("link", "r_ankle_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2"), ("upper", "2"), ("effort", "12"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_ankle_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00088171 0.0 -0.02245193"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.27064154")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00014549"), ("ixy", "-0.0"), ("ixz", "5.53e-06"), ("iyy", "0.00071745"), ("iyz", "-0.0"), ("izz", "0.00081666")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_ankle_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_ankle_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_ankle_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_ankle_y_link")] [],
.text "\n    ",
.element "child" [("link", "r_ankle_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.349"), ("upper", "0.349"), ("effort", "6"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "waist_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00448944 0.0 -0.02389195"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.21792014")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.089e-05"), ("ixy", "-0.0"), ("ixz", "3.456e-05"), ("iyy", "0.0001491"), ("iyz", "-0.0"), ("izz", "0.00013001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/waist_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/waist_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "waist_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0.1167"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "waist_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-1.57"), ("upper", "1.57"), ("effort", "40"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "waist_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.05316739")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.7e-06"), ("ixy", "-0.0"), ("ixz", "-0.0"), ("iyy", "9.7e-06"), ("iyz", "-0.0"), ("izz", "1.819e-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/waist_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/waist_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "waist_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "waist_z_link")] [],
.text "\n    ",
.element "child" [("link", "waist_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.262"), ("upper", "0.262"), ("effort", "50"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "waist_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00308477 0.00223688 0.1873963"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "8.1645757")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.12637158"), ("ixy", "-0.00018869"), ("ixz", "-0.0005031"), ("iyy", "0.08145202"), ("iyz", "-0.00060193"), ("izz", "0.06836301")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/waist_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/waist_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "waist_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "waist_x_link")] [],
.text "\n    ",
.element "child" [("link", "waist_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.523"), ("upper", "0.523"), ("effort", "50"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_shld_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00068297 -0.00449372 2.22e-06"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.53804971")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00030648"), ("ixy", "4.03e-06"), ("ixz", "2e-08"), ("iyy", "0.00029153"), ("iyz", "1e-07"), ("izz", "0.00032312")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_shld_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_shld_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_shld_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0.21705 0.30075"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "waist_y_link")] [],
.text "\n    ",
.element "child" [("link", "l_shld_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2"), ("upper", "2"), ("effort", "27"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_shld_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-2.047e-05 5.316e-05 -0.06162654"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.48847489")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00027194"), ("ixy", "4e-08"), ("ixz", "-5.4e-07"), ("iyy", "0.00033709"), ("iyz", "-5.4e-07"), ("izz", "0.0002884")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_shld_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_shld_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_shld_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_shld_y_link")] [],
.text "\n    ",
.element "child" [("link", "l_shld_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-0.5"), ("upper", "1.57"), ("effort", "27"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_shld_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "4.164e-05 0.00022669 -0.2212782"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.59309528")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00136573"), ("ixy", "5.3e-07"), ("ixz", "-1e-08"), ("iyy", "0.00133989"), ("iyz", "1.22e-06"), ("izz", "0.00030342")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_shld_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_shld_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_shld_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_shld_x_link")] [],
.text "\n    ",
.element "child" [("link", "l_shld_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "7"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_elb_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "5.192e-05 1.999e-05 -0.08561189"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.50005725")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00043713"), ("ixy", "-4e-08"), ("ixz", "-4.9e-07"), ("iyy", "0.00036043"), ("iyz", "6.3e-07"), ("izz", "0.00030266")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_elb_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_elb_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_elb_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.24"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_shld_z_link")] [],
.text "\n    ",
.element "child" [("link", "l_elb_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2.355"), ("upper", "0.5"), ("effort", "27"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_elb_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "1.97e-06 -1.756e-05 -0.18282539"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.13457416")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00040001"), ("ixy", "-0.0"), ("ixz", "-2e-08"), ("iyy", "0.00039996"), ("iyz", "1.5e-07"), ("izz", "5.662e-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_elb_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/l_elb_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_elb_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_elb_y_link")] [],
.text "\n    ",
.element "child" [("link", "l_elb_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "7"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_shld_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00068297 0.00449372 -2.22e-06"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.53804971")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00030648"), ("ixy", "-4.03e-06"), ("ixz", "-2e-08"), ("iyy", "0.00029153"), ("iyz", "1e-07"), ("izz", "0.00032312")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_shld_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_shld_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_shld_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 -0.21705 0.30075"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "waist_y_link")] [],
.text "\n    ",
.element "child" [("link", "r_shld_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2"), ("upper", "2"), ("effort", "27"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_shld_x_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "2.047e-05 -5.316e-05 -0.06162654"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.48847489")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00027194"), ("ixy", "4e-08"), ("ixz", "5.4e-07"), ("iyy", "0.00033709"), ("iyz", "5.4e-07"), ("izz", "0.0002884")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_shld_x_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_shld_x_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_shld_x_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_shld_y_link")] [],
.text "\n    ",
.element "child" [("link", "r_shld_x_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "-1.57"), ("upper", "0.5"), ("effort", "27"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_shld_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-4.164e-05 -0.00022669 -0.2212782"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.59309528")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00136573"), ("ixy", "5.3e-07"), ("ixz", "1e-08"), ("iyy", "0.00133989"), ("iyz", "-1.22e-06"), ("izz", "0.00030342")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_shld_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_shld_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_shld_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_shld_x_link")] [],
.text "\n    ",
.element "child" [("link", "r_shld_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "7"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_elb_y_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-5.192e-05 -1.999e-05 -0.08561189"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.50005725")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00043713"), ("ixy", "-4e-08"), ("ixz", "4.9e-07"), ("iyy", "0.00036043"), ("iyz", "-6.3e-07"), ("izz", "0.00030266")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_elb_y_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_elb_y_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_elb_y_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.24"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_shld_z_link")] [],
.text "\n    ",
.element "child" [("link", "r_elb_y_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("lower", "-2.355"), ("upper", "0.5"), ("effort", "27"), ("velocity", "20")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_elb_z_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-1.97e-06 1.756e-05 -0.18282539"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.13457416")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00040001"), ("ixy", "-0.0"), ("ixz", "2e-08"), ("iyy", "0.00039996"), ("iyz", "-1.5e-07"), ("izz", "5.662e-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_elb_z_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/r_elb_z_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_elb_z_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_elb_y_link")] [],
.text "\n    ",
.element "child" [("link", "r_elb_z_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "7"), ("velocity", "20")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "logo_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/logo_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "logo_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.068 -0.025 0.07")] [],
.text "\n    ",
.element "parent" [("link", "waist_y_link")] [],
.text "\n    ",
.element "child" [("link", "logo_link")] [],
.text "\n  "],
.text "\n"],
[],
[],
"d7a04ca245b606bba8c11dbe726aaeeaa692924663e7d135eefb3f3af9fb8bb9"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
