import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "qbhand_left"), ("xmlns:xacro", "http://www.ros.org/wiki/xacro")] [.text "\n  ",
.element "joint" [("name", "qbhand_left_base_fixed_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.14 0 0.0"), ("xyz", "0 0 -0.06")] [],
.text "\n    ",
.element "parent" [("link", "l_palm")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_base_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_base_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.15")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0.0015")] [],
.text "\n      ",
.element "inertia" [("ixx", "6e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "6e-05"), ("iyz", "0"), ("izz", "9e-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/flange_iso_04.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/flange_iso_04.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_palm_fixed_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57 0 3.14"), ("xyz", "0.0045 0.0145 0.144")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_base_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_palm_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_palm_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.36")] [],
.text "\n      ",
.element "origin" [("xyz", "0.0 0.02 0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00045"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0006"), ("iyz", "0.0"), ("izz", "0.00025")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/palm_pinch_l.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/palm_pinch_l.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_synergy_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_palm_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_tendon_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "1.0"), ("velocity", "100")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_tendon_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_thumb_knuckle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57 3.14 0"), ("xyz", "-0.0435 -0.0435 -0.002")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_palm_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_thumb_knuckle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "1.571"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "2.542")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_thumb_knuckle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_thumb_l.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_thumb_l.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_thumb_proximal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.15 0.0 0.0"), ("xyz", "0.0255 -0.004 0.0025")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_thumb_knuckle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_thumb_proximal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_thumb_proximal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_thumb_proximal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_thumb_proximal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_thumb_proximal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_thumb_proximal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_thumb_proximal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_thumb_distal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.009 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_thumb_proximal_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_thumb_distal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_thumb_distal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_thumb_distal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_thumb_distal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_thumb_distal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_thumb_distal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_thumb_distal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_knuckle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 3.14 0"), ("xyz", "-0.02 -0.007 -0.014")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_palm_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_knuckle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.524"), ("upper", "0.524"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.2")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_knuckle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_proximal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57 0 1.57"), ("xyz", "0 0.009 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_index_knuckle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_proximal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_proximal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_proximal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_index_proximal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_proximal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_index_proximal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_proximal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_medium.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_medium.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_middle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.017 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_index_proximal_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_middle_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_middle_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_middle_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_index_middle_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_middle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_index_middle_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_middle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_distal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.009 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_index_middle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_distal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_distal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_index_distal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_index_distal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_index_distal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_index_distal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_index_distal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_knuckle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 3.14 0"), ("xyz", "0 0 -0.014")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_palm_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_knuckle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.524"), ("upper", "0.524"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_knuckle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_proximal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57 0 1.57"), ("xyz", "0 0.009 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_middle_knuckle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_proximal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_proximal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_proximal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_middle_proximal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_proximal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_middle_proximal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_proximal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_medium.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_medium.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_middle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.017 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_middle_proximal_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_middle_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_middle_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_middle_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_middle_middle_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_middle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_middle_middle_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_middle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_distal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.009 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_middle_middle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_distal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_distal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_middle_distal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_middle_distal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_middle_distal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_middle_distal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_middle_distal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_knuckle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 3.14 0"), ("xyz", "0.02 -0.007 -0.014")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_palm_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_knuckle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.524"), ("upper", "0.524"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "-0.2")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_knuckle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_proximal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57 0 1.57"), ("xyz", "0 0.009 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_ring_knuckle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_proximal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_proximal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_proximal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_ring_proximal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_proximal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_ring_proximal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_proximal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_medium.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_medium.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_middle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.017 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_ring_proximal_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_middle_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_middle_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_middle_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_ring_middle_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_middle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_ring_middle_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_middle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_distal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.009 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_ring_middle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_distal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_distal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_ring_distal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_ring_distal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_ring_distal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_ring_distal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_ring_distal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_knuckle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 3.14 0"), ("xyz", "0.04 -0.012 -0.014")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_palm_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_knuckle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.524"), ("upper", "0.524"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "-0.4")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_knuckle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_knuckle.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_proximal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57 0 1.57"), ("xyz", "0 0.009 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_little_knuckle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_proximal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_proximal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_proximal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_little_proximal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_proximal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_little_proximal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_proximal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_middle_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.009 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_little_proximal_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_middle_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_middle_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_middle_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_little_middle_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_middle_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_little_middle_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_middle_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_small.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_distal_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.009 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_little_middle_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_distal_virtual_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_synergy_joint"), ("multiplier", "0.785")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_distal_virtual_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-08"), ("iyz", "0.0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "qbhand_left_little_distal_virtual_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.013 0 0")] [],
.text "\n    ",
.element "parent" [("link", "qbhand_left_little_distal_virtual_link")] [],
.text "\n    ",
.element "child" [("link", "qbhand_left_little_distal_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "0.0"), ("upper", "0.785"), ("velocity", "100")] [],
.text "\n    ",
.element "mimic" [("joint", "qbhand_left_little_distal_joint"), ("multiplier", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "qbhand_left_little_distal_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.005")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1e-06"), ("iyz", "0.0"), ("izz", "1e-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://qb_hand_description/meshes/ph_distal.obj"), ("scale", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"65776fb3ae3870b8b9c369083721e88c6fce3ae50042c743aa08c4ca9deaba7c"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
