import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "Perseverance")] [.text "\n\t",
.element "link" [("name", "ground")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_Chassis")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_CHASSIS")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.09002 0 -1.13338"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/CHASSIS.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_CHASSIS")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.09002 0 -1.13338"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/CHASSIS.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_MHS_DebrisShield")] [.text "\n\t\t\n\t"],
.text "\n\t",
.element "link" [("name", "Body_Differential")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_CenterDifferential")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.142 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/CenterDifferential.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RockerLeft")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Left_Rocker")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-0.214 0.79959 -0.2405"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Left_Rocker.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_BogieLeft")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Left_Bogie")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.54 0.91959 -0.4705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Left_Bogie.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_SteerLeftRear")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Steer_LeftRear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "1.165 1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Steer_LeftRear.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WheelLeftRear")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Wheel_LeftRear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "1.165 1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_LeftRear.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Wheel_LeftRear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "1.165 1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_LeftRear.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WheelLeftMiddle")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Wheel_LeftMiddle")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.09002 1.1845 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_LeftMiddle.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Wheel_LeftMiddle")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.09002 1.1845 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_LeftMiddle.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_SteerLeftFront")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Steer_LeftFront")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.095 1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Steer_LeftFront.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WheelLeftFront")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Wheel_LeftFront")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.095 1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_LeftFront.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Wheel_LeftFront")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.095 1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_LeftFront.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RockerRight")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Right_Rocker")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-0.214 -0.79959 -0.2405"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Right_Rocker.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_BogieRight")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Right_Bogie")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.54 -0.91959 -0.4705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Right_Bogie.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_SteerRightRear")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Steer_RightRear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "1.165 -1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Steer_RightRear.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WheelRightRear")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Wheel_RightRear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "1.165 -1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_RightRear.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Wheel_RightRear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "1.165 -1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_RightRear.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WheelRightMiddle")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Wheel_RightMiddle")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.09002 -1.1845 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_RightMiddle.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Wheel_RightMiddle")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.09002 -1.1845 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_RightMiddle.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_SteerRightFront")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Steer_RightFront")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.095 -1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Steer_RightFront.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WheelRightFront")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Wheel_RightFront")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.095 -1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_RightFront.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Wheel_RightFront")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.095 -1.0625 -0.8705"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Wheel_RightFront.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RSM_AZ")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_RSM")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-0.714017 -0.559028 0.78589"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/RSM.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RSM_EL")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_RSM_HEAD")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-0.714017 -0.559028 0.78589"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/RSM_Head.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_HGA_AZ")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_HGA_AZ")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.46 0.475 -0.0005"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/HGA_AZ.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_HGA_EL")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_HGA_EL")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.46 0.475 0.2475"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/HGA_EL.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RA_Base")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RA_Link1")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Arm_LINK_1")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.1756 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_1.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Arm_LINK_1")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.1756 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_1.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RA_Link2")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Arm_LINK_2")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.3416 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_2.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Arm_LINK_2")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-1.3416 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_2.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RA_Link3")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Arm_LINK_3")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.161 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_3.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Arm_LINK_3")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.161 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_3.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RA_Link4")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Arm_LINK_4")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.9143 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_4.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Arm_LINK_4")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.9143 0.4515 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_4.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_RA_Link5")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Arm_LINK_5")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.7386 0.2724 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_5.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t",
.element "collision" [("name", "ColGeom_Arm_LINK_5")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.7386 0.2724 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Arm_LINK_5.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_Turret")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_Turret")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/Turret.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_CorerFeed")] [.text "\n\t\t\n\t\t",
.element "visual" [("name", "VisGeom_AbradingBit")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.208499 -5.1e-05 -3.438e-05"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/AbradingBitInTurretAtZeroFeed.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t\t\n\t\t\n\t"],
.text "\n\t",
.element "link" [("name", "Body_StabilizerFar")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_StabilizerFar")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.208499 -5.1e-05 -3.438e-05"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/StabilizerFarInTurret.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_StabilizerNear")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_StabilizerNear")] [.text "\n\t\t\t",
.element "origin" [("xyz", "0.208499 -5.1e-05 -3.438e-05"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/StabilizerNearInTurret.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_WATSON_Cap")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_WATSON_Cap")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.6025 0.581204 0.0309103"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/WATSON_Camera_Cap.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Body_SHERLOC_Cap")] [.text "\n\t\t",
.element "visual" [("name", "VisGeom_SHERLOC_Cap")] [.text "\n\t\t\t",
.element "origin" [("xyz", "-2.86084 0.58439 -0.0124626"), ("rpy", "0 -0 0")] [],
.text "\n\t\t\t",
.element "geometry" [] [.text "\n\t\t\t\t",
.element "mesh" [("filename", "./meshes/ContextImager_Cap.gltf"), ("scale", "1 1 1")] [],
.text "\n\t\t\t"],
.text "\n\t\t"],
.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RNAV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RMECH")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHCB")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC1")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC2")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC3")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC4")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC1_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC2_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC3_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FHC4_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RHC1")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RHC2")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RHC1_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RHC2_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ATS1")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ATS2")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ATS3")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ATS4")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ATS5")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_HS")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ICU")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RDS")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_TIRS")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WS1")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WS2")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_MOXIE")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_MI")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_MAZ")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_MEL")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_SCI")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_SCRMI")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_SCLIBS")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_SCIR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_MCL")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_MCR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_NCL")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_NCR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_NCL_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_NCR_FOV")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ROCKER_L")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ROCKER_R")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_BOGIE_L")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_BOGIE_R")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_DIFF")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "_LF")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_STEER_LR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_STEER_RF")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_STEER_RR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WHEEL_LF")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WHEEL_LM")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WHEEL_LR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WHEEL_RF")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WHEEL_RM")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WHEEL_RR")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RIMUA")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RIMUB")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RIMFAX")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_HGAS")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_HGAG")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_ANT")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA_BASE")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA1")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA2")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA3")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA4")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA5")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_RA6")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_TURRET")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_DOCKING_POST")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_DRILL")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_FCS")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_GDRT")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_PIXL")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_SHERLOC")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_WATSON")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_CAL_MC1")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_CAL_MC2")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_CAL_SC")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_CAL_PIXL")] [.text "\n\t"],
.text "\n\t",
.element "link" [("name", "Frame_CAL_SHERLOC")] [.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JointRoot"), ("type", "floating")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -3.14 0")] [],
.text "\n\t\t",
.element "parent" [("link", "ground")] [],
.text "\n\t\t",
.element "child" [("link", "Body_Chassis")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_MHS_DebrisShield"), ("type", "floating")] [.text "\n\t\t",
.element "origin" [("xyz", "0.09002 0 -1.13338"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_MHS_DebrisShield")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "CENTER_DIFFERENTIAL"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.05198 0 -1.13338"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_Differential")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LEFT_DIFFERENTIAL"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.30402 -0.79959 -0.89288"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RockerLeft")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LEFT_BOGIE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.754 -0.12 0.23"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RockerLeft")] [],
.text "\n\t\t",
.element "child" [("link", "Body_BogieLeft")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LR_STEER"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.625 -0.14291 0.4"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_BogieLeft")] [],
.text "\n\t\t",
.element "child" [("link", "Body_SteerLeftRear")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LR_DRIVE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerLeftRear")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WheelLeftRear")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LM_DRIVE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.44998 -0.26491 0.4"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_BogieLeft")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WheelLeftMiddle")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LF_STEER"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.881 -0.26291 0.63"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RockerLeft")] [],
.text "\n\t\t",
.element "child" [("link", "Body_SteerLeftFront")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "LF_DRIVE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerLeftFront")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WheelLeftFront")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RIGHT_DIFFERENTIAL"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.30402 0.79959 -0.89288"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RockerRight")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RIGHT_BOGIE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.754 0.12 0.23"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RockerRight")] [],
.text "\n\t\t",
.element "child" [("link", "Body_BogieRight")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RR_STEER"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.625 0.14291 0.4"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_BogieRight")] [],
.text "\n\t\t",
.element "child" [("link", "Body_SteerRightRear")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RR_DRIVE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerRightRear")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WheelRightRear")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RM_DRIVE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.44998 0.26491 0.4"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_BogieRight")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WheelRightMiddle")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RF_STEER"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.881 0.26291 0.63"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RockerRight")] [],
.text "\n\t\t",
.element "child" [("link", "Body_SteerRightFront")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RF_DRIVE"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerRightFront")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WheelRightFront")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RSM_AZ_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.804037 0.559028 -1.91927"), ("rpy", "0 -0 3.12414")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RSM_AZ")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "0"), ("upper", "6.31809"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "RSM_EL_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "3.14159 -1.55334 3.14159")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_AZ")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "0"), ("upper", "3.1765"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "HGA_AZ"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.36998 -0.475 -1.13288"), ("rpy", "0 -0 0.436332")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_HGA_AZ")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "HGA_EL"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 -0.248"), ("rpy", "0.785398 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_HGA_AZ")] [],
.text "\n\t\t",
.element "child" [("link", "Body_HGA_EL")] [],
.text "\n\t\t",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JointRobotArmBase"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.09002 0 -1.13338"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RA_Base")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JOINT1_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "1.1756 -0.4515 0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Base")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RA_Link1")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-3.145"), ("upper", "1.592"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JOINT2_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.166 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link1")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RA_Link2")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-3.267"), ("upper", "0.126"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JOINT3_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.8194 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link2")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RA_Link3")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-2.866"), ("upper", "2.866"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JOINT4_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "0.7533 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link3")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RA_Link4")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-0.178"), ("upper", "3.669"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JOINT5_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.1757 0.1791 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link4")] [],
.text "\n\t\t",
.element "child" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-0.353"), ("upper", "6.636"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "JointTurret"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-2.7386 0.2724 -0.3116"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Body_Turret")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "DRILL_FEED"), ("type", "prismatic")] [.text "\n\t\t",
.element "origin" [("xyz", "2.5301 -0.272349 -0.0168656"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Turret")] [],
.text "\n\t\t",
.element "child" [("link", "Body_CorerFeed")] [],
.text "\n\t\t",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "STABILIZER_LOWER"), ("type", "prismatic")] [.text "\n\t\t",
.element "origin" [("xyz", "2.5301 -0.272349 -0.0168656"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Turret")] [],
.text "\n\t\t",
.element "child" [("link", "Body_StabilizerFar")] [],
.text "\n\t\t",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "STABILIZER_UPPER"), ("type", "prismatic")] [.text "\n\t\t",
.element "origin" [("xyz", "2.5301 -0.272349 -0.0168656"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Turret")] [],
.text "\n\t\t",
.element "child" [("link", "Body_StabilizerNear")] [],
.text "\n\t\t",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "WATSON_CAP_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "2.6025 -0.581204 -0.0309103"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Turret")] [],
.text "\n\t\t",
.element "child" [("link", "Body_WATSON_Cap")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "SHERLOC_CAP_ENC"), ("type", "revolute")] [.text "\n\t\t",
.element "origin" [("xyz", "2.86084 -0.58439 0.0124626"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Turret")] [],
.text "\n\t\t",
.element "child" [("link", "Body_SHERLOC_Cap")] [],
.text "\n\t\t",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n\t\t",
.element "limit" [("lower", "-1.79769e+308"), ("upper", "1.79769e+308"), ("effort", "1.79769e+308"), ("velocity", "1.79769e+308")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RNAV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RNAV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RMECH"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.09002 0 -1.13338"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RMECH")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHCB"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.95652 0.074 -0.76858"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHCB")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC1"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.03958 0.226094 -0.760608"), ("rpy", "-0.174841 1.117 -0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC1")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC2"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.05159 -0.002264 -0.754746"), ("rpy", "0.174841 1.117 0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC2")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC3"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.05159 0.150264 -0.754746"), ("rpy", "-0.174841 1.117 -0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC3")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC4"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.03958 -0.078094 -0.760608"), ("rpy", "0.174841 1.117 0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC4")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC1_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.09534 0.237039 -0.733411"), ("rpy", "-0.174841 1.117 -0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC1_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC2_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.10736 -0.0132091 -0.727549"), ("rpy", "0.174841 1.117 0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC2_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC3_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.10736 0.161209 -0.727549"), ("rpy", "-0.174841 1.117 -0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC3_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FHC4_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.09534 -0.0890391 -0.733411"), ("rpy", "0.174841 1.117 0.000247676")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FHC4_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RHC1"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-1.00766 -0.467 -0.77468"), ("rpy", "-2.99453e-22 0.785336 3.14159")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RHC1")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RHC2"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-1.00766 0.467 -0.77468"), ("rpy", "-2.99453e-22 0.785336 3.14159")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RHC2")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RHC1_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-1.0522 -0.467 -0.73013"), ("rpy", "-2.99453e-22 0.785336 3.14159")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RHC1_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RHC2_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-1.0522 0.467 -0.73013"), ("rpy", "-2.99453e-22 0.785336 3.14159")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RHC2_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ATS1"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.846027 0.597543 -1.44188"), ("rpy", "1.5708 -0 2.44323")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ATS1")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ATS2"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.749647 0.576177 -1.49028"), ("rpy", "-1.5708 -0 1.13391")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ATS2")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ATS3"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.816326 0.50341 -1.44188"), ("rpy", "1.5708 -0 0.348992")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ATS3")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ATS4"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.896872 -0.63405 -0.879074"), ("rpy", "-1.5708 -0 -1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ATS4")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ATS5"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.896872 0.63405 -0.830674"), ("rpy", "1.5708 -0 1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ATS5")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_HS"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.743443 0.576337 -1.50598"), ("rpy", "-0.463643 1.57079 0.463643")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_HS")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ICU"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.179008 -0.209 -1.04738"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ICU")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RDS"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.138992 -0.298597 -1.17948"), ("rpy", "3.14159 -2.64698e-23 -0.157044")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RDS")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_TIRS"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.802591 0.616374 -1.55388"), ("rpy", "0 -0 -1.53621")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_TIRS")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WS1"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.854257 0.597514 -1.59588"), ("rpy", "0 -0 0.104166")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WS1")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WS2"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.801386 0.623898 -1.62438"), ("rpy", "0 -0 2.19924")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WS2")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_MOXIE"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.193552 -0.508 -1.04738"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_MOXIE")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_MI"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.804037 0.559028 -1.13288"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_MI")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_MAZ"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_AZ")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_MAZ")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_MEL"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_MEL")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_SCI"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.071379 -0.112 -0.114609"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_SCI")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_SCRMI"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.062479 -0.112 -0.213609"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_SCRMI")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_SCLIBS"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.062479 -0.112 -0.213609"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_SCLIBS")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_SCIR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.062479 -0.112 -0.213609"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_SCIR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_MCL"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.085135 -0.126634 -0.065127"), ("rpy", "0 -0 0.0219954")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_MCL")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_MCR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.085134 0.121506 -0.065128"), ("rpy", "0 -0 -0.0220028")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_MCR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_NCL"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.080595 -0.214392 -0.057109"), ("rpy", "1.57079 1.57079 1.57079")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_NCL")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_NCR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.080595 0.209607 -0.057111"), ("rpy", "1.57079 1.57079 1.57079")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_NCR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_NCL_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.143595 -0.214392 -0.057109"), ("rpy", "1.57079 1.57079 1.57079")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_NCL_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_NCR_FOV"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.143595 0.209607 -0.057111"), ("rpy", "1.57079 1.57079 1.57079")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RSM_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_NCR_FOV")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ROCKER_L"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RockerLeft")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ROCKER_L")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ROCKER_R"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RockerRight")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ROCKER_R")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_BOGIE_L"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_BogieLeft")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_BOGIE_L")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_BOGIE_R"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_BogieRight")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_BOGIE_R")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_DIFF"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Differential")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_DIFF")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_STEER_LF"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerLeftFront")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_STEER_LF")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_STEER_LR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerLeftRear")] [],
.text "\n\t\t",
.element "child" [("link", "_LR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for__RF"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerRightFront")] [],
.text "\n\t\t",
.element "child" [("link", "_RF")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for__RR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_SteerRightRear")] [],
.text "\n\t\t",
.element "child" [("link", "_RR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WHEEL_LF"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_WheelLeftFront")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WHEEL_LF")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WHEEL_LM"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_WheelLeftMiddle")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WHEEL_LM")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WHEEL_LR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_WheelLeftRear")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WHEEL_LR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WHEEL_RF"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_WheelRightFront")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WHEEL_RF")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WHEEL_RM"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_WheelRightMiddle")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WHEEL_RM")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WHEEL_RR"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_WheelRightRear")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WHEEL_RR")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RIMUA"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.310906 -0.441586 -1.04738"), ("rpy", "0 0 -1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RIMUA")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RIMUB"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.403906 -0.441586 -1.04738"), ("rpy", "0 0 -1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RIMUB")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RIMFAX"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.79478 0 -0.71724"), ("rpy", "-0.686834 -5.55112e-17 1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RIMFAX")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_HGAS"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.36998 -0.475 -1.13288"), ("rpy", "0 -0 0.436316")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_HGAS")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_HGAG"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_HGA_AZ")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_HGAG")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_ANT"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.2084 0 0"), ("rpy", "2.35619 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_HGA_EL")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_ANT")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA_BASE"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.967871 -0.561 -0.90838"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA_BASE")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA1"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link1")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA1")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA2"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link2")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA2")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA3"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link3")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA3")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA4"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "1.5708 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link4")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA4")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA5"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA5")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_RA6"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 -0.208"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_RA6")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_TURRET"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0 -0.3285"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_TURRET")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_DOCKING_POST"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.29715 0 -0.3285"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_DOCKING_POST")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_DRILL"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.373 0 -0.3285"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_DRILL")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_FCS"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.37138 0 -0.2704"), ("rpy", "0 -0 3.14159")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_FCS")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_GDRT"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.283436 0.237831 -0.2625"), ("rpy", "0 -0 2.44346")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_GDRT")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_PIXL"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0 0.3577 -0.3385"), ("rpy", "0 -0 1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_PIXL")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_SHERLOC"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "0.143585 -0.305411 -0.292126"), ("rpy", "0 -0 -1.22173")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_SHERLOC")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_WATSON"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.115541 -0.317445 -0.342785"), ("rpy", "0 0 -1.91986")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link5")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_WATSON")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_CAL_MC1"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.28518 0.414008 -1.30252"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_CAL_MC1")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_CAL_MC2"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.23089 0.436008 -1.26302"), ("rpy", "3.14159 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_CAL_MC2")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_CAL_SC"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.73817 0.5365 -1.29482"), ("rpy", "2.26898 -0 1.5708")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_CAL_SC")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_CAL_PIXL"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "-0.1082 -0.01669 -0.025"), ("rpy", "0 -0 2.61799")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_RA_Link1")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_CAL_PIXL")] [],
.text "\n\t"],
.text "\n\t",
.element "joint" [("name", "Joint_for_Frame_CAL_SHERLOC"), ("type", "fixed")] [.text "\n\t\t",
.element "origin" [("xyz", "1.32087 0.488 -0.87888"), ("rpy", "0 -0 0")] [],
.text "\n\t\t",
.element "parent" [("link", "Body_Chassis")] [],
.text "\n\t\t",
.element "child" [("link", "Frame_CAL_SHERLOC")] [],
.text "\n\t"],
.text "\n"],
[],
[],
"781b6883360be0131d5b1baf602c5a8cbb6a1affde6f9b81dad2c7a06f0be419"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
