import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "draco_3"), ("xmlns:xacro", "http://www.ros.org/wiki/xacro")] [.text "\n\n  ",
.element "material" [("name", "dark_gray")] [.text "\n      ",
.element "color" [("rgba", "0.3 0.3 0.3 1")] [],
.text "\n  "],
.text "\n\n  ",
.element "material" [("name", "gray")] [.text "\n    ",
.element "color" [("rgba", "0.5 0.5 0.5 1.0")] [],
.text "\n  "],
.text "\n\n  ",
.element "material" [("name", "light_blue")] [.text "\n      ",
.element "color" [("rgba", "0.52 0.73 1 1")] [],
.text "\n  "],
.text "\n\n  ",
.element "material" [("name", "black")] [.text "\n      ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n  "],
.text "\n\n  ",
.element "material" [("name", "white")] [.text "\n    ",
.element "color" [("rgba", "0.8 0.8 0.8 1")] [],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "torso_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/torso_link3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0310745 -0.000497416 0.137484")] [],
.text "\n      ",
.element "mass" [("value", "6.41443")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.171435"), ("ixy", "6.32882e-05"), ("ixz", "0.0271615"), ("iyy", "0.175671"), ("iyz", "0.000581149"), ("izz", "0.036373")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "torso_com"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0310745 -0.000497416 0.137484")] [],
.text "\n    ",
.element "parent" [("link", "torso_link")] [],
.text "\n    ",
.element "child" [("link", "torso_com_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "torso_com_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "neck_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0025 0 0.352")] [],
.text "\n    ",
.element "parent" [("link", "torso_link")] [],
.text "\n    ",
.element "child" [("link", "neck_pitch_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "8.8"), ("lower", "-0.523599"), ("upper", "1.309"), ("velocity", "82.8")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "neck_pitch_link")] [.text "\n    ",
.element "visual" [] [.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/neck_pitch_link3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0133603 -0.00105814 0.0772145")] [],
.text "\n      ",
.element "mass" [("value", "1.22948")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00233791"), ("ixy", "-2.09082e-05"), ("ixz", "-0.000158016"), ("iyy", "0.00192287"), ("iyz", "-9.56707e-05"), ("izz", "0.00275375")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n\n  \n  ",
.element "joint" [("name", "camera_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.08 0 0.08")] [],
.text "\n    ",
.element "parent" [("link", "neck_pitch_link")] [],
.text "\n    ",
.element "child" [("link", "camera")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_shoulder_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0.523599 0 0"), ("xyz", "-0.05 0.156 0.2625")] [],
.text "\n    ",
.element "parent" [("link", "torso_link")] [],
.text "\n    ",
.element "child" [("link", "l_shoulder_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "18"), ("lower", "-2.26893"), ("upper", "0.698132"), ("velocity", "30")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_shoulder_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "-0.523599 0 0"), ("xyz", "0.05 -0.27 -0.15")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_shoulder_fe_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0270089 -0.0272215 0")] [],
.text "\n      ",
.element "mass" [("value", "1.02127")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.003"), ("ixy", "0.000188"), ("ixz", "-1.077e-04"), ("iyy", "0.002"), ("iyz", "-4.214e-07"), ("izz", "0.002")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_shoulder_aa"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-0.523599 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_shoulder_fe_link")] [],
.text "\n    ",
.element "child" [("link", "l_shoulder_aa_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "18"), ("lower", "0"), ("upper", "2.0944"), ("velocity", "30")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_shoulder_aa_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_shoulder_aa_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0189446 0.000135529 0.00688183")] [],
.text "\n      ",
.element "mass" [("value", "0.880498")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00104194"), ("ixy", "5.17675e-06"), ("ixz", "-0.000110264"), ("iyy", "0.00190054"), ("iyz", "6.87354e-06"), ("izz", "0.00224159")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_shoulder_ie"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_shoulder_aa_link")] [],
.text "\n    ",
.element "child" [("link", "l_shoulder_ie_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "18"), ("lower", "-1.48353"), ("upper", "1.48353"), ("velocity", "30")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_shoulder_ie_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.05 -0.15 -0.26")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_shoulder_ie_link3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00401807 0.0300008 -0.137263")] [],
.text "\n      ",
.element "mass" [("value", "1.21235")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00490878"), ("ixy", "4.35994e-05"), ("ixz", "-6.63613e-05"), ("iyy", "0.00459797"), ("iyz", "3.61794e-05"), ("izz", "0.00207282")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_elbow_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.25")] [],
.text "\n    ",
.element "parent" [("link", "l_shoulder_ie_link")] [],
.text "\n    ",
.element "child" [("link", "l_elbow_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("lower", "-2.0944"), ("upper", "0.0872665"), ("velocity", "37.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_elbow_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.055 -0.15 -0.01")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_elbow_fe_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0190443 0 -0.0633779")] [],
.text "\n      ",
.element "mass" [("value", "0.989887")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00220347"), ("ixy", "-2.91162e-08"), ("ixz", "-0.000310918"), ("iyy", "0.00297439"), ("iyz", "2.27665e-07"), ("izz", "0.0021045")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_wrist_ps"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_elbow_fe_link")] [],
.text "\n    ",
.element "child" [("link", "l_wrist_ps_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "12"), ("lower", "-1.5708"), ("upper", "1.5708"), ("velocity", "44.5")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_wrist_ps_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.05 -0.15 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_wrist_ps_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000433726 0.0158433 -0.154")] [],
.text "\n      ",
.element "mass" [("value", "0.64434")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "1.05504e-05"), ("ixz", "-5.41208e-06"), ("iyy", "0.001"), ("iyz", "4.65277e-05"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_wrist_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.1578")] [],
.text "\n    ",
.element "parent" [("link", "l_wrist_ps_link")] [],
.text "\n    ",
.element "child" [("link", "l_wrist_pitch_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "8.8"), ("lower", "-1.5708"), ("upper", "1.5708"), ("velocity", "82.8")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_wrist_pitch_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_wrist_mount"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_wrist_pitch_link")] [],
.text "\n    ",
.element "child" [("link", "l_sake_gripper_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_sake_gripper_link")] [.text "\n    ",
.element "visual" [] [.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0. 0. 0.")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_sake_gripper_mount.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "5.4498e-05 0.000382544 -0.0372594")] [],
.text "\n      ",
.element "mass" [("value", "0.145")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "3.07738e-09"), ("ixz", "2.26958e-07"), ("iyy", "0.0004628"), ("iyz", "-6.35882e-06"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "l_wrist_mount2"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 1.57 0"), ("xyz", "0 0 -0.053")] [],
.text "\n    ",
.element "parent" [("link", "l_wrist_pitch_link")] [],
.text "\n    ",
.element "child" [("link", "left_ezgripper_palm_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ezgripper_palm_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Palm_Dual_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "left_ezgripper_finger_L1_1")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L1_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ezgripper_finger_L1_2")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L1_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ezgripper_finger_L2_1")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ezgripper_finger_L2_2")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ezgripper_knuckle_palm_L1_1"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ezgripper_palm_link")] [],
.text "\n    ",
.element "child" [("link", "left_ezgripper_finger_L1_1")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.5708 0 1.57075"), ("xyz", "0.072569 0.03 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ezgripper_knuckle_palm_L1_2"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ezgripper_palm_link")] [],
.text "\n    ",
.element "child" [("link", "left_ezgripper_finger_L1_2")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5708 0 -1.57075"), ("xyz", "0.072569 -0.03 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ezgripper_knuckle_L1_L2_1"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ezgripper_finger_L1_1")] [],
.text "\n    ",
.element "child" [("link", "left_ezgripper_finger_L2_1")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.052 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ezgripper_knuckle_L1_L2_2"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ezgripper_finger_L1_2")] [],
.text "\n    ",
.element "child" [("link", "left_ezgripper_finger_L2_2")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.052 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_hand_contact_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.2")] [],
.text "\n    ",
.element "parent" [("link", "l_sake_gripper_link")] [],
.text "\n    ",
.element "child" [("link", "l_hand_contact")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hand_contact")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_shoulder_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-0.523599 0 0"), ("xyz", "-0.05 -0.156 0.2625")] [],
.text "\n    ",
.element "parent" [("link", "torso_link")] [],
.text "\n    ",
.element "child" [("link", "r_shoulder_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "18"), ("lower", "-2.26893"), ("upper", "0.698132"), ("velocity", "30")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_shoulder_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0.523599 0.0 0.0"), ("xyz", "0.05 0.27 -0.15")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_shoulder_fe_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0825089 0.0272215 6.40505e-05")] [],
.text "\n      ",
.element "mass" [("value", "1.02127")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.003"), ("ixy", "-0.000198378"), ("ixz", "3.31293e-05"), ("iyy", "0.002"), ("iyz", "-3.00004e-06"), ("izz", "0.002")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_shoulder_aa"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0.523599 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_shoulder_fe_link")] [],
.text "\n    ",
.element "child" [("link", "r_shoulder_aa_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "18"), ("lower", "-2.0944"), ("upper", "0"), ("velocity", "30")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_shoulder_aa_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_shoulder_aa_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0189446 0.000135529 0.00688183")] [],
.text "\n      ",
.element "mass" [("value", "0.880498")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00104194"), ("ixy", "5.17675e-06"), ("ixz", "-0.000110264"), ("iyy", "0.00190054"), ("iyz", "6.87354e-06"), ("izz", "0.00224159")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_shoulder_ie"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_shoulder_aa_link")] [],
.text "\n    ",
.element "child" [("link", "r_shoulder_ie_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "18"), ("lower", "-1.48353"), ("upper", "1.48353"), ("velocity", "30")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_shoulder_ie_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.05 0.15 -0.26")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_shoulder_ie_link3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00404627 -0.029987 -0.137257")] [],
.text "\n      ",
.element "mass" [("value", "1.21235")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00490973"), ("ixy", "-4.37742e-05"), ("ixz", "-6.62765e-05"), ("iyy", "0.00459809"), ("iyz", "-3.39569e-05"), ("izz", "0.002074")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_elbow_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.25")] [],
.text "\n    ",
.element "parent" [("link", "r_shoulder_ie_link")] [],
.text "\n    ",
.element "child" [("link", "r_elbow_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("lower", "-2.0944"), ("upper", "0.0872665"), ("velocity", "37.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_elbow_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.055 0.15 -0.01")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_elbow_fe_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0190415 1.75896e-05 -0.0633849")] [],
.text "\n      ",
.element "mass" [("value", "0.990031")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00220407"), ("ixy", "-2.9063e-08"), ("ixz", "-0.000310786"), ("iyy", "0.00297478"), ("iyz", "2.27528e-07"), ("izz", "0.00210481")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_wrist_ps"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_elbow_fe_link")] [],
.text "\n    ",
.element "child" [("link", "r_wrist_ps_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "12"), ("lower", "-1.5708"), ("upper", "1.5708"), ("velocity", "44.5")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_wrist_ps_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.05 0.15 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_wrist_ps_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000229308 0.0158433 -0.154481")] [],
.text "\n      ",
.element "mass" [("value", "0.64434")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "5.23851e-06"), ("ixz", "-4.22277e-06"), ("iyy", "0.001"), ("iyz", "3.40912e-05"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_wrist_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.1578")] [],
.text "\n    ",
.element "parent" [("link", "r_wrist_ps_link")] [],
.text "\n    ",
.element "child" [("link", "r_wrist_pitch_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "8.8"), ("lower", "-1.5708"), ("upper", "1.5708"), ("velocity", "82.8")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_wrist_pitch_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_wrist_mount"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_wrist_pitch_link")] [],
.text "\n    ",
.element "child" [("link", "r_sake_gripper_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_sake_gripper_link")] [.text "\n    ",
.element "visual" [] [.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0. 0. 0.")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_sake_gripper_mount.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "5.4498e-05 0.000382544 -0.0372594")] [],
.text "\n      ",
.element "mass" [("value", "0.145")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "3.07738e-09"), ("ixz", "2.26958e-07"), ("iyy", "0.0004628"), ("iyz", "-6.35882e-06"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "r_wrist_mount2"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 1.57 0"), ("xyz", "0 0 -0.053")] [],
.text "\n    ",
.element "parent" [("link", "r_wrist_pitch_link")] [],
.text "\n    ",
.element "child" [("link", "right_ezgripper_palm_link")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ezgripper_palm_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Palm_Dual_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "right_ezgripper_finger_L1_1")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L1_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ezgripper_finger_L1_2")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L1_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ezgripper_finger_L2_1")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ezgripper_finger_L2_2")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/ezgripper_gen2/SAKE_Finger_L2_Gen2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".025")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01"), ("iyz", "0.0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ezgripper_knuckle_palm_L1_1"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ezgripper_palm_link")] [],
.text "\n    ",
.element "child" [("link", "right_ezgripper_finger_L1_1")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.5708 0 1.57075"), ("xyz", "0.072569 0.03 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ezgripper_knuckle_palm_L1_2"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ezgripper_palm_link")] [],
.text "\n    ",
.element "child" [("link", "right_ezgripper_finger_L1_2")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5708 0 -1.57075"), ("xyz", "0.072569 -0.03 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ezgripper_knuckle_L1_L2_1"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ezgripper_finger_L1_1")] [],
.text "\n    ",
.element "child" [("link", "right_ezgripper_finger_L2_1")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.052 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ezgripper_knuckle_L1_L2_2"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ezgripper_finger_L1_2")] [],
.text "\n    ",
.element "child" [("link", "right_ezgripper_finger_L2_2")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.052 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "1"), ("lower", "0"), ("upper", "1.94"), ("velocity", "3.67")] [],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_hand_contact_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.2")] [],
.text "\n    ",
.element "parent" [("link", "r_sake_gripper_link")] [],
.text "\n    ",
.element "child" [("link", "r_hand_contact")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hand_contact")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_hip_ie"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0.523599 0 0"), ("xyz", "0 0.06 -0.0893782")] [],
.text "\n    ",
.element "parent" [("link", "torso_link")] [],
.text "\n    ",
.element "child" [("link", "l_hip_ie_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "44"), ("lower", "-0.872665"), ("upper", "0.872665"), ("velocity", "8.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hip_ie_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_hip_ie_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00699855 0.00580214 -0.0245826")] [],
.text "\n      ",
.element "mass" [("value", "0.139743")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000107251"), ("ixy", "-6.29131e-06"), ("ixz", "5.03369e-06"), ("iyy", "0.000199571"), ("iyz", "-2.59816e-07"), ("izz", "0.00015888")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_hip_aa"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-0.523599 0 0"), ("xyz", "0 0 -0.07")] [],
.text "\n    ",
.element "parent" [("link", "l_hip_ie_link")] [],
.text "\n    ",
.element "child" [("link", "l_hip_aa_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "56"), ("lower", "-0.261799"), ("upper", "0.785398"), ("velocity", "5.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hip_aa_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.0 -0.1 0.15")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_hip_aa_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00107664 0.00164809 -0.00149004")] [],
.text "\n      ",
.element "mass" [("value", "0.77975")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "1.93711e-05"), ("ixz", "-1.45347e-06"), ("iyy", "0.001"), ("iyz", "2.96392e-05"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_hip_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hip_aa_link")] [],
.text "\n    ",
.element "child" [("link", "l_hip_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "59.6"), ("lower", "-1.52716"), ("upper", "0.523599"), ("velocity", "36.7")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hip_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.1 0.15")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_hip_fe_link3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00057 -0.00303734 -0.164021")] [],
.text "\n      ",
.element "mass" [("value", "4.549")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0497956"), ("ixy", "0.000306806"), ("ixz", "0.000744022"), ("iyy", "0.0552997"), ("iyz", "0.00394109"), ("izz", "0.0129964")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_knee_fe_jp"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.324231")] [],
.text "\n    ",
.element "parent" [("link", "l_hip_fe_link")] [],
.text "\n    ",
.element "child" [("link", "l_knee_fe_lp")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "40.85"), ("lower", "-0.0872665"), ("upper", "1.52716"), ("velocity", "13.35")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_knee_fe_lp")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.005 -0.1 0.47")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_knee_fe_lp.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-4.80156e-09 0.00425279 -0.0291238")] [],
.text "\n      ",
.element "mass" [("value", "0.135683")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00048051"), ("ixy", "4.39106e-11"), ("ixz", "3.91495e-11"), ("iyy", "0.000329965"), ("iyz", "-3.71846e-05"), ("izz", "0.000282787")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_knee_adj"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0557693")] [],
.text "\n    ",
.element "parent" [("link", "l_knee_fe_lp")] [],
.text "\n    ",
.element "child" [("link", "l_knee_adj_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "72.62"), ("lower", "-0.174533"), ("upper", "3.05432"), ("velocity", "7.5")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_knee_adj_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_knee_adj_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.006 -0.0323676")] [],
.text "\n      ",
.element "mass" [("value", "0.090042")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000230283"), ("ixy", "7.86884e-09"), ("ixz", "-1.29921e-20"), ("iyy", "7.20839e-05"), ("iyz", "-1.23413e-18"), ("izz", "0.000195694")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_knee_fe_jd"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.1115386")] [],
.text "\n    ",
.element "parent" [("link", "l_knee_fe_lp")] [],
.text "\n    ",
.element "child" [("link", "l_knee_fe_ld")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "40.85"), ("lower", "-0.0872665"), ("upper", "1.52716"), ("velocity", "13.35")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_knee_fe_ld")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 -0.1 0.59")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_knee_fe_ld3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00392246 0.00238405 -0.07941")] [],
.text "\n      ",
.element "mass" [("value", "2.55664")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.011"), ("ixy", "-0.000259001"), ("ixz", "-0.000169"), ("iyy", "0.013"), ("iyz", "0.001"), ("izz", "0.005")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_ankle_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.00599 -0.248231")] [],
.text "\n    ",
.element "parent" [("link", "l_knee_fe_ld")] [],
.text "\n    ",
.element "child" [("link", "l_ankle_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "44"), ("lower", "-1.5708"), ("upper", "1.0472"), ("velocity", "8.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_ankle_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 -0.105 0.83")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_ankle_fe_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "2.67715e-05 0.0277455 -0.000699218")] [],
.text "\n      ",
.element "mass" [("value", "0.183143")] [],
.text "\n      ",
.element "inertia" [("ixx", "8.90758e-05"), ("ixy", "2.90654e-07"), ("ixz", "-2.26413e-06"), ("iyy", "5.81098e-05"), ("iyz", "1.95082e-07"), ("izz", "0.000101604")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_ankle_ie"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_ankle_fe_link")] [],
.text "\n    ",
.element "child" [("link", "l_ankle_ie_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "30"), ("lower", "-0.785398"), ("upper", "0.261799"), ("velocity", "11.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_ankle_ie_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.01 -0.08 0.835")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/l_ankle_ie_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    \n      \n      \n        \n      \n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 -0.005 -0.046")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        \n        ",
.element "box" [("size", "0.25 0.15 0.0591")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00320518 -0.0068186 -0.0444808")] [],
.text "\n      ",
.element "mass" [("value", "0.436553")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000962376"), ("ixy", "-2.58627e-05"), ("ixz", "0.000122026"), ("iyy", "0.00165909"), ("iyz", "0.000188621"), ("izz", "0.00108264")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "l_foot_contact_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.076")] [],
.text "\n    ",
.element "parent" [("link", "l_ankle_ie_link")] [],
.text "\n    ",
.element "child" [("link", "l_foot_contact")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_foot_contact")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_hip_ie"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-0.523599 0 0"), ("xyz", "0 -0.06 -0.0893782")] [],
.text "\n    ",
.element "parent" [("link", "torso_link")] [],
.text "\n    ",
.element "child" [("link", "r_hip_ie_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "44"), ("lower", "-0.872665"), ("upper", "0.872665"), ("velocity", "8.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hip_ie_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_hip_ie_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00703461 -0.00580298 -0.0246181")] [],
.text "\n      ",
.element "mass" [("value", "0.139506")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000107149"), ("ixy", "6.38614e-06"), ("ixz", "5.12641e-06"), ("iyy", "0.000199317"), ("iyz", "2.66262e-07"), ("izz", "0.000158733")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_hip_aa"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0.523599 0 0"), ("xyz", "0 0 -0.07")] [],
.text "\n    ",
.element "parent" [("link", "r_hip_ie_link")] [],
.text "\n    ",
.element "child" [("link", "r_hip_aa_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "56"), ("lower", "-0.785398"), ("upper", "0.261799"), ("velocity", "5.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hip_aa_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.0 0.1 0.15")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_hip_aa_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.000513526 -0.0019221 -0.00112805")] [],
.text "\n      ",
.element "mass" [("value", "0.849423")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000807304"), ("ixy", "-2.90747e-05"), ("ixz", "1.16932e-05"), ("iyy", "0.000791593"), ("iyz", "-2.47696e-05"), ("izz", "0.000937825")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_hip_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hip_aa_link")] [],
.text "\n    ",
.element "child" [("link", "r_hip_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "59.6"), ("lower", "-1.52716"), ("upper", "0.523599"), ("velocity", "36.7")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hip_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.0 0.1 0.15")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_hip_fe_link3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00121565 -0.000254558 -0.171535")] [],
.text "\n      ",
.element "mass" [("value", "4.983")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.057"), ("ixy", "-0.0003353"), ("ixz", "0.001"), ("iyy", "0.063"), ("iyz", "-0.004"), ("izz", "0.015")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_knee_fe_jp"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.324231")] [],
.text "\n    ",
.element "parent" [("link", "r_hip_fe_link")] [],
.text "\n    ",
.element "child" [("link", "r_knee_fe_lp")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "40.85"), ("lower", "-0.0872665"), ("upper", "1.52716"), ("velocity", "13.35")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_knee_fe_lp")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.005 0.1 0.47")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_knee_fe_lp.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "4.28378e-09 -0.000374047 -0.0259832")] [],
.text "\n      ",
.element "mass" [("value", "0.152083")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "4.75046e-11"), ("ixz", "-3.71034e-11"), ("iyy", "0.000343441"), ("iyz", "2.06816e-05"), ("izz", "0.000321184")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n    \n    \n    \n    \n    \n    \n  \n  \n    \n      \n      \n      \n    \n  \n\n  \n  ",
.element "joint" [("name", "r_knee_adj"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0557693")] [],
.text "\n    ",
.element "parent" [("link", "r_knee_fe_lp")] [],
.text "\n    ",
.element "child" [("link", "r_knee_adj_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "72.62"), ("lower", "-0.174533"), ("upper", "3.05432"), ("velocity", "7.5")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_knee_adj_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_knee_adj_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.006 -0.0323676")] [],
.text "\n      ",
.element "mass" [("value", "0.090042")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000230283"), ("ixy", "7.86884e-09"), ("ixz", "2.52488e-19"), ("iyy", "7.20839e-05"), ("iyz", "-8.07064e-19"), ("izz", "0.000195694")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_knee_fe_jd"), ("type", "revolute")] [.text "\n    \n    \n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.1115386")] [],
.text "\n    ",
.element "parent" [("link", "r_knee_fe_lp")] [],
.text "\n    ",
.element "child" [("link", "r_knee_fe_ld")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "40.85"), ("lower", "-0.0872665"), ("upper", "1.52716"), ("velocity", "13.35")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_knee_fe_ld")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0.1 0.59")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          \n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_knee_fe_ld3.obj")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00388972 -0.00235124 -0.0784681")] [],
.text "\n      ",
.element "mass" [("value", "2.58619")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0110576"), ("ixy", "0.00025372"), ("ixz", "-0.000138968"), ("iyy", "0.0125163"), ("iyz", "-0.001"), ("izz", "0.005")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_ankle_fe"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.006 -0.248231")] [],
.text "\n    ",
.element "parent" [("link", "r_knee_fe_ld")] [],
.text "\n    ",
.element "child" [("link", "r_ankle_fe_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "44"), ("lower", "-1.5708"), ("upper", "1.0472"), ("velocity", "8.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_ankle_fe_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0.105 0.83")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_ankle_fe_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.0277456 -0.000698932")] [],
.text "\n      ",
.element "mass" [("value", "0.183145")] [],
.text "\n      ",
.element "inertia" [("ixx", "8.9077e-05"), ("ixy", "-5.7205e-07"), ("ixz", "-2.14649e-06"), ("iyy", "5.81093e-05"), ("iyz", "-1.95113e-07"), ("izz", "0.000101603")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_ankle_ie"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_ankle_fe_link")] [],
.text "\n    ",
.element "child" [("link", "r_ankle_ie_link")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "30"), ("lower", "-0.261799"), ("upper", "0.785398"), ("velocity", "11.1")] [],
.text "\n    ",
.element "joint_properties" [("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_ankle_ie_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0.01 0.08 0.835")] [],
.text "\n      ",
.element "geometry" [] [.text "\n          ",
.element "mesh" [("filename", "package://draco3_description/meshes/r_ankle_ie_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    \n      \n      \n        \n      \n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 -0 0"), ("xyz", "0 0.005 -0.046")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        \n        ",
.element "box" [("size", "0.25 0.15 0.0591")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00300438 0.00685638 -0.0443499")] [],
.text "\n      ",
.element "mass" [("value", "0.437539")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000967631"), ("ixy", "2.37588e-05"), ("ixz", "0.000131807"), ("iyy", "0.00163004"), ("iyz", "-0.000128971"), ("izz", "0.00111644")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "joint" [("name", "r_foot_contact_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.076")] [],
.text "\n    ",
.element "parent" [("link", "r_ankle_ie_link")] [],
.text "\n    ",
.element "child" [("link", "r_foot_contact")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_foot_contact")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"445745adf0d7c405343f3d2988c9758b7f1e03674394d2f1ebf62402dc8844b1"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
