import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "wheel_biped")] [.text "\n    \n    \n    \n    ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 0.8 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "green")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.8 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.2 0.2 0.2 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "silver")] [.text "\n        ",
.element "color" [("rgba", "0.9137254901960784 0.9137254901960784 0.8470588235294118 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "orange")] [.text "\n        ",
.element "color" [("rgba", "1.0 0.4235294117647059 0.0392156862745098 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "brown")] [.text "\n        ",
.element "color" [("rgba", "0.8705882352941177 0.8117647058823529 0.7647058823529411 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "red")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.0 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [] [.text "\n        ",
.element "plugin" [("filename", "libpointfoot_hw_sim.so"), ("name", "gazebo_ros_control")] [.text "\n            ",
.element "robotNamespace" [] [.text "/"],
.text "\n            ",
.element "robotParam" [] [.text "robot_description"],
.text "\n            ",
.element "robotSimType" [] [.text "pointfoot_gazebo/PointFootHWSim"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [] [.text "\n        ",
.element "plugin" [("filename", "libgazebo_ros_p3d.so"), ("name", "p3d_base_controller")] [.text "\n            ",
.element "alwaysOn" [] [.text "true"],
.text "\n            ",
.element "updateRate" [] [.text "1000.0"],
.text "\n            ",
.element "bodyName" [] [.text "base_Link"],
.text "\n            ",
.element "topicName" [] [.text "ground_truth/state"],
.text "\n            ",
.element "gaussianNoise" [] [.text "0"],
.text "\n            ",
.element "frameName" [] [.text "world"],
.text "\n            ",
.element "xyzOffsets" [] [.text "0 0 0"],
.text "\n            ",
.element "rpyOffsets" [] [.text "0 0 0"],
.text "\n        "],
.text "\n    "],
.text "\n\n    \n\n    ",
.element "link" [("name", "base_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "45.76E-03 0.14E-03 -163.98E-03")] [],
.text "\n            ",
.element "mass" [("value", "9.585")] [],
.text "\n            ",
.element "inertia" [("ixx", "140110.479E-06"), ("ixy", "534.939E-06"), ("ixz", "28184.116E-06"), ("iyy", "110641.449E-06"), ("iyz", "-27.278E-06"), ("izz", "98944.542E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/base_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.03 0 -0.072"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.27 0.26 0.19")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n\n     ",
.element "joint" [("name", "limx_imu_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("rpy", "0. 0. 0."), ("xyz", "0. 0. 0.")] [],
.text "\n        ",
.element "parent" [("link", "base_Link")] [],
.text "\n        ",
.element "child" [("link", "limx_imu")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "limx_imu")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.01")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000001"), ("iyz", "0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.015 0.015 0.004")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "material" [("name", "orange")] [.text "\n            ",
.element "color" [("rgba", "255 108 10 255")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "limx_imu")] [.text "\n        ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "limx_imu_joint")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "abad_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-69.77E-03 44.79E-03 0.57E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.469")] [],
.text "\n            ",
.element "inertia" [("ixx", "1555.384E-06"), ("ixy", "397.78E-06"), ("ixz", "-13.10E-06"), ("iyy", "2359.25E-06"), ("iyz", "-0.98E-06"), ("izz", "2080.92E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/abad_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.03 0 0"), ("rpy", "1.57 0 1.57")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.05"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "abad_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "55.56E-03 105E-03 -260.2E-03"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_Link")] [],
.text "\n        ",
.element "child" [("link", "abad_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-0.38397"), ("upper", "1.39626"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "hip_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-28.69E-03 -47.7E-03 -39.92E-03")] [],
.text "\n            ",
.element "mass" [("value", "2.3")] [],
.text "\n            ",
.element "inertia" [("ixx", "16937.28E-06"), ("ixy", "1647.03E-06"), ("ixz", "-9232.53E-06"), ("iyy", "22853.28E-06"), ("iyz", "2202.40E-06"), ("izz", "9334.19E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/hip_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.10 -0.03 -0.14"), ("rpy", "0 0.53 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.15"), ("radius", "0.035")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "hip_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.077 0.02050 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "abad_L_Link")] [],
.text "\n        ",
.element "child" [("link", "hip_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-1.012291"), ("upper", "1.396263"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "knee_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "119.13E-03 11.06E-03 -203.63E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.49")] [],
.text "\n            ",
.element "inertia" [("ixx", "13232.8E-06"), ("ixy", "-435.46E-06"), ("ixz", "6935.69E-06"), ("iyy", "17661.37E-06"), ("iyz", "790.87E-06"), ("izz", "5016.98E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/knee_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.078 0 -0.12"), ("rpy", "0 -0.55 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.26"), ("radius", "0.015")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "knee_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.1500 -0.02050 -0.25981"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "hip_L_Link")] [],
.text "\n        ",
.element "child" [("link", "knee_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80"), ("lower", "-0.872665"), ("upper", "1.361357"), ("velocity", "15")] [],
.text "\n    "],
.text "\n\n    ",
.element "joint" [("name", "wheel_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "150E-03 43.5E-03 -259.81E-03")] [],
.text "\n        ",
.element "parent" [("link", "knee_L_Link")] [],
.text "\n        ",
.element "child" [("link", "wheel_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("lower", "-1000000"), ("upper", "1000000"), ("velocity", "40")] [],
.text "\n        ",
.element "dynamics" [("friction", "0.01")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "wheel_L_Link")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/wheel_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.69804 0.69804 0.69804 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.00707 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.05"), ("radius", "0.127")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03E-03 8.07E-03 -0.02E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.08")] [],
.text "\n            ",
.element "inertia" [("ixx", "5155.12E-06"), ("ixy", "0.01E-06"), ("ixz", "-0.97E-06"), ("iyy", "9742.72E-06"), ("iyz", "-0.01E-06"), ("izz", "5154.00E-06")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "gazebo" [("reference", "hip_L_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "knee_L_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "100.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "wheel_L_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n\n    ",
.element "transmission" [("name", "abad_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "abad_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "abad_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "hip_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "hip_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "hip_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "knee_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "knee_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "knee_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "wheel_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "wheel_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "wheel_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "abad_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-69.77E-03 -44.79E-03 0.57E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.469")] [],
.text "\n            ",
.element "inertia" [("ixx", "1555.384E-06"), ("ixy", "-397.78E-06"), ("ixz", "-13.10E-06"), ("iyy", "2359.25E-06"), ("iyz", "0.98E-06"), ("izz", "2080.92E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/abad_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.03 0 0"), ("rpy", "1.57 0 1.57")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.05"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "abad_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "55.56E-03 -105E-03 -260.2E-03"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_Link")] [],
.text "\n        ",
.element "child" [("link", "abad_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-1.39626"), ("upper", "0.38397"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "hip_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-28.69E-03 47.7E-03 -39.92E-03")] [],
.text "\n            ",
.element "mass" [("value", "2.30")] [],
.text "\n            ",
.element "inertia" [("ixx", "16937.28E-06"), ("ixy", "-1647.03E-06"), ("ixz", "-9232.53E-06"), ("iyy", "22853.28E-06"), ("iyz", "-2202.40E-06"), ("izz", "9334.19E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/hip_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.10 0.03 -0.14"), ("rpy", "0 0.53 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.15"), ("radius", "0.035")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "hip_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.077 -0.02050 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "abad_R_Link")] [],
.text "\n        ",
.element "child" [("link", "hip_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-1.396263"), ("upper", "1.012291"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "knee_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "119.13E-03 -11.06E-03 -203.63E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.49")] [],
.text "\n            ",
.element "inertia" [("ixx", "13232.8E-06"), ("ixy", "435.46E-06"), ("ixz", "6935.69E-06"), ("iyy", "17661.37E-06"), ("iyz", "-790.87E-06"), ("izz", "5016.98E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/knee_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.078 0 -0.12"), ("rpy", "0 -0.55 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.26"), ("radius", "0.015")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "knee_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.1500 0.02050 -0.25981"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "hip_R_Link")] [],
.text "\n        ",
.element "child" [("link", "knee_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80"), ("lower", "-1.361357"), ("upper", "0.872665"), ("velocity", "15")] [],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "wheel_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "150E-03 -43.5E-03 -259.81E-03")] [],
.text "\n        ",
.element "parent" [("link", "knee_R_Link")] [],
.text "\n        ",
.element "child" [("link", "wheel_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("lower", "-1000000"), ("upper", "1000000"), ("velocity", "40")] [],
.text "\n        ",
.element "dynamics" [("friction", "0.01")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "wheel_R_Link")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/WF_TRON1A/meshes/wheel_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.69804 0.69804 0.69804 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 -0.00707 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.05"), ("radius", "0.127")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03E-03 -8.07E-03 -0.02E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.08")] [],
.text "\n            ",
.element "inertia" [("ixx", "5155.12E-06"), ("ixy", "-0.01E-06"), ("ixz", "-0.97E-06"), ("iyy", "9742.72E-06"), ("iyz", "0.01E-06"), ("izz", "5154.00E-06")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "gazebo" [("reference", "hip_R_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "knee_R_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "100.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "wheel_R_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n\n    ",
.element "transmission" [("name", "abad_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "abad_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "abad_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "hip_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "hip_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "hip_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "knee_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "knee_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "knee_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "wheel_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "wheel_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "wheel_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n\n    \n    \n    \n"],
[],
[],
"f09c56c15acd507bba43b394e37a9abe024e0111fdde7dbf41796408895ee4c5"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
