import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "wheel_legged")] [.text "\n    ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 0.8 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "green")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.8 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.2 0.2 0.2 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "silver")] [.text "\n        ",
.element "color" [("rgba", "0.9137254901960784 0.9137254901960784 0.8470588235294118 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "orange")] [.text "\n        ",
.element "color" [("rgba", "1.0 0.4235294117647059 0.0392156862745098 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "brown")] [.text "\n        ",
.element "color" [("rgba", "0.8705882352941177 0.8117647058823529 0.7647058823529411 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "red")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.0 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [] [.text "\n        ",
.element "plugin" [("filename", "libwheellegged_hw_sim.so"), ("name", "gazebo_ros_control")] [.text "\n            ",
.element "robotNamespace" [] [.text "/"],
.text "\n            ",
.element "robotParam" [] [.text "robot_description"],
.text "\n            ",
.element "robotSimType" [] [.text "wheellegged_gazebo/WheelleggedHWSim"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [] [.text "\n        ",
.element "plugin" [("filename", "libgazebo_ros_p3d.so"), ("name", "p3d_base_controller")] [.text "\n            ",
.element "alwaysOn" [] [.text "true"],
.text "\n            ",
.element "updateRate" [] [.text "1000.0"],
.text "\n            ",
.element "bodyName" [] [.text "base"],
.text "\n            ",
.element "topicName" [] [.text "ground_truth/state"],
.text "\n            ",
.element "gaussianNoise" [] [.text "0"],
.text "\n            ",
.element "frameName" [] [.text "world"],
.text "\n            ",
.element "xyzOffsets" [] [.text "0 0 0"],
.text "\n            ",
.element "rpyOffsets" [] [.text "0 0 0"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "base_link")] [.text "\n        ",
.element "maxVel" [] [.text "100."],
.text "\n        ",
.element "kp" [] [.text "10000."],
.text "\n        ",
.element "kd" [] [.text "0."],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "stick_link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/White"],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [("reference", "LF_hip")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LF_thigh")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LF_calf")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LF_wheel")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LF_foot")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/White"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [("reference", "RF_hip")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RF_thigh")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RF_calf")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RF_wheel")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RF_foot")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/White"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [("reference", "LH_hip")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LH_thigh")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LH_calf")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LH_wheel")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LH_foot")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/White"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [("reference", "RH_hip")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RH_thigh")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RH_calf")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RH_wheel")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RH_foot")] [.text "\n        ",
.element "mu1" [] [.text "0.6"],
.text "\n        ",
.element "mu2" [] [.text "0.6"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/White"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "base")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0455 0 -0.07551")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/base_link.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [.text "\n                ",
.element "color" [("rgba", "0.752941176470588 0.752941176470588 0.752941176470588 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0455 0 -0.07551")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.515 0.2635 0.151")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.042212 -0.000883 -0.085535")] [],
.text "\n            ",
.element "mass" [("value", "18.188")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.138596272"), ("ixy", "-0.000463223"), ("ixz", "0.001179281"), ("iyy", "0.539545026"), ("iyz", "7.664e-06"), ("izz", "0.5975639")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "limx_imu_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("rpy", "0. 0. 0."), ("xyz", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "limx_imu")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "limx_imu")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.01")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000001"), ("iyz", "0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.015 0.015 0.004")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "material" [("name", "orange")] [.text "\n            ",
.element "color" [("rgba", "255 108 10 255")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "limx_imu")] [.text "\n        ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "limx_imu_joint")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LF_HAA"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.216 0.06 -0.07376")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "LF_hip")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-0.87"), ("upper", "0.87"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LF_hip")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LF_hip.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.053246 0.009578 -0.000256")] [],
.text "\n            ",
.element "mass" [("value", "1.434")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001158337"), ("ixy", "-2.5451e-05"), ("ixz", "7.91e-07"), ("iyy", "0.001701117"), ("iyz", "-1.883e-06"), ("izz", "0.001372051")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LF_HFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.058 0.0408 0")] [],
.text "\n        ",
.element "parent" [("link", "LF_hip")] [],
.text "\n        ",
.element "child" [("link", "LF_thigh")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-2.27"), ("upper", "1.22"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LF_thigh")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LF_thigh.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.057303 0.055844 0.004528")] [],
.text "\n            ",
.element "mass" [("value", "2.751")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.004607032"), ("ixy", "0.004707351"), ("ixz", "0.001380725"), ("iyy", "0.028533909"), ("iyz", "-0.000405022"), ("izz", "0.029844027")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LF_KFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.28 0.08155 0")] [],
.text "\n        ",
.element "parent" [("link", "LF_thigh")] [],
.text "\n        ",
.element "child" [("link", "LF_calf")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "0"), ("upper", "2.0943951023932"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LF_calf")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LF_calf.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.20392 0.20392 0.20392 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0.680678408 0"), ("xyz", "0.10876 0 -0.08805")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.28 0.023 0.0451")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.172578 0.002711 -0.142172")] [],
.text "\n            ",
.element "mass" [("value", "1.326")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.006426995"), ("ixy", "-0.000131916"), ("ixz", "0.006446843"), ("iyy", "0.01424856"), ("iyz", "0.000130699"), ("izz", "0.008429207")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LF_WHL"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.21449 0.03434 -0.17998")] [],
.text "\n        ",
.element "parent" [("link", "LF_calf")] [],
.text "\n        ",
.element "child" [("link", "LF_wheel")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("lower", "-1000"), ("upper", "1000"), ("velocity", "20")] [],
.text "\n        ",
.element "dynamics" [("friction", "1")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LF_wheel")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LF_wheel.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.69804 0.69804 0.69804 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.017"), ("radius", "0.127")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "3.8e-05 0.000878 5.1e-05")] [],
.text "\n            ",
.element "mass" [("value", "0.818")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.003929539"), ("ixy", "1e-08"), ("ixz", "1.808e-06"), ("iyy", "0.007451249"), ("iyz", "6.7e-08"), ("izz", "0.003930825")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LF_foot_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_wheel")] [],
.text "\n        ",
.element "child" [("link", "LF_foot")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.127")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LF_foot")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LF_foot_fixed")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LF_HAA_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LF_HAA")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LF_HAA_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LF_HFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LF_HFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LF_HFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LF_KFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LF_KFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LF_KFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LF_WHL_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LF_WHL")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LF_WHL_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RF_HAA"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.216 -0.06 -0.07376")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "RF_hip")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-0.87"), ("upper", "0.87"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RF_hip")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RF_hip.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.053246 -0.009578 -0.000256")] [],
.text "\n            ",
.element "mass" [("value", "1.434")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001158337"), ("ixy", "2.5451e-05"), ("ixz", "7.91e-07"), ("iyy", "0.001701117"), ("iyz", "1.883e-06"), ("izz", "0.001372051")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RF_HFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.058 -0.0408 0")] [],
.text "\n        ",
.element "parent" [("link", "RF_hip")] [],
.text "\n        ",
.element "child" [("link", "RF_thigh")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-2.27"), ("upper", "1.22"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RF_thigh")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RF_thigh.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.057303 -0.055844 0.004528")] [],
.text "\n            ",
.element "mass" [("value", "2.751")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.004607032"), ("ixy", "-0.004707351"), ("ixz", "0.001380725"), ("iyy", "0.028533909"), ("iyz", "0.000405022"), ("izz", "0.029844027")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RF_KFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.28 -0.08155 0")] [],
.text "\n        ",
.element "parent" [("link", "RF_thigh")] [],
.text "\n        ",
.element "child" [("link", "RF_calf")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "0"), ("upper", "2.0943951023932"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RF_calf")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RF_calf.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.20392 0.20392 0.20392 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0.680678408 0"), ("xyz", "0.10876 0 -0.08805")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.28 0.023 0.0451")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.172578 -0.002711 -0.142172")] [],
.text "\n            ",
.element "mass" [("value", "1.326")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.006426995"), ("ixy", "0.000131916"), ("ixz", "0.006446843"), ("iyy", "0.01424856"), ("iyz", "-0.000130699"), ("izz", "0.008429207")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RF_WHL"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.21449 -0.03434 -0.17998")] [],
.text "\n        ",
.element "parent" [("link", "RF_calf")] [],
.text "\n        ",
.element "child" [("link", "RF_wheel")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("lower", "-1000"), ("upper", "1000"), ("velocity", "20")] [],
.text "\n        ",
.element "dynamics" [("friction", "1")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RF_wheel")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RF_wheel.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.69804 0.69804 0.69804 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.017"), ("radius", "0.127")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "3.8e-05 -0.000878 5.1e-05")] [],
.text "\n            ",
.element "mass" [("value", "0.818")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.003929539"), ("ixy", "-1e-08"), ("ixz", "1.808e-06"), ("iyy", "0.007451249"), ("iyz", "-6.7e-08"), ("izz", "0.003930825")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RF_foot_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_wheel")] [],
.text "\n        ",
.element "child" [("link", "RF_foot")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.127")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RF_foot")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RF_foot_fixed")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RF_HAA_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RF_HAA")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RF_HAA_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RF_HFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RF_HFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RF_HFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RF_KFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RF_KFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RF_KFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RF_WHL_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RF_WHL")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RF_WHL_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LH_HAA"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.307 0.06 -0.07376")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "LH_hip")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-0.87"), ("upper", "0.87"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LH_hip")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LH_hip.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.053246 0.009578 -0.000256")] [],
.text "\n            ",
.element "mass" [("value", "1.434")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001158337"), ("ixy", "2.5451e-05"), ("ixz", "-7.91e-07"), ("iyy", "0.001701117"), ("iyz", "-1.883e-06"), ("izz", "0.001372051")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LH_HFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.058 0.0408 0")] [],
.text "\n        ",
.element "parent" [("link", "LH_hip")] [],
.text "\n        ",
.element "child" [("link", "LH_thigh")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-2.27"), ("upper", "1.22"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LH_thigh")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LH_thigh.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.057303 0.055844 0.004528")] [],
.text "\n            ",
.element "mass" [("value", "2.751")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.004607032"), ("ixy", "0.004707351"), ("ixz", "0.001380725"), ("iyy", "0.028533909"), ("iyz", "-0.000405022"), ("izz", "0.029844027")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LH_KFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.28 0.08155 0")] [],
.text "\n        ",
.element "parent" [("link", "LH_thigh")] [],
.text "\n        ",
.element "child" [("link", "LH_calf")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "0"), ("upper", "2.0943951023932"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LH_calf")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LH_calf.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.20392 0.20392 0.20392 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0.680678408 0"), ("xyz", "0.10876 0 -0.08805")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.28 0.023 0.0451")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.172578 0.002711 -0.142172")] [],
.text "\n            ",
.element "mass" [("value", "1.326")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.006426995"), ("ixy", "-0.000131916"), ("ixz", "0.006446843"), ("iyy", "0.01424856"), ("iyz", "0.000130699"), ("izz", "0.008429207")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LH_WHL"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.21449 0.03434 -0.17998")] [],
.text "\n        ",
.element "parent" [("link", "LH_calf")] [],
.text "\n        ",
.element "child" [("link", "LH_wheel")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("lower", "-1000"), ("upper", "1000"), ("velocity", "20")] [],
.text "\n        ",
.element "dynamics" [("friction", "1")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LH_wheel")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/LH_wheel.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.69804 0.69804 0.69804 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.017"), ("radius", "0.127")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "3.8e-05 0.000878 5.1e-05")] [],
.text "\n            ",
.element "mass" [("value", "0.818")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.003929539"), ("ixy", "1e-08"), ("ixz", "1.808e-06"), ("iyy", "0.007451249"), ("iyz", "6.7e-08"), ("izz", "0.003930825")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "LH_foot_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_wheel")] [],
.text "\n        ",
.element "child" [("link", "LH_foot")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.127")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "LH_foot")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "LH_foot_fixed")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LH_HAA_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LH_HAA")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LH_HAA_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LH_HFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LH_HFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LH_HFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LH_KFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LH_KFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LH_KFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "LH_WHL_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "LH_WHL")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "LH_WHL_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RH_HAA"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.307 -0.06 -0.07376")] [],
.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "RH_hip")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-0.87"), ("upper", "0.87"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RH_hip")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RH_hip.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.053246 -0.009578 -0.000256")] [],
.text "\n            ",
.element "mass" [("value", "1.434")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001158337"), ("ixy", "-2.5451e-05"), ("ixz", "-7.91e-07"), ("iyy", "0.001701117"), ("iyz", "1.883e-06"), ("izz", "0.001372051")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RH_HFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.058 -0.0408 0")] [],
.text "\n        ",
.element "parent" [("link", "RH_hip")] [],
.text "\n        ",
.element "child" [("link", "RH_thigh")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "-2.27"), ("upper", "1.22"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RH_thigh")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RH_thigh.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.8902 0.8902 0.91373 1")] [],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.057303 -0.055844 0.004528")] [],
.text "\n            ",
.element "mass" [("value", "2.751")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.004607032"), ("ixy", "-0.004707351"), ("ixz", "0.001380725"), ("iyy", "0.028533909"), ("iyz", "0.000405022"), ("izz", "0.029844027")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RH_KFE"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.28 -0.08155 0")] [],
.text "\n        ",
.element "parent" [("link", "RH_thigh")] [],
.text "\n        ",
.element "child" [("link", "RH_calf")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.05"), ("friction", "0.01")] [],
.text "\n        ",
.element "limit" [("effort", "60"), ("lower", "0"), ("upper", "2.0943951023932"), ("velocity", "20")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RH_calf")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RH_calf.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.20392 0.20392 0.20392 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0.680678408 0"), ("xyz", "0.10876 0 -0.08805")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.28 0.023 0.0451")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.172578 -0.002711 -0.142172")] [],
.text "\n            ",
.element "mass" [("value", "1.326")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.006426995"), ("ixy", "0.000131916"), ("ixz", "0.006446843"), ("iyy", "0.01424856"), ("iyz", "-0.000130699"), ("izz", "0.008429207")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RH_WHL"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.21449 -0.03434 -0.17998")] [],
.text "\n        ",
.element "parent" [("link", "RH_calf")] [],
.text "\n        ",
.element "child" [("link", "RH_wheel")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("lower", "-1000"), ("upper", "1000"), ("velocity", "20")] [],
.text "\n        ",
.element "dynamics" [("friction", "1")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RH_wheel")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/wheellegged/WL_P311D/meshes/RH_wheel.STL"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n            ",
.element "color" [("rgba", "0.69804 0.69804 0.69804 1")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.017"), ("radius", "0.127")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "3.8e-05 -0.000878 5.1e-05")] [],
.text "\n            ",
.element "mass" [("value", "0.818")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.003929539"), ("ixy", "-1e-08"), ("ixz", "1.808e-06"), ("iyy", "0.007451249"), ("iyz", "-6.7e-08"), ("izz", "0.003930825")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "RH_foot_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_wheel")] [],
.text "\n        ",
.element "child" [("link", "RH_foot")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.127")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "RH_foot")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "RH_foot_fixed")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RH_HAA_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RH_HAA")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RH_HAA_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RH_HFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RH_HFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RH_HFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RH_KFE_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RH_KFE")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RH_KFE_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "RH_WHL_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "RH_WHL")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "RH_WHL_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n"],
[],
[],
"71f711c603f3f35b17bc54cfd074bcc4dd86349325546ff21d23967da1f123d2"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
