import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "baxter")] [.text "\n  ",
.element "link" [("name", "base")] [.text "\n  "],
.text "\n  ",
.element "link" [("name", "torso")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/torso/base_link.DAE")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/torso/base_link_collision.DAE")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "35.336455")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.849155"), ("ixy", "-0.000354"), ("ixz", "-0.154188"), ("iyy", "1.662671"), ("iyz", "0.003292"), ("izz", "0.802239")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_torso_itb")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_torso_itb")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "pedestal")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/base/PEDESTAL.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkgray")] [.text "\n        ",
.element "color" [("rgba", ".2 .2 .2 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/base/pedestal_link_collision.DAE")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "60.86397744")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.0635929"), ("ixy", "0.00103417"), ("ixz", "0.80199628"), ("iyy", "6.08689388"), ("iyz", "0.00105311"), ("izz", "4.96191932")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "head")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 .00953")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/head/H0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkgray")] [.text "\n        ",
.element "color" [("rgba", ".2 .2 .2 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0 0.0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.547767")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.004641"), ("ixy", "0.000159"), ("ixz", "0.000242"), ("iyy", "0.003295"), ("iyz", "-0.001324"), ("izz", "0.003415")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "sonar_ring")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-.0347 0 .00953")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.01"), ("radius", "0.085")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkgray")] [.text "\n        ",
.element "color" [("rgba", ".2 .2 .2 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0 0.0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "screen")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 -1.57079632679 0"), ("xyz", "0 -.00953 -.0347")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/head/H1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0 0.0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.440171")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.004006"), ("ixy", "0.000230"), ("ixz", "0.000002"), ("iyy", "0.002800"), ("iyz", "0.000029"), ("izz", "0.001509")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "display")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0.2617993877991494 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.218 0.16 0.001")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "head_camera")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "dummyhead1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "collision_head_link_1")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "red")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.3 0.3 0.3")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "-0.07 -0.04 0.0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.22")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "collision_head_link_2")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.001")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "red")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.3 0.3 0.3")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.07 0.04 0.00")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.22")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "collision_head_1"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.11 0 0.75")] [],
.text "\n    ",
.element "parent" [("link", "base")] [],
.text "\n    ",
.element "child" [("link", "collision_head_link_1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "collision_head_2"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.11 0 0.75")] [],
.text "\n    ",
.element "parent" [("link", "base")] [],
.text "\n    ",
.element "child" [("link", "collision_head_link_2")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "dummy"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "dummyhead1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "torso_t0"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base")] [],
.text "\n    ",
.element "child" [("link", "torso")] [],
.text "\n    ",
.element "limit" [("effort", "50000"), ("lower", "-3.01"), ("upper", "3.01"), ("velocity", "10000")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_torso_itb_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 3.1415 0"), ("xyz", "-0.08897 0.15593 0.389125")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "left_torso_itb")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_torso_itb_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "-0.08897 -0.15593 0.389125")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "right_torso_itb")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "pedestal_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "pedestal")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "head_pan"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.06 0 0.686")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "head")] [],
.text "\n    ",
.element "limit" [("effort", "50000"), ("lower", "-1.57079632679"), ("upper", "1.57079632679"), ("velocity", "10000")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "head_nod"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.75057 0 1.57079632679"), ("xyz", ".1227 0 0")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "screen")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "head_camera"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.75057 0 1.57079632679"), ("xyz", "0.12839 0 0.06368")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "head_camera")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "display_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.016 0.0")] [],
.text "\n    ",
.element "parent" [("link", "screen")] [],
.text "\n    ",
.element "child" [("link", "display")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "sonar_s0"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0947 0 .817")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "sonar_ring")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_arm_mount")] [.text "\n    \n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_upper_shoulder")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/upper_shoulder/S0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.1361")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.2722"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01783 0.00086 0.19127")] [],
.text "\n      ",
.element "mass" [("value", "5.70044")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.04709102262"), ("ixy", "0.00012787556"), ("ixz", "0.00614870039"), ("iyy", "0.03766976455"), ("iyz", "0.00078086899"), ("izz", "0.03595988478")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_lower_shoulder")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/lower_shoulder/S1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.12"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.06845 0.00269 -0.00529")] [],
.text "\n      ",
.element "mass" [("value", "3.22698")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01175209419"), ("ixy", "-0.00030096398"), ("ixz", "0.00207675762"), ("iyy", "0.0278859752"), ("iyz", "-0.00018821993"), ("izz", "0.02078749298")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_upper_elbow")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/upper_elbow/E0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0535")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.107"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00276 0.00132 0.18086")] [],
.text "\n      ",
.element "mass" [("value", "4.31272")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02661733557"), ("ixy", "0.00029270634"), ("ixz", "0.00392189887"), ("iyy", "0.02844355207"), ("iyz", "0.0010838933"), ("izz", "0.01248008322")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_upper_elbow_visual")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.1365")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.273"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_lower_elbow")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/lower_elbow/E1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.10"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.02611 0.00159 -0.01117")] [],
.text "\n      ",
.element "mass" [("value", "2.07206")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00711582686"), ("ixy", "0.00036036173"), ("ixz", "0.0007459496"), ("iyy", "0.01318227876"), ("iyz", "-0.00019663418"), ("izz", "0.00926852064")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_upper_forearm")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/upper_forearm/W0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.044")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.088"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00168 0.0046 0.13952")] [],
.text "\n      ",
.element "mass" [("value", "2.24665")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01667742825"), ("ixy", "0.00018403705"), ("ixz", "0.00018657629"), ("iyy", "0.01675457264"), ("iyz", "-0.00064732352"), ("izz", "0.0037463115")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_upper_forearm_visual")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.136")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.272"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_arm_itb")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_lower_forearm")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/lower_forearm/W1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.10"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.06041 0.00697 0.006")] [],
.text "\n      ",
.element "mass" [("value", "1.60979")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00387607152"), ("ixy", "-0.00044384784"), ("ixz", "-0.00021115038"), ("iyy", "0.00700537914"), ("iyz", "0.00015348067"), ("izz", "0.0055275524")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_wrist")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/wrist/W2.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "lightgrey")] [.text "\n        ",
.element "color" [("rgba", ".1 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.165"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00198 0.00125 0.01855")] [],
.text "\n      ",
.element "mass" [("value", "0.35093")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00025289155"), ("ixy", "0.00000575311"), ("ixz", "-0.00000159345"), ("iyy", "0.0002688601"), ("iyz", "-0.00000519818"), ("izz", "0.0003074118")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hand")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0232")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.0464"), ("radius", "0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01093 0.00042 -0.01532")] [],
.text "\n      ",
.element "mass" [("value", "0.19125")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00017588"), ("ixy", "0.00000147073"), ("ixz", "0.0000243633"), ("iyy", "0.00021166377"), ("iyz", "0.00000172689"), ("izz", "0.00023745397")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hand_camera")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.01"), ("radius", "0.02")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0 0 1 0.8")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hand_camera_axis")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hand_range")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.005 .02 .005")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0 0 1 0.8")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hand_accelerometer")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_gripper_base")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.02")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.025 0.075 0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_gripper")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_torso_arm_mount"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 -0.7854"), ("xyz", "0.024645 -0.219645 0.118588")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "right_arm_mount")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_s0"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.055695 0 0.011038")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_arm_mount")] [],
.text "\n    ",
.element "child" [("link", "right_upper_shoulder")] [],
.text "\n    ",
.element "limit" [("effort", "50.0"), ("lower", "-1.70167993878"), ("upper", "1.70167993878"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_s1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "0.069 0 0.27035")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_upper_shoulder")] [],
.text "\n    ",
.element "child" [("link", "right_lower_shoulder")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "-2.147"), ("upper", "1.047"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_e0"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.102 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_lower_shoulder")] [],
.text "\n    ",
.element "child" [("link", "right_upper_elbow")] [],
.text "\n    ",
.element "limit" [("effort", "50.0"), ("lower", "-3.05417993878"), ("upper", "3.05417993878"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_e0_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.107 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_lower_shoulder")] [],
.text "\n    ",
.element "child" [("link", "right_upper_elbow_visual")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_e1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 -1.57079632679 0"), ("xyz", "0.069 0 0.26242")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_upper_elbow")] [],
.text "\n    ",
.element "child" [("link", "right_lower_elbow")] [],
.text "\n    ",
.element "limit" [("effort", "50.0"), ("lower", "-0.05"), ("upper", "2.618"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_w0"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.10359 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_lower_elbow")] [],
.text "\n    ",
.element "child" [("link", "right_upper_forearm")] [],
.text "\n    ",
.element "limit" [("effort", "15.0"), ("lower", "-3.059"), ("upper", "3.059"), ("velocity", "4.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_w0_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.088 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_lower_elbow")] [],
.text "\n    ",
.element "child" [("link", "right_upper_forearm_visual")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_w0_to_itb_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 1.57079632679"), ("xyz", "-0.0565 0 0.12")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_upper_forearm")] [],
.text "\n    ",
.element "child" [("link", "right_arm_itb")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_w1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 -1.57079632679 0"), ("xyz", "0.01 0 0.2707")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_upper_forearm")] [],
.text "\n    ",
.element "child" [("link", "right_lower_forearm")] [],
.text "\n    ",
.element "limit" [("effort", "15.0"), ("lower", "-1.57079632679"), ("upper", "2.094"), ("velocity", "4.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_w2"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.115975 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_lower_forearm")] [],
.text "\n    ",
.element "child" [("link", "right_wrist")] [],
.text "\n    ",
.element "limit" [("effort", "15.0"), ("lower", "-3.059"), ("upper", "3.059"), ("velocity", "4.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hand"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.11355")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "right_wrist")] [],
.text "\n    ",
.element "child" [("link", "right_hand")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hand_camera"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 -1.57079633"), ("xyz", "0.03825 0.012 0.015355")] [],
.text "\n    ",
.element "parent" [("link", "right_hand")] [],
.text "\n    ",
.element "child" [("link", "right_hand_camera")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hand_camera_axis"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03825 0.012 0.015355")] [],
.text "\n    ",
.element "parent" [("link", "right_hand")] [],
.text "\n    ",
.element "child" [("link", "right_hand_camera_axis")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hand_range"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 -1.57079632679 -1.57079632679"), ("xyz", "0.032 -0.020245 0.0288")] [],
.text "\n    ",
.element "parent" [("link", "right_hand")] [],
.text "\n    ",
.element "child" [("link", "right_hand_range")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hand_accelerometer"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00198 0.000133 -0.0146")] [],
.text "\n    ",
.element "parent" [("link", "right_hand")] [],
.text "\n    ",
.element "child" [("link", "right_hand_accelerometer")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_gripper_base"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "right_hand")] [],
.text "\n    ",
.element "child" [("link", "right_gripper_base")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_endpoint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0 0.025")] [],
.text "\n    ",
.element "parent" [("link", "right_gripper_base")] [],
.text "\n    ",
.element "child" [("link", "right_gripper")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_arm_mount")] [.text "\n    \n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_upper_shoulder")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/upper_shoulder/S0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.1361")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.2722"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01783 0.00086 0.19127")] [],
.text "\n      ",
.element "mass" [("value", "5.70044")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.04709102262"), ("ixy", "0.00012787556"), ("ixz", "0.00614870039"), ("iyy", "0.03766976455"), ("iyz", "0.00078086899"), ("izz", "0.03595988478")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_lower_shoulder")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/lower_shoulder/S1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.12"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.06845 0.00269 -0.00529")] [],
.text "\n      ",
.element "mass" [("value", "3.22698")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01175209419"), ("ixy", "-0.00030096398"), ("ixz", "0.00207675762"), ("iyy", "0.0278859752"), ("iyz", "-0.00018821993"), ("izz", "0.02078749298")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_upper_elbow")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/upper_elbow/E0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0535")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.107"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00276 0.00132 0.18086")] [],
.text "\n      ",
.element "mass" [("value", "4.31272")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.02661733557"), ("ixy", "0.00029270634"), ("ixz", "0.00392189887"), ("iyy", "0.02844355207"), ("iyz", "0.0010838933"), ("izz", "0.01248008322")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_upper_elbow_visual")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.1365")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.273"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_lower_elbow")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/lower_elbow/E1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.10"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.02611 0.00159 -0.01117")] [],
.text "\n      ",
.element "mass" [("value", "2.07206")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00711582686"), ("ixy", "0.00036036173"), ("ixz", "0.0007459496"), ("iyy", "0.01318227876"), ("iyz", "-0.00019663418"), ("izz", "0.00926852064")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_upper_forearm")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/upper_forearm/W0.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.044")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.088"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00168 0.0046 0.13952")] [],
.text "\n      ",
.element "mass" [("value", "2.24665")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.01667742825"), ("ixy", "0.00018403705"), ("ixz", "0.00018657629"), ("iyy", "0.01675457264"), ("iyz", "-0.00064732352"), ("izz", "0.0037463115")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_upper_forearm_visual")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.136")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.272"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_arm_itb")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_lower_forearm")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/lower_forearm/W1.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.10"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.06041 0.00697 0.006")] [],
.text "\n      ",
.element "mass" [("value", "1.60979")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00387607152"), ("ixy", "-0.00044384784"), ("ixz", "-0.00021115038"), ("iyy", "0.00700537914"), ("iyz", "0.00015348067"), ("izz", "0.0055275524")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_wrist")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://baxter_description/meshes/wrist/W2.DAE")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "lightgrey")] [.text "\n        ",
.element "color" [("rgba", ".1 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.165"), ("radius", "0.06")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00198 0.00125 0.01855")] [],
.text "\n      ",
.element "mass" [("value", "0.35093")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00025289155"), ("ixy", "0.00000575311"), ("ixz", "-0.00000159345"), ("iyy", "0.0002688601"), ("iyz", "-0.00000519818"), ("izz", "0.0003074118")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hand")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0232")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.0464"), ("radius", "0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01093 0.00042 -0.01532")] [],
.text "\n      ",
.element "mass" [("value", "0.19125")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00017588"), ("ixy", "0.00000147073"), ("ixz", "0.0000243633"), ("iyy", "0.00021166377"), ("iyz", "0.00000172689"), ("izz", "0.00023745397")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hand_camera")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.01"), ("radius", "0.02")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0 0 1 0.8")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hand_camera_axis")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hand_range")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.005 .02 .005")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0 0 1 0.8")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hand_accelerometer")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_gripper_base")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.02")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.025 0.075 0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "darkred")] [.text "\n        ",
.element "color" [("rgba", ".5 .1 .1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_gripper")] [.text "\n ",
.element "gravity" [] [.text "0"],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.000000 0.000000 0.000000")] [],
.text "\n      ",
.element "mass" [("value", "0.0001")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-08"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-08"), ("iyz", "0"), ("izz", "1e-08")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_torso_arm_mount"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0.7854"), ("xyz", "0.024645 0.219645 0.118588")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "left_arm_mount")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_s0"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.055695 0 0.011038")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_arm_mount")] [],
.text "\n    ",
.element "child" [("link", "left_upper_shoulder")] [],
.text "\n    ",
.element "limit" [("effort", "50.0"), ("lower", "-1.70167993878"), ("upper", "1.70167993878"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_s1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "0.069 0 0.27035")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_upper_shoulder")] [],
.text "\n    ",
.element "child" [("link", "left_lower_shoulder")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "-2.147"), ("upper", "1.047"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_e0"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.102 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_lower_shoulder")] [],
.text "\n    ",
.element "child" [("link", "left_upper_elbow")] [],
.text "\n    ",
.element "limit" [("effort", "50.0"), ("lower", "-3.05417993878"), ("upper", "3.05417993878"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_e0_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.107 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_lower_shoulder")] [],
.text "\n    ",
.element "child" [("link", "left_upper_elbow_visual")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_e1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 -1.57079632679 0"), ("xyz", "0.069 0 0.26242")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_upper_elbow")] [],
.text "\n    ",
.element "child" [("link", "left_lower_elbow")] [],
.text "\n    ",
.element "limit" [("effort", "50.0"), ("lower", "-0.05"), ("upper", "2.618"), ("velocity", "1.5")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_w0"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.10359 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_lower_elbow")] [],
.text "\n    ",
.element "child" [("link", "left_upper_forearm")] [],
.text "\n    ",
.element "limit" [("effort", "15.0"), ("lower", "-3.059"), ("upper", "3.059"), ("velocity", "4.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_w0_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.088 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_lower_elbow")] [],
.text "\n    ",
.element "child" [("link", "left_upper_forearm_visual")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_w0_to_itb_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 1.57079632679"), ("xyz", "-0.0565 0 0.12")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_upper_forearm")] [],
.text "\n    ",
.element "child" [("link", "left_arm_itb")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_w1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 -1.57079632679 0"), ("xyz", "0.01 0 0.2707")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_upper_forearm")] [],
.text "\n    ",
.element "child" [("link", "left_lower_forearm")] [],
.text "\n    ",
.element "limit" [("effort", "15.0"), ("lower", "-1.57079632679"), ("upper", "2.094"), ("velocity", "4.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_w2"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 1.57079632679"), ("xyz", "0.115975 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_lower_forearm")] [],
.text "\n    ",
.element "child" [("link", "left_wrist")] [],
.text "\n    ",
.element "limit" [("effort", "15.0"), ("lower", "-3.059"), ("upper", "3.059"), ("velocity", "4.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hand"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.11355")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "left_wrist")] [],
.text "\n    ",
.element "child" [("link", "left_hand")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.7"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hand_camera"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 -1.57079633"), ("xyz", "0.03825 0.012 0.015355")] [],
.text "\n    ",
.element "parent" [("link", "left_hand")] [],
.text "\n    ",
.element "child" [("link", "left_hand_camera")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hand_camera_axis"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03825 0.012 0.015355")] [],
.text "\n    ",
.element "parent" [("link", "left_hand")] [],
.text "\n    ",
.element "child" [("link", "left_hand_camera_axis")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hand_range"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 -1.57079632679 -1.57079632679"), ("xyz", "0.032 -0.020245 0.0288")] [],
.text "\n    ",
.element "parent" [("link", "left_hand")] [],
.text "\n    ",
.element "child" [("link", "left_hand_range")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hand_accelerometer"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00198 0.000133 -0.0146")] [],
.text "\n    ",
.element "parent" [("link", "left_hand")] [],
.text "\n    ",
.element "child" [("link", "left_hand_accelerometer")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_gripper_base"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "left_hand")] [],
.text "\n    ",
.element "child" [("link", "left_gripper_base")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_endpoint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0 0.025")] [],
.text "\n    ",
.element "parent" [("link", "left_gripper_base")] [],
.text "\n    ",
.element "child" [("link", "left_gripper")] [],
.text "\n  "],
.text "\n\n  \n\n  \n  ",
.element "transmission" [("name", "right_tran1")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_s0")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "right_tran2")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_s1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor2")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "right_tran3")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_e0")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor3")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "right_tran4")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_e1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor4")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "right_tran5")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_w0")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor5")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "right_tran6")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_w1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor6")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "right_tran7")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "right_w2")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "right_motor7")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "transmission" [("name", "left_tran1")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_s0")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "left_tran2")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_s1")] [.text "      \n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor2")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "left_tran3")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_e0")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor3")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "left_tran4")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_e1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor4")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "left_tran5")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_w0")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor5")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "left_tran6")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_w1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor6")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "left_tran7")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "left_w2")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "left_motor7")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "transmission" [("name", "head1")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "head_pan")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "head_motor1")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("name", "baxter_ros_control"), ("filename", "libbaxter_gazebo_ros_control.so")] [.text "\n      ",
.element "robotNamespace" [] [.text "/robot"],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "gazebo" [("reference", "torso")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "head_pan")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_s0")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_s1")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_e0")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_e1")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_w0")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_w1")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_w2")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_s0")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_s1")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_e0")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_e1")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_w0")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_w1")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_w2")] [.text "\n    ",
.element "implicitSpringDamper" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "head_camera")] [.text "\n    ",
.element "sensor" [("name", "head_camera"), ("type", "camera")] [.text "\n      ",
.element "update_rate" [] [.text "30.0"],
.text "\n      ",
.element "camera" [("name", "head_camera")] [.text "\n        ",
.element "pose" [] [.text "0.0 0.21 0.0 0.0 -0.8 -1.570796327 "],
.text "\n        ",
.element "horizontal_fov" [] [.text "1.3962634"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "800"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "300"],
.text "\n        "],
.text "\n        ",
.element "noise" [] [.text "\n          ",
.element "type" [] [.text "gaussian"],
.text "\n          ",
.element "mean" [] [.text "0.0"],
.text "\n          ",
.element "stddev" [] [.text "0.007"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "head_camera"],
.text "\n        ",
.element "imageTopicName" [] [.text "image"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "head_camera"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.07"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "robotNamespace" [] [.text "/cameras"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_hand_camera")] [.text "\n    ",
.element "sensor" [("name", "right_hand_camera"), ("type", "camera")] [.text "\n      ",
.element "update_rate" [] [.text "30.0"],
.text "\n      ",
.element "camera" [("name", "right_hand_camera")] [.text "\n        ",
.element "pose" [] [.text "0.0 0.0 0.0 0.0 -1.570796327 1.570796327 "],
.text "\n        ",
.element "horizontal_fov" [] [.text "1.3962634"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "800"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "300"],
.text "\n        "],
.text "\n        ",
.element "noise" [] [.text "\n          ",
.element "type" [] [.text "gaussian"],
.text "\n          ",
.element "mean" [] [.text "0.0"],
.text "\n          ",
.element "stddev" [] [.text "0.007"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "right_hand_camera"],
.text "\n        ",
.element "imageTopicName" [] [.text "image"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "right_hand_camera"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.07"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "robotNamespace" [] [.text "/cameras"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_hand_camera")] [.text "\n    ",
.element "sensor" [("name", "left_hand_camera"), ("type", "camera")] [.text "\n      ",
.element "update_rate" [] [.text "30.0"],
.text "\n      ",
.element "camera" [("name", "left_hand_camera")] [.text "\n        ",
.element "pose" [] [.text "0.0 0.0 0.0 0.0 -1.570796327 1.570796327 "],
.text "\n        ",
.element "horizontal_fov" [] [.text "1.3962634"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "800"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "300"],
.text "\n        "],
.text "\n        ",
.element "noise" [] [.text "\n          ",
.element "type" [] [.text "gaussian"],
.text "\n          ",
.element "mean" [] [.text "0.0"],
.text "\n          ",
.element "stddev" [] [.text "0.007"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "left_hand_camera"],
.text "\n        ",
.element "imageTopicName" [] [.text "image"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "left_hand_camera"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.07"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "robotNamespace" [] [.text "/cameras"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "display")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("name", "screen_video_controller"), ("filename", "libgazebo_ros_video.so")] [.text "\n        ",
.element "height" [] [.text "600"],
.text "\n        ",
.element "width" [] [.text "1024"],
.text "\n        ",
.element "topicName" [] [.text "/robot/xdisplay"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "sonar_ring")] [.text "\n    ",
.element "sensor" [("name", "sonar"), ("type", "ray")] [.text "\n      ",
.element "pose" [] [.text "0.0 0.0 0.0 0.0 0.0 0.0"],
.text "\n      ",
.element "ray" [] [.text "\n        ",
.element "scan" [] [.text "\n          ",
.element "horizontal" [] [.text "\n            ",
.element "samples" [] [.text "12"],
.text "\n            ",
.element "resolution" [] [.text "1.0"],
.text "\n            ",
.element "min_angle" [] [.text "-3.14"],
.text "\n            ",
.element "max_angle" [] [.text "3.14"],
.text "\n          "],
.text "\n          ",
.element "vertical" [] [.text "\n            ",
.element "samples" [] [.text "2"],
.text "\n            ",
.element "resolution" [] [.text "1.0"],
.text "\n            ",
.element "min_angle" [] [.text "-0.001"],
.text "\n            ",
.element "max_angle" [] [.text "0"],
.text "\n          "],
.text "\n        "],
.text "\n        ",
.element "range" [] [.text "\n          ",
.element "min" [] [.text "0.05"],
.text "\n          ",
.element "max" [] [.text "50.0"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("name", "sonar_plugin"), ("filename", "libgazebo_ros_block_laser.so")] [.text "\n        ",
.element "gaussianNoise" [] [.text "0.00"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "100.0"],
.text "\n        ",
.element "topicName" [] [.text "/robot/sonar/head_sonar/state"],
.text "\n        ",
.element "frameName" [] [.text "sonar_ring"],
.text "\n      "],
.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "100.0"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "right_hand_range")] [.text "\n    ",
.element "sensor" [("name", "ir_right"), ("type", "ray")] [.text "\n      ",
.element "pose" [] [.text "0.0 0.0 0.0 0.0 0.0 0.0"],
.text "\n      ",
.element "ray" [] [.text "\n        ",
.element "scan" [] [.text "\n          ",
.element "horizontal" [] [.text "\n            ",
.element "samples" [] [.text "1"],
.text "\n            ",
.element "resolution" [] [.text "1.0"],
.text "\n            ",
.element "min_angle" [] [.text "-0.5"],
.text "\n            ",
.element "max_angle" [] [.text "0.5"],
.text "\n          "],
.text "\n        "],
.text "\n        ",
.element "range" [] [.text "\n          ",
.element "min" [] [.text "0.004"],
.text "\n          ",
.element "max" [] [.text "0.4"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("name", "plugin_3"), ("filename", "libgazebo_ros_laser.so")] [.text "\n        ",
.element "gaussianNoise" [] [.text "0.005"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "100"],
.text "\n        ",
.element "topicName" [] [.text "/sim/laserscan/right_hand_range/state"],
.text "\n        ",
.element "frameName" [] [.text "right_hand_range"],
.text "\n      "],
.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "100.0"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "left_hand_range")] [.text "\n    ",
.element "sensor" [("name", "ir_left"), ("type", "ray")] [.text "\n      ",
.element "pose" [] [.text "0.0 0.0 0.0 0.0 0.0 0.0"],
.text "\n      ",
.element "ray" [] [.text "\n        ",
.element "scan" [] [.text "\n          ",
.element "horizontal" [] [.text "\n            ",
.element "samples" [] [.text "1"],
.text "\n            ",
.element "resolution" [] [.text "1.0"],
.text "\n            ",
.element "min_angle" [] [.text "-0.5"],
.text "\n            ",
.element "max_angle" [] [.text "0.5"],
.text "\n          "],
.text "\n        "],
.text "\n        ",
.element "range" [] [.text "\n          ",
.element "min" [] [.text "0.004"],
.text "\n          ",
.element "max" [] [.text "0.4"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("name", "plugin_4"), ("filename", "libgazebo_ros_laser.so")] [.text "\n        ",
.element "gaussianNoise" [] [.text "0.005"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "100"],
.text "\n        ",
.element "topicName" [] [.text "/sim/laserscan/left_hand_range/state"],
.text "\n        ",
.element "frameName" [] [.text "left_hand_range"],
.text "\n      "],
.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "100.0"],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"ab936bfb412f9d94e54563107078d6862349975ee8235e5590f235b3664e6d51"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
