import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "hyq"), ("xmlns:xacro", "http://ros.org/wiki/xacro")] [.text "\n  ",
.element "material" [("name", "white")] [.text "\n    ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "black")] [.text "\n    ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n  "],
.text "\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_control.so"), ("name", "gazebo_ros_controller_manager")] [.text "\n      ",
.element "robotNamespace" [] [.text "/hyq"],
.text "\n      \n      ",
.element "controlPeriod" [] [.text "0.004"],
.text "\n    "],
.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_p3d.so"), ("name", "gazebo_ros_p3d")] [.text "\n      ",
.element "robotNamespace" [] [.text "/hyq"],
.text "\n      ",
.element "bodyName" [] [.text "trunk"],
.text "\n      ",
.element "topicName" [] [.text "ground_truth"],
.text "\n      ",
.element "frameName" [] [.text "world"],
.text "\n      ",
.element "xyzOffsets" [] [.text "0 0 0"],
.text "\n      ",
.element "rpyOffsets" [] [.text "0 0 0"],
.text "\n      ",
.element "gaussianNoise" [] [.text "0"],
.text "\n      ",
.element "alwaysOn" [] [.text "true"],
.text "\n      ",
.element "updateRate" [] [.text "250.0"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  \n  \n  \n  ",
.element "joint" [("name", "floating_base"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "trunk")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "base_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "1e-6"), ("ixz", "1e-6"), ("iyy", "1e-6"), ("iyz", "1e-6"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.01"), ("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "trunk")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.056 0.0215 0.00358")] [],
.text "\n      ",
.element "mass" [("value", "60.96")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.5725937"), ("ixy", "0.028375"), ("ixz", "-0.203139"), ("iyy", "8.5015928"), ("iyz", "-0.004462"), ("izz", "9.1954911")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/trunk/trunk.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/trunk/trunk.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "trunk")] [.text "\n    ",
.element "mu1" [] [.text "1.5"],
.text "\n    ",
.element "mu2" [] [.text "1.5"],
.text "\n  "],
.text "\n  \n  \n  \n  ",
.element "joint" [("name", "lf_haa_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 1.57079632679 3.14159265359"), ("xyz", "0.3735 0.207 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "lf_hipassembly")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-1.2217304764"), ("upper", "0.436332312999"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-1.2217304764"), ("soft_upper_limit", "0.436332312999")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "lf_hfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.08 0 0")] [],
.text "\n    ",
.element "parent" [("link", "lf_hipassembly")] [],
.text "\n    ",
.element "child" [("link", "lf_upperleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-0.872664625997"), ("upper", "1.2217304764"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-0.872664625997"), ("soft_upper_limit", "1.2217304764")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "lf_kfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.35 0 0")] [],
.text "\n    ",
.element "parent" [("link", "lf_upperleg")] [],
.text "\n    ",
.element "child" [("link", "lf_lowerleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-2.44346095279"), ("upper", "-0.349065850399"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-2.44346095279"), ("soft_upper_limit", "-0.349065850399")] [],
.text "\n    \n  "],
.text "\n  ",
.element "joint" [("name", "lf_foot_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 -1.57079632679"), ("xyz", "0.346 0 0")] [],
.text "\n    ",
.element "parent" [("link", "lf_lowerleg")] [],
.text "\n    ",
.element "child" [("link", "lf_foot")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "lf_hipassembly")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.04263         0.0         0.16931")] [],
.text "\n      ",
.element "mass" [("value", "2.93")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.05071"), ("ixy", "-4e-05"), ("ixz", "-0.00159"), ("iyy", "0.05486"), ("iyz", "-5e-05"), ("izz", "0.00571")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "lf_upperleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.15074 -0.02625 0.0")] [],
.text "\n      ",
.element "mass" [("value", "2.638")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00368"), ("ixy", "-0.00302"), ("ixz", "0.0001"), ("iyy", "0.02719"), ("iyz", "2e-05"), ("izz", "0.02811")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "lf_lowerleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.1254 4e-05 -0.0001")] [],
.text "\n      ",
.element "mass" [("value", "0.881")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00047"), ("ixy", "6e-05"), ("ixz", "-1e-05"), ("iyy", "0.01256"), ("iyz", "-0.0"), ("izz", "0.01233")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/lowerleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 -1.57079632679  0"), ("xyz", "0.173 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.346"), ("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "lf_foot")] [.text "\n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1")] [],
.text "\n      ",
.element "stiffness" [("value", "30000")] [],
.text "\n      ",
.element "damping" [("value", "1000")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "1e-6"), ("ixz", "1e-6"), ("iyy", "1e-6"), ("iyz", "1e-6"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "transmission" [("name", "lf_haa_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "lf_haa_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "lf_haa_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "lf_hfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "lf_hfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "lf_hfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "lf_kfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "lf_kfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "lf_kfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lf_haa_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lf_kfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lf_hfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lf_upperleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.5"],
.text "\n    ",
.element "mu2" [] [.text "1.5"],
.text "\n    ",
.element "fdir1" [] [.text "1 0 0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "minDepth" [] [.text "0.00"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lf_lowerleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "lf_shin_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "lf_lowerleg_collision"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "lf_shin_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/lf_shin_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lf_foot")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "lf_foot_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "lf_lowerleg_fixed_joint_lump__lf_foot_collision_1"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "lf_foot_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/lf_foot_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n        ",
.element "robotNamespace" [] [.text "hyq"],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "material" [] [.text "Gazebo/Black"],
.text "\n  "],
.text "\n  \n  \n  \n  ",
.element "joint" [("name", "rf_haa_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.3735 -0.207 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "rf_hipassembly")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-1.2217304764"), ("upper", "0.436332312999"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-1.2217304764"), ("soft_upper_limit", "0.436332312999")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "rf_hfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "0.08 0 0")] [],
.text "\n    ",
.element "parent" [("link", "rf_hipassembly")] [],
.text "\n    ",
.element "child" [("link", "rf_upperleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-0.872664625997"), ("upper", "1.2217304764"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-0.872664625997"), ("soft_upper_limit", "1.2217304764")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "rf_kfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.35 0 0")] [],
.text "\n    ",
.element "parent" [("link", "rf_upperleg")] [],
.text "\n    ",
.element "child" [("link", "rf_lowerleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-2.44346095279"), ("upper", "-0.349065850399"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-2.44346095279"), ("soft_upper_limit", "-0.349065850399")] [],
.text "\n    \n  "],
.text "\n  ",
.element "joint" [("name", "rf_foot_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 -1.57079632679"), ("xyz", "0.346 0 0")] [],
.text "\n    ",
.element "parent" [("link", "rf_lowerleg")] [],
.text "\n    ",
.element "child" [("link", "rf_foot")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "rf_hipassembly")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.04263         -0.0         -0.16931")] [],
.text "\n      ",
.element "mass" [("value", "2.93")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.05071"), ("ixy", "4e-05"), ("ixz", "0.00159"), ("iyy", "0.05486"), ("iyz", "-5e-05"), ("izz", "0.00571")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "rf_upperleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.15074 -0.02625 0.0")] [],
.text "\n      ",
.element "mass" [("value", "2.638")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00368"), ("ixy", "-0.00302"), ("ixz", "0.0001"), ("iyy", "0.02719"), ("iyz", "2e-05"), ("izz", "0.02811")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "rf_lowerleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.1254 4e-05 -0.0001")] [],
.text "\n      ",
.element "mass" [("value", "0.881")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00047"), ("ixy", "6e-05"), ("ixz", "-1e-05"), ("iyy", "0.01256"), ("iyz", "-0.0"), ("izz", "0.01233")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/lowerleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 -1.57079632679  0"), ("xyz", "0.173 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.346"), ("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "rf_foot")] [.text "\n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1")] [],
.text "\n      ",
.element "stiffness" [("value", "30000")] [],
.text "\n      ",
.element "damping" [("value", "1000")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "1e-6"), ("ixz", "1e-6"), ("iyy", "1e-6"), ("iyz", "1e-6"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "transmission" [("name", "rf_haa_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "rf_haa_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "rf_haa_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "rf_hfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "rf_hfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "rf_hfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "rf_kfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "rf_kfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "rf_kfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rf_haa_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rf_kfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rf_hfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rf_upperleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.5"],
.text "\n    ",
.element "mu2" [] [.text "1.5"],
.text "\n    ",
.element "fdir1" [] [.text "1 0 0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "minDepth" [] [.text "0.00"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rf_lowerleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "rf_shin_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "rf_lowerleg_collision"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "rf_shin_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/rf_shin_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rf_foot")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "rf_foot_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "rf_lowerleg_fixed_joint_lump__rf_foot_collision_1"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "rf_foot_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/rf_foot_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n        ",
.element "robotNamespace" [] [.text "hyq"],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "material" [] [.text "Gazebo/Black"],
.text "\n  "],
.text "\n  \n  \n  \n  ",
.element "joint" [("name", "lh_haa_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 1.57079632679 3.14159265359"), ("xyz", "-0.3735 0.207 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "lh_hipassembly")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-1.2217304764"), ("upper", "0.436332312999"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-1.2217304764"), ("soft_upper_limit", "0.436332312999")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "lh_hfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.08 0 0")] [],
.text "\n    ",
.element "parent" [("link", "lh_hipassembly")] [],
.text "\n    ",
.element "child" [("link", "lh_upperleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-1.2217304764"), ("upper", "0.872664625997"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-1.2217304764"), ("soft_upper_limit", "0.872664625997")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "lh_kfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.35 0 0")] [],
.text "\n    ",
.element "parent" [("link", "lh_upperleg")] [],
.text "\n    ",
.element "child" [("link", "lh_lowerleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "0.349065850399"), ("upper", "2.44346095279"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "0.349065850399"), ("soft_upper_limit", "2.44346095279")] [],
.text "\n    \n  "],
.text "\n  ",
.element "joint" [("name", "lh_foot_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 -1.57079632679"), ("xyz", "0.346 0 0")] [],
.text "\n    ",
.element "parent" [("link", "lh_lowerleg")] [],
.text "\n    ",
.element "child" [("link", "lh_foot")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "lh_hipassembly")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.04263         -0.0         -0.16931")] [],
.text "\n      ",
.element "mass" [("value", "2.93")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.05071"), ("ixy", "4e-05"), ("ixz", "0.00159"), ("iyy", "0.05486"), ("iyz", "-5e-05"), ("izz", "0.00571")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "lh_upperleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.15074 0.02625 0.0")] [],
.text "\n      ",
.element "mass" [("value", "2.638")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00368"), ("ixy", "0.00302"), ("ixz", "-0.0001"), ("iyy", "0.02719"), ("iyz", "2e-05"), ("izz", "0.02811")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "lh_lowerleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.1254 -4e-05 0.0001")] [],
.text "\n      ",
.element "mass" [("value", "0.881")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00047"), ("ixy", "-6e-05"), ("ixz", "1e-05"), ("iyy", "0.01256"), ("iyz", "-0.0"), ("izz", "0.01233")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/lowerleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 -1.57079632679  0"), ("xyz", "0.173 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.346"), ("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "lh_foot")] [.text "\n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1")] [],
.text "\n      ",
.element "stiffness" [("value", "30000")] [],
.text "\n      ",
.element "damping" [("value", "1000")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "1e-6"), ("ixz", "1e-6"), ("iyy", "1e-6"), ("iyz", "1e-6"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "transmission" [("name", "lh_haa_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "lh_haa_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "lh_haa_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "lh_hfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "lh_hfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "lh_hfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "lh_kfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "lh_kfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "lh_kfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lh_haa_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lh_kfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lh_hfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lh_upperleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.5"],
.text "\n    ",
.element "mu2" [] [.text "1.5"],
.text "\n    ",
.element "fdir1" [] [.text "1 0 0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "minDepth" [] [.text "0.00"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lh_lowerleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "lh_shin_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "lh_lowerleg_collision"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "lh_shin_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/lh_shin_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "lh_foot")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "lh_foot_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "lh_lowerleg_fixed_joint_lump__lh_foot_collision_1"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "lh_foot_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/lh_foot_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n        ",
.element "robotNamespace" [] [.text "hyq"],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "material" [] [.text "Gazebo/Black"],
.text "\n  "],
.text "\n  \n  \n  \n  ",
.element "joint" [("name", "rh_haa_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.3735 -0.207 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "rh_hipassembly")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-1.2217304764"), ("upper", "0.436332312999"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-1.2217304764"), ("soft_upper_limit", "0.436332312999")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "rh_hfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "0.08 0 0")] [],
.text "\n    ",
.element "parent" [("link", "rh_hipassembly")] [],
.text "\n    ",
.element "child" [("link", "rh_upperleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "-1.2217304764"), ("upper", "0.872664625997"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "-1.2217304764"), ("soft_upper_limit", "0.872664625997")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "rh_kfe_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.35 0 0")] [],
.text "\n    ",
.element "parent" [("link", "rh_upperleg")] [],
.text "\n    ",
.element "child" [("link", "rh_lowerleg")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "150"), ("lower", "0.349065850399"), ("upper", "2.44346095279"), ("velocity", "12.0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "safety_controller" [("k_position", "50"), ("k_velocity", "10"), ("soft_lower_limit", "0.349065850399"), ("soft_upper_limit", "2.44346095279")] [],
.text "\n    \n  "],
.text "\n  ",
.element "joint" [("name", "rh_foot_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.57079632679 0 -1.57079632679"), ("xyz", "0.346 0 0")] [],
.text "\n    ",
.element "parent" [("link", "rh_lowerleg")] [],
.text "\n    ",
.element "child" [("link", "rh_foot")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "rh_hipassembly")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.04263         0.0         0.16931")] [],
.text "\n      ",
.element "mass" [("value", "2.93")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.05071"), ("ixy", "-4e-05"), ("ixz", "-0.00159"), ("iyy", "0.05486"), ("iyz", "-5e-05"), ("izz", "0.00571")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/hipassembly.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "rh_upperleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.15074 0.02625 0.0")] [],
.text "\n      ",
.element "mass" [("value", "2.638")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00368"), ("ixy", "0.00302"), ("ixz", "-0.0001"), ("iyy", "0.02719"), ("iyz", "2e-05"), ("izz", "0.02811")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "3.14159265359 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/upperleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "rh_lowerleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.1254 -4e-05 0.0001")] [],
.text "\n      ",
.element "mass" [("value", "0.881")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00047"), ("ixy", "-6e-05"), ("ixz", "1e-05"), ("iyy", "0.01256"), ("iyz", "-0.0"), ("izz", "0.01233")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/hyq_description/meshes/leg/lowerleg.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 -1.57079632679  0"), ("xyz", "0.173 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.346"), ("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "rh_foot")] [.text "\n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1")] [],
.text "\n      ",
.element "stiffness" [("value", "30000")] [],
.text "\n      ",
.element "damping" [("value", "1000")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "1e-6"), ("ixz", "1e-6"), ("iyy", "1e-6"), ("iyz", "1e-6"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02175")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "transmission" [("name", "rh_haa_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "rh_haa_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "rh_haa_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "rh_hfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "rh_hfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "rh_hfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "transmission" [("name", "rh_kfe_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "rh_kfe_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "rh_kfe_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rh_haa_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rh_kfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rh_hfe_joint")] [.text "\n    ",
.element "provideFeedback" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rh_upperleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.5"],
.text "\n    ",
.element "mu2" [] [.text "1.5"],
.text "\n    ",
.element "fdir1" [] [.text "1 0 0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "minDepth" [] [.text "0.00"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rh_lowerleg")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "rh_shin_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "rh_lowerleg_collision"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "rh_shin_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/rh_shin_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "rh_foot")] [.text "\n    ",
.element "kp" [] [.text "1000000.0"],
.text "\n    ",
.element "kd" [] [.text "100.0"],
.text "\n    ",
.element "mu1" [] [.text "1.0"],
.text "\n    ",
.element "mu2" [] [.text "1.0"],
.text "\n    ",
.element "maxVel" [] [.text "1.0"],
.text "\n    ",
.element "maxContacts" [] [.text "1"],
.text "\n    ",
.element "sensor" [("name", "rh_foot_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "250.0"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "rh_lowerleg_fixed_joint_lump__rh_foot_collision_1"],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_bumper.so"), ("name", "rh_foot_bumper")] [.text "\n        ",
.element "bumperTopicName" [] [.text "/hyq/rh_foot_bumper"],
.text "\n        ",
.element "frameName" [] [.text "base_link"],
.text "\n        ",
.element "robotNamespace" [] [.text "hyq"],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "material" [] [.text "Gazebo/Black"],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "trunk_imu_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 -3.14159265359 0"), ("xyz", "0.290 0.000 0.0999214")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "trunk_imu")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "trunk_imu")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00020  0.00010  0.00110")] [],
.text "\n      ",
.element "mass" [("value", "0.018")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0"), ("iyz", "0.0"), ("izz", "0.0")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00485 0 -0.00105")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.0329 0.0244 0.0111")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0 0 0 0.9")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_imu.so"), ("name", "trunk_imu_controller")] [.text "\n      ",
.element "alwaysOn" [] [.text "true"],
.text "\n      ",
.element "updateRate" [] [.text "250"],
.text "\n      ",
.element "bodyName" [] [.text "trunk_imu"],
.text "\n      ",
.element "topicName" [] [.text "trunk_imu/data"],
.text "\n      ",
.element "gaussianNoise" [] [.text "4e-08"],
.text "\n      ",
.element "xyzOffset" [] [.text "0 0 0"],
.text "\n      ",
.element "rpyOffset" [] [.text "0 0 0"],
.text "\n      ",
.element "serviceName" [] [.text "/trunk_imu_imu"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "trunk_imu")] [.text "\n    ",
.element "sensor" [("name", "trunk_imu"), ("type", "imu")] [.text "\n      ",
.element "always_on" [] [.text "1"],
.text "\n      ",
.element "update_rate" [] [.text "250"],
.text "\n      ",
.element "imu" [] [.text "\n        ",
.element "noise" [] [.text "\n          ",
.element "type" [] [.text "gaussian"],
.text "\n          ",
.element "rate" [] [.text "\n            ",
.element "mean" [] [.text "0"],
.text "\n            ",
.element "stddev" [] [.text "0.0002"],
.text "\n            ",
.element "bias_mean" [] [.text "0.00087"],
.text "\n            ",
.element "bias_stddev" [] [.text "8e-07"],
.text "\n          "],
.text "\n          ",
.element "accel" [] [.text "\n            ",
.element "mean" [] [.text "0"],
.text "\n            ",
.element "stddev" [] [.text "0.017"],
.text "\n            ",
.element "bias_mean" [] [.text "0.002"],
.text "\n            ",
.element "bias_stddev" [] [.text "0.001"],
.text "\n          "],
.text "\n        "],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"0846e80a596e0569f9b480f41cba97db299d6efcdd9406786df24dcf853fc5d5"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
