import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "robotiq_hand-e")] [.text "\n  ",
.element "link" [("name", "lhand_base")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.050025")] [],
.text "\n      ",
.element "mass" [("value", "1")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0011831687297672"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0011831687297672"), ("iyz", "0"), ("izz", "0.000698003452271223")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [("name", "Housing")] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://robotiq_hand-e/meshes/Housing.obj"), ("scale", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [("name", "Bolts")] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.04595")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://robotiq_hand-e/meshes/Bolts.obj"), ("scale", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [("name", "Housing_Collision_1")] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.050025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.10005"), ("radius", "0.0375")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "lhand_base_fixed_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.14 0 0"), ("xyz", "0 0 -0.06")] [],
.text "\n    ",
.element "parent" [("link", "l_palm")] [],
.text "\n    ",
.element "child" [("link", "lhand_base")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "lhand_FingerA")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0141 0.0051 0.0129")] [],
.text "\n      ",
.element "mass" [("value", "0.0450000018")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.51374875815236E-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.99499947181903E-06"), ("iyz", "0"), ("izz", "1.78874961420661E-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [("name", "FingerA_Visual")] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://robotiq_hand-e/meshes/FingerA.obj"), ("scale", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [("name", "FingerA_col_1")] [.text "\n      ",
.element "origin" [("xyz", "0.0141 0.0051 0.0129")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.006 0.021 0.036")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "lhand_FingerB")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0141 -0.0051 0.0129")] [],
.text "\n      ",
.element "mass" [("value", "0.0450000018")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.51374875815236E-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.99499947181903E-06"), ("iyz", "0"), ("izz", "1.78874961420661E-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [("name", "FingerB_Visual")] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://robotiq_hand-e/meshes/FingerB.obj"), ("scale", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [("name", "FingerB_col_1")] [.text "\n      ",
.element "origin" [("xyz", "-0.0141 -0.0051 0.0129")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.006 0.021 0.036")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "lhand_fingerA_joint"), ("type", "prismatic")] [.text "\n    ",
.element "origin" [("xyz", "0.013914 -0.00523 0.11505")] [],
.text "\n    ",
.element "parent" [("link", "lhand_base")] [],
.text "\n    ",
.element "child" [("link", "lhand_FingerA")] [],
.text "\n    ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "0.0"), ("upper", "0.025"), ("effort", "1000"), ("velocity", "1000")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "lhand_fingerB_joint"), ("type", "prismatic")] [.text "\n    ",
.element "origin" [("xyz", "-0.013914 0.00523 0.11505")] [],
.text "\n    ",
.element "parent" [("link", "lhand_base")] [],
.text "\n    ",
.element "child" [("link", "lhand_FingerB")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "0.0"), ("upper", "0.025"), ("effort", "1000"), ("velocity", "1000")] [],
.text "\n  "],
.text "\n"],
[],
[],
"abacd5a5459d92605bbf357f7859fde8454594c0adeaae500c745ed04f07a7fb"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
