import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "cf2")] [.text "\n\n  ",
.element "properties" [("arm", "0.0397"), ("kf", "3.16e-10"), ("km", "7.94e-12"), ("thrust2weight", "2.25"), ("max_speed_kmh", "30"), ("gnd_eff_coeff", "11.36859"), ("prop_radius", "2.31348e-2"), ("drag_coeff_xy", "9.1785e-7"), ("drag_coeff_z", "10.311e-7"), ("dw_coeff_1", "2267.18"), ("dw_coeff_2", ".16"), ("dw_coeff_3", "-.11")] [],
.text "\n\n  ",
.element "link" [("name", "base_link")] [.text " \n\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.027")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.3951e-5"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "2.3951e-5"), ("iyz", "0.0"), ("izz", "3.2347e-5")] [],
.text "\n    "],
.text "\n\n    \n\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 95"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "./cf2.dae"), ("scale", " 1 1 1")] [],
.text "\n      "],
.text " \n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", ".5 .5 .5 1")] [],
.text "\n      "],
.text " \n    "],
.text "\n\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("radius", ".06"), ("length", ".025")] [],
.text "\n      "],
.text "\n    "],
.text "  \n\n  "],
.text "\n\n  ",
.element "link" [("name", "prop0_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0397 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "prop0_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "prop0_link")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "prop1_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.0397 0")] [],
.text "\n      ",
.element "mass" [("value", "0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "prop1_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "prop1_link")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "prop2_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0397 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "prop2_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "prop2_link")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "prop3_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.0397 0")] [],
.text "\n      ",
.element "mass" [("value", "0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "prop3_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "prop3_link")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "center_of_mass_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "center_of_mass_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "center_of_mass_link")] [],
.text "\n  "],
.text "\n\n"],
[],
[],
"4ea77835521cd4afffd1350aa564b15d782b419724b4694f7ab74d02e3bd2042"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
