import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "N1")] [.text "\n    ",
.element "link" [("name", "base_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.00025493 1.049e-05 -0.05502"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "3.18")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.011139"), ("ixy", "-1.3e-07"), ("ixz", "-2.455e-05"), ("iyy", "0.007619"), ("iyz", "-9.79e-06"), ("izz", "0.0089904")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/base_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.05"), ("rpy", "1.57 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.135"), ("radius", "0.065")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_thigh_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.017114 0.035514 0.00025368"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "1.31")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.12319793999999999"), ("ixy", "0.0008376"), ("ixz", "-2.51e-06"), ("iyy", "0.12353984"), ("iyz", "-3.69e-06"), ("izz", "0.12463263999999999")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_thigh_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_thigh_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0029103 -4.92e-06 -0.020023"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "1.35")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.169481409139308"), ("ixy", "-2.66e-06"), ("ixz", "7.439e-05"), ("iyy", "0.169418509139308"), ("iyz", "-3.23e-06"), ("izz", "0.16889950913930799")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_thigh_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.57 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.0415")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_thigh_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0021441 -0.010608 -0.086616"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "3.37")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.18234200913930798"), ("ixy", "-8.532e-05"), ("ixz", "0.00058666"), ("iyy", "0.182416009139308"), ("iyz", "-0.00082274"), ("izz", "0.172899009139308")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_thigh_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.08"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.19"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_shank_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0027736 0.0049964 -0.13547"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "2.21")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.13462723999999998"), ("ixy", "2.941e-05"), ("ixz", "-0.0001756"), ("iyy", "0.13466324"), ("iyz", "-0.00024128"), ("izz", "0.12272264")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_shank_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.12"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.2"), ("radius", "0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_foot_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0018625 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.113")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.031307100000000004"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.03129395"), ("iyz", "0.0"), ("izz", "0.03131147")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_foot_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_foot_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.031083 -0.00011033 -0.031859"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.528")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.03153592"), ("ixy", "6.21e-06"), ("ixz", "9.43e-06"), ("iyy", "0.0329626"), ("iyz", "-6.8e-07"), ("izz", "0.0331146")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_thigh_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.017114 -0.035515 0.0002533"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "1.31")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.12319793999999999"), ("ixy", "-0.00083756"), ("ixz", "-2.59e-06"), ("iyy", "0.12353984"), ("iyz", "3.65e-06"), ("izz", "0.12463244")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_thigh_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_thigh_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0029092 1.208e-05 -0.020023"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "1.35")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.169481309139308"), ("ixy", "-3.06e-06"), ("ixz", "7.448e-05"), ("iyy", "0.169418609139308"), ("iyz", "-2.33e-06"), ("izz", "0.16889950913930799")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_thigh_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.57 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.0415")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_thigh_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.002043 0.010083 -0.086622"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "3.37")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.182417009139308"), ("ixy", "4.648e-05"), ("ixz", "0.00059303"), ("iyy", "0.182474009139308"), ("iyz", "0.00079496"), ("izz", "0.172904009139308")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_thigh_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.08"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.19"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_shank_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0026916 -0.004784 -0.13593"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "2.21")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.13445424"), ("ixy", "-2.679e-05"), ("ixz", "-0.00016834"), ("iyy", "0.13448124"), ("iyz", "0.00022613"), ("izz", "0.12274104")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_shank_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.12"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.2"), ("radius", "0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_foot_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 -0.0018793 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.113")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.03130717"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.03129395"), ("iyz", "0.0"), ("izz", "0.031311530000000004")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_foot_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_foot_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.031082 0.0001577 -0.031593"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.528")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.03153591"), ("ixy", "-6.64e-06"), ("ixz", "9.42e-06"), ("iyy", "0.032962500000000006"), ("iyz", "-1.1e-07"), ("izz", "0.0331146")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "imu_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0071125 0.0 0.00072936"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.038")] [],
.text "\n            ",
.element "inertia" [("ixx", "8.69e-06"), ("ixy", "0.0"), ("ixz", "5e-07"), ("iyy", "2.012e-05"), ("iyz", "0.0"), ("izz", "2.336e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/imu_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "waist_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.00025493 1.049e-05 -0.05502"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "3.18")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.178731009139308"), ("ixy", "-1.3e-07"), ("ixz", "-2.455e-05"), ("iyy", "0.17521100913930798"), ("iyz", "-9.79e-06"), ("izz", "0.176582409139308")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/waist_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.04"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.055"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "torso_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0070827 0.00038627 -0.041747"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "7.99")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.081895"), ("ixy", "4.891e-05"), ("ixz", "-0.00016303"), ("iyy", "0.070788"), ("iyz", "0.00029003"), ("izz", "0.035401")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/torso_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.06"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.22"), ("radius", "0.1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.19"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.08")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "camera_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.011772 0.0016608 2.48e-06"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.0382")] [],
.text "\n            ",
.element "inertia" [("ixx", "2.466e-05"), ("ixy", "1.7e-07"), ("ixz", "1e-08"), ("iyy", "3.66e-06"), ("iyz", "1e-08"), ("izz", "2.483e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/camera_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_upper_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00045952 0.060859 7.73e-05"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.885")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.16842761913930798"), ("ixy", "1.518e-05"), ("ixz", "2.12e-06"), ("iyy", "0.168111689139308"), ("iyz", "-9.9e-07"), ("izz", "0.168406149139308")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_upper_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_upper_arm_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0049529 0.00053148 -0.043369"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.033068600000000004"), ("ixy", "9.2e-07"), ("ixz", "-0.00015431"), ("iyy", "0.033179200000000006"), ("iyz", "-4.13e-06"), ("izz", "0.031772070000000006")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_upper_arm_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_upper_arm_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 -0.00057869 -0.060729"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.913")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0341776"), ("ixy", "-1.94e-06"), ("ixz", "-5.05e-06"), ("iyy", "0.034195500000000004"), ("iyz", "-3.918e-05"), ("izz", "0.031887450000000005")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_upper_arm_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_lower_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00053164 0.0049499 -0.04337"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0331788"), ("ixy", "-9.2e-07"), ("ixz", "4.05e-06"), ("iyy", "0.0330683"), ("iyz", "-0.00015416"), ("izz", "0.03177196")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_lower_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_hand_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0020835 6.386e-05 -0.013715"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.44")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.031715740000000006"), ("ixy", "9.3e-07"), ("ixz", "7.3e-07"), ("iyy", "0.031689800000000004"), ("iyz", "-3.5e-07"), ("izz", "0.03155227")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_hand_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_end_effector_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.003465 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.0994")] [],
.text "\n            ",
.element "inertia" [("ixx", "3.741e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "3.741e-05"), ("iyz", "0.0"), ("izz", "4.538e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_end_effector_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.02751")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_upper_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00045952 -0.060859 -7.73e-05"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.885")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.16842761913930798"), ("ixy", "-1.518e-05"), ("ixz", "-2.12e-06"), ("iyy", "0.168111689139308"), ("iyz", "-9.9e-07"), ("izz", "0.168406149139308")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_upper_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_upper_arm_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0049504 -0.0005218 -0.043377"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.033068"), ("ixy", "-9.2e-07"), ("ixz", "-0.00015415"), ("iyy", "0.0331785"), ("iyz", "3.9e-06"), ("izz", "0.031771690000000005")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_upper_arm_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_upper_arm_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.00055669 -0.060729"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.913")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.034176700000000004"), ("ixy", "-5.07e-06"), ("ixz", "3.43e-06"), ("iyy", "0.0341964"), ("iyz", "3.939e-05"), ("izz", "0.031887490000000004")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_upper_arm_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_lower_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0005218 -0.0049504 -0.043377"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0331785"), ("ixy", "9.2e-07"), ("ixz", "3.9e-06"), ("iyy", "0.033068"), ("iyz", "0.00015415"), ("izz", "0.031771690000000005")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_lower_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_hand_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00020719 -1.94e-05 -0.013715"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.44")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.03171447"), ("ixy", "1.81e-06"), ("ixz", "1.25e-06"), ("iyy", "0.03169107"), ("iyz", "-8.8e-07"), ("izz", "0.03155227")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_hand_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_end_effector_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.003465 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "0.0994")] [],
.text "\n            ",
.element "inertia" [("ixx", "3.741e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "3.741e-05"), ("iyz", "0.0"), ("izz", "4.538e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_end_effector_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.02751")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_hip_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "left_thigh_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.050453 -0.067365"), ("rpy", "-0.2618 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "95.0"), ("velocity", "12.356"), ("lower", "-2.617"), ("upper", "2.617")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_hip_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_thigh_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_thigh_roll_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.072 0.0"), ("rpy", "0.2618 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-0.261"), ("upper", "1.57")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_hip_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_thigh_roll_link")] [],
.text "\n        ",
.element "child" [("link", "left_thigh_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.0815"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-2.617"), ("upper", "2.617")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_knee_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_thigh_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "left_shank_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.2075"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "95.0"), ("velocity", "12.356"), ("lower", "-0.0872"), ("upper", "2.356")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_ankle_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_shank_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_foot_roll_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.28"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.436"), ("upper", "0.436")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_ankle_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_foot_roll_link")] [],
.text "\n        ",
.element "child" [("link", "left_foot_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.785"), ("upper", "0.785")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_hip_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "right_thigh_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 -0.050453 -0.067365"), ("rpy", "0.2618 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "95.0"), ("velocity", "12.356"), ("lower", "-2.617"), ("upper", "2.617")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_hip_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_thigh_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_thigh_roll_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 -0.072 0.0"), ("rpy", "-0.2618 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-1.57"), ("upper", "0.261")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_hip_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_thigh_roll_link")] [],
.text "\n        ",
.element "child" [("link", "right_thigh_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.0815"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-2.617"), ("upper", "2.617")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_knee_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_thigh_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "right_shank_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.2075"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "95.0"), ("velocity", "12.356"), ("lower", "-0.0872"), ("upper", "2.356")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_ankle_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_shank_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_foot_roll_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.28"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.436"), ("upper", "0.436")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_ankle_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_foot_roll_link")] [],
.text "\n        ",
.element "child" [("link", "right_foot_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.785"), ("upper", "0.785")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "imu_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "imu_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1472"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "waist_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "waist_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0256"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-2.617"), ("upper", "2.617")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "torso_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "waist_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "torso_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.2598"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "camera_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "torso_link")] [],
.text "\n        ",
.element "child" [("link", "camera_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.071343 -0.0048077 0.17959"), ("rpy", "0.0 0.5236 -0.067287")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_shoulder_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "torso_link")] [],
.text "\n        ",
.element "child" [("link", "left_upper_arm_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.09765 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-2.966"), ("upper", "2.966")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_shoulder_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_upper_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_upper_arm_roll_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.078 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.174"), ("upper", "2.792")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_shoulder_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_upper_arm_roll_link")] [],
.text "\n        ",
.element "child" [("link", "left_upper_arm_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1005"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-1.832"), ("upper", "1.832")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_elbow_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_upper_arm_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "left_lower_arm_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1095"), ("rpy", "3.141592653589793 -1.5707926535897934 3.141592653589793")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.349"), ("upper", "1.658")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_wrist_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "left_lower_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_hand_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1005"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-1.832"), ("upper", "1.832")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_end_effector_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "left_hand_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "left_end_effector_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1045"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_shoulder_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "torso_link")] [],
.text "\n        ",
.element "child" [("link", "right_upper_arm_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 -0.09765 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "54.0"), ("velocity", "14.738"), ("lower", "-2.966"), ("upper", "2.966")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_shoulder_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_upper_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_upper_arm_roll_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 -0.078 0.0"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "1.0 0.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-2.792"), ("upper", "0.174")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_shoulder_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_upper_arm_roll_link")] [],
.text "\n        ",
.element "child" [("link", "right_upper_arm_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1005"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-1.832"), ("upper", "1.832")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_elbow_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_upper_arm_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "right_lower_arm_pitch_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1095"), ("rpy", "3.141592653589793 -1.5707926535897934 3.141592653589793")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 1.0 0.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-0.349"), ("upper", "1.658")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_wrist_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "right_lower_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_hand_yaw_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1005"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("effort", "30.0"), ("velocity", "16.747"), ("lower", "-1.832"), ("upper", "1.832")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_end_effector_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "right_hand_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "right_end_effector_link")] [],
.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 -0.1045"), ("rpy", "0.0 -0.0 0.0")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n"],
[],
[],
"d3a7e44ffab842c5109e48e5a9c29ccbf2a6da84625effba38839615d6ba46ac"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
