import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "SF_TRON1")] [.text "\n    ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "blue")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.0 0.8 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "green")] [.text "\n        ",
.element "color" [("rgba", "0.0 0.8 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.2 0.2 0.2 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "silver")] [.text "\n        ",
.element "color" [("rgba", "0.9137254901960784 0.9137254901960784 0.8470588235294118 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "orange")] [.text "\n        ",
.element "color" [("rgba", "1.0 0.4235294117647059 0.0392156862745098 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "brown")] [.text "\n        ",
.element "color" [("rgba", "0.8705882352941177 0.8117647058823529 0.7647058823529411 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "red")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.0 0.0 1.0")] [],
.text "\n    "],
.text "\n    ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "gazebo" [] [.text "\n        ",
.element "plugin" [("filename", "libpointfoot_hw_sim.so"), ("name", "gazebo_ros_control")] [.text "\n            ",
.element "robotNamespace" [] [.text "/"],
.text "\n            ",
.element "robotParam" [] [.text "robot_description"],
.text "\n            ",
.element "robotSimType" [] [.text "pointfoot_gazebo/PointFootHWSim"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [] [.text "\n        ",
.element "plugin" [("filename", "libgazebo_ros_p3d.so"), ("name", "p3d_base_controller")] [.text "\n            ",
.element "alwaysOn" [] [.text "true"],
.text "\n            ",
.element "updateRate" [] [.text "1000.0"],
.text "\n            ",
.element "bodyName" [] [.text "base_Link"],
.text "\n            ",
.element "topicName" [] [.text "ground_truth/state"],
.text "\n            ",
.element "gaussianNoise" [] [.text "0"],
.text "\n            ",
.element "frameName" [] [.text "world"],
.text "\n            ",
.element "xyzOffsets" [] [.text "0 0 0"],
.text "\n            ",
.element "rpyOffsets" [] [.text "0 0 0"],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    \n    ",
.element "link" [("name", "base_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "45.76E-03 0.14E-03 -163.98E-03")] [],
.text "\n            ",
.element "mass" [("value", "9.585")] [],
.text "\n            ",
.element "inertia" [("ixx", "140110.479E-06"), ("ixy", "534.939E-06"), ("ixz", "28184.116E-06"), ("iyy", "110641.449E-06"), ("iyz", "-27.278E-06"), ("izz", "98944.542E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/base_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.03 0 -0.072"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.27 0.26 0.19")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n\n     ",
.element "joint" [("name", "limx_imu_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("rpy", "0. 0. 0."), ("xyz", "0. 0. 0.")] [],
.text "\n        ",
.element "parent" [("link", "base_Link")] [],
.text "\n        ",
.element "child" [("link", "limx_imu")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "limx_imu")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.01")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000001"), ("iyz", "0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.015 0.015 0.004")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "material" [("name", "orange")] [.text "\n            ",
.element "color" [("rgba", "255 108 10 255")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "limx_imu")] [.text "\n        ",
.element "material" [] [.text "Gazebo/Orange"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "limx_imu_joint")] [.text "\n        ",
.element "disableFixedJointLumping" [] [.text "true"],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "abad_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-69.77E-03 44.79E-03 0.57E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.469")] [],
.text "\n            ",
.element "inertia" [("ixx", "1555.384E-06"), ("ixy", "397.78E-06"), ("ixz", "-13.10E-06"), ("iyy", "2359.25E-06"), ("iyz", "-0.98E-06"), ("izz", "2080.92E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/abad_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.03 0 0"), ("rpy", "1.57 0 1.57")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.05"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "abad_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "55.56E-03 105E-03 -260.2E-03"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_Link")] [],
.text "\n        ",
.element "child" [("link", "abad_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-0.38397"), ("upper", "1.39626"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "hip_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-28.69E-03 -47.7E-03 -39.92E-03")] [],
.text "\n            ",
.element "mass" [("value", "2.30")] [],
.text "\n            ",
.element "inertia" [("ixx", "16937.28E-06"), ("ixy", "1647.03E-06"), ("ixz", "-9232.53E-06"), ("iyy", "22853.28E-06"), ("iyz", "2202.40E-06"), ("izz", "9334.19E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/hip_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.10 -0.03 -0.14"), ("rpy", "0 0.53 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.15"), ("radius", "0.035")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "hip_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.077 0.02050 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "abad_L_Link")] [],
.text "\n        ",
.element "child" [("link", "hip_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-1.012291"), ("upper", "1.396263"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "knee_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "114.52E-03 1.3E-03 -193.67E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.22")] [],
.text "\n            ",
.element "inertia" [("ixx", "10938.43E-06"), ("ixy", "-7.87E-06"), ("ixz", "5986.5E-06"), ("iyy", "14358.12E-06"), ("iyz", "10.11E-06"), ("izz", "4087.65E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/knee_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.078 0 -0.12"), ("rpy", "0 -0.55 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.26"), ("radius", "0.02")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "knee_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.1500 -0.02050 -0.25981"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "hip_L_Link")] [],
.text "\n        ",
.element "child" [("link", "knee_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80"), ("lower", "-0.872665"), ("upper", "1.361357"), ("velocity", "15")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "ankle_L_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "10.74E-03 -0.61E-03 -33.14E-03")] [],
.text "\n            ",
.element "mass" [("value", "0.62")] [],
.text "\n            ",
.element "inertia" [("ixx", "525.46E-06"), ("ixy", "-3.51E-06"), ("ixz", "-51.36E-06"), ("iyy", "1812.05E-06"), ("iyz", "6.54E-06"), ("izz", "1973.81E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/ankle_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.26667 0.26667 0.26667 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/ankle_L_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.26667 0.26667 0.26667 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "ankle_L_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.150 0 -0.25981"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "knee_L_Link")] [],
.text "\n        ",
.element "child" [("link", "ankle_L_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\n        ",
.element "limit" [("effort", "20"), ("lower", "-1.15191730631626"), ("upper", "1.5707963267949"), ("velocity", "15")] [],
.text "\n        ",
.element "dynamics" [("friction", "0.01")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "hip_L_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "knee_L_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "100.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "ankle_L_Link")] [.text "\n        ",
.element "mu1" [] [.text "4.0"],
.text "\n        ",
.element "mu2" [] [.text "4.0"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "600000.0")] [],
.text "\n        ",
.element "kd" [("value", "100.0")] [],
.text "\n    "],
.text "\n\n    ",
.element "transmission" [("name", "abad_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "abad_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "abad_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "hip_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "hip_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "hip_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "knee_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "knee_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "knee_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "transmission" [("name", "ankle_L_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "ankle_L_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "ankle_L_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "abad_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-69.77E-03 -44.79E-03 0.57E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.469")] [],
.text "\n            ",
.element "inertia" [("ixx", "1555.384E-06"), ("ixy", "-397.78E-06"), ("ixz", "-13.10E-06"), ("iyy", "2359.25E-06"), ("iyz", "0.98E-06"), ("izz", "2080.92E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/abad_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.03 0 0"), ("rpy", "1.57 0 1.57")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.05"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "abad_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "55.56E-03 -105E-03 -260.2E-03"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_Link")] [],
.text "\n        ",
.element "child" [("link", "abad_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-1.39626"), ("upper", "0.38397"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "hip_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-28.69E-03 47.7E-03 -39.92E-03")] [],
.text "\n            ",
.element "mass" [("value", "2.30")] [],
.text "\n            ",
.element "inertia" [("ixx", "16937.28E-06"), ("ixy", "-1647.03E-06"), ("ixz", "-9232.53E-06"), ("iyy", "22853.28E-06"), ("iyz", "-2202.40E-06"), ("izz", "9334.19E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/hip_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.10 0.03 -0.14"), ("rpy", "0 0.53 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.15"), ("radius", "0.035")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "hip_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.077 -0.02050 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "abad_R_Link")] [],
.text "\n        ",
.element "child" [("link", "hip_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-1.396263"), ("upper", "1.012291"), ("velocity", "15.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "knee_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "114.52E-03 -1.3E-03 -193.67E-03")] [],
.text "\n            ",
.element "mass" [("value", "1.22")] [],
.text "\n            ",
.element "inertia" [("ixx", "10938.43E-06"), ("ixy", "7.87E-06"), ("ixz", "5986.5E-06"), ("iyy", "14358.12E-06"), ("iyz", "-10.11E-06"), ("izz", "4087.65E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/knee_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.79216 0.81961 0.93333 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.078 0 -0.12"), ("rpy", "0 -0.55 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.26"), ("radius", "0.02")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "knee_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.1500 0.02050 -0.25981"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "hip_R_Link")] [],
.text "\n        ",
.element "child" [("link", "knee_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("effort", "80"), ("lower", "-1.361357"), ("upper", "0.872665"), ("velocity", "15")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "ankle_R_Link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "10.74E-03 0.61E-03 -33.14E-03")] [],
.text "\n            ",
.element "mass" [("value", "0.62")] [],
.text "\n            ",
.element "inertia" [("ixx", "525.46E-06"), ("ixy", "3.51E-06"), ("ixz", "-51.36E-06"), ("iyy", "1812.05E-06"), ("iyz", "-6.54E-06"), ("izz", "1973.81E-06")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/ankle_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.26667 0.26667 0.26667 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://robot_description/pointfoot/SF_TRON1A/meshes/ankle_R_Link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "0.26667 0.26667 0.26667 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "ankle_R_Joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.150 0 -0.25981"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "knee_R_Link")] [],
.text "\n        ",
.element "child" [("link", "ankle_R_Link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 0")] [],
.text "\n\n        ",
.element "limit" [("effort", "20"), ("lower", "-1.15191730631626"), ("upper", "1.5707963267949"), ("velocity", "15")] [],
.text "\n        ",
.element "dynamics" [("friction", "0.01")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "hip_R_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "knee_R_Link")] [.text "\n        ",
.element "mu1" [] [.text "0.2"],
.text "\n        ",
.element "mu2" [] [.text "0.2"],
.text "\n        ",
.element "self_collide" [] [.text "0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "1000000.0")] [],
.text "\n        ",
.element "kd" [("value", "100.0")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "ankle_R_Link")] [.text "\n        ",
.element "mu1" [] [.text "4.0"],
.text "\n        ",
.element "mu2" [] [.text "4.0"],
.text "\n        ",
.element "self_collide" [] [.text "1"],
.text "\n        ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n        ",
.element "kp" [("value", "600000.0")] [],
.text "\n        ",
.element "kd" [("value", "100.0")] [],
.text "\n    "],
.text "\n\n    ",
.element "transmission" [("name", "abad_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "abad_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "abad_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "hip_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "hip_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "hip_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "knee_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "knee_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "knee_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "transmission" [("name", "ankle_R_Joint_tran")] [.text "\n        ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n        ",
.element "joint" [("name", "ankle_R_Joint")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n        "],
.text "\n        ",
.element "actuator" [("name", "ankle_R_Joint_motor")] [.text "\n            ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n            ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n\n    \n    \n    \n"],
[],
[],
"177867b287ac1f30866b7a46544512bc81e017873f7f1fad7e0e43be59ddac78"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
