import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("xmlns:ns2", "http://www.ros.org"), ("xmlns:xi", "http://www.w3.org/2003/XInclude"), ("name", "eve_r3_upper_body")] [.text "\n    ",
.element "link" [("name", "abdomen")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.055941 0.001616 0.129607"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "3.429553")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.055816"), ("ixy", "6.93E-4"), ("ixz", "-0.014517"), ("iyy", "0.054022"), ("iyz", "-0.001917"), ("izz", "0.020076")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/abdomen.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "j_hip_z"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n        ",
.element "parent" [("link", "abdomen")] [],
.text "\n        ",
.element "child" [("link", "pelvis")] [],
.text "\n        ",
.element "axis" [("xyz", "0.0 0.0 1.0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.0472"), ("upper", "1.0472"), ("effort", "-1.0"), ("velocity", "-1.0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "pelvis")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.02071479 -0.00544353 0.4100644"), ("rpy", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "mass" [("value", "10.12075049")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.2085075"), ("ixy", "8.581E-4"), ("ixz", "0.02176178"), ("iyy", "0.20882646"), ("iyz", "-0.00715583"), ("izz", "0.05515818")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0 0.0 0.0"), ("rpy", "1.5707963 0.0 1.5707963")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://eve_r3_description/meshes/torso.obj"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "xi:include" [("href", "eve_r3_right_arm.in.urdf"), ("xpointer", "xpointer(//robot/*)")] [],
.text "\n    ",
.element "xi:include" [("href", "qbhand.right.in.urdf"), ("xpointer", "xpointer(//robot/*)")] [],
.text "\n    ",
.element "xi:include" [("href", "eve_r3_left_arm.in.urdf"), ("xpointer", "xpointer(//robot/*)")] [],
.text "\n    ",
.element "xi:include" [("href", "qbhand.left.in.urdf"), ("xpointer", "xpointer(//robot/*)")] [],
.text "\n    ",
.element "xi:include" [("href", "eve_r3_head.in.urdf"), ("xpointer", "xpointer(//robot/*)")] [],
.text "\n"],
[],
[],
"3d93dec4415780b9ec19174fccbe7f1f9d92d1a060ae2767731cd099a23d6396"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
