import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("xmlns:drake", "http://drake.mit.edu"), ("xmlns:xacro", "http://www.ros.org/wiki/xacro"), ("name", "atlas")] [.text "\n  ",
.element "link" [("name", "l_clav")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "4.466")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.084")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.011"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.009"), ("iyz", "0.004"), ("izz", "0.004")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_clav.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_clav_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_foot")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.410")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.027 0 -0.067")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.002"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.007"), ("iyz", "0"), ("izz", "0.008")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_foot.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_foot_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 -0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 -0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 -0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 -0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0426 0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0426 0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0426 -0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0426 -0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hand")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.5839")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00016 -0.08159 0.00002")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000388"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000477"), ("iyz", "0"), ("izz", "0.000379")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_larm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "3.248")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00265"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00446"), ("iyz", "0"), ("izz", "0.00446")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_larm.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_larm_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_lfarm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.648")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00017 -0.02515 0.00163")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000764"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000429"), ("iyz", "0"), ("izz", "0.000825")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_hand.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_hand_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_lglut")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.898")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0133341 0.0170484 -0.0312052")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000691326"), ("ixy", "-2.24344e-05"), ("ixz", "2.50508e-06"), ("iyy", "0.00126856"), ("iyz", "0.000137862"), ("izz", "0.00106487")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_lglut.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_lglut_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_lleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "4.515")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.001 0 -0.187")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.077"), ("ixy", "0"), ("ixz", "-0.003"), ("iyy", "0.076"), ("iyz", "0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_lleg.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_lleg_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_scap")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "3.899")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00319"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00583"), ("iyz", "0"), ("izz", "0.00583")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_scap.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_scap_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_talus")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.125")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.01674e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "8.42775e-06"), ("iyz", "0"), ("izz", "1.30101e-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_talus.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_uarm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "4.386")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.065 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00656"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00358"), ("iyz", "0"), ("izz", "0.00656")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uarm.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uarm_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_ufarm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.4798")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00015 0.08296 0.00037")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.012731"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.002857"), ("iyz", "0"), ("izz", "0.011948")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_farm.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_farm_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_uglut")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1.959")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00529262 -0.00344732 0.00313046")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00074276"), ("ixy", "-3.79607e-08"), ("ixz", "-2.79549e-05"), ("iyy", "0.000688179"), ("iyz", "-3.2735e-08"), ("izz", "0.00041242")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_uglut.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_uglut_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_uleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "8.204")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.21")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.09"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.09"), ("iyz", "0"), ("izz", "0.02")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_uleg.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    \n    \n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/l_uleg_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "ltorso")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.270")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0112984 -3.15366e-06 0.0746835")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0039092"), ("ixy", "-5.04491e-08"), ("ixz", "-0.000342157"), ("iyy", "0.00341694"), ("iyz", "4.87119e-07"), ("izz", "0.00174492")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/ltorso.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "mtorso")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.799")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00816266 -0.0131245 0.0305974")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000454181"), ("ixy", "-6.10764e-05"), ("ixz", "3.94009e-05"), ("iyy", "0.000483282"), ("iyz", "5.27463e-05"), ("izz", "0.000444215")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/mtorso.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "pelvis")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "9.509")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0111 0 0.0271")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.1244"), ("ixy", "0.0008"), ("ixz", "-0.0007"), ("iyy", "0.0958"), ("iyz", "-0.0005"), ("izz", "0.1167")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/pelvis.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/pelvis_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_clav")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "4.466")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.084")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.011"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.009"), ("iyz", "0.004"), ("izz", "0.004")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_clav.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_clav_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_foot")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.41")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.027 0 -0.067")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.002"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.007"), ("iyz", "0"), ("izz", "0.008")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_foot.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_foot_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 -0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0876 -0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 -0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1728 -0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0426 0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0426 0.0626 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0426 -0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0426 -0.066 -0.07645")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hand")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.5839")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00016 -0.08159 0.00002")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000388"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000477"), ("iyz", "0"), ("izz", "0.000379")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_larm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "3.248")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00265"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00446"), ("iyz", "0"), ("izz", "0.00446")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_larm.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_larm_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_lfarm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.648")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00017 -0.02515 0.00163")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000764"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000429"), ("iyz", "0"), ("izz", "0.000825")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_hand.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_hand_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_lglut")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.898")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0133341 -0.0170484 -0.0312052")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000691326"), ("ixy", "2.24344e-05"), ("ixz", "2.50508e-06"), ("iyy", "0.00126856"), ("iyz", "-0.000137862"), ("izz", "0.00106487")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_lglut.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_lglut_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_lleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "4.515")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.001 0 -0.187")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.077"), ("ixy", "-0"), ("ixz", "-0.003"), ("iyy", "0.076"), ("iyz", "-0"), ("izz", "0.01")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_lleg.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_lleg_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_scap")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "3.899")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00319"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00583"), ("iyz", "0"), ("izz", "0.00583")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_scap.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_scap_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_talus")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.125")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.01674e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "8.42775e-06"), ("iyz", "0"), ("izz", "1.30101e-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_talus.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_uarm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "4.386")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.065 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00656"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00358"), ("iyz", "0"), ("izz", "0.00656")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uarm.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uarm_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_ufarm")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.4798")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00015 0.08296 0.00037")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.012731"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.002857"), ("iyz", "0"), ("izz", "0.011948")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_farm.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_farm_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_uglut")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1.959")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00529262 0.00344732 0.00313046")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00074276"), ("ixy", "3.79607e-08"), ("ixz", "-2.79549e-05"), ("iyy", "0.000688179"), ("iyz", "3.2735e-08"), ("izz", "0.00041242")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uglut.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uglut_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_uleg")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "8.204")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.21")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.09"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.09"), ("iyz", "0"), ("izz", "0.02")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uleg.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    \n    \n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/r_uleg_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "utorso")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "84.409")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0622 0.0023 0.3157")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.577"), ("ixy", "-0.032"), ("ixz", "0.102"), ("iyy", "1.602"), ("iyz", "0.047"), ("izz", "0.565")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/utorso.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/utorso_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "back_bkx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.05")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "mtorso")] [],
.text "\n    ",
.element "child" [("link", "utorso")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "-0.523599"), ("upper", "0.523599"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "back_bky"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.162")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "ltorso")] [],
.text "\n    ",
.element "child" [("link", "mtorso")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "445"), ("lower", "-0.219388"), ("upper", "0.538783"), ("velocity", "9")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "back_bkz"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0125 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "pelvis")] [],
.text "\n    ",
.element "child" [("link", "ltorso")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "106"), ("lower", "-0.663225"), ("upper", "0.663225"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_elx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.119 0.0092")] [],
.text "\n    ",
.element "axis" [("xyz", "-1.0 -0.0 -0.0")] [],
.text "\n    ",
.element "parent" [("link", "l_uarm")] [],
.text "\n    ",
.element "child" [("link", "l_larm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "112"), ("lower", "0"), ("upper", "2.35619"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_ely"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.187 -0.016")] [],
.text "\n    ",
.element "axis" [("xyz", "-0.0 -1.0 -0.0")] [],
.text "\n    ",
.element "parent" [("link", "l_scap")] [],
.text "\n    ",
.element "child" [("link", "l_uarm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "63"), ("lower", "0"), ("upper", "3.14159"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_shx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.11 -0.245")] [],
.text "\n    ",
.element "axis" [("xyz", "-1.0 -0.0 -0.0")] [],
.text "\n    ",
.element "parent" [("link", "l_clav")] [],
.text "\n    ",
.element "child" [("link", "l_scap")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "99"), ("lower", "-1.5708"), ("upper", "1.5708"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_shz"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 3.14159265359"), ("xyz", "0.1406 0.2256 0.4776")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "utorso")] [],
.text "\n    ",
.element "child" [("link", "l_clav")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "87"), ("lower", "-1.5708"), ("upper", "0.785398"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_mwx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_ufarm")] [],
.text "\n    ",
.element "child" [("link", "l_lfarm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-1.7628"), ("upper", "1.7628"), ("velocity", "10")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_uwy"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 3.14159265359 0"), ("xyz", "0 -0.29955 -0.00921")] [],
.text "\n    ",
.element "axis" [("xyz", "-0.0 -1.0 -0.0")] [],
.text "\n    ",
.element "parent" [("link", "l_larm")] [],
.text "\n    ",
.element "child" [("link", "l_ufarm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-3.011"), ("upper", "3.011"), ("velocity", "10")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_arm_lwy"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 3.14159265359 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "-0.0 -1.0 -0.0")] [],
.text "\n    ",
.element "parent" [("link", "l_lfarm")] [],
.text "\n    ",
.element "child" [("link", "l_hand")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-2.9671"), ("upper", "2.9671"), ("velocity", "10")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_leg_akx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_talus")] [],
.text "\n    ",
.element "child" [("link", "l_foot")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "360"), ("lower", "-0.8"), ("upper", "0.8"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_leg_aky"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.422")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "l_lleg")] [],
.text "\n    ",
.element "child" [("link", "l_talus")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "740"), ("lower", "-1"), ("upper", "0.7"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_leg_hpx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_uglut")] [],
.text "\n    ",
.element "child" [("link", "l_lglut")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "530"), ("lower", "-0.523599"), ("upper", "0.523599"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_leg_hpy"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.05 0.0225 -0.066")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "l_lglut")] [],
.text "\n    ",
.element "child" [("link", "l_uleg")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "840"), ("lower", "-1.61234"), ("upper", "0.65764"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_leg_hpz"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.089 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "pelvis")] [],
.text "\n    ",
.element "child" [("link", "l_uglut")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "275"), ("lower", "-0.174358"), ("upper", "0.786794"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_leg_kny"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.05 0 -0.374")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "l_uleg")] [],
.text "\n    ",
.element "child" [("link", "l_lleg")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "890"), ("lower", "0"), ("upper", "2.35637"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "neck_ay"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.2546 0 0.6215")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "utorso")] [],
.text "\n    ",
.element "child" [("link", "head")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-0.602139"), ("upper", "1.14319"), ("velocity", "6.28")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_elx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.119 0.0092")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_uarm")] [],
.text "\n    ",
.element "child" [("link", "r_larm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "112"), ("lower", "-2.35619"), ("upper", "0"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_ely"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.187 -0.016")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "r_scap")] [],
.text "\n    ",
.element "child" [("link", "r_uarm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "63"), ("lower", "0"), ("upper", "3.14159"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_shx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.11 -0.245")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_clav")] [],
.text "\n    ",
.element "child" [("link", "r_scap")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "99"), ("lower", "-1.5708"), ("upper", "1.5708"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_shz"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1406 -0.2256 0.4776")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "utorso")] [],
.text "\n    ",
.element "child" [("link", "r_clav")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "87"), ("lower", "-0.785398"), ("upper", "1.5708"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_mwx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_ufarm")] [],
.text "\n    ",
.element "child" [("link", "r_lfarm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-1.7628"), ("upper", "1.7628"), ("velocity", "10")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_uwy"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.29955 -0.00921")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "r_larm")] [],
.text "\n    ",
.element "child" [("link", "r_ufarm")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-3.011"), ("upper", "3.011"), ("velocity", "10")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_arm_lwy"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "r_lfarm")] [],
.text "\n    ",
.element "child" [("link", "r_hand")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "25"), ("lower", "-2.9671"), ("upper", "2.9671"), ("velocity", "10")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_leg_akx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_talus")] [],
.text "\n    ",
.element "child" [("link", "r_foot")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "360"), ("lower", "-0.8"), ("upper", "0.8"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_leg_aky"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.422")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "r_lleg")] [],
.text "\n    ",
.element "child" [("link", "r_talus")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "740"), ("lower", "-1"), ("upper", "0.7"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_leg_hpx"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_uglut")] [],
.text "\n    ",
.element "child" [("link", "r_lglut")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "530"), ("lower", "-0.523599"), ("upper", "0.523599"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_leg_hpy"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.05 -0.0225 -0.066")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "r_lglut")] [],
.text "\n    ",
.element "child" [("link", "r_uleg")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "840"), ("lower", "-1.61234"), ("upper", "0.65764"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_leg_hpz"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.089 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "pelvis")] [],
.text "\n    ",
.element "child" [("link", "r_uglut")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "275"), ("lower", "-0.786794"), ("upper", "0.174358"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_leg_kny"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.05 0 -0.374")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "r_uleg")] [],
.text "\n    ",
.element "child" [("link", "r_lleg")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.1"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "890"), ("lower", "0"), ("upper", "2.35637"), ("velocity", "12")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_situational_awareness_camera_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00001"), ("iyz", "0"), ("izz", "0.00001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_situational_awareness_camera_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "utorso")] [],
.text "\n    ",
.element "child" [("link", "r_situational_awareness_camera_link")] [],
.text "\n    \n    ",
.element "origin" [("rpy", "0 0 -1.309"), ("xyz", "0.155 -0.121 0.785")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_situational_awareness_camera_optical_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5708 0.0 -1.5708"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_situational_awareness_camera_link")] [],
.text "\n    ",
.element "child" [("link", "r_situational_awareness_camera_optical_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_situational_awareness_camera_optical_frame")] [],
.text "\n  ",
.element "link" [("name", "l_situational_awareness_camera_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00001"), ("iyz", "0"), ("izz", "0.00001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_situational_awareness_camera_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "utorso")] [],
.text "\n    ",
.element "child" [("link", "l_situational_awareness_camera_link")] [],
.text "\n    \n    ",
.element "origin" [("rpy", "0 0 1.309"), ("xyz", "0.155 0.121 0.785")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_situational_awareness_camera_optical_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5708 0.0 -1.5708"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_situational_awareness_camera_link")] [],
.text "\n    ",
.element "child" [("link", "l_situational_awareness_camera_optical_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_situational_awareness_camera_optical_frame")] [],
.text "\n  ",
.element "frame" [("link", "l_foot"), ("name", "l_foot_sole"), ("rpy", "0 0 0"), ("xyz", "0.0426  0.0017 -0.07645")] [],
.text "\n  ",
.element "frame" [("link", "r_foot"), ("name", "r_foot_sole"), ("rpy", "0 0 0"), ("xyz", "0.0426 -0.0017 -0.07645")] [],
.text "\n  ",
.element "frame" [("link", "l_foot"), ("name", "l_foot_toe"), ("rpy", "0 0 0"), ("xyz", "0.1728 0.0017 -0.07645")] [],
.text "\n  ",
.element "frame" [("link", "r_foot"), ("name", "r_foot_toe"), ("rpy", "0 0 0"), ("xyz", "0.1728 -0.0017 -0.07645")] [],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "feet")] [.text "\n    ",
.element "drake:member" [("link", "l_foot")] [],
.text "\n    ",
.element "drake:member" [("link", "r_foot")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "feet")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "core")] [.text "\n    ",
.element "drake:member" [("link", "utorso")] [],
.text "\n    ",
.element "drake:member" [("link", "pelvis")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "core")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "ignore_core")] [.text "\n    ",
.element "drake:member" [("link", "r_scap")] [],
.text "\n    ",
.element "drake:member" [("link", "l_scap")] [],
.text "\n    ",
.element "drake:member" [("link", "r_clav")] [],
.text "\n    ",
.element "drake:member" [("link", "l_clav")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "core")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "r_uleg")] [.text "\n    ",
.element "drake:member" [("link", "r_uglut")] [],
.text "\n    ",
.element "drake:member" [("link", "r_lglut")] [],
.text "\n    ",
.element "drake:member" [("link", "r_uleg")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "core")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "r_uleg")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "l_uleg")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "l_uleg")] [.text "\n    ",
.element "drake:member" [("link", "l_uglut")] [],
.text "\n    ",
.element "drake:member" [("link", "l_lglut")] [],
.text "\n    ",
.element "drake:member" [("link", "l_uleg")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "core")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "l_uleg")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "l_uleg")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "r_leg")] [.text "\n    ",
.element "drake:member" [("link", "r_lleg")] [],
.text "\n    ",
.element "drake:member" [("link", "r_talus")] [],
.text "\n    ",
.element "drake:member" [("link", "r_foot")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "r_leg")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "r_uleg")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "l_leg")] [.text "\n    ",
.element "drake:member" [("link", "l_lleg")] [],
.text "\n    ",
.element "drake:member" [("link", "l_talus")] [],
.text "\n    ",
.element "drake:member" [("link", "l_foot")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "l_leg")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "l_uleg")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "r_arm")] [.text "\n    ",
.element "drake:member" [("link", "r_clav")] [],
.text "\n    ",
.element "drake:member" [("link", "r_scap")] [],
.text "\n    ",
.element "drake:member" [("link", "r_uarm")] [],
.text "\n    ",
.element "drake:member" [("link", "r_larm")] [],
.text "\n    ",
.element "drake:member" [("link", "r_ufarm")] [],
.text "\n    ",
.element "drake:member" [("link", "r_lfarm")] [],
.text "\n    ",
.element "drake:member" [("link", "r_hand")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "r_arm")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "l_arm")] [.text "\n    ",
.element "drake:member" [("link", "l_clav")] [],
.text "\n    ",
.element "drake:member" [("link", "l_scap")] [],
.text "\n    ",
.element "drake:member" [("link", "l_uarm")] [],
.text "\n    ",
.element "drake:member" [("link", "l_larm")] [],
.text "\n    ",
.element "drake:member" [("link", "l_ufarm")] [],
.text "\n    ",
.element "drake:member" [("link", "l_lfarm")] [],
.text "\n    ",
.element "drake:member" [("link", "l_hand")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "l_arm")] [],
.text "\n  "],
.text "\n  ",
.element "drake:collision_filter_group" [("name", "hokuyo_filter")] [.text "\n    ",
.element "drake:member" [("link", "hokuyo_link")] [],
.text "\n    ",
.element "drake:member" [("link", "utorso")] [],
.text "\n    ",
.element "drake:member" [("link", "head")] [],
.text "\n    ",
.element "drake:ignored_collision_filter_group" [("name", "hokuyo_filter")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "head")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.075493 3.3383E-05 0.02774")] [],
.text "\n      ",
.element "mass" [("value", "1.4199")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0039688"), ("ixy", "-1.5797E-06"), ("ixz", "-0.00089293"), ("iyy", "0.0041178"), ("iyz", "-6.8415E-07"), ("izz", "0.0035243")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/head.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/head_chull.obj")] [],
.text "\n        ",
.element "drake:declare_convex" [] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "pre_spindle")] [],
.text "\n  ",
.element "joint" [("name", "pre_spindle_joint"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0446 0 0.0880")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "pre_spindle_cal_x")] [],
.text "\n  ",
.element "link" [("name", "pre_spindle_cal_y")] [],
.text "\n  ",
.element "link" [("name", "pre_spindle_cal_z")] [],
.text "\n  ",
.element "link" [("name", "pre_spindle_cal_roll")] [],
.text "\n  ",
.element "link" [("name", "pre_spindle_cal_pitch")] [],
.text "\n  ",
.element "link" [("name", "pre_spindle_cal_yaw")] [],
.text "\n  ",
.element "joint" [("name", "pre_spindle_cal_x_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "pre_spindle")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle_cal_x")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "0.0"), ("lower", "-0.5"), ("upper", "0.5"), ("velocity", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "pre_spindle_cal_y_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "pre_spindle_cal_x")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle_cal_y")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "0.0"), ("lower", "-0.5"), ("upper", "0.5"), ("velocity", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "pre_spindle_cal_z_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "pre_spindle_cal_y")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle_cal_z")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "0.0"), ("lower", "-0.5"), ("upper", "0.5"), ("velocity", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "pre_spindle_cal_roll_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "pre_spindle_cal_z")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle_cal_roll")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "pre_spindle_cal_pitch_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "pre_spindle_cal_roll")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle_cal_pitch")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "pre_spindle_cal_yaw_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "pre_spindle_cal_pitch")] [],
.text "\n    ",
.element "child" [("link", "pre_spindle_cal_yaw")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "hokuyo_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "pre_spindle_cal_yaw")] [],
.text "\n    ",
.element "child" [("link", "post_spindle")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "post_spindle")] [],
.text "\n  ",
.element "link" [("name", "post_spindle_cal_x")] [],
.text "\n  ",
.element "link" [("name", "post_spindle_cal_y")] [],
.text "\n  ",
.element "link" [("name", "post_spindle_cal_z")] [],
.text "\n  ",
.element "link" [("name", "post_spindle_cal_roll")] [],
.text "\n  ",
.element "link" [("name", "post_spindle_cal_pitch")] [],
.text "\n  ",
.element "joint" [("name", "post_spindle_cal_x_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "post_spindle")] [],
.text "\n    ",
.element "child" [("link", "post_spindle_cal_x")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("effort", "0.0"), ("lower", "-0.5"), ("upper", "0.5"), ("velocity", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "post_spindle_cal_y_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "post_spindle_cal_x")] [],
.text "\n    ",
.element "child" [("link", "post_spindle_cal_y")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "0.0"), ("lower", "-0.5"), ("upper", "0.5"), ("velocity", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "post_spindle_cal_z_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "post_spindle_cal_y")] [],
.text "\n    ",
.element "child" [("link", "post_spindle_cal_z")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "0.0"), ("lower", "-0.5"), ("upper", "0.5"), ("velocity", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "post_spindle_cal_roll_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "post_spindle_cal_z")] [],
.text "\n    ",
.element "child" [("link", "post_spindle_cal_roll")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "post_spindle_cal_pitch_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "post_spindle_cal_roll")] [],
.text "\n    ",
.element "child" [("link", "post_spindle_cal_pitch")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "post_spindle_cal_yaw_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "post_spindle_cal_pitch")] [],
.text "\n    ",
.element "child" [("link", "hokuyo_link")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "hokuyo_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.012428 0.0004084 -0.0041835")] [],
.text "\n      ",
.element "mass" [("value", "0.057664")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.7174E-05"), ("ixy", "4.9927E-08"), ("ixz", "1.1015E-05"), ("iyy", "4.2412E-05"), ("iyz", "-9.8165E-09"), ("izz", "4.167E-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "-0.314 0 0"), ("xyz", "0.045 -0.0261018277 -0.08342369")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/head_camera.gltf")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "-0.314 0 0"), ("xyz", "0.045 -0.0261018277 -0.08342369")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/head_camera_chull.obj")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "head_hokuyo_fixed_joint"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03 0 0.015")] [],
.text "\n    ",
.element "parent" [("link", "hokuyo_link")] [],
.text "\n    ",
.element "child" [("link", "head_hokuyo_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "head_hokuyo_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.01")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00001"), ("iyz", "0"), ("izz", "0.00001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "head_hokuyo_frame")] [.text "\n    ",
.element "sensor" [("name", "head_hokuyo_sensor"), ("type", "ray")] [.text "\n      ",
.element "visualize" [] [.text "false"],
.text "\n      ",
.element "update_rate" [] [.text "40"],
.text "\n      ",
.element "ray" [] [.text "\n        ",
.element "scan" [] [.text "\n          ",
.element "horizontal" [] [.text "\n            ",
.element "samples" [] [.text "720"],
.text "\n            ",
.element "resolution" [] [.text "1"],
.text "\n            ",
.element "min_angle" [] [.text "-1.570796"],
.text "\n            ",
.element "max_angle" [] [.text "1.570796"],
.text "\n          "],
.text "\n        "],
.text "\n        ",
.element "range" [] [.text "\n          ",
.element "min" [] [.text "0.10"],
.text "\n          ",
.element "max" [] [.text "30.0"],
.text "\n          ",
.element "resolution" [] [.text "0.01"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_laser.so"), ("name", "gazebo_ros_head_hokuyo_controller")] [.text "\n        ",
.element "gaussianNoise" [] [.text "0.005"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "40"],
.text "\n        ",
.element "topicName" [] [.text "/scan"],
.text "\n        ",
.element "frameName" [] [.text "head_hokuyo_frame"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_camera_frame_joint"), ("type", "fixed")] [.text "\n    \n    ",
.element "origin" [("xyz", "0.0 0.035 -0.002")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "left_camera_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_camera_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.001"), ("iyz", "0.0"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_camera_optical_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5708 0.0 -1.5708"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "left_camera_frame")] [],
.text "\n    ",
.element "child" [("link", "left_camera_optical_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_camera_optical_frame")] [],
.text "\n  ",
.element "gazebo" [("reference", "left_camera_frame")] [.text "\n    ",
.element "sensor" [("name", "left_camera_sensor"), ("type", "camera")] [.text "\n      \n      ",
.element "update_rate" [] [.text "15.0"],
.text "\n      ",
.element "camera" [] [.text "\n        \n        \n        \n        ",
.element "horizontal_fov" [] [.text "1.3962634"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "2048"],
.text "\n          ",
.element "height" [] [.text "1088"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "100"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "left_camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        \n        ",
.element "updateRate" [] [.text "15.0"],
.text "\n        ",
.element "cameraName" [] [.text "multisense/left"],
.text "\n        ",
.element "imageTopicName" [] [.text "image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "left_camera_optical_frame"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.0"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_camera_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0.0 -0.035 -0.002")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "right_camera_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_camera_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.001"), ("iyz", "0.0"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_camera_optical_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5708 0.0 -1.5708"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "right_camera_frame")] [],
.text "\n    ",
.element "child" [("link", "right_camera_optical_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_camera_optical_frame")] [],
.text "\n  ",
.element "gazebo" [("reference", "right_camera_frame")] [.text "\n    ",
.element "sensor" [("name", "right_camera_sensor"), ("type", "camera")] [.text "\n      \n      ",
.element "update_rate" [] [.text "15.0"],
.text "\n      ",
.element "camera" [] [.text "\n        \n        \n        \n        ",
.element "horizontal_fov" [] [.text "1.3962634"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "2048"],
.text "\n          ",
.element "height" [] [.text "1088"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "100"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "right_camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        \n        ",
.element "updateRate" [] [.text "15.0"],
.text "\n        ",
.element "cameraName" [] [.text "multisense/right"],
.text "\n        ",
.element "imageTopicName" [] [.text "image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "left_camera_optical_frame"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.07"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "center_top_led_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0.01125 0.0 0.0105")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "center_top_led_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "center_top_led_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.001"), ("iyz", "0.0"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "center_bottom_led_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0.01125 0.0 -0.0155")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "center_bottom_led_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "center_bottom_led_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.001"), ("iyz", "0.0"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_led_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 -0.15 0.53"), ("xyz", "-0.01443 0.07452 0.050346")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "left_led_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_led_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.001"), ("iyz", "0.0"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_led_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 -0.15 -0.53"), ("xyz", "-0.01443 -0.07452 0.050346")] [],
.text "\n    ",
.element "parent" [("link", "head")] [],
.text "\n    ",
.element "child" [("link", "right_led_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_led_frame")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.001"), ("iyz", "0.0"), ("izz", "0.001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "r_foot")] [.text "\n    \n    ",
.element "sensor" [("name", "r_foot_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "1000.0"],
.text "\n      ",
.element "always_on" [] [.text "1"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "topic" [] [.text "/r_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "l_foot")] [.text "\n    \n    ",
.element "sensor" [("name", "l_foot_contact_sensor"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "1000.0"],
.text "\n      ",
.element "always_on" [] [.text "1"],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "topic" [] [.text "/l_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "head_hokuyo_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "joint" [("name", "hokuyo_joint")] [],
.text "\n    ",
.element "actuator" [("name", "hokuyo_motor")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "back_bkz_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "joint" [("name", "back_bkz")] [],
.text "\n    ",
.element "actuator" [("name", "back_bkz_motor")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "back_bky_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "back_bky_motor")] [],
.text "\n    ",
.element "joint" [("name", "back_bky")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "back_bkx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "back_bkx_motor")] [],
.text "\n    ",
.element "joint" [("name", "back_bkx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_elx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_elx_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_elx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_ely_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_ely_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_ely")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_mwx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_mwx_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_mwx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_shx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_shx_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_shx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_shz_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_shz_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_shz")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_uwy_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_uwy_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_uwy")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_arm_lwy_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_arm_lwy_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_lwy")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_leg_kny_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_leg_kny_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_kny")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_leg_akx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_leg_akx_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_akx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_leg_hpy_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_leg_hpy_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_hpy")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_leg_hpx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_leg_hpx_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_hpx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_leg_aky_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_leg_aky_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_aky")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "l_leg_hpz_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "l_leg_hpz_motor")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_hpz")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "neck_ay_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "neck_ay_motor")] [],
.text "\n    ",
.element "joint" [("name", "neck_ay")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_elx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_elx_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_elx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_ely_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_ely_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_ely")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_mwx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_mwx_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_mwx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_shx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_shx_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_shx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_shz_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_shz_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_shz")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_uwy_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_uwy_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_uwy")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_arm_lwy_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_arm_lwy_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_lwy")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_leg_kny_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_leg_kny_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_kny")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_leg_akx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_leg_akx_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_akx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_leg_hpy_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_leg_hpy_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_hpy")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_leg_hpx_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_leg_hpx_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_hpx")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_leg_aky_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_leg_aky_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_aky")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "r_leg_hpz_trans"), ("type", "pr2_mechanism_model/SimpleTransmission")] [.text "\n    ",
.element "actuator" [("name", "r_leg_hpz_motor")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_hpz")] [],
.text "\n    ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hand_force_torque")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00001"), ("iyz", "0"), ("izz", "0.00001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_hand_force_torque_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 3.141592"), ("xyz", "0 -0.1245 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hand")] [],
.text "\n    ",
.element "child" [("link", "l_hand_force_torque")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hand_force_torque")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00001"), ("iyz", "0"), ("izz", "0.00001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_hand_force_torque_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 3.141592"), ("xyz", "0 -0.1245 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hand")] [],
.text "\n    ",
.element "child" [("link", "r_hand_force_torque")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "left_palm")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "-1.57079 -1.57079 0"), ("xyz", "0 0.1725 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/GRIPPER_OPEN_chull.gltf"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "-1.57079 -1.57079 0"), ("xyz", "0 0.1725 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/GRIPPER_OPEN_chull.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_palm_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "l_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "left_palm")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_palm")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "-1.57079 -1.57079 0"), ("xyz", "0 0.1725 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/GRIPPER_OPEN_chull.gltf"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "-1.57079 -1.57079 0"), ("xyz", "0 0.1725 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://drake_models/atlas/meshes/GRIPPER_OPEN_chull.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_palm_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "r_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "right_palm")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_hand_face_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0 0.12 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "l_hand_face")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hand_face")] [],
.text "\n  ",
.element "joint" [("name", "l_hand_gripper_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0 0.18 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "l_hand_gripper")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hand_gripper")] [],
.text "\n  ",
.element "link" [("name", "l_hand_camera_link")] [],
.text "\n  ",
.element "joint" [("name", "l_hand_camera_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "l_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "l_hand_camera_link")] [],
.text "\n    \n    ",
.element "origin" [("rpy", " -1.57079 0  1.5708"), ("xyz", "-0.09892  0.01431 0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "l_hand_camera_optical_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079 0.0 -1.57079"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "l_hand_camera_link")] [],
.text "\n    ",
.element "child" [("link", "l_hand_camera_optical_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "l_hand_camera_optical_frame")] [],
.text "\n  ",
.element "gazebo" [("reference", "l_hand_camera_link")] [.text "\n    ",
.element "sensor" [("name", "l_hand_camera_sensor"), ("type", "camera")] [.text "\n      ",
.element "update_rate" [] [.text "10.0"],
.text "\n      ",
.element "camera" [("name", "l_hand_camera")] [.text "\n        \n        ",
.element "horizontal_fov" [] [.text "1.7281"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "1280"],
.text "\n          ",
.element "height" [] [.text "1024"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "100"],
.text "\n        "],
.text "\n        ",
.element "noise" [] [.text "\n          ",
.element "type" [] [.text "gaussian"],
.text "\n          \n          ",
.element "mean" [] [.text "0.0"],
.text "\n          ",
.element "stddev" [] [.text "0.007"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "l_hand_camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "robotiq_hands/l_hand_camera"],
.text "\n        ",
.element "imageTopicName" [] [.text "image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "l_hand_camera_optical_frame"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.07"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_hand_face_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0 0.12 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "r_hand_face")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hand_face")] [],
.text "\n  ",
.element "joint" [("name", "r_hand_gripper_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0 0.18 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "r_hand_gripper")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hand_gripper")] [],
.text "\n  ",
.element "link" [("name", "r_hand_camera_link")] [],
.text "\n  ",
.element "joint" [("name", "r_hand_camera_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "r_hand_force_torque")] [],
.text "\n    ",
.element "child" [("link", "r_hand_camera_link")] [],
.text "\n    \n    ",
.element "origin" [("rpy", " 1.57079 0  1.5708"), ("xyz", "0.09892  0.01431 0.0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "r_hand_camera_optical_frame_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079 0.0 -1.57079"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "r_hand_camera_link")] [],
.text "\n    ",
.element "child" [("link", "r_hand_camera_optical_frame")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "r_hand_camera_optical_frame")] [],
.text "\n  ",
.element "gazebo" [("reference", "r_hand_camera_link")] [.text "\n    ",
.element "sensor" [("name", "r_hand_camera_sensor"), ("type", "camera")] [.text "\n      ",
.element "update_rate" [] [.text "10.0"],
.text "\n      ",
.element "camera" [("name", "r_hand_camera")] [.text "\n        \n        ",
.element "horizontal_fov" [] [.text "1.7281"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "1280"],
.text "\n          ",
.element "height" [] [.text "1024"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.02"],
.text "\n          ",
.element "far" [] [.text "100"],
.text "\n        "],
.text "\n        ",
.element "noise" [] [.text "\n          ",
.element "type" [] [.text "gaussian"],
.text "\n          \n          ",
.element "mean" [] [.text "0.0"],
.text "\n          ",
.element "stddev" [] [.text "0.007"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_camera.so"), ("name", "r_hand_camera_controller")] [.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "robotiq_hands/r_hand_camera"],
.text "\n        ",
.element "imageTopicName" [] [.text "image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "camera_info"],
.text "\n        ",
.element "frameName" [] [.text "r_hand_camera_optical_frame"],
.text "\n        ",
.element "hackBaseline" [] [.text "0.07"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"807e47f85a0ff9fe924ff0cd0444760fee31a33768eb40e702ccec404970c282"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
