import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "2dof_planar")] [.text "\n  ",
.element "link" [("name", "base_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.05 0.05 0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "1 0 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.05 0.05 0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "link1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.05"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.2")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000177083"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000177083"), ("iyz", "0"), ("izz", "0.000020833")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.05"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.025 0.025 0.1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0 1 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.05"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.025 0.025 0.1")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint1"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.025 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "link1")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "0"), ("effort", "0"), ("velocity", "0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.05")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "link2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001015625"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.001015625"), ("iyz", "0"), ("izz", "0.002")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.025 0.025 0.2")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0 0 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.025 0.025 0.2")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint2"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.0125 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "link1")] [],
.text "\n    ",
.element "child" [("link", "link2")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "0"), ("effort", "0"), ("velocity", "0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.05")] [],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "link3")] [.text "\n    ",
.element "inertial" [] [.text "\n    ",
.element "mass" [("value", "0.0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "inertia" [("ixx", "0.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0"), ("iyz", "0.0"), ("izz", "0.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint3"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0.2"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "link2")] [],
.text "\n    ",
.element "child" [("link", "link3")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n  "],
.text "\n\n"],
[],
[],
"0abde3dc5cd1100df4ff49e3a71d4e8e6fa8a5f118df809f3d0324df769d2fa6"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
