import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "go1")] [.text "\n  ",
.element "material" [("name", "black")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.0 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "blue")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.0 0.8 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "green")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.8 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "grey")] [.text "\n    ",
.element "color" [("rgba", "0.2 0.2 0.2 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "silver")] [.text "\n    ",
.element "color" [("rgba", "0.9137254901960784 0.9137254901960784 0.8470588235294118 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "orange")] [.text "\n    ",
.element "color" [("rgba", "1.0 0.4235294117647059 0.0392156862745098 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "brown")] [.text "\n    ",
.element "color" [("rgba", "0.8705882352941177 0.8117647058823529 0.7647058823529411 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "red")] [.text "\n    ",
.element "color" [("rgba", "0.8 0.0 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "white")] [.text "\n    ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_control.so"), ("name", "gazebo_ros_control")] [.text "\n      ",
.element "robotNamespace" [] [.text "/go1_gazebo"],
.text "\n      ",
.element "robotSimType" [] [.text "gazebo_ros_control/DefaultRobotHWSim"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libLinkPlot3DPlugin.so"), ("name", "3dplot")] [.text "\n      ",
.element "frequency" [] [.text "10"],
.text "\n      ",
.element "plot" [] [.text "\n        ",
.element "link" [] [.text "base"],
.text "\n        ",
.element "pose" [] [.text "0 0 0 0 0 0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/Yellow"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_force.so"), ("name", "gazebo_ros_force")] [.text "\n      ",
.element "bodyName" [] [.text "trunk"],
.text "\n      ",
.element "topicName" [] [.text "/apply_force/trunk"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "imu_link")] [.text "\n    ",
.element "gravity" [] [.text "true"],
.text "\n    ",
.element "sensor" [("name", "imu_sensor"), ("type", "imu")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "1000"],
.text "\n      ",
.element "visualize" [] [.text "true"],
.text "\n      ",
.element "topic" [] [.text "__default_topic__"],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_imu_sensor.so"), ("name", "imu_plugin")] [.text "\n        ",
.element "topicName" [] [.text "trunk_imu"],
.text "\n        ",
.element "bodyName" [] [.text "imu_link"],
.text "\n        ",
.element "updateRateHZ" [] [.text "1000.0"],
.text "\n        ",
.element "gaussianNoise" [] [.text "0.0"],
.text "\n        ",
.element "xyzOffset" [] [.text "0 0 0"],
.text "\n        ",
.element "rpyOffset" [] [.text "0 0 0"],
.text "\n        ",
.element "frameName" [] [.text "imu_link"],
.text "\n      "],
.text "\n      ",
.element "pose" [] [.text "0 0 0 0 0 0"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  \n  ",
.element "gazebo" [("reference", "depthCamera_link_left")] [.text "\n    ",
.element "sensor" [("name", "camera_link_camera"), ("type", "depth")] [.text "\n      ",
.element "update_rate" [] [.text "20"],
.text "\n      ",
.element "camera" [] [.text "\n        ",
.element "horizontal_fov" [] [.text "1.047198"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "640"],
.text "\n          ",
.element "height" [] [.text "480"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.05"],
.text "\n          ",
.element "far" [] [.text "3"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_openni_kinect.so"), ("name", "camera_link_controller")] [.text "\n        ",
.element "baseline" [] [.text "0.2"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "1.0"],
.text "\n        ",
.element "cameraName" [] [.text "camera_link_ir"],
.text "\n        ",
.element "imageTopicName" [] [.text "/camera_link/color/image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "/camera_link/color/camera_info"],
.text "\n        ",
.element "depthImageTopicName" [] [.text "/camera_link/depth/image_raw"],
.text "\n        ",
.element "depthImageInfoTopicName" [] [.text "/camera_link/depth/camera_info"],
.text "\n        ",
.element "pointCloudTopicName" [] [.text "/camera_link/depth/points"],
.text "\n        ",
.element "frameName" [] [.text "depthCamera_link_left"],
.text "\n        ",
.element "pointCloudCutoff" [] [.text "0.5"],
.text "\n        ",
.element "pointCloudCutoffMax" [] [.text "3.0"],
.text "\n        ",
.element "distortionK1" [] [.text "0.00000001"],
.text "\n        ",
.element "distortionK2" [] [.text "0.00000001"],
.text "\n        ",
.element "distortionK3" [] [.text "0.00000001"],
.text "\n        ",
.element "distortionT1" [] [.text "0.00000001"],
.text "\n        ",
.element "distortionT2" [] [.text "0.00000001"],
.text "\n        ",
.element "CxPrime" [] [.text "0"],
.text "\n        ",
.element "Cx" [] [.text "0"],
.text "\n        ",
.element "Cy" [] [.text "0"],
.text "\n        ",
.element "focalLength" [] [.text "0"],
.text "\n        ",
.element "hackBaseline" [] [.text "0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FR_calf")] [.text "\n    ",
.element "sensor" [("name", "FR_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "FR_calf_fixed_joint_lump__FR_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_calf")] [.text "\n    ",
.element "sensor" [("name", "FL_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "FL_calf_fixed_joint_lump__FL_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_calf")] [.text "\n    ",
.element "sensor" [("name", "RR_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "RR_calf_fixed_joint_lump__RR_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_calf")] [.text "\n    ",
.element "sensor" [("name", "RL_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "RL_calf_fixed_joint_lump__RL_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "FR_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "FL_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "RR_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "RL_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "base")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Green"],
.text "\n    ",
.element "turnGravityOff" [] [.text "false"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "trunk")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "stick_link")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/White"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "imu_link")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/Red"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FL_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FR_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FR_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FR_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FR_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "RL_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "RR_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  \n  \n  \n  \n  \n  ",
.element "link" [("name", "base")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "floating_base"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base")] [],
.text "\n    ",
.element "child" [("link", "trunk")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "trunk")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/trunk.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.3762 0.0935 0.114")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0223 0.002 -0.0005")] [],
.text "\n      ",
.element "mass" [("value", "5.204")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0168128557"), ("ixy", "-0.0002296769"), ("ixz", "-0.0002945293"), ("iyy", "0.063009565"), ("iyz", "-4.18731e-05"), ("izz", "0.0716547275")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "imu_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "imu_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.01592 -0.06659 -0.00617")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "imu_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1881 -0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FR_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.863"), ("upper", "0.863"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.11215 -0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FR_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.141592653589793 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/hip.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 -0.08 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.04"), ("radius", "0.046")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.005657 0.008752 -0.000102")] [],
.text "\n      ",
.element "mass" [("value", "0.591")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000334008405"), ("ixy", "1.0826066e-05"), ("ixz", "1.290732e-06"), ("iyy", "0.000619101213"), ("iyz", "-1.643194e-06"), ("izz", "0.00040057614")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000111842"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "5.9647e-05"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.08 0")] [],
.text "\n    ",
.element "parent" [("link", "FR_hip")] [],
.text "\n    ",
.element "child" [("link", "FR_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.686"), ("upper", "4.501"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.00015 0")] [],
.text "\n    ",
.element "parent" [("link", "FR_hip")] [],
.text "\n    ",
.element "child" [("link", "FR_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/thigh_mirror.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.0245 0.034")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003342 0.018054 -0.033451")] [],
.text "\n      ",
.element "mass" [("value", "0.92")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.004431760472"), ("ixy", "-5.7496807e-05"), ("ixz", "-0.000218457134"), ("iyy", "0.004485671726"), ("iyz", "-0.000572001265"), ("izz", "0.000740309489")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "FR_thigh")] [],
.text "\n    ",
.element "child" [("link", "FR_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "35.55"), ("lower", "-2.818"), ("upper", "-0.888"), ("velocity", "20.06")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.03235 0")] [],
.text "\n    ",
.element "parent" [("link", "FR_thigh")] [],
.text "\n    ",
.element "child" [("link", "FR_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/calf.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.016 0.016")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.006197 0.001408 -0.116695")] [],
.text "\n      ",
.element "mass" [("value", "0.135862")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001088793059"), ("ixy", "-2.55679e-07"), ("ixz", "7.117814e-06"), ("iyy", "0.001100428748"), ("iyz", "2.077264e-06"), ("izz", "2.4787446e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "FR_calf")] [],
.text "\n    ",
.element "child" [("link", "FR_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.06")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.600000000000001e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "9.600000000000001e-06"), ("iyz", "0.0"), ("izz", "9.600000000000001e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FR_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FR_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FR_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FR_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FR_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FR_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FR_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FR_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FR_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1881 0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FL_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.863"), ("upper", "0.863"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.11215 0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FL_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/hip.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.08 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.04"), ("radius", "0.046")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.005657 -0.008752 -0.000102")] [],
.text "\n      ",
.element "mass" [("value", "0.591")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000334008405"), ("ixy", "-1.0826066e-05"), ("ixz", "1.290732e-06"), ("iyy", "0.000619101213"), ("iyz", "1.643194e-06"), ("izz", "0.00040057614")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000111842"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "5.9647e-05"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.08 0")] [],
.text "\n    ",
.element "parent" [("link", "FL_hip")] [],
.text "\n    ",
.element "child" [("link", "FL_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.686"), ("upper", "4.501"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.00015 0")] [],
.text "\n    ",
.element "parent" [("link", "FL_hip")] [],
.text "\n    ",
.element "child" [("link", "FL_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/thigh.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.0245 0.034")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003342 -0.018054 -0.033451")] [],
.text "\n      ",
.element "mass" [("value", "0.92")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.004431760472"), ("ixy", "5.7496807e-05"), ("ixz", "-0.000218457134"), ("iyy", "0.004485671726"), ("iyz", "0.000572001265"), ("izz", "0.000740309489")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "FL_thigh")] [],
.text "\n    ",
.element "child" [("link", "FL_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "35.55"), ("lower", "-2.818"), ("upper", "-0.888"), ("velocity", "20.06")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.03235 0")] [],
.text "\n    ",
.element "parent" [("link", "FL_thigh")] [],
.text "\n    ",
.element "child" [("link", "FL_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/calf.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.016 0.016")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.006197 0.001408 -0.116695")] [],
.text "\n      ",
.element "mass" [("value", "0.135862")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001088793059"), ("ixy", "-2.55679e-07"), ("ixz", "7.117814e-06"), ("iyy", "0.001100428748"), ("iyz", "2.077264e-06"), ("izz", "2.4787446e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "FL_calf")] [],
.text "\n    ",
.element "child" [("link", "FL_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.06")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.600000000000001e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "9.600000000000001e-06"), ("iyz", "0.0"), ("izz", "9.600000000000001e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FL_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FL_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FL_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FL_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FL_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FL_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FL_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FL_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FL_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1881 -0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RR_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.863"), ("upper", "0.863"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.11215 -0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RR_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.141592653589793 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/hip.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 -0.08 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.04"), ("radius", "0.046")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.005657 0.008752 -0.000102")] [],
.text "\n      ",
.element "mass" [("value", "0.591")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000334008405"), ("ixy", "-1.0826066e-05"), ("ixz", "-1.290732e-06"), ("iyy", "0.000619101213"), ("iyz", "-1.643194e-06"), ("izz", "0.00040057614")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000111842"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "5.9647e-05"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.08 0")] [],
.text "\n    ",
.element "parent" [("link", "RR_hip")] [],
.text "\n    ",
.element "child" [("link", "RR_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.686"), ("upper", "4.501"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.00015 0")] [],
.text "\n    ",
.element "parent" [("link", "RR_hip")] [],
.text "\n    ",
.element "child" [("link", "RR_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/thigh_mirror.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.0245 0.034")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003342 0.018054 -0.033451")] [],
.text "\n      ",
.element "mass" [("value", "0.92")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.004431760472"), ("ixy", "-5.7496807e-05"), ("ixz", "-0.000218457134"), ("iyy", "0.004485671726"), ("iyz", "-0.000572001265"), ("izz", "0.000740309489")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "RR_thigh")] [],
.text "\n    ",
.element "child" [("link", "RR_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "35.55"), ("lower", "-2.818"), ("upper", "-0.888"), ("velocity", "20.06")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.03235 0")] [],
.text "\n    ",
.element "parent" [("link", "RR_thigh")] [],
.text "\n    ",
.element "child" [("link", "RR_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/calf.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.016 0.016")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.006197 0.001408 -0.116695")] [],
.text "\n      ",
.element "mass" [("value", "0.135862")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001088793059"), ("ixy", "-2.55679e-07"), ("ixz", "7.117814e-06"), ("iyy", "0.001100428748"), ("iyz", "2.077264e-06"), ("izz", "2.4787446e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "RR_calf")] [],
.text "\n    ",
.element "child" [("link", "RR_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.06")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.600000000000001e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "9.600000000000001e-06"), ("iyz", "0.0"), ("izz", "9.600000000000001e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RR_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RR_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RR_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RR_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RR_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RR_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RR_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RR_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RR_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1881 0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RL_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.863"), ("upper", "0.863"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.11215 0.04675 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RL_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/hip.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.08 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.04"), ("radius", "0.046")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.005657 -0.008752 -0.000102")] [],
.text "\n      ",
.element "mass" [("value", "0.591")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000334008405"), ("ixy", "1.0826066e-05"), ("ixz", "-1.290732e-06"), ("iyy", "0.000619101213"), ("iyz", "1.643194e-06"), ("izz", "0.00040057614")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000111842"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "5.9647e-05"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.08 0")] [],
.text "\n    ",
.element "parent" [("link", "RL_hip")] [],
.text "\n    ",
.element "child" [("link", "RL_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "23.7"), ("lower", "-0.686"), ("upper", "4.501"), ("velocity", "30.1")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.00015 0")] [],
.text "\n    ",
.element "parent" [("link", "RL_hip")] [],
.text "\n    ",
.element "child" [("link", "RL_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/thigh.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.0245 0.034")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003342 -0.018054 -0.033451")] [],
.text "\n      ",
.element "mass" [("value", "0.92")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.004431760472"), ("ixy", "5.7496807e-05"), ("ixz", "-0.000218457134"), ("iyy", "0.004485671726"), ("iyz", "0.000572001265"), ("izz", "0.000740309489")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "RL_thigh")] [],
.text "\n    ",
.element "child" [("link", "RL_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    ",
.element "limit" [("effort", "35.55"), ("lower", "-2.818"), ("upper", "-0.888"), ("velocity", "20.06")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.03235 0")] [],
.text "\n    ",
.element "parent" [("link", "RL_thigh")] [],
.text "\n    ",
.element "child" [("link", "RL_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/calf.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 -0.1065")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.213 0.016 0.016")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.006197 0.001408 -0.116695")] [],
.text "\n      ",
.element "mass" [("value", "0.135862")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.001088793059"), ("ixy", "-2.55679e-07"), ("ixz", "7.117814e-06"), ("iyy", "0.001100428748"), ("iyz", "2.077264e-06"), ("izz", "2.4787446e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.035")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.089")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.9647e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000111842"), ("iyz", "0.0"), ("izz", "5.9647e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.213")] [],
.text "\n    ",
.element "parent" [("link", "RL_calf")] [],
.text "\n    ",
.element "child" [("link", "RL_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.01")] [],
.text "\n      "],
.text "\n      \n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.02")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.06")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.600000000000001e-06"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "9.600000000000001e-06"), ("iyz", "0.0"), ("izz", "9.600000000000001e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RL_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RL_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RL_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RL_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RL_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RL_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RL_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RL_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RL_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_joint_face"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 0 0"), ("xyz", "0.2785 0.0125 0.0167")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "camera_face")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_face")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/depthCamera.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_optical_joint_face"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 -1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_face")] [],
.text "\n    ",
.element "child" [("link", "camera_optical_face")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_optical_face")] [.text "\n        "],
.text "\n  ",
.element "gazebo" [("reference", "camera_face")] [.text "\n    \n    ",
.element "sensor" [("name", "camera_face_camera"), ("type", "depth")] [.text "\n      ",
.element "update_rate" [] [.text "16"],
.text "\n      ",
.element "camera" [] [.text "\n        ",
.element "horizontal_fov" [] [.text "2.094"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "928"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.1"],
.text "\n          ",
.element "far" [] [.text "5"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_openni_kinect.so"), ("name", "camera_face_controller")] [.text "\n        ",
.element "baseline" [] [.text "0.025"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "camera_face_ir"],
.text "\n        ",
.element "imageTopicName" [] [.text "/camera_face/color/image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "/camera_face/color/camera_info"],
.text "\n        ",
.element "depthImageTopicName" [] [.text "/camera_face/depth/image_raw"],
.text "\n        ",
.element "depthImageInfoTopicName" [] [.text "/camera_face/depth/camera_info"],
.text "\n        \n        ",
.element "pointCloudTopicName" [] [.text "/cam1/point_cloud_face"],
.text "\n        ",
.element "frameName" [] [.text "camera_optical_face"],
.text "\n        ",
.element "pointCloudCutoff" [] [.text "0.1"],
.text "\n        ",
.element "pointCloudCutoffMax" [] [.text "1.5"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "CxPrime" [] [.text "0"],
.text "\n        ",
.element "Cx" [] [.text "0.0045"],
.text "\n        ",
.element "Cy" [] [.text "0.0039"],
.text "\n        ",
.element "focalLength" [] [.text "0"],
.text "\n        ",
.element "hackBaseline" [] [.text "0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_joint_chin"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 1.5707963267948966 0"), ("xyz", "0.2522 0.0125 -0.0436")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "camera_chin")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_chin")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/depthCamera.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_optical_joint_chin"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 -1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_chin")] [],
.text "\n    ",
.element "child" [("link", "camera_optical_chin")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_optical_chin")] [.text "\n        "],
.text "\n  ",
.element "gazebo" [("reference", "camera_chin")] [.text "\n    \n    ",
.element "sensor" [("name", "camera_chin_camera"), ("type", "depth")] [.text "\n      ",
.element "update_rate" [] [.text "16"],
.text "\n      ",
.element "camera" [] [.text "\n        ",
.element "horizontal_fov" [] [.text "2.094"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "928"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.1"],
.text "\n          ",
.element "far" [] [.text "5"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_openni_kinect.so"), ("name", "camera_chin_controller")] [.text "\n        ",
.element "baseline" [] [.text "0.025"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "camera_chin_ir"],
.text "\n        ",
.element "imageTopicName" [] [.text "/camera_chin/color/image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "/camera_chin/color/camera_info"],
.text "\n        ",
.element "depthImageTopicName" [] [.text "/camera_chin/depth/image_raw"],
.text "\n        ",
.element "depthImageInfoTopicName" [] [.text "/camera_chin/depth/camera_info"],
.text "\n        \n        ",
.element "pointCloudTopicName" [] [.text "/cam2/point_cloud_chin"],
.text "\n        ",
.element "frameName" [] [.text "camera_optical_chin"],
.text "\n        ",
.element "pointCloudCutoff" [] [.text "0.1"],
.text "\n        ",
.element "pointCloudCutoffMax" [] [.text "1.5"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "CxPrime" [] [.text "0"],
.text "\n        ",
.element "Cx" [] [.text "0.0045"],
.text "\n        ",
.element "Cy" [] [.text "0.0039"],
.text "\n        ",
.element "focalLength" [] [.text "0"],
.text "\n        ",
.element "hackBaseline" [] [.text "0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_joint_left"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 0.2618 1.5707963267948966"), ("xyz", "-0.066 0.082 -0.0176")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "camera_left")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_left")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/depthCamera.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_optical_joint_left"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 -1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_left")] [],
.text "\n    ",
.element "child" [("link", "camera_optical_left")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_optical_left")] [.text "\n        "],
.text "\n  ",
.element "gazebo" [("reference", "camera_left")] [.text "\n    \n    ",
.element "sensor" [("name", "camera_left_camera"), ("type", "depth")] [.text "\n      ",
.element "update_rate" [] [.text "16"],
.text "\n      ",
.element "camera" [] [.text "\n        ",
.element "horizontal_fov" [] [.text "2.094"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "928"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.1"],
.text "\n          ",
.element "far" [] [.text "5"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_openni_kinect.so"), ("name", "camera_left_controller")] [.text "\n        ",
.element "baseline" [] [.text "0.025"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "camera_left_ir"],
.text "\n        ",
.element "imageTopicName" [] [.text "/camera_left/color/image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "/camera_left/color/camera_info"],
.text "\n        ",
.element "depthImageTopicName" [] [.text "/camera_left/depth/image_raw"],
.text "\n        ",
.element "depthImageInfoTopicName" [] [.text "/camera_left/depth/camera_info"],
.text "\n        \n        ",
.element "pointCloudTopicName" [] [.text "/cam3/point_cloud_left"],
.text "\n        ",
.element "frameName" [] [.text "camera_optical_left"],
.text "\n        ",
.element "pointCloudCutoff" [] [.text "0.1"],
.text "\n        ",
.element "pointCloudCutoffMax" [] [.text "1.5"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "CxPrime" [] [.text "0"],
.text "\n        ",
.element "Cx" [] [.text "0.0045"],
.text "\n        ",
.element "Cy" [] [.text "0.0039"],
.text "\n        ",
.element "focalLength" [] [.text "0"],
.text "\n        ",
.element "hackBaseline" [] [.text "0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_joint_right"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 0.2618 -1.5707963267948966"), ("xyz", "-0.041 -0.082 -0.0176")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "camera_right")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_right")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/depthCamera.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_optical_joint_right"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 -1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_right")] [],
.text "\n    ",
.element "child" [("link", "camera_optical_right")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_optical_right")] [.text "\n        "],
.text "\n  ",
.element "gazebo" [("reference", "camera_right")] [.text "\n    \n    ",
.element "sensor" [("name", "camera_right_camera"), ("type", "depth")] [.text "\n      ",
.element "update_rate" [] [.text "16"],
.text "\n      ",
.element "camera" [] [.text "\n        ",
.element "horizontal_fov" [] [.text "2.094"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "928"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.1"],
.text "\n          ",
.element "far" [] [.text "5"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_openni_kinect.so"), ("name", "camera_right_controller")] [.text "\n        ",
.element "baseline" [] [.text "0.025"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "camera_right_ir"],
.text "\n        ",
.element "imageTopicName" [] [.text "/camera_right/color/image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "/camera_right/color/camera_info"],
.text "\n        ",
.element "depthImageTopicName" [] [.text "/camera_right/depth/image_raw"],
.text "\n        ",
.element "depthImageInfoTopicName" [] [.text "/camera_right/depth/camera_info"],
.text "\n        \n        ",
.element "pointCloudTopicName" [] [.text "/cam4/point_cloud_right"],
.text "\n        ",
.element "frameName" [] [.text "camera_optical_right"],
.text "\n        ",
.element "pointCloudCutoff" [] [.text "0.1"],
.text "\n        ",
.element "pointCloudCutoffMax" [] [.text "1.5"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "CxPrime" [] [.text "0"],
.text "\n        ",
.element "Cx" [] [.text "0.0045"],
.text "\n        ",
.element "Cy" [] [.text "0.0039"],
.text "\n        ",
.element "focalLength" [] [.text "0"],
.text "\n        ",
.element "hackBaseline" [] [.text "0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_joint_rearDown"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 1.5707963267948966 0"), ("xyz", "-0.0825 0.0125 -0.04365")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "camera_rearDown")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_rearDown")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/depthCamera.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_optical_joint_rearDown"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 -1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_rearDown")] [],
.text "\n    ",
.element "child" [("link", "camera_optical_rearDown")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_optical_rearDown")] [.text "\n        "],
.text "\n  ",
.element "gazebo" [("reference", "camera_rearDown")] [.text "\n    \n    ",
.element "sensor" [("name", "camera_rearDown_camera"), ("type", "depth")] [.text "\n      ",
.element "update_rate" [] [.text "16"],
.text "\n      ",
.element "camera" [] [.text "\n        ",
.element "horizontal_fov" [] [.text "2.094"],
.text "\n        ",
.element "image" [] [.text "\n          ",
.element "width" [] [.text "928"],
.text "\n          ",
.element "height" [] [.text "800"],
.text "\n          ",
.element "format" [] [.text "R8G8B8"],
.text "\n        "],
.text "\n        ",
.element "clip" [] [.text "\n          ",
.element "near" [] [.text "0.1"],
.text "\n          ",
.element "far" [] [.text "5"],
.text "\n        "],
.text "\n      "],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_openni_kinect.so"), ("name", "camera_rearDown_controller")] [.text "\n        ",
.element "baseline" [] [.text "0.025"],
.text "\n        ",
.element "alwaysOn" [] [.text "true"],
.text "\n        ",
.element "updateRate" [] [.text "0.0"],
.text "\n        ",
.element "cameraName" [] [.text "camera_rearDown_ir"],
.text "\n        ",
.element "imageTopicName" [] [.text "/camera_rearDown/color/image_raw"],
.text "\n        ",
.element "cameraInfoTopicName" [] [.text "/camera_rearDown/color/camera_info"],
.text "\n        ",
.element "depthImageTopicName" [] [.text "/camera_rearDown/depth/image_raw"],
.text "\n        ",
.element "depthImageInfoTopicName" [] [.text "/camera_rearDown/depth/camera_info"],
.text "\n        \n        ",
.element "pointCloudTopicName" [] [.text "/cam5/point_cloud_rearDown"],
.text "\n        ",
.element "frameName" [] [.text "camera_optical_rearDown"],
.text "\n        ",
.element "pointCloudCutoff" [] [.text "0.1"],
.text "\n        ",
.element "pointCloudCutoffMax" [] [.text "1.5"],
.text "\n        ",
.element "distortionK1" [] [.text "0.0"],
.text "\n        ",
.element "distortionK2" [] [.text "0.0"],
.text "\n        ",
.element "distortionK3" [] [.text "0.0"],
.text "\n        ",
.element "distortionT1" [] [.text "0.0"],
.text "\n        ",
.element "distortionT2" [] [.text "0.0"],
.text "\n        ",
.element "CxPrime" [] [.text "0"],
.text "\n        ",
.element "Cx" [] [.text "0.0045"],
.text "\n        ",
.element "Cy" [] [.text "0.0039"],
.text "\n        ",
.element "focalLength" [] [.text "0"],
.text "\n        ",
.element "hackBaseline" [] [.text "0"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "camera_laserscan_joint_left"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0.2618 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_left")] [],
.text "\n    ",
.element "child" [("link", "camera_laserscan_link_left")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_laserscan_link_left")] [.text "\n    "],
.text "\n  ",
.element "joint" [("name", "camera_laserscan_joint_right"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0.2618 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "camera_right")] [],
.text "\n    ",
.element "child" [("link", "camera_laserscan_link_right")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "camera_laserscan_link_right")] [.text "\n    "],
.text "\n  ",
.element "joint" [("name", "ultraSound_joint_left"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0.2618 1.5707963267948966"), ("xyz", "-0.0535  0.0826 0.00868")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "ultraSound_left")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "ultraSound_left")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/ultraSound.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "ultraSound_joint_right"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0.2618 -1.5707963267948966"), ("xyz", "-0.0535 -0.0826 0.00868")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "ultraSound_right")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "ultraSound_right")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/ultraSound.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "ultraSound_joint_face"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.2747 0.0 -0.0088")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "ultraSound_face")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "ultraSound_face")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://go1_description/meshes/ultraSound.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1e-5")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "1e-6"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1e-6"), ("iyz", "0"), ("izz", "1e-6")] [],
.text "\n    "],
.text "\n  "],
.text "\n"],
[],
[],
"8c4c22e581b549027c1918259627bb5172afdf56ab970814b0c6f62ecf5604ff"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
