import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "solo"), ("xmlns:controller", "http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"), ("xmlns:interface", "http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"), ("xmlns:sensor", "http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"), ("xmlns:xacro", "http://playerstage.sourceforge.net/gazebo/xmlschema/#interface")] [.text "\n  \n  ",
.element "link" [("name", "base_link")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.16115091")] [],
.text "\n      \n      ",
.element "inertia" [("ixx", "0.00578574"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.01938108"), ("iyz", "0.0"), ("izz", "0.02476124")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo_12_base.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo_12_base.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "FL_HAA"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "FL_SHOULDER")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1946 0.0875 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_SHOULDER")] [.text "\n    \n    \n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_fl.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_fl.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.07870700 0.01 0.")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00003024"), ("ixy", "0.00004671"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "0.0"), ("izz", "0.00041107")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_HFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "FL_SHOULDER")] [],
.text "\n    ",
.element "child" [("link", "FL_UPPER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.014 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_UPPER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00001377 0.01935853 -0.07870700")] [],
.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00041107"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "0.00004671"), ("izz", "0.00003024")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "FL_KFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "FL_UPPER_LEG")] [],
.text "\n    ",
.element "child" [("link", "FL_LOWER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.03745 -0.16")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_LOWER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.00787644 -0.08928215")] [],
.text "\n      ",
.element "mass" [("value", "0.03070001")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00012024"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00012029"), ("iyz", "0.00000305"), ("izz", "0.00000216")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "FL_ANKLE"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "FL_LOWER_LEG")] [],
.text "\n    ",
.element "child" [("link", "FL_FOOT")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.008 -0.16")] [],
.text "\n    \n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_FOOT")] [.text "\n    \n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.00035767")] [],
.text "\n      ",
.element "mass" [("value", "0.00693606")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00000057"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00000084"), ("iyz", "0.0"), ("izz", "0.00000053")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "FR_HAA"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "FR_SHOULDER")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1946 -0.0875 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_SHOULDER")] [.text "\n    \n    \n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_fr.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_fr.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.07870700 -0.01 0.")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00003024"), ("ixy", "-0.00004671"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "0.0"), ("izz", "0.00041107")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_HFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "FR_SHOULDER")] [],
.text "\n    ",
.element "child" [("link", "FR_UPPER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.014 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_UPPER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00001377 -0.01935853 -0.07870700")] [],
.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00041107"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "-0.00004671"), ("izz", "0.00003024")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "FR_KFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "FR_UPPER_LEG")] [],
.text "\n    ",
.element "child" [("link", "FR_LOWER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.03745 -0.16")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_LOWER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.00787644 -0.08928215")] [],
.text "\n      ",
.element "mass" [("value", "0.03070001")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00012024"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00012029"), ("iyz", "-0.00000305"), ("izz", "0.00000216")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "FR_ANKLE"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "FR_LOWER_LEG")] [],
.text "\n    ",
.element "child" [("link", "FR_FOOT")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.008 -0.16")] [],
.text "\n    \n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_FOOT")] [.text "\n    \n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.00035767")] [],
.text "\n      ",
.element "mass" [("value", "0.00693606")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00000057"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00000084"), ("iyz", "0.0"), ("izz", "0.00000053")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "HL_HAA"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "HL_SHOULDER")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1946 0.0875 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HL_SHOULDER")] [.text "\n    \n    \n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_hl.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_hl.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.07870700 0.01 0.")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00003024"), ("ixy", "0.00004671"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "0.0"), ("izz", "0.00041107")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "HL_HFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "HL_SHOULDER")] [],
.text "\n    ",
.element "child" [("link", "HL_UPPER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.014 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HL_UPPER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00001377 0.01935853 -0.07870700")] [],
.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00041107"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "0.00004671"), ("izz", "0.00003024")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "HL_KFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "HL_UPPER_LEG")] [],
.text "\n    ",
.element "child" [("link", "HL_LOWER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.03745 -0.16")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HL_LOWER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.00787644 -0.08928215")] [],
.text "\n      ",
.element "mass" [("value", "0.03070001")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00012024"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00012029"), ("iyz", "0.00000305"), ("izz", "0.00000216")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_left_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "HL_ANKLE"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "HL_LOWER_LEG")] [],
.text "\n    ",
.element "child" [("link", "HL_FOOT")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.008 -0.16")] [],
.text "\n    \n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HL_FOOT")] [.text "\n    \n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.00035767")] [],
.text "\n      ",
.element "mass" [("value", "0.00693606")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00000057"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00000084"), ("iyz", "0.0"), ("izz", "0.00000053")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "HR_HAA"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "HR_SHOULDER")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1946 -0.0875 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HR_SHOULDER")] [.text "\n    \n    \n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_hr.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.01950 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/solo12/solo12_hip_fe_hr.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      \n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.07870700 -0.01 0.")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00003024"), ("ixy", "-0.00004671"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "0.0"), ("izz", "0.00041107")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "HR_HFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "HR_SHOULDER")] [],
.text "\n    ",
.element "child" [("link", "HR_UPPER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.014 0")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HR_UPPER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00001377 -0.01935853 -0.07870700")] [],
.text "\n      ",
.element "mass" [("value", "0.14853845")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00041107"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00041193"), ("iyz", "-0.00004671"), ("izz", "0.00003024")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_upper_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "HR_KFE"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "HR_UPPER_LEG")] [],
.text "\n    ",
.element "child" [("link", "HR_LOWER_LEG")] [],
.text "\n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.03745 -0.16")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HR_LOWER_LEG")] [.text "\n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.00787644 -0.08928215")] [],
.text "\n      ",
.element "mass" [("value", "0.03070001")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00012024"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00012029"), ("iyz", "-0.00000305"), ("izz", "0.00000216")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_lower_leg_right_side.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "joint" [("name", "HR_ANKLE"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "HR_LOWER_LEG")] [],
.text "\n    ",
.element "child" [("link", "HR_FOOT")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.008 -0.16")] [],
.text "\n    \n    ",
.element "limit" [("effort", "1000"), ("lower", "-10"), ("upper", "10"), ("velocity", "1000")] [],
.text "\n    \n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "HR_FOOT")] [.text "\n    \n    \n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.00035767")] [],
.text "\n      ",
.element "mass" [("value", "0.00693606")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00000057"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00000084"), ("iyz", "0.0"), ("izz", "0.00000053")] [],
.text "\n    "],
.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/solo_description/meshes/stl/with_foot/solo_foot.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.8 0.8 0.8 1.0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    \n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "restitution" [("value", "0.5")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n"],
[],
[],
"d200b04281c30544bb38fec2cc42c9284d45ff960c1380120b373abc5345aaa5"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
