import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "ur3"), ("xmlns:xacro", "http://wiki.ros.org/xacro")] [.text "\n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_control.so"), ("name", "ros_control")] [.text "\n      \n      \n    "],
.text "\n    \n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "base_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/base.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/base.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.0")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0030531654454"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0030531654454"), ("iyz", "0.0"), ("izz", "0.005625")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "shoulder_pan_joint"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "shoulder_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 0.0 0.1519")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "330.0"), ("lower", "-6.28318530718"), ("upper", "6.28318530718"), ("velocity", "2.16")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "shoulder_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/shoulder.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/shoulder.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "2.0")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0080931634294"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0080931634294"), ("iyz", "0.0"), ("izz", "0.005625")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "shoulder_lift_joint"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "shoulder_link")] [],
.text "\n    ",
.element "child" [("link", "upper_arm_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 1.57079632679 0.0"), ("xyz", "0.0 0.1198 0.0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "330.0"), ("lower", "-6.28318530718"), ("upper", "6.28318530718"), ("velocity", "2.16")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "upper_arm_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/upperarm.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/upperarm.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "3.42")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.121825")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0217284832211"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0217284832211"), ("iyz", "0.0"), ("izz", "0.00961875")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "elbow_joint"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "upper_arm_link")] [],
.text "\n    ",
.element "child" [("link", "forearm_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 -0.0925 0.24365")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "150.0"), ("lower", "-3.14159265359"), ("upper", "3.14159265359"), ("velocity", "3.15")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "forearm_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/forearm.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/forearm.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "1.26")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.106625")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00654680644378"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00654680644378"), ("iyz", "0.0"), ("izz", "0.00354375")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "wrist_1_joint"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "forearm_link")] [],
.text "\n    ",
.element "child" [("link", "wrist_1_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 1.57079632679 0.0"), ("xyz", "0.0 0.0 0.21325")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "54.0"), ("lower", "-6.28318530718"), ("upper", "6.28318530718"), ("velocity", "3.2")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "wrist_1_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/wrist1.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/wrist1.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.8")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.002084999166"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.002084999166"), ("iyz", "0.0"), ("izz", "0.00225")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "wrist_2_joint"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "wrist_1_link")] [],
.text "\n    ",
.element "child" [("link", "wrist_2_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 0.08505 0.0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "54.0"), ("lower", "-6.28318530718"), ("upper", "6.28318530718"), ("velocity", "3.2")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "wrist_2_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/wrist2.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/wrist2.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.8")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.002084999166"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.002084999166"), ("iyz", "0.0"), ("izz", "0.00225")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "wrist_3_joint"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "wrist_2_link")] [],
.text "\n    ",
.element "child" [("link", "wrist_3_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 0.0 0.08535")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "limit" [("effort", "54.0"), ("lower", "-6.28318530718"), ("upper", "6.28318530718"), ("velocity", "3.2")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "wrist_3_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/visual/wrist3.dae")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/ur_description/meshes/ur3/collision/wrist3.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.35")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000912187135125"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000912187135125"), ("iyz", "0.0"), ("izz", "0.000984375")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "ee_fixed_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "wrist_3_link")] [],
.text "\n    ",
.element "child" [("link", "ee_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 1.57079632679"), ("xyz", "0.0 0.0819 0.0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "ee_link")] [.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.01 0.01 0.01")] [],
.text "\n      "],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.01 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0"), ("iyz", "0.0"), ("izz", "0.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "shoulder_pan_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "shoulder_pan_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "shoulder_pan_motor")] [.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "shoulder_lift_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "shoulder_lift_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "shoulder_lift_motor")] [.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "elbow_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "elbow_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "elbow_motor")] [.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "wrist_1_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "wrist_1_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "wrist_1_motor")] [.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "wrist_2_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "wrist_2_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "wrist_2_motor")] [.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "wrist_3_trans")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "wrist_3_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/PositionJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "wrist_3_motor")] [.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "shoulder_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "upper_arm_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "forearm_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "wrist_1_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "wrist_3_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "wrist_2_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "ee_link")] [.text "\n    ",
.element "selfCollide" [] [.text "true"],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "base")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0"), ("iyz", "0.0"), ("izz", "0.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "base_link-base_fixed_joint"), ("type", "fixed")] [.text "\n    \n    ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "base")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "tool0")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.0")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.0"), ("iyz", "0.0"), ("izz", "0.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "wrist_3_link-tool0_fixed_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "0 0.0819 0")] [],
.text "\n    ",
.element "parent" [("link", "wrist_3_link")] [],
.text "\n    ",
.element "child" [("link", "tool0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "world")] [],
.text "\n  ",
.element "joint" [("name", "world_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "world")] [],
.text "\n    ",
.element "child" [("link", "base_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n  "],
.text "\n"],
[],
[],
"679f2ee7e9b182e746a5a93b53a336ae8dffc63ec554c272b2c8ba3692d086eb"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
