import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("xmlns:xacro", "http://ros.org/wiki/xacro"), ("name", "simple_humanoid_classical")] [.text "\n  ",
.element "link" [("name", "base_link")] [],
.text "\n\n  \n  ",
.element "link" [("name", "BODY")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.0375"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "27")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "WAIST_LINK1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "WAIST_LINK2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.11 0 0.25"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "30")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "torso")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "13")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LARM_LINK1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.1 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "3")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LARM_LINK2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LARM_LINK3")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LARM_LINK4")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LARM_LINK5")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.4")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LARM_LINK6")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.1 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.4")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "l_wrist")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.4")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RARM_LINK1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.1 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "3")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RARM_LINK2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RARM_LINK3")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RARM_LINK4")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.6")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RARM_LINK5")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.4")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RARM_LINK6")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.1 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.4")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "r_wrist")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.1"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.4")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LLEG_LINK1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0.1 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2.5")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LLEG_LINK2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.15"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LLEG_LINK3")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0.04 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "5.1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LLEG_LINK4")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "7")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "LLEG_LINK5")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.15 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2.5")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "l_ankle")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.28 0 -0.2"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.9")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RLEG_LINK1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 -0.1 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2.5")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RLEG_LINK2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.15"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RLEG_LINK3")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 -0.04 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "5.1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RLEG_LINK4")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "7")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "RLEG_LINK5")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.15 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "2.5")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  \n  ",
.element "link" [("name", "r_ankle")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.28 0 -0.2"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1.9")] [],
.text "\n      ",
.element "inertia" [("ixx", "1"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1"), ("iyz", "0"), ("izz", "1")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n\n\n  \n\n  ",
.element "joint" [("name", "waist"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "BODY")] [],
.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RLEG_HIP_Y"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 -0.09 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "BODY")] [],
.text "\n    ",
.element "child" [("link", "RLEG_LINK1")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.349065850399"), ("upper", "1.57079632679"), ("velocity", "3.87")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RLEG_HIP_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "RLEG_LINK1")] [],
.text "\n    ",
.element "child" [("link", "RLEG_LINK2")] [],
.text "\n    ",
.element "limit" [("effort", "160"), ("lower", "-0.5236"), ("upper", "0.5236"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RLEG_HIP_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "RLEG_LINK2")] [],
.text "\n    ",
.element "child" [("link", "RLEG_LINK3")] [],
.text "\n    ",
.element "limit" [("effort", "160"), ("lower", "-2.095"), ("upper", "0.7"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RLEG_KNEE"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3535"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "RLEG_LINK3")] [],
.text "\n    ",
.element "child" [("link", "RLEG_LINK4")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "0"), ("upper", "2.618"), ("velocity", "7")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RLEG_ANKLE_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "RLEG_LINK4")] [],
.text "\n    ",
.element "child" [("link", "RLEG_LINK5")] [],
.text "\n    ",
.element "limit" [("effort", "30"), ("lower", "0"), ("upper", "2.618"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RLEG_ANKLE_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "RLEG_LINK5")] [],
.text "\n    ",
.element "child" [("link", "r_ankle")] [],
.text "\n    ",
.element "limit" [("effort", "160"), ("lower", "-1.27"), ("upper", "0.68"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_SHOULDER_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 -0.21 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "RARM_LINK1")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "-1.57079632679"), ("upper", "0.785398163397"), ("velocity", "2.7")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_SHOULDER_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "RARM_LINK1")] [],
.text "\n    ",
.element "child" [("link", "RARM_LINK2")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "0.00872664625997"), ("upper", "2.87106661953"), ("velocity", "3.66")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_SHOULDER_Y"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.263"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "RARM_LINK2")] [],
.text "\n    ",
.element "child" [("link", "RARM_LINK3")] [],
.text "\n    ",
.element "limit" [("effort", "70.0"), ("lower", "-2.42600766027"), ("upper", "2.42600766027"), ("velocity", "4.58")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_ELBOW"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "RARM_LINK3")] [],
.text "\n    ",
.element "child" [("link", "RARM_LINK4")] [],
.text "\n    ",
.element "limit" [("effort", "70.0"), ("lower", "-2.23402144255"), ("upper", "0.00349065850399"), ("velocity", "4.58")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_WRIST_Y"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.247"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "RARM_LINK4")] [],
.text "\n    ",
.element "child" [("link", "RARM_LINK5")] [],
.text "\n    ",
.element "limit" [("effort", "20.0"), ("lower", "-2.51327412287"), ("upper", "2.51327412287"), ("velocity", "1.95")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_WRIST_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "RARM_LINK5")] [],
.text "\n    ",
.element "child" [("link", "RARM_LINK6")] [],
.text "\n    ",
.element "limit" [("effort", "8.0"), ("lower", "-1.37008346282"), ("upper", "1.37008346282"), ("velocity", "1.76")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "RARM_WRIST_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "RARM_LINK6")] [],
.text "\n    ",
.element "child" [("link", "r_wrist")] [],
.text "\n    ",
.element "limit" [("effort", "8.0"), ("lower", "-0.680678408278"), ("upper", "0.680678408278"), ("velocity", "1.76")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LLEG_HIP_Y"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0.09 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "BODY")] [],
.text "\n    ",
.element "child" [("link", "LLEG_LINK1")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.349065850399"), ("upper", "1.57079632679"), ("velocity", "3.87")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LLEG_HIP_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "LLEG_LINK1")] [],
.text "\n    ",
.element "child" [("link", "LLEG_LINK2")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("lower", "-0.349065850399"), ("upper", "1.57079632679"), ("velocity", "3.87")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LLEG_HIP_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "LLEG_LINK2")] [],
.text "\n    ",
.element "child" [("link", "LLEG_LINK3")] [],
.text "\n    ",
.element "limit" [("effort", "160"), ("lower", "-0.5236"), ("upper", "0.5236"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LLEG_KNEE"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3535"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "LLEG_LINK3")] [],
.text "\n    ",
.element "child" [("link", "LLEG_LINK4")] [],
.text "\n    ",
.element "limit" [("effort", "160"), ("lower", "-2.095"), ("upper", "0.7"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LLEG_ANKLE_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.3"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "LLEG_LINK4")] [],
.text "\n    ",
.element "child" [("link", "LLEG_LINK5")] [],
.text "\n    ",
.element "limit" [("effort", "300"), ("lower", "0"), ("upper", "2.618"), ("velocity", "7")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LLEG_ANKLE_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "LLEG_LINK5")] [],
.text "\n    ",
.element "child" [("link", "l_ankle")] [],
.text "\n    ",
.element "limit" [("effort", "160"), ("lower", "-1.27"), ("upper", "0.68"), ("velocity", "5.8")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_SHOULDER_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0.21 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "LARM_LINK1")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "-1.57079632679"), ("upper", "0.785398163397"), ("velocity", "2.7")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_SHOULDER_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "LARM_LINK1")] [],
.text "\n    ",
.element "child" [("link", "LARM_LINK2")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "0.00872664625997"), ("upper", "2.87106661953"), ("velocity", "3.66")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_SHOULDER_Y"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.263"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "LARM_LINK2")] [],
.text "\n    ",
.element "child" [("link", "LARM_LINK3")] [],
.text "\n    ",
.element "limit" [("effort", "100.0"), ("lower", "-1.57079632679"), ("upper", "0.785398163397"), ("velocity", "2.7")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_ELBOW"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "LARM_LINK3")] [],
.text "\n    ",
.element "child" [("link", "LARM_LINK4")] [],
.text "\n    ",
.element "limit" [("effort", "70.0"), ("lower", "-2.42600766027"), ("upper", "2.42600766027"), ("velocity", "4.58")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_WRIST_Y"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 -0.247"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "LARM_LINK4")] [],
.text "\n    ",
.element "child" [("link", "LARM_LINK5")] [],
.text "\n    ",
.element "limit" [("effort", "70.0"), ("lower", "-2.23402144255"), ("upper", "0.00349065850399"), ("velocity", "4.58")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_WRIST_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "LARM_LINK5")] [],
.text "\n    ",
.element "child" [("link", "LARM_LINK6")] [],
.text "\n    ",
.element "limit" [("effort", "20.0"), ("lower", "-2.51327412287"), ("upper", "2.51327412287"), ("velocity", "1.95")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "LARM_WRIST_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "LARM_LINK6")] [],
.text "\n    ",
.element "child" [("link", "l_wrist")] [],
.text "\n    ",
.element "limit" [("effort", "8.0"), ("lower", "-1.37008346282"), ("upper", "1.37008346282"), ("velocity", "1.76")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "WAIST_P"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0.176"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "BODY")] [],
.text "\n    ",
.element "child" [("link", "WAIST_LINK1")] [],
.text "\n    ",
.element "limit" [("effort", "30"), ("lower", "-1.27"), ("upper", "1.27"), ("velocity", "1.76")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "WAIST_R"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "parent" [("link", "WAIST_LINK1")] [],
.text "\n    ",
.element "child" [("link", "WAIST_LINK2")] [],
.text "\n    ",
.element "limit" [("effort", "30"), ("lower", "-1.27"), ("upper", "1.27"), ("velocity", "1.76")] [],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "CHEST"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0.35"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "WAIST_LINK2")] [],
.text "\n    ",
.element "child" [("link", "torso")] [],
.text "\n    ",
.element "limit" [("effort", "30"), ("lower", "-1.27"), ("upper", "1.27"), ("velocity", "1.76")] [],
.text "\n  "],
.text "\n\n"],
[],
[],
"44b58d575fecbdfe5ee1d1dc041b0bc24e1a75dc2a14244cc4ea11f07798cf48"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
