import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "N1")] [.text "\n    ",
.element "link" [("name", "base_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.00025493 1.049E-05 -0.05502"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "3.18")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.011139"), ("ixy", "-1.3E-07"), ("ixz", "-2.455E-05"), ("iyy", "0.007619"), ("iyz", "-9.79E-06"), ("izz", "0.0089904")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/base_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.05"), ("rpy", "1.57 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.135"), ("radius", "0.065")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_thigh_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.017114 0.035514 0.00025368"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "1.31")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0020997"), ("ixy", "0.0008376"), ("ixz", "-2.51E-06"), ("iyy", "0.0024416"), ("iyz", "-3.69E-06"), ("izz", "0.0035344")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_thigh_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "left_hip_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0.050453 -0.067365"), ("rpy", "-0.2618 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "left_thigh_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-2.617"), ("upper", "2.617"), ("effort", "95"), ("velocity", "12.356")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_thigh_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0029103 -4.92E-06 -0.020023"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "1.35")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0018894"), ("ixy", "-2.66E-06"), ("ixz", "7.439E-05"), ("iyy", "0.0018265"), ("iyz", "-3.23E-06"), ("izz", "0.0013075")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_thigh_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.57 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.0415")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_hip_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0.072 0"), ("rpy", "0.2618 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_thigh_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_thigh_roll_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.261"), ("upper", "1.57"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_thigh_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0021441 -0.010608 -0.086616"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "3.37")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.01475"), ("ixy", "-8.532E-05"), ("ixz", "0.00058666"), ("iyy", "0.014824"), ("iyz", "-0.00082274"), ("izz", "0.005307")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_thigh_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.08"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.19"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_hip_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.0815"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_thigh_roll_link")] [],
.text "\n        ",
.element "child" [("link", "left_thigh_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-2.617"), ("upper", "2.617"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_shank_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0027736 0.0049964 -0.13547"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "2.21")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.013529"), ("ixy", "2.941E-05"), ("ixz", "-0.0001756"), ("iyy", "0.013565"), ("iyz", "-0.00024128"), ("izz", "0.0016244")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_shank_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.12"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.2"), ("radius", "0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_knee_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.2075"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_thigh_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "left_shank_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.0872"), ("upper", "2.356"), ("effort", "95"), ("velocity", "12.356")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_foot_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0 0.0018625 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.113")] [],
.text "\n            ",
.element "inertia" [("ixx", "2.49E-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.175E-05"), ("iyz", "0"), ("izz", "2.927E-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_foot_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "left_ankle_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.28"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_shank_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_foot_roll_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.436"), ("upper", "0.436"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_foot_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.031083 -0.00011033 -0.031859"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.528")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00025372"), ("ixy", "6.21E-06"), ("ixz", "9.43E-06"), ("iyy", "0.0016804"), ("iyz", "-6.8E-07"), ("izz", "0.0018324")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_ankle_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_foot_roll_link")] [],
.text "\n        ",
.element "child" [("link", "left_foot_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_thigh_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.017114 -0.035515 0.0002533"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "1.31")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0020997"), ("ixy", "-0.00083756"), ("ixz", "-2.59E-06"), ("iyy", "0.0024416"), ("iyz", "3.65E-06"), ("izz", "0.0035342")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_thigh_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "right_hip_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.050453 -0.067365"), ("rpy", "0.2618 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "right_thigh_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-2.617"), ("upper", "2.617"), ("effort", "95"), ("velocity", "12.356")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_thigh_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0029092 1.208E-05 -0.020023"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "1.35")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0018893"), ("ixy", "-3.06E-06"), ("ixz", "7.448E-05"), ("iyy", "0.0018266"), ("iyz", "-2.33E-06"), ("izz", "0.0013075")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_thigh_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.57 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.0415")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_hip_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.072 0"), ("rpy", "-0.2618 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_thigh_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_thigh_roll_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("lower", "-1.57"), ("upper", "0.261"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_thigh_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.002043 0.010083 -0.086622"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "3.37")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.014825"), ("ixy", "4.648E-05"), ("ixz", "0.00059303"), ("iyy", "0.014882"), ("iyz", "0.00079496"), ("izz", "0.005312")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_thigh_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.08"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.19"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_hip_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.0815"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_thigh_roll_link")] [],
.text "\n        ",
.element "child" [("link", "right_thigh_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-2.617"), ("upper", "2.617"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_shank_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0026916 -0.004784 -0.13593"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "2.21")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.013356"), ("ixy", "-2.679E-05"), ("ixz", "-0.00016834"), ("iyy", "0.013383"), ("iyz", "0.00022613"), ("izz", "0.0016428")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_shank_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.12"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.2"), ("radius", "0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_knee_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.2075"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_thigh_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "right_shank_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.0872"), ("upper", "2.356"), ("effort", "95"), ("velocity", "12.356")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_foot_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0 -0.0018793 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.113")] [],
.text "\n            ",
.element "inertia" [("ixx", "2.497E-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.175E-05"), ("iyz", "0"), ("izz", "2.933E-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_foot_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "right_ankle_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.28"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_shank_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_foot_roll_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.436"), ("upper", "0.436"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_foot_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.031082 0.0001577 -0.031593"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.528")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00025371"), ("ixy", "-6.64E-06"), ("ixz", "9.42E-06"), ("iyy", "0.0016803"), ("iyz", "-1.1E-07"), ("izz", "0.0018324")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_foot_pitch_link.STL")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_ankle_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_foot_roll_link")] [],
.text "\n        ",
.element "child" [("link", "right_foot_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.785"), ("upper", "0.785"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "imu_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0071125 0 0.00072936"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.038")] [],
.text "\n            ",
.element "inertia" [("ixx", "8.69E-06"), ("ixy", "0"), ("ixz", "5E-07"), ("iyy", "2.012E-05"), ("iyz", "0"), ("izz", "2.336E-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/imu_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "imu_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1472"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "imu_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "waist_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.00025493 1.049E-05 -0.05502"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "3.18")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.011139"), ("ixy", "-1.3E-07"), ("ixz", "-2.455E-05"), ("iyy", "0.007619"), ("iyz", "-9.79E-06"), ("izz", "0.0089904")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/waist_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.04"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.055"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "waist_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.0256"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "waist_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-2.617"), ("upper", "2.617"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "torso_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0070827 0.00038627 -0.041747"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "7.99")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.081895"), ("ixy", "4.891E-05"), ("ixz", "-0.00016303"), ("iyy", "0.070788"), ("iyz", "0.00029003"), ("izz", "0.035401")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/torso_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 -0.06"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.22"), ("radius", "0.1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.19"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.08")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "torso_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.2598"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "waist_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "torso_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "camera_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.011772 0.0016608 2.48E-06"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.0382")] [],
.text "\n            ",
.element "inertia" [("ixx", "2.466E-05"), ("ixy", "1.7E-07"), ("ixz", "1E-08"), ("iyy", "3.66E-06"), ("iyz", "1E-08"), ("izz", "2.483E-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/camera_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "camera_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.071343 -0.0048077 0.17959"), ("rpy", "0 0.5236 -0.067287")] [],
.text "\n        ",
.element "parent" [("link", "torso_link")] [],
.text "\n        ",
.element "child" [("link", "camera_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_upper_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00045952 0.060859 7.73E-05"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.885")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00083561"), ("ixy", "1.518E-05"), ("ixz", "2.12E-06"), ("iyy", "0.00051968"), ("iyz", "-9.9E-07"), ("izz", "0.00081414")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_upper_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "left_shoulder_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0.09765 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "torso_link")] [],
.text "\n        ",
.element "child" [("link", "left_upper_arm_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-2.966"), ("upper", "2.966"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_upper_arm_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0049529 0.00053148 -0.043369"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0017864"), ("ixy", "9.2E-07"), ("ixz", "-0.00015431"), ("iyy", "0.001897"), ("iyz", "-4.13E-06"), ("izz", "0.00048987")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_upper_arm_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_shoulder_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0.078 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_upper_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_upper_arm_roll_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.174"), ("upper", "2.792"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_upper_arm_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0 -0.00057869 -0.060729"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.913")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0028954"), ("ixy", "-1.94E-06"), ("ixz", "-5.05E-06"), ("iyy", "0.0029133"), ("iyz", "-3.918E-05"), ("izz", "0.00060525")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_upper_arm_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_shoulder_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1005"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_upper_arm_roll_link")] [],
.text "\n        ",
.element "child" [("link", "left_upper_arm_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-1.832"), ("upper", "1.832"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_lower_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00053164 0.0049499 -0.04337"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0018966"), ("ixy", "-9.2E-07"), ("ixz", "4.05E-06"), ("iyy", "0.0017861"), ("iyz", "-0.00015416"), ("izz", "0.00048976")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_lower_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "left_elbow_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1095"), ("rpy", "0 -1.5708 0")] [],
.text "\n        ",
.element "parent" [("link", "left_upper_arm_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "left_lower_arm_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.349"), ("upper", "1.658"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_hand_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0020835 6.386E-05 -0.013715"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.440")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00043354"), ("ixy", "9.3E-07"), ("ixz", "7.3E-07"), ("iyy", "0.0004076"), ("iyz", "-3.5E-07"), ("izz", "0.00027007")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_hand_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_wrist_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1005"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_lower_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "left_hand_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-1.832"), ("upper", "1.832"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "left_end_effector_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.003465 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.0994")] [],
.text "\n            ",
.element "inertia" [("ixx", "3.741E-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "3.741E-05"), ("iyz", "0"), ("izz", "4.538E-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/left_end_effector_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.02751")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "left_end_effector_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1045"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "left_hand_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "left_end_effector_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_upper_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00045952 -0.060859 -7.73E-05"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.885")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00083561"), ("ixy", "-1.518E-05"), ("ixz", "-2.12E-06"), ("iyy", "0.00051968"), ("iyz", "-9.9E-07"), ("izz", "0.00081414")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_upper_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "right_shoulder_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.09765 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "torso_link")] [],
.text "\n        ",
.element "child" [("link", "right_upper_arm_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-2.966"), ("upper", "2.966"), ("effort", "54"), ("velocity", "14.738")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_upper_arm_roll_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.0049504 -0.0005218 -0.043377"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0017858"), ("ixy", "-9.2E-07"), ("ixz", "-0.00015415"), ("iyy", "0.0018963"), ("iyz", "3.9E-06"), ("izz", "0.00048949")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_upper_arm_roll_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_shoulder_roll_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.078 0"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_upper_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_upper_arm_roll_link")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("lower", "-2.792"), ("upper", "0.174"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_upper_arm_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0 0.00055669 -0.060729"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.913")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0028945"), ("ixy", "-5.07E-06"), ("ixz", "3.43E-06"), ("iyy", "0.0029142"), ("iyz", "3.939E-05"), ("izz", "0.00060529")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_upper_arm_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_shoulder_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1005"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_upper_arm_roll_link")] [],
.text "\n        ",
.element "child" [("link", "right_upper_arm_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-1.832"), ("upper", "1.832"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_lower_arm_pitch_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0005218 -0.0049504 -0.043377"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.716")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0018963"), ("ixy", "9.2E-07"), ("ixz", "3.9E-06"), ("iyy", "0.0017858"), ("iyz", "0.00015415"), ("izz", "0.00048949")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_lower_arm_pitch_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n    "],
.text "\n    ",
.element "joint" [("name", "right_elbow_pitch_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1095"), ("rpy", "0 -1.5708 0")] [],
.text "\n        ",
.element "parent" [("link", "right_upper_arm_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "right_lower_arm_pitch_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n        ",
.element "limit" [("lower", "-0.349"), ("upper", "1.658"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_hand_yaw_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00020719 -1.94E-05 -0.013715"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.440")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00043227"), ("ixy", "1.81E-06"), ("ixz", "1.25E-06"), ("iyy", "0.00040887"), ("iyz", "-8.8E-07"), ("izz", "0.00027007")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_hand_yaw_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.032")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_wrist_yaw_joint"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1005"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_lower_arm_pitch_link")] [],
.text "\n        ",
.element "child" [("link", "right_hand_yaw_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "limit" [("lower", "-1.832"), ("upper", "1.832"), ("effort", "30"), ("velocity", "16.747")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "right_end_effector_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("xyz", "0.003465 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.0994")] [],
.text "\n            ",
.element "inertia" [("ixx", "3.741E-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "3.741E-05"), ("iyz", "0"), ("izz", "4.538E-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "../meshes/right_end_effector_link.STL")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "")] [.text "\n                ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.02751")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "right_end_effector_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 -0.1045"), ("rpy", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "right_hand_yaw_link")] [],
.text "\n        ",
.element "child" [("link", "right_end_effector_link")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n"],
[],
[],
"a1afda3ad63e27938fe9adc41dd3247aed17d6970b6a0b30da6d3dc564b88867"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
