import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "skydio_x2")] [.text "\n    ",
.element "mujoco" [] [.text "\n        ",
.element "compiler" [("balanceinertia", "true"), ("discardvisual", "false"), ("fusestatic", "false")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "world")] [],
.text "\n    ",
.element "joint" [("name", "floating_base_joint"), ("type", "floating")] [.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "world")] [],
.text "\n        ",
.element "child" [("link", "x2")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "x2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.1")] [],
.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("radius", ".06"), ("length", ".025")] [],
.text "\n            "],
.text "\n        "],
.text "\n\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("radius", ".06"), ("length", ".025")] [],
.text "\n            "],
.text "\n        "],
.text "\n\n    "],
.text "\n\n    ",
.element "link" [("name", "rotor1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00085"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00085"), ("iyz", "0"), ("izz", "0.00169")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("radius", ".13"), ("length", ".005")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "rotor2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00085"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00085"), ("iyz", "0"), ("izz", "0.00169")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("radius", ".13"), ("length", ".005")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "rotor3")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00085"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00085"), ("iyz", "0"), ("izz", "0.00169")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("radius", ".13"), ("length", ".005")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "rotor4")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00085"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00085"), ("iyz", "0"), ("izz", "0.00169")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("radius", ".13"), ("length", ".005")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "center_of_mass_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.02")] [],
.text "\n            ",
.element "mass" [("value", "0.325")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00013"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00169"), ("iyz", "0"), ("izz", "0.001768")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "joint" [("name", "center_of_mass_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "x2")] [],
.text "\n        ",
.element "child" [("link", "center_of_mass_link")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "prop0_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "x2")] [],
.text "\n        ",
.element "child" [("link", "rotor1")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.14 -0.18 0.05")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "prop1_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "x2")] [],
.text "\n        ",
.element "child" [("link", "rotor2")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.14 0.18 0.05")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "prop2_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "x2")] [],
.text "\n        ",
.element "child" [("link", "rotor3")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.14 0.18 0.08")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "prop3_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "x2")] [],
.text "\n        ",
.element "child" [("link", "rotor4")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.14 -0.18 0.08")] [],
.text "\n    "],
.text "\n\n"],
[],
[],
"b6100832934e0f8972d5c7a9b27adca43f5fa6f1ab0af916e567344b0b411ea9"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
