import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "b1_description")] [.text "\n  ",
.element "material" [("name", "black")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.0 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "blue")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.0 0.8 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "green")] [.text "\n    ",
.element "color" [("rgba", "0.0 0.8 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "grey")] [.text "\n    ",
.element "color" [("rgba", "0.2 0.2 0.2 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "silver")] [.text "\n    ",
.element "color" [("rgba", "0.9137254901960784 0.9137254901960784 0.8470588235294118 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "orange")] [.text "\n    ",
.element "color" [("rgba", "1.0 0.4235294117647059 0.0392156862745098 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "brown")] [.text "\n    ",
.element "color" [("rgba", "0.8705882352941177 0.8117647058823529 0.7647058823529411 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "red")] [.text "\n    ",
.element "color" [("rgba", "0.8 0.0 0.0 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "white")] [.text "\n    ",
.element "color" [("rgba", "1.0 1.0 1.0 1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_control.so"), ("name", "gazebo_ros_control")] [.text "\n      ",
.element "robotNamespace" [] [.text "/aliengo_gazebo"],
.text "\n      ",
.element "robotSimType" [] [.text "gazebo_ros_control/DefaultRobotHWSim"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libLinkPlot3DPlugin.so"), ("name", "3dplot")] [.text "\n      ",
.element "frequency" [] [.text "10"],
.text "\n      ",
.element "plot" [] [.text "\n        ",
.element "link" [] [.text "base"],
.text "\n        ",
.element "pose" [] [.text "0 0 0 0 0 0"],
.text "\n        ",
.element "material" [] [.text "Gazebo/Yellow"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  \n  ",
.element "gazebo" [] [.text "\n    ",
.element "plugin" [("filename", "libgazebo_ros_force.so"), ("name", "gazebo_ros_force")] [.text "\n      ",
.element "bodyName" [] [.text "trunk"],
.text "\n      ",
.element "topicName" [] [.text "/apply_force/trunk"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "imu_link")] [.text "\n    ",
.element "gravity" [] [.text "true"],
.text "\n    ",
.element "sensor" [("name", "imu_sensor"), ("type", "imu")] [.text "\n      ",
.element "always_on" [] [.text "true"],
.text "\n      ",
.element "update_rate" [] [.text "1000"],
.text "\n      ",
.element "visualize" [] [.text "true"],
.text "\n      ",
.element "topic" [] [.text "__default_topic__"],
.text "\n      ",
.element "plugin" [("filename", "libgazebo_ros_imu_sensor.so"), ("name", "imu_plugin")] [.text "\n        ",
.element "topicName" [] [.text "trunk_imu"],
.text "\n        ",
.element "bodyName" [] [.text "imu_link"],
.text "\n        ",
.element "updateRateHZ" [] [.text "1000.0"],
.text "\n        ",
.element "gaussianNoise" [] [.text "0.0"],
.text "\n        ",
.element "xyzOffset" [] [.text "0 0 0"],
.text "\n        ",
.element "rpyOffset" [] [.text "0 0 0"],
.text "\n        ",
.element "frameName" [] [.text "imu_link"],
.text "\n      "],
.text "\n      ",
.element "pose" [] [.text "0 0 0 0 0 0"],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FR_calf")] [.text "\n    ",
.element "sensor" [("name", "FR_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "FR_calf_fixed_joint_lump__FR_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_calf")] [.text "\n    ",
.element "sensor" [("name", "FL_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "FL_calf_fixed_joint_lump__FL_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_calf")] [.text "\n    ",
.element "sensor" [("name", "RR_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "RR_calf_fixed_joint_lump__RR_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_calf")] [.text "\n    ",
.element "sensor" [("name", "RL_foot_contact"), ("type", "contact")] [.text "\n      ",
.element "update_rate" [] [.text "100"],
.text "\n      ",
.element "plugin" [("filename", "libunitreeFootContactPlugin.so"), ("name", "contactPlugin")] [],
.text "\n      ",
.element "contact" [] [.text "\n        ",
.element "collision" [] [.text "RL_calf_fixed_joint_lump__RL_foot_collision_1"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "FR_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "FL_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "RR_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "plugin" [("filename", "libunitreeDrawForcePlugin.so"), ("name", "drawForcePlugin")] [.text "\n        ",
.element "topicName" [] [.text "RL_foot_contact"],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "base")] [.text "\n    ",
.element "material" [] [.text "Gazebo/Green"],
.text "\n    ",
.element "turnGravityOff" [] [.text "false"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "trunk")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "stick_link")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/White"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "imu_link")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/Red"],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FL_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FL_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "FR_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FR_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FR_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "FR_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "RL_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RL_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "gazebo" [("reference", "RR_hip")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_thigh")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_calf")] [.text "\n    ",
.element "mu1" [] [.text "0.2"],
.text "\n    ",
.element "mu2" [] [.text "0.2"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n  "],
.text "\n  ",
.element "gazebo" [("reference", "RR_foot")] [.text "\n    ",
.element "mu1" [] [.text "0.6"],
.text "\n    ",
.element "mu2" [] [.text "0.6"],
.text "\n    ",
.element "self_collide" [] [.text "1"],
.text "\n    ",
.element "material" [] [.text "Gazebo/DarkGrey"],
.text "\n    ",
.element "kp" [("value", "1000000.0")] [],
.text "\n    ",
.element "kd" [("value", "1.0")] [],
.text "\n  "],
.text "\n  \n  \n  \n  \n  ",
.element "link" [("name", "base")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "floating_base"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base")] [],
.text "\n    ",
.element "child" [("link", "trunk")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "trunk")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/trunkb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/trunkb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.008987 0.002243 0.003013")] [],
.text "\n      ",
.element "mass" [("value", "29.45")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.183142146"), ("ixy", "-0.001379002"), ("ixz", "-0.027956055"), ("iyy", "0.756327752"), ("iyz", "0.000193774"), ("izz", "0.783777558")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "imu_joint"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "imu_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "imu_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.000001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.001 0.001 0.001")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "red")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".001 .001 .001")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n    ",
.element "joint" [("name", "left_side_camera_joint"), ("type", "fixed")] [.text "\n\t    ",
.element "parent" [("link", "trunk")] [],
.text "\n\t    ",
.element "child" [("link", "left_side_camera_link")] [],
.text "\n\t    ",
.element "origin" [("rpy", "-0.331612 0 0"), ("xyz", "-0.1086 0.1371 -0.03077")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "left_side_camera_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n\t    \n    ",
.element "joint" [("name", "right_side_camera_joint"), ("type", "fixed")] [.text "\n\t    ",
.element "parent" [("link", "trunk")] [],
.text "\n\t    ",
.element "child" [("link", "right_side_camera_link")] [],
.text "\n\t    ",
.element "origin" [("rpy", "0.331612 0 0"), ("xyz", "-0.10190 -0.1371 -0.03077")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "right_side_camera_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n        "],
.text "\n    "],
.text "\n-\n    ",
.element "joint" [("name", "head_camera_1_joint"), ("type", "fixed")] [.text "\n\t    ",
.element "parent" [("link", "trunk")] [],
.text "\n\t    ",
.element "child" [("link", "head_camera_1_link")] [],
.text "\n\t    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.48883 0 0.0255")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "head_camera_1_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "joint" [("name", "head_camera_2_joint"), ("type", "fixed")] [.text "\n\t    ",
.element "parent" [("link", "trunk")] [],
.text "\n\t    ",
.element "child" [("link", "head_camera_2_link")] [],
.text "\n\t    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.45430 0 -0.081")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "head_camera_2_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n    ",
.element "joint" [("name", "tail_camera_joint"), ("type", "fixed")] [.text "\n\t    ",
.element "parent" [("link", "trunk")] [],
.text "\n\t    ",
.element "child" [("link", "tail_camera_link")] [],
.text "\n\t    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.459 0 -0.081")] [],
.text "\n    "],
.text "\n\n    ",
.element "link" [("name", "tail_camera_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0001"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0001"), ("iyz", "0"), ("izz", "0.0001")] [],
.text "\n        "],
.text "\n    "],
.text "\n\n  ",
.element "joint" [("name", "FR_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.3455 -0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FR_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "91.0035"), ("lower", "-0.75"), ("upper", "0.75"), ("velocity", "19.69")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1955 -0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FR_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.141592653589793 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "3.141592653589793 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.020298 -0.009758 0.000109")] [],
.text "\n      ",
.element "mass" [("value", "2.15")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00406608"), ("ixy", "0.000288071"), ("ixz", "-4.371e-06"), ("iyy", "0.008775259"), ("iyz", "-1.811e-06"), ("izz", "0.006060348")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.199")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00039249"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000219397"), ("iyz", "0.0"), ("izz", "0.000219397")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.12675 0")] [],
.text "\n    ",
.element "parent" [("link", "FR_hip")] [],
.text "\n    ",
.element "child" [("link", "FR_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "93.33"), ("lower", "-1.0"), ("upper", "3.5"), ("velocity", "23.32")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.00935 0")] [],
.text "\n    ",
.element "parent" [("link", "FR_hip")] [],
.text "\n    ",
.element "child" [("link", "FR_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thigh_mirrorb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thigh_mirrorb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.000235 0.028704 -0.054169")] [],
.text "\n      ",
.element "mass" [("value", "4.3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.044459086"), ("ixy", "-0.000128738"), ("ixz", "-0.002343913"), ("iyy", "0.046023457"), ("iyz", "-0.006032996"), ("izz", "0.008696078")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "FR_thigh")] [],
.text "\n    ",
.element "child" [("link", "FR_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "140"), ("lower", "-2.6"), ("upper", "-0.6"), ("velocity", "15.55")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0519 0")] [],
.text "\n    ",
.element "parent" [("link", "FR_thigh")] [],
.text "\n    ",
.element "child" [("link", "FR_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.005237 0.0 -0.202805")] [],
.text "\n      ",
.element "mass" [("value", "1.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.015011003"), ("ixy", "5.2e-08"), ("ixz", "0.000250042"), ("iyy", "0.015159462"), ("iyz", "4.61e-07"), ("izz", "0.000375749")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FR_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "FR_calf")] [],
.text "\n    ",
.element "child" [("link", "FR_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.03")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.2000000000000005e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "3.2000000000000005e-05"), ("iyz", "0.0"), ("izz", "3.2000000000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FR_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FR_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FR_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FR_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FR_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FR_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FR_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FR_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FR_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.3455 0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FL_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "91.0035"), ("lower", "-0.75"), ("upper", "0.75"), ("velocity", "19.69")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.1955 0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "FL_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.020298 0.009758 0.000109")] [],
.text "\n      ",
.element "mass" [("value", "2.15")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00406608"), ("ixy", "-0.000288071"), ("ixz", "-4.371e-06"), ("iyy", "0.008775259"), ("iyz", "1.811e-06"), ("izz", "0.006060348")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.199")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00039249"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000219397"), ("iyz", "0.0"), ("izz", "0.000219397")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.12675 0")] [],
.text "\n    ",
.element "parent" [("link", "FL_hip")] [],
.text "\n    ",
.element "child" [("link", "FL_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "93.33"), ("lower", "-1.0"), ("upper", "3.5"), ("velocity", "23.32")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.00935 0")] [],
.text "\n    ",
.element "parent" [("link", "FL_hip")] [],
.text "\n    ",
.element "child" [("link", "FL_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thighb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thighb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.000235 -0.028704 -0.054169")] [],
.text "\n      ",
.element "mass" [("value", "4.3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.044459086"), ("ixy", "0.000128738"), ("ixz", "-0.002343913"), ("iyy", "0.046023457"), ("iyz", "0.006032996"), ("izz", "0.008696078")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "FL_thigh")] [],
.text "\n    ",
.element "child" [("link", "FL_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "140"), ("lower", "-2.6"), ("upper", "-0.6"), ("velocity", "15.55")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.0519 0")] [],
.text "\n    ",
.element "parent" [("link", "FL_thigh")] [],
.text "\n    ",
.element "child" [("link", "FL_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.005237 0.0 -0.202805")] [],
.text "\n      ",
.element "mass" [("value", "1.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.015011003"), ("ixy", "5.2e-08"), ("ixz", "0.000250042"), ("iyy", "0.015159462"), ("iyz", "4.61e-07"), ("izz", "0.000375749")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "FL_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "FL_calf")] [],
.text "\n    ",
.element "child" [("link", "FL_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "FL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.03")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.2000000000000005e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "3.2000000000000005e-05"), ("iyz", "0.0"), ("izz", "3.2000000000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FL_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FL_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FL_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FL_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FL_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FL_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "FL_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "FL_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "FL_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.3455 -0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RR_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "91.0035"), ("lower", "-0.75"), ("upper", "0.75"), ("velocity", "19.69")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1955 -0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RR_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "3.141592653589793 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "3.141592653589793 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.020298 -0.009758 0.000109")] [],
.text "\n      ",
.element "mass" [("value", "2.15")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00406608"), ("ixy", "-0.000288071"), ("ixz", "4.371e-06"), ("iyy", "0.008775259"), ("iyz", "-1.811e-06"), ("izz", "0.006060348")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.199")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00039249"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000219397"), ("iyz", "0.0"), ("izz", "0.000219397")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.12675 0")] [],
.text "\n    ",
.element "parent" [("link", "RR_hip")] [],
.text "\n    ",
.element "child" [("link", "RR_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "93.33"), ("lower", "-1.0"), ("upper", "3.5"), ("velocity", "23.32")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.00935 0")] [],
.text "\n    ",
.element "parent" [("link", "RR_hip")] [],
.text "\n    ",
.element "child" [("link", "RR_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thigh_mirrorb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thigh_mirrorb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.000235 0.028704 -0.054169")] [],
.text "\n      ",
.element "mass" [("value", "4.3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.044459086"), ("ixy", "-0.000128738"), ("ixz", "-0.002343913"), ("iyy", "0.046023457"), ("iyz", "-0.006032996"), ("izz", "0.008696078")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "RR_thigh")] [],
.text "\n    ",
.element "child" [("link", "RR_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "140"), ("lower", "-2.6"), ("upper", "-0.6"), ("velocity", "15.55")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0519 0")] [],
.text "\n    ",
.element "parent" [("link", "RR_thigh")] [],
.text "\n    ",
.element "child" [("link", "RR_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.005237 0.0 -0.202805")] [],
.text "\n      ",
.element "mass" [("value", "1.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.015011003"), ("ixy", "5.2e-08"), ("ixz", "0.000250042"), ("iyy", "0.015159462"), ("iyz", "4.61e-07"), ("izz", "0.000375749")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RR_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "RR_calf")] [],
.text "\n    ",
.element "child" [("link", "RR_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RR_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.03")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.2000000000000005e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "3.2000000000000005e-05"), ("iyz", "0.0"), ("izz", "3.2000000000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RR_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RR_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RR_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RR_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RR_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RR_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RR_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RR_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RR_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_hip_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.3455 0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RL_hip")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "91.0035"), ("lower", "-0.75"), ("upper", "0.75"), ("velocity", "19.69")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_hip_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.1955 0.072 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "RL_hip_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_hip")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/hipb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.020298 0.009758 0.000109")] [],
.text "\n      ",
.element "mass" [("value", "2.15")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00406608"), ("ixy", "0.000288071"), ("ixz", "4.371e-06"), ("iyy", "0.008775259"), ("iyz", "1.811e-06"), ("izz", "0.006060348")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_hip_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.199")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00039249"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000219397"), ("iyz", "0.0"), ("izz", "0.000219397")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_thigh_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.12675 0")] [],
.text "\n    ",
.element "parent" [("link", "RL_hip")] [],
.text "\n    ",
.element "child" [("link", "RL_thigh")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "93.33"), ("lower", "-1.0"), ("upper", "3.5"), ("velocity", "23.32")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_thigh_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.00935 0")] [],
.text "\n    ",
.element "parent" [("link", "RL_hip")] [],
.text "\n    ",
.element "child" [("link", "RL_thigh_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_thigh")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thighb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/thighb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.000235 -0.028704 -0.054169")] [],
.text "\n      ",
.element "mass" [("value", "4.3")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.044459086"), ("ixy", "0.000128738"), ("ixz", "-0.002343913"), ("iyy", "0.046023457"), ("iyz", "0.006032996"), ("izz", "0.008696078")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_thigh_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_calf_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "RL_thigh")] [],
.text "\n    ",
.element "child" [("link", "RL_calf")] [],
.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0"), ("friction", "0")] [],
.text "\n    ",
.element "limit" [("effort", "140"), ("lower", "-2.6"), ("upper", "-0.6"), ("velocity", "15.55")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_calf_rotor_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.0519 0")] [],
.text "\n    ",
.element "parent" [("link", "RL_thigh")] [],
.text "\n    ",
.element "child" [("link", "RL_calf_rotor")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_calf")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "orange")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://b1_description/meshes/calfb.dae"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.005237 0.0 -0.202805")] [],
.text "\n      ",
.element "mass" [("value", "1.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.015011003"), ("ixy", "5.2e-08"), ("ixz", "0.000250042"), ("iyy", "0.015159462"), ("iyz", "4.61e-07"), ("izz", "0.000375749")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_calf_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.02"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n      ",
.element "mass" [("value", "0.266")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000485657"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.00091885"), ("iyz", "0.0"), ("izz", "0.000485657")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "RL_foot_fixed"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.35")] [],
.text "\n    ",
.element "parent" [("link", "RL_calf")] [],
.text "\n    ",
.element "child" [("link", "RL_foot")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "RL_foot")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.03")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "green")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "sphere" [("radius", "0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.2000000000000005e-05"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "3.2000000000000005e-05"), ("iyz", "0.0"), ("izz", "3.2000000000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RL_hip_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RL_hip_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RL_hip_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RL_thigh_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RL_thigh_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RL_thigh_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "transmission" [("name", "RL_calf_tran")] [.text "\n    ",
.element "type" [] [.text "transmission_interface/SimpleTransmission"],
.text "\n    ",
.element "joint" [("name", "RL_calf_joint")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n    "],
.text "\n    ",
.element "actuator" [("name", "RL_calf_motor")] [.text "\n      ",
.element "hardwareInterface" [] [.text "hardware_interface/EffortJointInterface"],
.text "\n      ",
.element "mechanicalReduction" [] [.text "1"],
.text "\n    "],
.text "\n  "],
.text "\n  \n"],
[],
[],
"c9dea70c85f41a09c2edfba628403b6402a10fefb97ea45a23df47b3eb07cb1f"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
