import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "anymal")] [.text "\n    \n    ",
.element "link" [("name", "base")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/base.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.58 0.14 0.18")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.2175 0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.145"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.2175 0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.145"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.2175 -0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.145"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.2175 -0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.145"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "self_filter" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "1.05 0.5 0.5")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_to_base_inertia"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "base_inertia")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "base_inertia")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.018 -0.002 0.024")] [],
.text "\n            ",
.element "mass" [("value", "6.222")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.017938806"), ("ixy", "0.00387963"), ("ixz", "0.001500772"), ("iyy", "0.370887745"), ("iyz", "6.8963e-05"), ("izz", "0.372497653")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_top_shell"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "top_shell")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "top_shell")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/top_shell.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00777 -0.00013 0.06523")] [],
.text "\n            ",
.element "mass" [("value", "0.534")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00664789486"), ("ixy", "1.247923e-05"), ("ixz", "0.00053990097"), ("iyy", "0.02587392411"), ("iyz", "3.7614e-07"), ("izz", "0.03152303792")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_bottom_shell"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "bottom_shell")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "bottom_shell")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/bottom_shell.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00333 1e-05 -0.07705")] [],
.text "\n            ",
.element "mass" [("value", "1.15")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00927353677"), ("ixy", "5.41222e-06"), ("ixz", "9.039821e-05"), ("iyy", "0.06134388239"), ("iyz", "2.3042e-07"), ("izz", "0.06853531465")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_remote"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "remote")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "remote")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/remote.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.171 0.002 0.096")] [],
.text "\n            ",
.element "mass" [("value", "0.3262")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000528486"), ("ixy", "4.547e-05"), ("ixz", "1.10327e-05"), ("iyy", "0.001165035"), ("iyz", "7.4e-07"), ("izz", "0.00124026")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_handle"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "handle")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "handle")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/handle.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.37801 0.0 0.1372")] [],
.text "\n            ",
.element "mass" [("value", "0.314")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001525739"), ("ixy", "0.0"), ("ixz", "6.272e-05"), ("iyy", "0.00071584"), ("iyz", "1e-09"), ("izz", "0.001164779")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_face_front"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "face_front")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -0.0"), ("xyz", "0.4145 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "face_front")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/face.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.055 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.11 0.14 0.18")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.055 0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.11"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.055 -0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.11"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.042 -0.001 0.004")] [],
.text "\n            ",
.element "mass" [("value", "0.73")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.005238611"), ("ixy", "1.7609e-05"), ("ixz", "7.2167e-05"), ("iyy", "0.002643098"), ("iyz", "1.9548e-05"), ("izz", "0.004325938")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "face_front_to_depth_camera_front_camera"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "face_front")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_front_camera")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.523598775598 0"), ("xyz", "0.04715 0.0 -0.0292")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_front_camera")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/depth_camera.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.021 -0.002 0.025")] [],
.text "\n            ",
.element "mass" [("value", "0.16043")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000637051"), ("ixy", "0.000484569"), ("ixz", "0.000424211"), ("iyy", "0.000929402"), ("iyz", "5.138e-06"), ("izz", "0.000484569")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "depth_camera_front_camera_to_camera_parent"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_front_camera")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_front_camera_parent")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0255 0.0175 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_front_camera_parent")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_front_camera_parent_to_depth_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_front_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_front_depth_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_front_depth_optical_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_front_camera_parent_to_color_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_front_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_front_color_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.015 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_front_color_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_front_color_frame_to_color_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_front_color_frame")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_front_color_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_front_color_optical_frame")] [],
.text "\n    \n    \n    ",
.element "joint" [("name", "face_front_to_wide_angle_camera_front_camera"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "face_front")] [],
.text "\n        ",
.element "child" [("link", "wide_angle_camera_front_camera")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.09850 0.0 0.01497")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "wide_angle_camera_front_camera")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/wide_angle_camera.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.053 -0.001 0.025")] [],
.text "\n            ",
.element "mass" [("value", "0.287")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000559232"), ("ixy", "1.6875e-05"), ("ixz", "0.000423761"), ("iyy", "0.000946504"), ("iyz", "1.3234e-07"), ("izz", "0.000493052")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "wide_angle_camera_front_camera_to_camera_parent"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "wide_angle_camera_front_camera")] [],
.text "\n        ",
.element "child" [("link", "wide_angle_camera_front_camera_parent")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "wide_angle_camera_front_camera_parent")] [],
.text "\n    \n    ",
.element "joint" [("name", "base_face_rear"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "face_rear")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 3.14159265359"), ("xyz", "-0.4145 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "face_rear")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/face.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.055 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.11 0.14 0.18")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.055 0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.11"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.055 -0.07 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.11"), ("radius", "0.09")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.042 -0.001 0.004")] [],
.text "\n            ",
.element "mass" [("value", "0.73")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.005238611"), ("ixy", "1.7609e-05"), ("ixz", "7.2167e-05"), ("iyy", "0.002643098"), ("iyz", "1.9548e-05"), ("izz", "0.004325938")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "face_rear_to_depth_camera_rear_camera"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "face_rear")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_rear_camera")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.523598775598 0"), ("xyz", "0.04715 0.0 -0.0292")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_rear_camera")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/depth_camera.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.021 -0.002 0.025")] [],
.text "\n            ",
.element "mass" [("value", "0.16043")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000637051"), ("ixy", "0.000484569"), ("ixz", "0.000424211"), ("iyy", "0.000929402"), ("iyz", "5.138e-06"), ("izz", "0.000484569")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "depth_camera_rear_camera_to_camera_parent"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_rear_camera")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_rear_camera_parent")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0255 0.0175 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_rear_camera_parent")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_rear_camera_parent_to_depth_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_rear_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_rear_depth_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_rear_depth_optical_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_rear_camera_parent_to_color_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_rear_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_rear_color_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.015 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_rear_color_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_rear_color_frame_to_color_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_rear_color_frame")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_rear_color_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_rear_color_optical_frame")] [],
.text "\n    \n    \n    ",
.element "joint" [("name", "face_rear_to_wide_angle_camera_rear_camera"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "face_rear")] [],
.text "\n        ",
.element "child" [("link", "wide_angle_camera_rear_camera")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.09850 0.0 0.01497")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "wide_angle_camera_rear_camera")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/wide_angle_camera.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.053 -0.001 0.025")] [],
.text "\n            ",
.element "mass" [("value", "0.287")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000559232"), ("ixy", "1.6875e-05"), ("ixz", "0.000423761"), ("iyy", "0.000946504"), ("iyz", "1.3234e-07"), ("izz", "0.000493052")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "wide_angle_camera_rear_camera_to_camera_parent"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "wide_angle_camera_rear_camera")] [],
.text "\n        ",
.element "child" [("link", "wide_angle_camera_rear_camera_parent")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "wide_angle_camera_rear_camera_parent")] [],
.text "\n    \n    ",
.element "joint" [("name", "base_battery"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "battery")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "battery")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/battery.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00067 -0.00023 -0.03362")] [],
.text "\n            ",
.element "mass" [("value", "5.53425")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00749474794"), ("ixy", "0.00016686282"), ("ixz", "7.82763e-05"), ("iyy", "0.0722338913"), ("iyz", "1.42902e-06"), ("izz", "0.07482717535")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_to_docking_hatch_cover"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "docking_hatch_cover")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.343 0.0 -0.07")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "docking_hatch_cover")] [.text "\n        \n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003 0.0 0.005")] [],
.text "\n            ",
.element "mass" [("value", "0.065")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00063283"), ("ixy", "0.0"), ("ixz", "3.45e-07"), ("iyy", "0.00110971"), ("iyz", "0.0"), ("izz", "0.00171883")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "imu_link")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.005")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.024 0.024 0.01")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "orange")] [],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.005")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.024 0.024 0.01")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.01")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "5.63333333333e-07"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "9.6e-07"), ("iyz", "0.0"), ("izz", "5.63333333333e-07")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "imu_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "imu_link")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.0 1.57079632679"), ("xyz", "0.2488 0.00835 0.04628")] [],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "base_to_depth_camera_left_camera"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_left_camera")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.523598775598 1.57079632679"), ("xyz", "0.0 0.07646 0.02905")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_left_camera")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/depth_camera.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.021 -0.002 0.025")] [],
.text "\n            ",
.element "mass" [("value", "0.16043")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000637051"), ("ixy", "0.000484569"), ("ixz", "0.000424211"), ("iyy", "0.000929402"), ("iyz", "5.138e-06"), ("izz", "0.000484569")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "depth_camera_left_camera_to_camera_parent"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_left_camera")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_left_camera_parent")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0255 0.0175 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_left_camera_parent")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_left_camera_parent_to_depth_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_left_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_left_depth_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_left_depth_optical_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_left_camera_parent_to_color_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_left_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_left_color_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.015 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_left_color_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_left_color_frame_to_color_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_left_color_frame")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_left_color_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_left_color_optical_frame")] [],
.text "\n    \n    \n    ",
.element "joint" [("name", "base_to_depth_camera_right_camera"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_right_camera")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.523598775598 -1.57079632679"), ("xyz", "0.0 -0.07646 0.02905")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_right_camera")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/depth_camera.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.021 -0.002 0.025")] [],
.text "\n            ",
.element "mass" [("value", "0.16043")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000637051"), ("ixy", "0.000484569"), ("ixz", "0.000424211"), ("iyy", "0.000929402"), ("iyz", "5.138e-06"), ("izz", "0.000484569")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "depth_camera_right_camera_to_camera_parent"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_right_camera")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_right_camera_parent")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0255 0.0175 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_right_camera_parent")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_right_camera_parent_to_depth_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_right_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_right_depth_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_right_depth_optical_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_right_camera_parent_to_color_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_right_camera_parent")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_right_color_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.015 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_right_color_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "depth_camera_right_color_frame_to_color_optical_frame"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "depth_camera_right_color_frame")] [],
.text "\n        ",
.element "child" [("link", "depth_camera_right_color_optical_frame")] [],
.text "\n        ",
.element "origin" [("rpy", "-1.57079632679 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "depth_camera_right_color_optical_frame")] [],
.text "\n    \n    ",
.element "joint" [("name", "base_to_lidar_cage"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "lidar_cage")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.364 0.0 0.0735")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "lidar_cage")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/lidar_cage.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.06")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.07")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.002 0.0 0.099")] [],
.text "\n            ",
.element "mass" [("value", "0.545")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.003156254"), ("ixy", "0.0"), ("ixz", "1.0992e-05"), ("iyy", "0.002357216"), ("iyz", "0.0"), ("izz", "0.001326455")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "lidar_cage_to_lidar"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "lidar_cage")] [],
.text "\n        ",
.element "child" [("link", "lidar")] [],
.text "\n        ",
.element "origin" [("rpy", "0.0 0.0 -1.57079632679"), ("xyz", "0.0 0.0 0.0687")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "lidar")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "-0.012 0.001 -0.008")] [],
.text "\n            ",
.element "mass" [("value", "0.695")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000846765"), ("ixy", "6.9565e-05"), ("ixz", "0.00027111"), ("iyy", "0.001367583"), ("iyz", "5.8984e-05"), ("izz", "0.001363673")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/lidar.dae")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_LF_HAA"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "LF_HAA")] [],
.text "\n        ",
.element "origin" [("rpy", "2.61799387799 0 0.0"), ("xyz", "0.2999 0.104 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_HAA")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_HAA"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "LF_HAA")] [],
.text "\n        ",
.element "child" [("link", "LF_HIP")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-0.72"), ("upper", "0.49"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_HIP")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_HIP_LF_hip_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_HIP")] [],
.text "\n        ",
.element "child" [("link", "LF_hip_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "-2.61799387799 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_hip_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/hip_l.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.048 0.008 -0.003")] [],
.text "\n            ",
.element "mass" [("value", "0.74")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001393106"), ("ixy", "8.4012e-05"), ("ixz", "2.3378e-05"), ("iyy", "0.003798579"), ("iyz", "7.1319e-05"), ("izz", "0.003897509")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_hip_fixed_LF_HFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_hip_fixed")] [],
.text "\n        ",
.element "child" [("link", "LF_HFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "0.0599 0.08381 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_HFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_HFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "LF_HFE")] [],
.text "\n        ",
.element "child" [("link", "LF_THIGH")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_THIGH")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_THIGH_LF_thigh_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_THIGH")] [],
.text "\n        ",
.element "child" [("link", "LF_thigh_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_thigh_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/thigh.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 0.04 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.08"), ("radius", "0.065")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.03 -0.1413135")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.075 0.06 0.282627")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.018 -0.169")] [],
.text "\n            ",
.element "mass" [("value", "1.03")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.018644469"), ("ixy", "5.2e-08"), ("ixz", "1.0157e-05"), ("iyy", "0.019312599"), ("iyz", "0.002520077"), ("izz", "0.002838361")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_thigh_fixed_LF_KFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_thigh_fixed")] [],
.text "\n        ",
.element "child" [("link", "LF_KFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "0.0 0.1003 -0.285")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_KFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_KFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "LF_KFE")] [],
.text "\n        ",
.element "child" [("link", "LF_SHANK")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_SHANK")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LF_shank_LF_shank_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_SHANK")] [],
.text "\n        ",
.element "child" [("link", "LF_shank_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_shank_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/shank_l.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.04"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.057499 0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.114998 0.0675 0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03463 0.00688 0.00098")] [],
.text "\n            ",
.element "mass" [("value", "0.33742")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00032748005"), ("ixy", "2.142561e-05"), ("ixz", "1.33942e-05"), ("iyy", "0.00110974122"), ("iyz", "7.601e-08"), ("izz", "0.00089388521")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "LF_shank_fixed_LF_FOOT"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LF_shank_fixed")] [],
.text "\n        ",
.element "child" [("link", "LF_FOOT")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.08795 0.01305 -0.33797")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LF_FOOT")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -0.785398163397"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/foot.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.168985")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.282504"), ("radius", "0.0175")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.0225")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00948 -0.00948 0.1468")] [],
.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00317174097"), ("ixy", "2.63048e-06"), ("ixz", "6.815581e-05"), ("iyy", "0.00317174092"), ("iyz", "6.815583e-05"), ("izz", "8.319196e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_RF_HAA"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "RF_HAA")] [],
.text "\n        ",
.element "origin" [("rpy", "-2.61799387799 0 0.0"), ("xyz", "0.2999 -0.104 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_HAA")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_HAA"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "RF_HAA")] [],
.text "\n        ",
.element "child" [("link", "RF_HIP")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-0.49"), ("upper", "0.72"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_HIP")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_HIP_RF_hip_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_HIP")] [],
.text "\n        ",
.element "child" [("link", "RF_hip_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "2.61799387799 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_hip_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/hip_r.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.048 -0.008 -0.003")] [],
.text "\n            ",
.element "mass" [("value", "0.74")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001393106"), ("ixy", "-8.4012e-05"), ("ixz", "2.3378e-05"), ("iyy", "0.003798579"), ("iyz", "-7.1319e-05"), ("izz", "0.003897509")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_hip_fixed_RF_HFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_hip_fixed")] [],
.text "\n        ",
.element "child" [("link", "RF_HFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "0.0599 -0.08381 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_HFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_HFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "RF_HFE")] [],
.text "\n        ",
.element "child" [("link", "RF_THIGH")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_THIGH")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_THIGH_RF_thigh_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_THIGH")] [],
.text "\n        ",
.element "child" [("link", "RF_thigh_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_thigh_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/thigh.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 -0.04 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.08"), ("radius", "0.065")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.03 -0.1413135")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.075 0.06 0.282627")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 -0.018 -0.169")] [],
.text "\n            ",
.element "mass" [("value", "1.03")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.018644469"), ("ixy", "-5.2e-08"), ("ixz", "1.0157e-05"), ("iyy", "0.019312599"), ("iyz", "-0.002520077"), ("izz", "0.002838361")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_thigh_fixed_RF_KFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_thigh_fixed")] [],
.text "\n        ",
.element "child" [("link", "RF_KFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "0.0 -0.1003 -0.285")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_KFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_KFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "RF_KFE")] [],
.text "\n        ",
.element "child" [("link", "RF_SHANK")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_SHANK")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RF_shank_RF_shank_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_SHANK")] [],
.text "\n        ",
.element "child" [("link", "RF_shank_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_shank_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/shank_r.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 -0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.04"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.057499 -0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.114998 0.0675 0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.03463 -0.00688 0.00098")] [],
.text "\n            ",
.element "mass" [("value", "0.33742")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00032748005"), ("ixy", "-2.142561e-05"), ("ixz", "1.33942e-05"), ("iyy", "0.00110974122"), ("iyz", "-7.601e-08"), ("izz", "0.00089388521")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "RF_shank_fixed_RF_FOOT"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RF_shank_fixed")] [],
.text "\n        ",
.element "child" [("link", "RF_FOOT")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.08795 -0.01305 -0.33797")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RF_FOOT")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.785398163397"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/foot.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.168985")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.282504"), ("radius", "0.0175")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.0225")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.00948 0.00948 0.1468")] [],
.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00317174097"), ("ixy", "-2.63048e-06"), ("ixz", "6.815581e-05"), ("iyy", "0.00317174092"), ("iyz", "-6.815583e-05"), ("izz", "8.319196e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_LH_HAA"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "LH_HAA")] [],
.text "\n        ",
.element "origin" [("rpy", "-2.61799387799 0 -3.14159265359"), ("xyz", "-0.2999 0.104 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_HAA")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_HAA"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "LH_HAA")] [],
.text "\n        ",
.element "child" [("link", "LH_HIP")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-0.72"), ("upper", "0.49"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_HIP")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_HIP_LH_hip_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_HIP")] [],
.text "\n        ",
.element "child" [("link", "LH_hip_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "-2.61799387799 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_hip_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/hip_r.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.048 0.008 -0.003")] [],
.text "\n            ",
.element "mass" [("value", "0.74")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001393106"), ("ixy", "-8.4012e-05"), ("ixz", "-2.3378e-05"), ("iyy", "0.003798579"), ("iyz", "7.1319e-05"), ("izz", "0.003897509")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_hip_fixed_LH_HFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_hip_fixed")] [],
.text "\n        ",
.element "child" [("link", "LH_HFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "-0.0599 0.08381 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_HFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_HFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "LH_HFE")] [],
.text "\n        ",
.element "child" [("link", "LH_THIGH")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_THIGH")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_THIGH_LH_thigh_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_THIGH")] [],
.text "\n        ",
.element "child" [("link", "LH_thigh_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_thigh_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/thigh.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 0.04 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.08"), ("radius", "0.065")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.03 -0.1413135")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.075 0.06 0.282627")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0 0.018 -0.169")] [],
.text "\n            ",
.element "mass" [("value", "1.03")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.018644469"), ("ixy", "-5.2e-08"), ("ixz", "-1.0157e-05"), ("iyy", "0.019312599"), ("iyz", "0.002520077"), ("izz", "0.002838361")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_thigh_fixed_LH_KFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_thigh_fixed")] [],
.text "\n        ",
.element "child" [("link", "LH_KFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "-0.0 0.1003 -0.285")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_KFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_KFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "LH_KFE")] [],
.text "\n        ",
.element "child" [("link", "LH_SHANK")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_SHANK")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "LH_shank_LH_shank_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_SHANK")] [],
.text "\n        ",
.element "child" [("link", "LH_shank_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_shank_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/shank_r.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.04"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "-0.057499 0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.114998 0.0675 0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.03463 0.00688 0.00098")] [],
.text "\n            ",
.element "mass" [("value", "0.33742")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00032748005"), ("ixy", "-2.142561e-05"), ("ixz", "-1.33942e-05"), ("iyy", "0.00110974122"), ("iyz", "7.601e-08"), ("izz", "0.00089388521")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "LH_shank_fixed_LH_FOOT"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "LH_shank_fixed")] [],
.text "\n        ",
.element "child" [("link", "LH_FOOT")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.08795 0.01305 -0.33797")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "LH_FOOT")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -2.35619449019"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/foot.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.168985")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.282504"), ("radius", "0.0175")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.0225")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00948 -0.00948 0.1468")] [],
.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00317174097"), ("ixy", "-2.63048e-06"), ("ixz", "-6.815581e-05"), ("iyy", "0.00317174092"), ("iyz", "6.815583e-05"), ("izz", "8.319196e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_RH_HAA"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "RH_HAA")] [],
.text "\n        ",
.element "origin" [("rpy", "2.61799387799 0 -3.14159265359"), ("xyz", "-0.2999 -0.104 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_HAA")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_HAA"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "RH_HAA")] [],
.text "\n        ",
.element "child" [("link", "RH_HIP")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-0.49"), ("upper", "0.72"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_HIP")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_HIP_RH_hip_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_HIP")] [],
.text "\n        ",
.element "child" [("link", "RH_hip_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "2.61799387799 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_hip_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/hip_l.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.048 -0.008 -0.003")] [],
.text "\n            ",
.element "mass" [("value", "0.74")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001393106"), ("ixy", "8.4012e-05"), ("ixz", "-2.3378e-05"), ("iyy", "0.003798579"), ("iyz", "-7.1319e-05"), ("izz", "0.003897509")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_hip_fixed_RH_HFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_hip_fixed")] [],
.text "\n        ",
.element "child" [("link", "RH_HFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "-0.0599 -0.08381 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_HFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_HFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "RH_HFE")] [],
.text "\n        ",
.element "child" [("link", "RH_THIGH")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_THIGH")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_THIGH_RH_thigh_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_THIGH")] [],
.text "\n        ",
.element "child" [("link", "RH_thigh_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_thigh_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/thigh.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 -0.04 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.08"), ("radius", "0.065")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.03 -0.1413135")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.075 0.06 0.282627")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.0 -0.018 -0.169")] [],
.text "\n            ",
.element "mass" [("value", "1.03")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.018644469"), ("ixy", "5.2e-08"), ("ixz", "-1.0157e-05"), ("iyy", "0.019312599"), ("iyz", "-0.002520077"), ("izz", "0.002838361")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_thigh_fixed_RH_KFE"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_thigh_fixed")] [],
.text "\n        ",
.element "child" [("link", "RH_KFE")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 -1.57079632679"), ("xyz", "-0.0 -0.1003 -0.285")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_KFE")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/drive.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.07 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.14"), ("radius", "0.05")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.063 7e-05 0.00046")] [],
.text "\n            ",
.element "mass" [("value", "2.04")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001053013"), ("ixy", "4.527e-05"), ("ixz", "8.855e-05"), ("iyy", "0.001805509"), ("iyz", "9.909e-05"), ("izz", "0.001765827")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_KFE"), ("type", "revolute")] [.text "\n        ",
.element "parent" [("link", "RH_KFE")] [],
.text "\n        ",
.element "child" [("link", "RH_SHANK")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 0")] [],
.text "\n        ",
.element "limit" [("effort", "80.0"), ("lower", "-9.42477796077"), ("upper", "9.42477796077"), ("velocity", "7.5")] [],
.text "\n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_SHANK")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "mass" [("value", "0.001")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000001"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "0.000001"), ("iyz", "0.0"), ("izz", "0.000001")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "RH_shank_RH_shank_fixed"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_SHANK")] [],
.text "\n        ",
.element "child" [("link", "RH_shank_fixed")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 1.57079632679"), ("xyz", "0 0 0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_shank_fixed")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/shank_l.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0 -0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.04"), ("radius", "0.06")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "-0.057499 -0.02 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "box" [("size", "0.114998 0.0675 0.04")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.03463 -0.00688 0.00098")] [],
.text "\n            ",
.element "mass" [("value", "0.33742")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00032748005"), ("ixy", "2.142561e-05"), ("ixz", "-1.33942e-05"), ("iyy", "0.00110974122"), ("iyz", "-7.601e-08"), ("izz", "0.00089388521")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    \n    ",
.element "joint" [("name", "RH_shank_fixed_RH_FOOT"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "RH_shank_fixed")] [],
.text "\n        ",
.element "child" [("link", "RH_FOOT")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.08795 -0.01305 -0.33797")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "RH_FOOT")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 -3.92699081699"), ("xyz", "0 0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/foot.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.168985")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "cylinder" [("length", "0.282504"), ("radius", "0.0175")] [],
.text "\n            "],
.text "\n        "],
.text "\n        \n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0.0225")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "sphere" [("radius", "0.03")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.00948 0.00948 0.1468")] [],
.text "\n            ",
.element "mass" [("value", "0.25")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00317174097"), ("ixy", "2.63048e-06"), ("ixz", "-6.815581e-05"), ("iyy", "0.00317174092"), ("iyz", "-6.815583e-05"), ("izz", "8.319196e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    \n    ",
.element "joint" [("name", "base_hatch"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "base")] [],
.text "\n        ",
.element "child" [("link", "hatch")] [],
.text "\n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.0 0.0")] [],
.text "\n    "],
.text "\n    \n    ",
.element "link" [("name", "hatch")] [.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.116 0 0.073")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://anymal_c_simple_description/meshes/hatch.dae"), ("scale", "1.0 1.0 1.0")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.116 0.0 0.0758")] [],
.text "\n            ",
.element "mass" [("value", "0.142")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.001"), ("ixy", "0.001"), ("ixz", "0.001"), ("iyy", "0.001"), ("iyz", "0.001"), ("izz", "0.001")] [],
.text "\n        "],
.text "\n    "],
.text "\n"],
[],
[],
"3902c3957ac82176e15e87e20086a86d0dff4f23b8cb55bcbd4d3158cd36947b"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
