import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "urdf")] [.text "\n  \n  ",
.element "link" [("name", "trunk")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00454781 -0.000104579 0.053896"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.347283")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.000608722"), ("ixy", "-5.1387e-07"), ("ixz", "-1.16287e-05"), ("iyy", "0.000477224"), ("iyz", "1.9299e-06"), ("izz", "0.000357224")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "body")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "body_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "body")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "imu")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "imu_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0.01483 -0.002 0.0675"), ("rpy", "1.5708 -0 -1.5708")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "imu")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "head")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "5.1303e-08 -0.0074561 0.0161837"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0166215")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.92963e-06"), ("ixy", "-1.6e-11"), ("ixz", "4e-12"), ("iyy", "3.58354e-06"), ("iyz", "2.61187e-07"), ("izz", "4.24694e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "joint" [("name", "head"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.00204165 -0 0.126"), ("rpy", "0 0 1.5708")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "head")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-1.5708"), ("upper", "1.5708")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "shoulder")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "4.19e-10 2.814e-09 -0.00850029"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.00898451")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.06003e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.78233e-06"), ("iyz", "-0"), ("izz", "1.86739e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "humerus__configuration_right")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.000309872 -0.0252784 -0.0143918"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0416867")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.76899e-05"), ("ixy", "-3.03216e-07"), ("ixz", "-2.278e-09"), ("iyy", "3.95132e-06"), ("iyz", "-7.8184e-08"), ("izz", "1.75854e-05")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "radius")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-4.0628e-08 -0.0310611 0.0130165"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0115415")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.26775e-06"), ("ixy", "-4e-12"), ("ixz", "-1.2e-11"), ("iyy", "1.21602e-06"), ("iyz", "1.7157e-07"), ("izz", "4.45903e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_elbow"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0145 -0.0515 -0.0145"), ("rpy", "-0 1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "humerus__configuration_right")] [],
.text "\n    ",
.element "child" [("link", "radius")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-2.18166"), ("upper", "2.18166")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_shoulder_roll"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.0145 0 -0.0195"), ("rpy", "-3.14159 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "shoulder")] [],
.text "\n    ",
.element "child" [("link", "humerus__configuration_right")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-3.14159"), ("upper", "0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_shoulder_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 -0.0505 0.081"), ("rpy", "-1.5708 0 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "shoulder")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-3.14159"), ("upper", "3.14159")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "hip")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00421822 1.46909e-07 -0.00948697"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.00884451")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.36719e-07"), ("ixy", "-3.3e-11"), ("ixz", "1.95496e-07"), ("iyy", "4.32505e-06"), ("iyz", "0"), ("izz", "4.03697e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "hip_block__configuration_right")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-5.75932e-05 0.00982795 0.0271518"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.04763")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.64064e-05"), ("ixy", "-9.153e-09"), ("ixz", "7.8745e-08"), ("iyy", "1.33088e-05"), ("iyz", "6.63067e-07"), ("izz", "7.85889e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "femur__configuration_right")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.0109472 -0.0366847 -0.0147025"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.014726")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.12665e-05"), ("ixy", "-1.12592e-06"), ("ixz", "1.333e-09"), ("iyy", "4.38335e-06"), ("iyz", "-4.521e-09"), ("izz", "8.95932e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "tibia__configuration_right")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.00276278 -0.0196679 -0.0144621"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0300463")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.53882e-05"), ("ixy", "2.25674e-06"), ("ixz", "7.6682e-08"), ("iyy", "5.3311e-06"), ("iyz", "-1.37001e-07"), ("izz", "1.38581e-05")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "ankle_block__configuration_left")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.0110676 -0.00979852 -0.0144015"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.04722")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.83993e-06"), ("ixy", "-6.00742e-07"), ("ixz", "-4.9782e-08"), ("iyy", "1.29837e-05"), ("iyz", "-6.127e-09"), ("izz", "1.60971e-05")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "foot")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0 -0.0168869 0.0347422"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.016823")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.15605e-05"), ("ixy", "0"), ("ixz", "-0"), ("iyy", "1.2167e-05"), ("iyz", "5.67932e-07"), ("izz", "2.53496e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "right_foot")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_foot_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "-0 -0.023 0.042"), ("rpy", "-1.5708 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "foot")] [],
.text "\n    ",
.element "child" [("link", "right_foot")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_ankle_roll"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0385 0 -0.0145"), ("rpy", "3.14159 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "ankle_block__configuration_left")] [],
.text "\n    ",
.element "child" [("link", "foot")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-0.610865"), ("upper", "0.610865")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_ankle_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.008 -0.0612131 -0"), ("rpy", "-0 0 3.14159")] [],
.text "\n    ",
.element "parent" [("link", "tibia__configuration_right")] [],
.text "\n    ",
.element "child" [("link", "ankle_block__configuration_left")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-1.5708"), ("upper", "0.610865")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_knee"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.005 -0.062 -0"), ("rpy", "-0 0 -0")] [],
.text "\n    ",
.element "parent" [("link", "femur__configuration_right")] [],
.text "\n    ",
.element "child" [("link", "tibia__configuration_right")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-0.785398"), ("upper", "2.35619")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_hip_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0145 -0 0.0385"), ("rpy", "3.14159 1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "hip_block__configuration_right")] [],
.text "\n    ",
.element "child" [("link", "femur__configuration_right")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-1.5708"), ("upper", "1.5708")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_hip_roll"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.02 0 -0.0214"), ("rpy", "-1.5708 -0 -1.5708")] [],
.text "\n    ",
.element "parent" [("link", "hip")] [],
.text "\n    ",
.element "child" [("link", "hip_block__configuration_right")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-0.610865"), ("upper", "0.610865")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_hip_yaw"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0 -0.036 0"), ("rpy", "-0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "hip")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-4.18879"), ("upper", "1.0472")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "shoulder_2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-4.19e-10 2.814e-09 0.00850029"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.00898451")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.06003e-06"), ("ixy", "-0"), ("ixz", "0"), ("iyy", "1.78233e-06"), ("iyz", "0"), ("izz", "1.86739e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "humerus__configuration_left")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.000313281 0.0252784 -0.0143884"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0416867")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.76899e-05"), ("ixy", "3.01684e-07"), ("ixz", "-5.77e-10"), ("iyy", "3.9512e-06"), ("iyz", "7.6531e-08"), ("izz", "1.75853e-05")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "radius_2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-4.0628e-08 0.0310611 -0.0130165"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0115415")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.26775e-06"), ("ixy", "4e-12"), ("ixz", "1.2e-11"), ("iyy", "1.21602e-06"), ("iyz", "1.7157e-07"), ("izz", "4.45903e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_elbow"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0145 0.0515 -0.0145"), ("rpy", "0 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "humerus__configuration_left")] [],
.text "\n    ",
.element "child" [("link", "radius_2")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-2.18166"), ("upper", "2.18166")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_shoulder_roll"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0145 0 0.0195"), ("rpy", "-3.14159 1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "shoulder_2")] [],
.text "\n    ",
.element "child" [("link", "humerus__configuration_left")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "0"), ("upper", "3.14159")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_shoulder_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0 0.0505 0.081"), ("rpy", "1.5708 -0 -3.14159")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "shoulder_2")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-3.14159"), ("upper", "3.14159")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "hip_2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00421822 -1.46909e-07 -0.00948697"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.00884451")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.36719e-07"), ("ixy", "-3.3e-11"), ("ixz", "-1.95496e-07"), ("iyy", "4.32505e-06"), ("iyz", "-0"), ("izz", "4.03697e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "hip_block__configuration_left")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "6.0554e-05 0.00982795 0.0271548"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.04763")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.64096e-05"), ("ixy", "8.495e-09"), ("ixz", "-7.6959e-08"), ("iyy", "1.3312e-05"), ("iyz", "6.62404e-07"), ("izz", "7.85888e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "femur__configuration_left")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0109472 0.0366847 -0.0142975"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.014726")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.12665e-05"), ("ixy", "-1.12592e-06"), ("ixz", "1.333e-09"), ("iyy", "4.38335e-06"), ("iyz", "-4.521e-09"), ("izz", "8.95932e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "tibia__configuration_left")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.00275805 0.0196679 -0.0145379"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0300463")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.53882e-05"), ("ixy", "2.25747e-06"), ("ixz", "7.7561e-08"), ("iyy", "5.33188e-06"), ("iyz", "-1.37001e-07"), ("izz", "1.38589e-05")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "ankle_block__configuration_right")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0110706 0.00979852 -0.0145955"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.04722")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.83996e-06"), ("ixy", "-6.01409e-07"), ("ixz", "-5.1613e-08"), ("iyy", "1.29805e-05"), ("iyz", "-6.789e-09"), ("izz", "1.6094e-05")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "foot_2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0 -0.0168869 0.0347422"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.016823")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.15605e-05"), ("ixy", "0"), ("ixz", "-0"), ("iyy", "1.2167e-05"), ("iyz", "5.67932e-07"), ("izz", "2.53496e-06")] [],
.text "\n    "],
.text "\n    \n    \n    \n    \n    \n    \n    \n    \n    \n  "],
.text "\n  \n  ",
.element "link" [("name", "left_foot")] [.text "\n    ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1e-9")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_foot_frame"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "-0 -0.023 0.042"), ("rpy", "-1.5708 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "foot_2")] [],
.text "\n    ",
.element "child" [("link", "left_foot")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_ankle_roll"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.0385 0 -0.0145"), ("rpy", "-0 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "ankle_block__configuration_right")] [],
.text "\n    ",
.element "child" [("link", "foot_2")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-0.610865"), ("upper", "0.610865")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_ankle_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.008 0.0612131 -0"), ("rpy", "-0 -0 3.14159")] [],
.text "\n    ",
.element "parent" [("link", "tibia__configuration_left")] [],
.text "\n    ",
.element "child" [("link", "ankle_block__configuration_right")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-1.5708"), ("upper", "0.610865")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_knee"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.005 0.062 0"), ("rpy", "-0 -0 -0")] [],
.text "\n    ",
.element "parent" [("link", "femur__configuration_left")] [],
.text "\n    ",
.element "child" [("link", "tibia__configuration_left")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-0.785398"), ("upper", "2.35619")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_hip_pitch"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0145 -0 0.0385"), ("rpy", "0 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "hip_block__configuration_left")] [],
.text "\n    ",
.element "child" [("link", "femur__configuration_left")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-1.5708"), ("upper", "1.5708")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_hip_roll"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.02 0 -0.0214"), ("rpy", "-1.5708 -0 1.5708")] [],
.text "\n    ",
.element "parent" [("link", "hip_2")] [],
.text "\n    ",
.element "child" [("link", "hip_block__configuration_left")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-0.610865"), ("upper", "0.610865")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_hip_yaw"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0 0.036 0"), ("rpy", "0 -0 -3.14159")] [],
.text "\n    ",
.element "parent" [("link", "trunk")] [],
.text "\n    ",
.element "child" [("link", "hip_2")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("effort", "10"), ("velocity", "10"), ("lower", "-1.0472"), ("upper", "4.18879")] [],
.text "\n  "],
.text "\n"],
[],
[],
"b5d2863ab255b1dbf6908beead7f0177b1935e849294181b5d25a4c606ee9dab"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
