import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "iCub")] [.text "\n    ",
.element "link" [("name", "base_link")] [],
.text "\n    ",
.element "link" [("name", "chest")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "4.81")] [],
.text "\n            ",
.element "origin" [("xyz", "0.00222898 0.075 -1.18362e-17"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.07472"), ("ixy", "-3.6e-06"), ("ixz", "-4.705e-05"), ("iyy", "0.08145"), ("iyz", "0.004567"), ("izz", "0.01306")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0055 -6.93889e-18 -1.72085e-18"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_chest.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0055 -6.93889e-18 -1.72085e-18"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_chest.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "chest_skin_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "codyco_balancing_world")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "head")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "1.33687")] [],
.text "\n            ",
.element "origin" [("xyz", "0.0185 -0.1108 6.78454e-18"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "2.40741e-35"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0045 -0.0235 9.42554e-13"), ("rpy", "0 1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_head.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.0045 -0.0235 9.42554e-13"), ("rpy", "0 1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_head.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "imu_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_ankle_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.643")] [],
.text "\n            ",
.element "origin" [("xyz", "2.65892e-05 -0.00082253 0.0102574"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "4.76593"), ("ixy", "9.7426e-06"), ("ixz", "2.68085e-05"), ("iyy", "0.0040935"), ("iyz", "-0.000353796"), ("izz", "0.0036688")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.001555 -5.54343e-12 0.0009175"), ("rpy", "1.5708 1.53106e-11 1.53105e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_ankle_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.001555 -5.54343e-12 0.0009175"), ("rpy", "1.5708 1.53106e-11 1.53105e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_ankle_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_ankle_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.2675")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.0035 0 0.0645"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_elbow_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.074")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.0013 0.00371 -0.00105"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "2.8389e-05"), ("ixy", "-5.15e-07"), ("ixz", "-4.08e-07"), ("iyy", "9.244e-06"), ("iyz", "-3.71e-07"), ("izz", "2.9968e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_foot")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.5935")] [],
.text "\n            ",
.element "origin" [("xyz", "0.024069 -0.000613931 -0.0284154"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00167275"), ("ixy", "-4.51893e-06"), ("ixz", "0.000567785"), ("iyy", "0.00320869"), ("iyz", "-6.62361e-07"), ("izz", "0.00208378")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0044175 -5.54341e-12 -0.062945"), ("rpy", "0 1.5708 -2.0414e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_foot.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.0044175 -5.54341e-12 -0.062945"), ("rpy", "0 1.5708 -2.0414e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_foot.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_foot_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_forearm")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.525")] [],
.text "\n            ",
.element "origin" [("xyz", "0.000347 0.066 0.00476"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000765393"), ("ixy", "4.337e-06"), ("ixz", "2.39e-07"), ("iyy", "0.000164578"), ("iyz", "1.9381e-05"), ("izz", "0.00069806")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.000143922 -1.25977e-12 0.0204334"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_forearm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.000143922 -1.25977e-12 0.0204334"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_forearm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_forearm_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_gripper")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_hand")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.213")] [],
.text "\n            ",
.element "origin" [("xyz", "0.07023 -0.00805 -0.007"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000157143"), ("ixy", "1.278e-05"), ("ixz", "4.823e-06"), ("iyy", "0.000247995"), ("iyz", "-1.8188e-05"), ("izz", "0.000380535")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-1.25981e-12 0.0204334 -0.000143922"), ("rpy", "5.10195e-12 -2.64173e-12 1.49623e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_hand.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-1.25981e-12 0.0204334 -0.000143922"), ("rpy", "5.10195e-12 -2.64173e-12 1.49623e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_hand.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_hand_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_hip_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.695")] [],
.text "\n            ",
.element "origin" [("xyz", "8.0431e-05 -0.00691643 -0.0023047"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00447053"), ("ixy", "-2.2209e-05"), ("ixz", "1.39712e-05"), ("iyy", "0.00325085"), ("iyz", "4.77629e-05"), ("izz", "0.00490487")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_hip_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_hip_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_hip_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.982")] [],
.text "\n            ",
.element "origin" [("xyz", "0.0010964 -3.13229e-05 0.0598624"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0253646"), ("ixy", "1.2116e-06"), ("ixz", "0.000491081"), ("iyy", "0.0272714"), ("iyz", "1.15713e-05"), ("izz", "0.0041739")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 3.14159")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_hip_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 3.14159")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_hip_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_hip_3")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_lower_leg")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "2.032")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.0761044 -4.50091e-05 0.0062408"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0154559"), ("ixy", "-0.0013903"), ("ixz", "-0.0039454"), ("iyy", "0.070277"), ("iyz", "0.00071995"), ("izz", "0.0659645")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.010945 0.0009175 2.2823e-12"), ("rpy", "-3.14159 -2.33487e-16 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_shank.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.010945 0.0009175 2.2823e-12"), ("rpy", "-3.14159 -2.33487e-16 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_shank.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_shoulder_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.189")] [],
.text "\n            ",
.element "origin" [("xyz", "-5e-06 0.0187 -0.00119"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "5.4421e-05"), ("ixy", "9e-09"), ("ixz", "0"), ("iyy", "9.331e-06"), ("iyz", "-1.7e-08"), ("izz", "5.4862e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "3.08087e-14 0.109285 -0.00521101"), ("rpy", "0 1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_shoulder_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "3.08087e-14 0.109285 -0.00521101"), ("rpy", "0 1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_shoulder_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_shoulder_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.179")] [],
.text "\n            ",
.element "origin" [("xyz", "9.4e-05 -0.00627 0.0166"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0001372"), ("ixy", "4.66e-07"), ("ixz", "3.65e-07"), ("iyy", "8.2927e-05"), ("iyz", "-2.0524e-05"), ("izz", "9.9274e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00154529 -0.00521101 -1.11181e-12"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_shoulder_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00154529 -0.00521101 -1.11181e-12"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_shoulder_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_shoulder_3")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.156157")] [],
.text "\n            ",
.element "origin" [("xyz", "0.00559398 9.77357e-05 0.0501346"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "4.84118e-05"), ("ixy", "-5.662e-08"), ("ixz", "-4.3618e-06"), ("iyy", "5.79067e-05"), ("iyz", "-7.42844e-07"), ("izz", "6.7103e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_sole")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_upper_arm")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.727843")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.000156 -9.87e-05 0.0298"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000408"), ("ixy", "-1.08e-06"), ("ixz", "-2.29e-06"), ("iyy", "0.00038"), ("iyz", "3.57e-06"), ("izz", "0.00026")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0204334 0.000143922 -0.068"), ("rpy", "1.15275e-11 4.9296e-12 -1.309")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_arm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0204334 0.000143922 -0.068"), ("rpy", "1.15275e-11 4.9296e-12 -1.309")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_arm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_upper_arm_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_upper_leg")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "1.522")] [],
.text "\n            ",
.element "origin" [("xyz", "0.0021968 -0.174502 0.0013437"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0454917"), ("ixy", "-0.000940971"), ("ixz", "5.37405e-05"), ("iyy", "0.01004"), ("iyz", "0.001203"), ("izz", "0.0458255")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_l_thigh.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_l_thigh.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_wrist_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "neck_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-1.11022e-16 9.62964e-13 -0.0055"), ("rpy", "0 -1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_neck_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-1.11022e-16 9.62964e-13 -0.0055"), ("rpy", "0 -1.5708 -1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_neck_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "neck_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-9.62967e-13 0.0055 0.0235"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_neck_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-9.62967e-13 0.0055 0.0235"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_neck_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_ankle_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.643")] [],
.text "\n            ",
.element "origin" [("xyz", "-2.65892e-05 -0.00082253 -0.0102574"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "4.76593"), ("ixy", "9.7426e-06"), ("ixz", "-2.68085e-05"), ("iyy", "0.0040935"), ("iyz", "0.000353796"), ("izz", "0.0036688")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.001555 -1.08717e-12 -0.0009175"), ("rpy", "-1.5708 -1.53106e-11 5.10376e-12")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_ankle_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.001555 -1.08717e-12 -0.0009175"), ("rpy", "-1.5708 -1.53106e-11 5.10376e-12")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_ankle_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_ankle_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.2675")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.0035 4.28626e-19 0.0645"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "4.70198e-38"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_elbow_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.074")] [],
.text "\n            ",
.element "origin" [("xyz", "0.0013 -0.00371 0.00105"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "2.84e-05"), ("ixy", "-5.02e-07"), ("ixz", "-3.99e-07"), ("iyy", "9.24e-06"), ("iyz", "-3.71e-07"), ("izz", "2.99e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_foot")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.5935")] [],
.text "\n            ",
.element "origin" [("xyz", "0.024069 0.000613931 -0.0284154"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00167275"), ("ixy", "4.51893e-06"), ("ixz", "0.000567784"), ("iyy", "0.00320869"), ("iyz", "6.62535e-07"), ("izz", "0.00208378")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.0044175 1.08716e-12 -0.062945"), ("rpy", "0 1.5708 3.14159")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_foot.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.0044175 1.08716e-12 -0.062945"), ("rpy", "0 1.5708 3.14159")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_foot.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_foot_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_forearm")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.525")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.000347 -0.066 -0.00476"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000766"), ("ixy", "5.66e-06"), ("ixz", "1.4e-06"), ("iyy", "0.000164"), ("iyz", "1.82e-05"), ("izz", "0.000699")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.000143922 -1.07216e-12 -0.0204334"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_forearm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.000143922 -1.07216e-12 -0.0204334"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_forearm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_forearm_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_gripper")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_hand")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.213")] [],
.text "\n            ",
.element "origin" [("xyz", "0.07023 -0.00805 0.007"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000154"), ("ixy", "1.26e-05"), ("ixz", "-6.08e-06"), ("iyy", "0.00025"), ("iyz", "1.76e-05"), ("izz", "0.000378")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "1.07207e-12 0.0204334 0.000143922"), ("rpy", "1.53098e-11 2.00665e-11 -3.14159")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_hand.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "1.07207e-12 0.0204334 0.000143922"), ("rpy", "1.53098e-11 2.00665e-11 -3.14159")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_hand.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_hand_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_hip_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.695")] [],
.text "\n            ",
.element "origin" [("xyz", "8.0431e-05 -0.00691643 0.0023047"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.00447053"), ("ixy", "-2.2209e-05"), ("ixz", "-1.39712e-05"), ("iyy", "0.00325085"), ("iyz", "-4.77629e-05"), ("izz", "0.00490487")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 4.71239")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_hip_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 4.71239")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_hip_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_hip_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.982")] [],
.text "\n            ",
.element "origin" [("xyz", "0.0010964 -3.13229e-05 0.0598624"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0253646"), ("ixy", "1.2116e-06"), ("ixz", "0.000491081"), ("iyy", "0.0272714"), ("iyz", "1.15713e-05"), ("izz", "0.0041739")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 1.02066e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_hip_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 1.02066e-11")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_hip_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_hip_3")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_lower_leg")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "2.032")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.0761044 -4.50091e-05 -0.0062408"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0154559"), ("ixy", "-0.0013903"), ("ixz", "0.0039454"), ("iyy", "0.070277"), ("iyz", "-0.00071995"), ("izz", "0.0659645")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0.010945 0.0009175 -8.32667e-17"), ("rpy", "3.14159 -1.14424e-17 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_shank.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0.010945 0.0009175 -8.32667e-17"), ("rpy", "3.14159 -1.14424e-17 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_shank.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_shoulder_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.189")] [],
.text "\n            ",
.element "origin" [("xyz", "5e-06 0.0187 0.00119"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000123"), ("ixy", "2.1e-08"), ("ixz", "-1e-09"), ("iyy", "2.44e-05"), ("iyz", "4.22e-06"), ("izz", "0.000113")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-3.08642e-14 0.109285 0.00521101"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_shoulder_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-3.08642e-14 0.109285 0.00521101"), ("rpy", "0 1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_shoulder_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_shoulder_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.179")] [],
.text "\n            ",
.element "origin" [("xyz", "-9.4e-05 -0.00627 -0.0166"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000137"), ("ixy", "-4.53e-07"), ("ixz", "2.03e-07"), ("iyy", "8.3e-05"), ("iyz", "2.07e-05"), ("izz", "9.93e-05")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00154529 -0.00521101 -1.11186e-12"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_shoulder_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.00154529 -0.00521101 -1.11186e-12"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_shoulder_2.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_shoulder_3")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.155")] [],
.text "\n            ",
.element "origin" [("xyz", "0.00553932 -2.47652e-05 0.0493895"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "3.44122e-05"), ("ixy", "3.56977e-07"), ("ixz", "-3.95372e-06"), ("iyy", "4.33544e-05"), ("iyz", "-6.5128e-06"), ("izz", "6.49393e-05")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_sole")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_upper_arm")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0.729")] [],
.text "\n            ",
.element "origin" [("xyz", "-0.00015906 8.28733e-05 0.0298828"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.000408"), ("ixy", "-1.08e-06"), ("ixz", "-2.29e-06"), ("iyy", "0.00038"), ("iyz", "3.57e-06"), ("izz", "0.00026")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0204334 -0.000143922 -0.068"), ("rpy", "-3.14159 -1.5137e-11 1.309")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_arm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "-0.0204334 -0.000143922 -0.068"), ("rpy", "-3.14159 -1.5137e-11 1.309")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_arm.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_upper_arm_dh_frame")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_upper_leg")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "1.522")] [],
.text "\n            ",
.element "origin" [("xyz", "0.0021968 -0.174502 -0.0013437"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0454917"), ("ixy", "-0.000940971"), ("ixz", "-5.37405e-05"), ("iyy", "0.01004"), ("iyz", "-0.001203"), ("izz", "0.0458255")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_r_thigh.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 1.5708")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_r_thigh.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_wrist_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "root_link")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "4.72")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_root_link.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_root_link.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "torso")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "torso_1")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0004544"), ("ixy", "-4.263e-05"), ("ixz", "-3.889e-08"), ("iyy", "0.001141"), ("iyz", "0"), ("izz", "0.001236")] [],
.text "\n        "],
.text "\n        ",
.element "visual" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 5.10314e-12 1.11022e-16")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/visual/icub_lap_belt_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n            ",
.element "material" [("name", "material.metal")] [.text "\n                ",
.element "texture" [] [],
.text "\n                ",
.element "color" [("rgba", "0 0 0 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n        ",
.element "collision" [] [.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 5.10314e-12 1.11022e-16")] [],
.text "\n            ",
.element "geometry" [] [.text "\n                ",
.element "mesh" [("filename", "package://iCub/meshes/upmc/collision/icub_simple_collision_lap_belt_1.dae"), ("scale", "1 1 1")] [],
.text "\n            "],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "torso_2")] [.text "\n        ",
.element "inertial" [] [.text "\n            ",
.element "mass" [("value", "0")] [],
.text "\n            ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n            ",
.element "inertia" [("ixx", "0.0005308"), ("ixy", "-1.923e-06"), ("ixz", "5.095e-05"), ("iyy", "0.002031"), ("iyz", "-3.849e-07"), ("izz", "0.001803")] [],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "torso_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-7.46298e-34 -0.0055 0"), ("rpy", "-1.5708 1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "torso_2")] [],
.text "\n        ",
.element "child" [("link", "chest")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "80"), ("velocity", "100"), ("lower", "-1.02974"), ("upper", "1.02974")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "chest_skin_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "-0.0055 -0.032 3.36778e-19"), ("rpy", "1.5708 -1.22465e-16 -3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "chest")] [],
.text "\n        ",
.element "child" [("link", "chest_skin_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "codyco_balancing_world_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "-8.67362e-19 -1.38778e-17 0.004"), ("rpy", "3.14159 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_foot")] [],
.text "\n        ",
.element "child" [("link", "codyco_balancing_world")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "neck_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-5.77779e-34 0 0"), ("rpy", "-1.5708 -1.11022e-16 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "neck_2")] [],
.text "\n        ",
.element "child" [("link", "head")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "20"), ("velocity", "100"), ("lower", "-0.959931"), ("upper", "0.959931")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "imu_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.0185 -0.1108 0.0066"), ("rpy", "1.5708 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "head")] [],
.text "\n        ",
.element "child" [("link", "imu_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_ankle_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.2005 0 0"), ("rpy", "-1.5708 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_lower_leg")] [],
.text "\n        ",
.element "child" [("link", "l_ankle_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "24"), ("velocity", "100"), ("lower", "-0.733038"), ("upper", "0.366519")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_ankle_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 0")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_ankle_1")] [],
.text "\n        ",
.element "child" [("link", "l_ankle_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "11"), ("velocity", "100"), ("lower", "-0.418879"), ("upper", "0.418879")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_elbow"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.08428"), ("rpy", "-6.12323e-17 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_upper_arm")] [],
.text "\n        ",
.element "child" [("link", "l_elbow_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "20"), ("velocity", "100"), ("lower", "0.0959931"), ("upper", "1.85005")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_foot_ft_sensor"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "-0.0035 0 0.0645"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_ankle_2")] [],
.text "\n        ",
.element "child" [("link", "l_foot")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_foot_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.004"), ("rpy", "0 1.5708 -0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_foot")] [],
.text "\n        ",
.element "child" [("link", "l_foot_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_wrist_prosup"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.015 0 0"), ("rpy", "1.5708 -1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_elbow_1")] [],
.text "\n        ",
.element "child" [("link", "l_forearm")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "0.45"), ("velocity", "100"), ("lower", "-0.872665"), ("upper", "0.872665")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_forearm_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0.1373 8.4072e-18"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_forearm")] [],
.text "\n        ",
.element "child" [("link", "l_forearm_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_gripper_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.0625 0 -0.016"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_hand")] [],
.text "\n        ",
.element "child" [("link", "l_gripper")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_wrist_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "parent" [("link", "l_wrist_1")] [],
.text "\n        ",
.element "child" [("link", "l_hand")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "0.65"), ("velocity", "100"), ("lower", "-0.436332"), ("upper", "0.436332")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_hand_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.0625 0 -0.016"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_hand")] [],
.text "\n        ",
.element "child" [("link", "l_hand_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_hip_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.0681 -0.1199"), ("rpy", "0 1.5708 -3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "root_link")] [],
.text "\n        ",
.element "child" [("link", "l_hip_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "-0.767945"), ("upper", "2.30383")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_hip_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "1 0 -6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_hip_1")] [],
.text "\n        ",
.element "child" [("link", "l_hip_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "-2.07694"), ("upper", "0.296706")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_leg_ft_sensor"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.0665"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_hip_2")] [],
.text "\n        ",
.element "child" [("link", "l_hip_3")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_knee"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.0009175 -0.234545 -1.43617e-17"), ("rpy", "3.14159 -1.2326e-32 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1.22465e-16 -1")] [],
.text "\n        ",
.element "parent" [("link", "l_upper_leg")] [],
.text "\n        ",
.element "child" [("link", "l_lower_leg")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "30"), ("velocity", "100"), ("lower", "-2.18166"), ("upper", "0.401426")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_shoulder_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.00525 0.1433 -0.11026"), ("rpy", "1.309 5.55112e-17 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 5.55112e-17")] [],
.text "\n        ",
.element "parent" [("link", "chest")] [],
.text "\n        ",
.element "child" [("link", "l_shoulder_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "-1.65806"), ("upper", "0.0872665")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_shoulder_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "1.5708 -1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_shoulder_1")] [],
.text "\n        ",
.element "child" [("link", "l_shoulder_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "0"), ("upper", "2.80649")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_shoulder_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "4.33681e-19 1.73472e-18 0"), ("rpy", "6.12323e-17 -0 1.309")] [],
.text "\n        ",
.element "axis" [("xyz", "0 6.12323e-17 1")] [],
.text "\n        ",
.element "parent" [("link", "l_shoulder_2")] [],
.text "\n        ",
.element "child" [("link", "l_shoulder_3")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "34"), ("velocity", "100"), ("lower", "-0.645772"), ("upper", "1.74533")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_sole_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "-8.67362e-19 -1.38778e-17 0.004"), ("rpy", "3.14159 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_foot")] [],
.text "\n        ",
.element "child" [("link", "l_sole")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_arm_ft_sensor"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.015 9.36797e-18 0.068"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_shoulder_3")] [],
.text "\n        ",
.element "child" [("link", "l_upper_arm")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_upper_arm_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.08428"), ("rpy", "-1.5708 0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "l_upper_arm")] [],
.text "\n        ",
.element "child" [("link", "l_upper_arm_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_hip_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -1.68519e-34 -0.0665"), ("rpy", "-1.5708 -6.16298e-33 -6.12323e-17")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_hip_3")] [],
.text "\n        ",
.element "child" [("link", "l_upper_leg")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("velocity", "100"), ("lower", "-1.37881"), ("upper", "1.37881")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "l_wrist_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0.1373 8.4072e-18"), ("rpy", "1.5708 1.11022e-16 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "l_forearm")] [],
.text "\n        ",
.element "child" [("link", "l_wrist_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "0.65"), ("velocity", "100"), ("lower", "-1.13446"), ("upper", "0.174533")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "neck_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.00231 0.1933 -1.18362e-17"), ("rpy", "1.5708 1.11022e-16 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "chest")] [],
.text "\n        ",
.element "child" [("link", "neck_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "20"), ("velocity", "100"), ("lower", "-0.698132"), ("upper", "0.523599")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "neck_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.0095 0 0"), ("rpy", "-1.5708 1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "neck_1")] [],
.text "\n        ",
.element "child" [("link", "neck_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "20"), ("velocity", "100"), ("lower", "-1.22173"), ("upper", "1.0472")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_ankle_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.2005 0 0"), ("rpy", "1.5708 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_lower_leg")] [],
.text "\n        ",
.element "child" [("link", "r_ankle_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "24"), ("velocity", "100"), ("lower", "-0.733038"), ("upper", "0.366519")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_ankle_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.5708 3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 1.22465e-16 0")] [],
.text "\n        ",
.element "parent" [("link", "r_ankle_1")] [],
.text "\n        ",
.element "child" [("link", "r_ankle_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "11"), ("velocity", "100"), ("lower", "-0.418879"), ("upper", "0.418879")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_elbow"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.08428"), ("rpy", "3.14159 -0 3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_upper_arm")] [],
.text "\n        ",
.element "child" [("link", "r_elbow_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "20"), ("velocity", "100"), ("lower", "0.0959931"), ("upper", "1.85005")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_foot_ft_sensor"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "-0.0035 4.28626e-19 0.0645"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_ankle_2")] [],
.text "\n        ",
.element "child" [("link", "r_foot")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_foot_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.004"), ("rpy", "0 1.5708 -0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_foot")] [],
.text "\n        ",
.element "child" [("link", "r_foot_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_wrist_prosup"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.015 0 0"), ("rpy", "1.5708 -1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_elbow_1")] [],
.text "\n        ",
.element "child" [("link", "r_forearm")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "0.45"), ("velocity", "100"), ("lower", "-0.872665"), ("upper", "0.872665")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_forearm_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.1373 -8.4072e-18"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_forearm")] [],
.text "\n        ",
.element "child" [("link", "r_forearm_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_gripper_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.0625 0 0.016"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_hand")] [],
.text "\n        ",
.element "child" [("link", "r_gripper")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_wrist_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n        ",
.element "parent" [("link", "r_wrist_1")] [],
.text "\n        ",
.element "child" [("link", "r_hand")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "0.65"), ("velocity", "100"), ("lower", "-0.436332"), ("upper", "0.436332")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_hand_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.0625 0 0.016"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_hand")] [],
.text "\n        ",
.element "child" [("link", "r_hand_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_hip_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0.0681 -0.1199"), ("rpy", "0 1.5708 6.12323e-17")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "root_link")] [],
.text "\n        ",
.element "child" [("link", "r_hip_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "-0.767945"), ("upper", "2.30383")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_hip_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 1.5708 -6.12323e-17")] [],
.text "\n        ",
.element "axis" [("xyz", "-1 0 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_hip_1")] [],
.text "\n        ",
.element "child" [("link", "r_hip_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "-2.07694"), ("upper", "0.296706")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_leg_ft_sensor"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.0665"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_hip_2")] [],
.text "\n        ",
.element "child" [("link", "r_hip_3")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_knee"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-0.0009175 -0.234545 1.43617e-17"), ("rpy", "3.14159 -1.2326e-32 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1.22465e-16 -1")] [],
.text "\n        ",
.element "parent" [("link", "r_upper_leg")] [],
.text "\n        ",
.element "child" [("link", "r_lower_leg")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "30"), ("velocity", "100"), ("lower", "-2.18166"), ("upper", "0.401426")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_shoulder_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.00525 0.1433 0.11026"), ("rpy", "-1.309 -0 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 5.55112e-17")] [],
.text "\n        ",
.element "parent" [("link", "chest")] [],
.text "\n        ",
.element "child" [("link", "r_shoulder_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "-1.65806"), ("upper", "0.0872665")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_shoulder_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "-1.5708 1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_shoulder_1")] [],
.text "\n        ",
.element "child" [("link", "r_shoulder_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "84"), ("velocity", "100"), ("lower", "0"), ("upper", "2.80649")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_shoulder_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "-4.33681e-19 0 0"), ("rpy", "3.14159 -0 1.309")] [],
.text "\n        ",
.element "axis" [("xyz", "0 6.12323e-17 -1")] [],
.text "\n        ",
.element "parent" [("link", "r_shoulder_2")] [],
.text "\n        ",
.element "child" [("link", "r_shoulder_3")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "34"), ("velocity", "100"), ("lower", "-0.645772"), ("upper", "1.74533")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_sole_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "-8.67362e-19 1.38778e-17 0.004"), ("rpy", "3.14159 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_foot")] [],
.text "\n        ",
.element "child" [("link", "r_sole")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_arm_ft_sensor"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.015 -8.93429e-18 0.068"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_shoulder_3")] [],
.text "\n        ",
.element "child" [("link", "r_upper_arm")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_upper_arm_dh_frame_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0.08428"), ("rpy", "1.5708 -0 3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "r_upper_arm")] [],
.text "\n        ",
.element "child" [("link", "r_upper_arm_dh_frame")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_hip_yaw"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 1.68519e-34 -0.0665"), ("rpy", "-1.5708 -6.16298e-33 6.12323e-17")] [],
.text "\n        ",
.element "axis" [("xyz", "0 -1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_hip_3")] [],
.text "\n        ",
.element "child" [("link", "r_upper_leg")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "40"), ("velocity", "100"), ("lower", "-1.37881"), ("upper", "1.37881")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "r_wrist_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 -0.1373 -8.4072e-18"), ("rpy", "1.5708 1.11022e-16 1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "r_forearm")] [],
.text "\n        ",
.element "child" [("link", "r_wrist_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "0.65"), ("velocity", "100"), ("lower", "-1.13446"), ("upper", "0.174533")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "base_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "base_link")] [],
.text "\n        ",
.element "child" [("link", "root_link")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "torso_joint"), ("type", "fixed")] [.text "\n        ",
.element "origin" [("xyz", "0.00231 0.1933 -1.18362e-17"), ("rpy", "0 -0 0")] [],
.text "\n        ",
.element "axis" [("xyz", "0 0 0")] [],
.text "\n        ",
.element "parent" [("link", "chest")] [],
.text "\n        ",
.element "child" [("link", "torso")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "torso_pitch"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 -1.5708 3.14159")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "root_link")] [],
.text "\n        ",
.element "child" [("link", "torso_1")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "36"), ("velocity", "100"), ("lower", "-0.383972"), ("upper", "1.46608")] [],
.text "\n    "],
.text "\n    ",
.element "joint" [("name", "torso_roll"), ("type", "revolute")] [.text "\n        ",
.element "origin" [("xyz", "0.032 -2.67276e-51 0"), ("rpy", "1.5708 -1.11022e-16 -1.5708")] [],
.text "\n        ",
.element "axis" [("xyz", "0 1 6.12323e-17")] [],
.text "\n        ",
.element "parent" [("link", "torso_1")] [],
.text "\n        ",
.element "child" [("link", "torso_2")] [],
.text "\n        ",
.element "dynamics" [("damping", "1"), ("friction", "0")] [],
.text "\n        ",
.element "limit" [("effort", "80"), ("velocity", "100"), ("lower", "-0.680678"), ("upper", "0.680678")] [],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "l_arm_ft_sensor")] [.text "\n        ",
.element "sensor" [("name", "left_arm_ft"), ("type", "force_torque")] [.text "\n            ",
.element "force_torque" [] [.text "\n                ",
.element "frame" [] [.text "child"],
.text "\n                ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n            "],
.text "\n            ",
.element "update_rate" [] [.text "100"],
.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "r_arm_ft_sensor")] [.text "\n        ",
.element "sensor" [("name", "right_arm_ft"), ("type", "force_torque")] [.text "\n            ",
.element "force_torque" [] [.text "\n                ",
.element "frame" [] [.text "child"],
.text "\n                ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n            "],
.text "\n            ",
.element "update_rate" [] [.text "100"],
.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "l_leg_ft_sensor")] [.text "\n        ",
.element "sensor" [("name", "left_leg_ft"), ("type", "force_torque")] [.text "\n            ",
.element "force_torque" [] [.text "\n                ",
.element "frame" [] [.text "child"],
.text "\n                ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n            "],
.text "\n            ",
.element "update_rate" [] [.text "100"],
.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "r_leg_ft_sensor")] [.text "\n        ",
.element "sensor" [("name", "right_leg_ft"), ("type", "force_torque")] [.text "\n            ",
.element "force_torque" [] [.text "\n                ",
.element "frame" [] [.text "child"],
.text "\n                ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n            "],
.text "\n            ",
.element "update_rate" [] [.text "100"],
.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "l_foot_ft_sensor")] [.text "\n        ",
.element "sensor" [("name", "left_foot_ft"), ("type", "force_torque")] [.text "\n            ",
.element "force_torque" [] [.text "\n                ",
.element "frame" [] [.text "child"],
.text "\n                ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n            "],
.text "\n            ",
.element "update_rate" [] [.text "100"],
.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "gazebo" [("reference", "r_foot_ft_sensor")] [.text "\n        ",
.element "sensor" [("name", "right_foot_ft"), ("type", "force_torque")] [.text "\n            ",
.element "force_torque" [] [.text "\n                ",
.element "frame" [] [.text "child"],
.text "\n                ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n            "],
.text "\n            ",
.element "update_rate" [] [.text "100"],
.text "\n            ",
.element "always_on" [] [.text "1"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_arm_ft")] [],
.text "\n    ",
.element "joint" [("name", "l_arm_ft_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "l_upper_arm")] [],
.text "\n        ",
.element "child" [("link", "l_arm_ft")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_arm_ft")] [],
.text "\n    ",
.element "joint" [("name", "r_arm_ft_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "r_upper_arm")] [],
.text "\n        ",
.element "child" [("link", "r_arm_ft")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "l_leg_ft")] [],
.text "\n    ",
.element "joint" [("name", "l_leg_ft_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "l_hip_3")] [],
.text "\n        ",
.element "child" [("link", "l_leg_ft")] [],
.text "\n    "],
.text "\n    ",
.element "link" [("name", "r_leg_ft")] [],
.text "\n    ",
.element "joint" [("name", "r_leg_ft_fixed_joint"), ("type", "fixed")] [.text "\n        ",
.element "parent" [("link", "r_hip_3")] [],
.text "\n        ",
.element "child" [("link", "r_leg_ft")] [],
.text "\n    "],
.text "\n    ",
.element "sensor" [("type", "force_torque"), ("name", "l_arm_ft")] [.text "\n        ",
.element "parent" [("joint", "l_arm_ft_sensor")] [],
.text "\n        ",
.element "force_torque" [] [.text "\n            ",
.element "frame" [] [.text "child"],
.text "\n            ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "sensor" [("type", "force_torque"), ("name", "r_arm_ft")] [.text "\n        ",
.element "parent" [("joint", "r_arm_ft_sensor")] [],
.text "\n        ",
.element "force_torque" [] [.text "\n            ",
.element "frame" [] [.text "child"],
.text "\n            ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "sensor" [("type", "force_torque"), ("name", "l_leg_ft")] [.text "\n        ",
.element "parent" [("joint", "l_leg_ft_sensor")] [],
.text "\n        ",
.element "force_torque" [] [.text "\n            ",
.element "frame" [] [.text "child"],
.text "\n            ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "sensor" [("type", "force_torque"), ("name", "r_leg_ft")] [.text "\n        ",
.element "parent" [("joint", "r_leg_ft_sensor")] [],
.text "\n        ",
.element "force_torque" [] [.text "\n            ",
.element "frame" [] [.text "child"],
.text "\n            ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "sensor" [("type", "force_torque"), ("name", "l_foot_ft_sensor")] [.text "\n        ",
.element "parent" [("joint", "l_foot_ft_sensor")] [],
.text "\n        ",
.element "force_torque" [] [.text "\n            ",
.element "frame" [] [.text "child"],
.text "\n            ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n        "],
.text "\n    "],
.text "\n    ",
.element "sensor" [("type", "force_torque"), ("name", "r_foot_ft_sensor")] [.text "\n        ",
.element "parent" [("joint", "r_foot_ft_sensor")] [],
.text "\n        ",
.element "force_torque" [] [.text "\n            ",
.element "frame" [] [.text "child"],
.text "\n            ",
.element "measure_direction" [] [.text "child_to_parent"],
.text "\n        "],
.text "\n    "],
.text "\n"],
[],
[],
"4bbce1cebc04aa482123f6b7d8bbc870225d860bebff3b4575cf2a1b757775ca"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
