import FluxKernel.Design
open FluxKernel.Design
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def designDigest : String := "2cd36b42661ab552720cd6e956fe6afa104aef1dce847872d6e1ebe58903f8dd"
def design : Model := ⟨[⟨⟨((1 : Rat) / (4 : Rat)), ⟨0, 0, 0⟩⟩, ((1 : Rat) / (10 : Rat)), ((2 : Rat) / (1 : Rat))⟩,
⟨⟨((3 : Rat) / (25 : Rat)), ⟨1, 0, 0⟩⟩, ((2 : Rat) / (25 : Rat)), ((1 : Rat) / (5 : Rat))⟩,
⟨⟨((3 : Rat) / (50 : Rat)), ⟨1, 0, 0⟩⟩, ((3 : Rat) / (100 : Rat)), ((3 : Rat) / (40 : Rat))⟩,
⟨⟨((1 : Rat) / (100 : Rat)), ⟨1, 0, 0⟩⟩, ((1 : Rat) / (500 : Rat)), ((1 : Rat) / (50 : Rat))⟩,
⟨⟨((1 : Rat) / (250 : Rat)), ⟨1, 0, 0⟩⟩, ((1 : Rat) / (1000 : Rat)), ((1 : Rat) / (100 : Rat))⟩,
⟨⟨((3 : Rat) / (500 : Rat)), ⟨1, 0, 0⟩⟩, ((1 : Rat) / (500 : Rat)), ((3 : Rat) / (250 : Rat))⟩,
⟨⟨((5 : Rat) / (1 : Rat)), ⟨1, 1, -2⟩⟩, ((0 : Rat) / (1 : Rat)), ((100 : Rat) / (1 : Rat))⟩], [⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 1), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 3), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .lt⟩,
⟨(.add (.add (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.parameter 1)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.parameter 1))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.parameter 1) (.parameter 1)), .eq⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 2), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 3), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .lt⟩,
⟨(.add (.add (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.parameter 2) (.parameter 2)), .eq⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 1), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 3), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .lt⟩,
⟨(.add (.add (.mul (.sub (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))) (.add (.parameter 1) (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))))) (.sub (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))) (.add (.parameter 1) (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))))) (.mul (.sub (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))) (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))) (.sub (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))) (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.parameter 1) (.parameter 1)), .eq⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 2), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 3), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .lt⟩,
⟨(.add (.add (.mul (.sub (.parameter 1) (.add (.parameter 1) (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))))) (.sub (.parameter 1) (.add (.parameter 1) (.mul (.parameter 2) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.parameter 2) (.parameter 2)), .eq⟩,
⟨(.literal ((-3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .lt⟩,
⟨(.literal ((-3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.parameter 5), .lt⟩,
⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (500 : Rat)) ⟨1, 0, 0⟩), .lt⟩,
⟨(.parameter 5), (.literal ((3 : Rat) / (500 : Rat)) ⟨1, 0, 0⟩), .eq⟩,
⟨(.literal ((4 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩), (.literal ((4 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩), .eq⟩,
⟨(.add (.add (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)), .eq⟩,
⟨(.literal ((1 : Rat) / (125 : Rat)) ⟨1, 0, 0⟩), (.parameter 3), .le⟩,
⟨(.literal ((3 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .le⟩,
⟨(.add (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.literal ((3 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩)), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .le⟩,
⟨(.div (.parameter 6) (.mul (.parameter 3) (.parameter 4))), (.literal ((2000000 : Rat) / (1 : Rat)) ⟨-1, 1, -2⟩), .le⟩,
⟨(.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩), (.mul (.parameter 2) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))), .lt⟩,
⟨(.add (.mul (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))) (.div (.sub (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0))))) (.mul (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))) (.div (.mul (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.parameter 0)) (.add (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.parameter 0) (.parameter 0)))))), (.literal ((1 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩), .eq⟩], [(.not (.atom ⟨(.mul (.sub (.add (.add (.add (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩))) (.mul (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)))) (.sub (.add (.add (.add (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩))) (.mul (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩))))), (.mul (.mul (.literal ((4 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩))) (.add (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), .le⟩)),
(.atom ⟨(.mul (.sub (.add (.add (.add (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩)) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩))) (.mul (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)))) (.sub (.add (.add (.add (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩)) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩))) (.mul (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩))))), (.mul (.mul (.literal ((4 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩) (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩))) (.add (.mul (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩)) (.mul (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), .le⟩),
(.not (.and (.and (.and (.and (.and (.and (.atom ⟨(.literal ((-3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), .le⟩) (.atom ⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((-3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .le⟩)) (.not (.and (.atom ⟨(.add (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩))), .le⟩) (.atom ⟨(.mul (.sub (.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))), (.mul (.div (.literal ((3 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.literal ((3 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩))), .le⟩))))),
(.and (.and (.and (.and (.and (.and (.atom ⟨(.literal ((-3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩), .le⟩) (.atom ⟨(.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((-3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((3 : Rat) / (200 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩), (.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩), .le⟩)) (.atom ⟨(.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩), (.parameter 4), .le⟩)) (.not (.and (.atom ⟨(.add (.mul (.sub (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((1 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))) (.mul (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)))), (.mul (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.parameter 5) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩))), .le⟩) (.atom ⟨(.mul (.sub (.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩)) (.sub (.literal ((1 : Rat) / (1000 : Rat)) ⟨1, 0, 0⟩) (.literal ((0 : Rat) / (1 : Rat)) ⟨1, 0, 0⟩))), (.mul (.div (.literal ((3 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩)) (.div (.literal ((3 : Rat) / (100 : Rat)) ⟨1, 0, 0⟩) (.literal ((2 : Rat) / (1 : Rat)) ⟨0, 0, 0⟩))), .le⟩))))]⟩
theorem accepted : check design = true := by decide +kernel
theorem obligationsHold : Valid design := check_sound design accepted
#print axioms obligationsHold
#print axioms parallelogram_family
