import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "2dof_planar")] [.text "\n  ",
.element "link" [("name", "base_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0030299 2.6279E-13 0.02912"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.10159")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.636E-05"), ("ixy", "-1.007E-16"), ("ixz", "-2.3835E-06"), ("iyy", "1.8042E-05"), ("iyz", "-4.6617E-09"), ("izz", "1.8795E-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/double_pendulum_description/meshes/base_link.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.96078 1 0 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/double_pendulum_description/meshes/base_link.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "link1")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0086107 2.1727E-06 0.036012"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.26703")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00040827"), ("ixy", "1.2675E-09"), ("ixz", "1.8738E-05"), ("iyy", "0.00038791"), ("iyz", "3.5443E-08"), ("izz", "3.6421E-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/double_pendulum_description/meshes/link1.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.64706 0.61961 0.58824 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/double_pendulum_description/meshes/link1.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint1"), ("type", "continuous")] [.text "\n    ",
.element "origin" [("xyz", "0.0060872 0 0.035"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "base_link")] [],
.text "\n    ",
.element "child" [("link", "link1")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "0"), ("effort", "0"), ("velocity", "0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.05")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "link2")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.0050107 1.9371E-10 0.10088"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.33238")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0011753"), ("ixy", "-3.854E-13"), ("ixz", "-2.9304E-08"), ("iyy", "0.0011666"), ("iyz", "-5.2365E-12"), ("izz", "1.4553E-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/double_pendulum_description/meshes/link2.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "")] [.text "\n        ",
.element "color" [("rgba", "0.64706 0.61961 0.58824 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://example-robot-data/robots/double_pendulum_description/meshes/link2.stl")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "joint2"), ("type", "continuous")] [.text "\n    ",
.element "origin" [("xyz", "0.023 0 0.1"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "link1")] [],
.text "\n    ",
.element "child" [("link", "link2")] [],
.text "\n    ",
.element "axis" [("xyz", "1 0 0")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "0"), ("effort", "0"), ("velocity", "0")] [],
.text "\n    ",
.element "dynamics" [("damping", "0.05")] [],
.text "\n  "],
.text "\n"],
[],
[],
"ebdef1b5d1182149f7740ad7d513cc6d1b5efb55b00e6ff355ae37ee2e19c316"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
