import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "Lhand")] [.text "\n\n  ",
.element "mujoco" [] [.text "\n    ",
.element "compiler" [("meshdir", "meshes"), ("discardvisual", "false")] [],
.text "\n  "],
.text "\n\n  \n\n  ",
.element "link" [("name", "left_wrist_yaw_link")] [],
.text "\n\n  ",
.element "joint" [("name", "L_base_link_joint"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("xyz", "0.0415 0 0"), ("rpy", "0 0 1.5707963267948966192313216916398")] [],
.text "\n    ",
.element "parent" [("link", "left_wrist_yaw_link")] [],
.text "\n    ",
.element "child" [("link", "L_hand_base_link")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_hand_base_link")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "-0.002551 -0.066047 -0.0019357"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.14143")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0001234"), ("ixy", "2.1995E-06"), ("ixz", "-1.7694E-06"), ("iyy", "8.3835E-05"), ("iyz", "1.5968E-06"), ("izz", "7.7231E-05")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/L_hand_base_link.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/L_hand_base_link.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_thumb_proximal_base")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0048817 0.00038782 -0.00722"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0018869")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.5158E-08"), ("ixy", "-1.1803E-08"), ("ixz", "-4.6743E-09"), ("iyy", "8.2164E-08"), ("iyz", "-1.3521E-09"), ("izz", "6.7434E-08")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link11_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link11_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_thumb_proximal_yaw_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.01696 -0.0691 0.02045"), ("rpy", "1.5708 -1.5708 0")] [],
.text "\n    ",
.element "parent" [("link", "L_hand_base_link")] [],
.text "\n    ",
.element "child" [("link", "L_thumb_proximal_base")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.1"), ("upper", "1.3"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_thumb_proximal")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.021936 -0.01279 -0.0080386"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0066101")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.5693E-06"), ("ixy", "7.8339E-07"), ("ixz", "8.5959E-10"), ("iyy", "1.7356E-06"), ("iyz", "1.0378E-09"), ("izz", "2.787E-06")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link12_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link12_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_thumb_proximal_pitch_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.0099867 0.0098242 -0.0089"), ("rpy", "-1.5708 0 0.16939")] [],
.text "\n    ",
.element "parent" [("link", "L_thumb_proximal_base")] [],
.text "\n    ",
.element "child" [("link", "L_thumb_proximal")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "-0.1"), ("upper", "0.6"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_thumb_intermediate")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0095531 0.0016282 -0.0072002"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0037844")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.6981E-07"), ("ixy", "9.8603E-08"), ("ixz", "-2.8173E-12"), ("iyy", "3.2395E-07"), ("iyz", "-2.8028E-12"), ("izz", "4.6532E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link13_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link13_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_thumb_intermediate_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.04407 -0.034553 -0.0008"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_thumb_proximal")] [],
.text "\n    ",
.element "child" [("link", "L_thumb_intermediate")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "0.8"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n    ",
.element "mimic" [("joint", "L_thumb_proximal_pitch_joint"), ("multiplier", "1.6"), ("offset", "0")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_thumb_distal")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0092888 -0.004953 -0.0060033"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.003344")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.3632E-07"), ("ixy", "5.6787E-08"), ("ixz", "-9.1939E-11"), ("iyy", "1.4052E-07"), ("iyz", "1.2145E-10"), ("izz", "2.0026E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link14_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link14_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_thumb_distal_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.020248 -0.010156 -0.0012"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_thumb_intermediate")] [],
.text "\n    ",
.element "child" [("link", "L_thumb_distal")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.2"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n    ",
.element "mimic" [("joint", "L_thumb_proximal_pitch_joint"), ("multiplier", "2.4"), ("offset", "0")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_index_proximal")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0012971 -0.011934 -0.0059998"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0042405")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.6215E-07"), ("ixy", "1.8442E-08"), ("ixz", "1.3746E-12"), ("iyy", "2.1167E-07"), ("iyz", "-1.4773E-11"), ("izz", "6.9402E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link15_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link15_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_index_proximal_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.00028533 -0.13653 0.032268"), ("rpy", "-0.034907 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_hand_base_link")] [],
.text "\n    ",
.element "child" [("link", "L_index_proximal")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_index_intermediate")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0021753 -0.019567 -0.005"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0045682")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.6284E-07"), ("ixy", "-8.063E-08"), ("ixz", "3.6797E-13"), ("iyy", "9.4308E-08"), ("iyz", "1.5743E-13"), ("izz", "7.8176E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link16_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link16_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_index_intermediate_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0024229 -0.032041 -0.001"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_index_proximal")] [],
.text "\n    ",
.element "child" [("link", "L_index_intermediate")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n    ",
.element "mimic" [("joint", "L_index_proximal_joint"), ("multiplier", "1"), ("offset", "0")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_middle_proximal")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0012971 -0.011934 -0.0059999"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0042405")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.6215E-07"), ("ixy", "1.8442E-08"), ("ixz", "1.2299E-12"), ("iyy", "2.1167E-07"), ("iyz", "-1.4484E-11"), ("izz", "6.9402E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link17_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link17_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_middle_proximal_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.00028533 -0.1371 0.01295"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_hand_base_link")] [],
.text "\n    ",
.element "child" [("link", "L_middle_proximal")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_middle_intermediate")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.001921 -0.020796 -0.0049999"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0050397")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.5823E-07"), ("ixy", "-1.1425E-07"), ("ixz", "-2.4186E-12"), ("iyy", "1.0646E-07"), ("iyz", "3.6974E-12"), ("izz", "9.8385E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link18_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link18_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_middle_intermediate_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0024229 -0.032041 -0.001"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_middle_proximal")] [],
.text "\n    ",
.element "child" [("link", "L_middle_intermediate")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n    ",
.element "mimic" [("joint", "L_middle_proximal_joint"), ("multiplier", "1"), ("offset", "0")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_ring_proximal")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0012971 -0.011934 -0.0059999"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0042405")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.6215E-07"), ("ixy", "1.8442E-08"), ("ixz", "9.6052E-13"), ("iyy", "2.1167E-07"), ("iyz", "-1.4124E-11"), ("izz", "6.9402E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link19_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link19_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_ring_proximal_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.00028533 -0.13691 -0.0062872"), ("rpy", "0.05236 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_hand_base_link")] [],
.text "\n    ",
.element "child" [("link", "L_ring_proximal")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_ring_intermediate")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0021753 -0.019567 -0.005"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0045682")] [],
.text "\n      ",
.element "inertia" [("ixx", "7.6285E-07"), ("ixy", "-8.0631E-08"), ("ixz", "3.3472E-14"), ("iyy", "9.4308E-08"), ("iyz", "-4.4773E-13"), ("izz", "7.8176E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link20_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link20_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_ring_intermediate_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0024229 -0.032041 -0.001"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_ring_proximal")] [],
.text "\n    ",
.element "child" [("link", "L_ring_intermediate")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n    ",
.element "mimic" [("joint", "L_ring_proximal_joint"), ("multiplier", "1"), ("offset", "0")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_pinky_proximal")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0012971 -0.011934 -0.0059999"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0042405")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.6215E-07"), ("ixy", "1.8442E-08"), ("ixz", "1.0279E-12"), ("iyy", "2.1167E-07"), ("iyz", "-1.4277E-11"), ("izz", "6.9402E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link21_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link21_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_pinky_proximal_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "0.00028533 -0.13571 -0.025488"), ("rpy", "0.10472 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_hand_base_link")] [],
.text "\n    ",
.element "child" [("link", "L_pinky_proximal")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "L_pinky_intermediate")] [.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("xyz", "0.0024788 -0.016208 -0.0050001"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.0036036")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.3923E-07"), ("ixy", "-4.1355E-08"), ("ixz", "1.2263E-12"), ("iyy", "7.0315E-08"), ("iyz", "3.1311E-12"), ("izz", "4.4881E-07")] [],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link22_L.STL")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("xyz", "0 0 0"), ("rpy", "0 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "meshes/Link22_L.STL")] [],
.text "\n      "],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "L_pinky_intermediate_joint"), ("type", "revolute")] [.text "\n    ",
.element "origin" [("xyz", "-0.0024229 -0.032041 -0.001"), ("rpy", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "L_pinky_proximal")] [],
.text "\n    ",
.element "child" [("link", "L_pinky_intermediate")] [],
.text "\n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("lower", "0"), ("upper", "1.7"), ("effort", "1"), ("velocity", "0.5")] [],
.text "\n    ",
.element "mimic" [("joint", "L_pinky_proximal_joint"), ("multiplier", "1"), ("offset", "0")] [],
.text "\n  "],
.text "\n\n"],
[],
[],
"c0b18c100d82e3080241edde91034fe66c3ee0883a227e1eeb310f49387cccbb"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
