import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "upkie")] [.text "\n  ",
.element "material" [("name", "black")] [.text "\n    ",
.element "color" [("rgba", "0.1 0.1 0.1 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "chalky_blue")] [.text "\n    ",
.element "color" [("rgba", "0.65 0.76 0.91 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "dark_gray")] [.text "\n    ",
.element "color" [("rgba", "0.3 0.3 0.3 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "light_gray")] [.text "\n    ",
.element "color" [("rgba", "0.8 0.8 0.8 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "light_wood")] [.text "\n    ",
.element "color" [("rgba", "1 0.77 0.48 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "mj5208_rotor")] [.text "\n    ",
.element "color" [("rgba", "0.5 0.55 0.6 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "mj5208_stator")] [.text "\n    ",
.element "color" [("rgba", "0.22 0.22 0.25 1.0")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "terracotta_light")] [.text "\n    ",
.element "color" [("rgba", "0.93 0.64 0.52 1")] [],
.text "\n  "],
.text "\n  ",
.element "material" [("name", "terracotta_transparent")] [.text "\n    ",
.element "color" [("rgba", "0.93 0.64 0.52 0.8")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "base")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "torso")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.125 0.17 0.25")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_transparent")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.125 0.17 0.25")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "1")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.007616666666666667"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.006510416666666667"), ("iyz", "0"), ("izz", "0.0037104166666666674")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "torso_fix"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.1")] [],
.text "\n    ",
.element "parent" [("link", "base")] [],
.text "\n    ",
.element "child" [("link", "torso")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "imu")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "imu_fix"), ("type", "fixed")] [.text "\n    \n    ",
.element "origin" [("rpy", "3.141592653589793 0 3.141592653589793"), ("xyz", "0 0 0")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "imu")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "battery")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.13 0.074 0.055")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark_gray")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.13 0.074 0.055")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.8")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.0005667333333333333"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.0013283333333333335"), ("iyz", "0"), ("izz", "0.0014917333333333335")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "battery_fix"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 1.5707963267948966"), ("xyz", "-0.04 0 0")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "battery")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "handle")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/add-ons/handle.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.120 0.07 0.04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01")] [],
.text "\n      ",
.element "mass" [("value", "0.0525")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.8437500000000003e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "7.000000000000001e-05"), ("iyz", "0"), ("izz", "8.44375e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "handle_fix"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "0 0 -1.5707963267948966"), ("xyz", "0 0 0.135")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "handle")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "left_hip_qdd100_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.03"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "mass" [("value", "0.47")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00032900000000000003"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00032900000000000003"), ("iyz", "0"), ("izz", "0.0005875000000000001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hip_qdd100_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 0"), ("xyz", "0.0 0.085 -0.064")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "left_hip_qdd100_stator")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hip_qdd100_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_rotor.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.005"), ("radius", "0.023")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "mass" [("value", "0.015")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.0149999999999998e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "2.0149999999999998e-06"), ("iyz", "0"), ("izz", "3.9675e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hip"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "left_hip_qdd100_stator")] [],
.text "\n    ",
.element "child" [("link", "left_hip_qdd100_rotor")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0292")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "16.0"), ("lower", "-1.26"), ("upper", "1.26"), ("velocity", "28.8")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_hip_horn")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_horn.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.09"), ("radius", "0.025")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "mass" [("value", "0.05267")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.37819375e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.37819375e-05"), ("iyz", "0"), ("izz", "1.6459375000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_hip_horn_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_hip_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "left_hip_horn")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "left_femur")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.25"), ("radius", "0.011")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.26"), ("radius", "0.012")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.056")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.170666666666667e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "5.170666666666667e-06"), ("iyz", "0"), ("izz", "4.0320000000000005e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_femur_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_hip_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "left_femur")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.07 0.025")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "left_knee_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_femur")] [],
.text "\n    ",
.element "child" [("link", "left_knee_stator")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 -1.5707963267948966"), ("xyz", "0 0.042 -0.098")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_knee_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/knee_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0.03 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.06"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0.03 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.09874")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.133450000000001e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "9.133450000000001e-05"), ("iyz", "0"), ("izz", "0.000123425")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_knee_qdd100_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.03"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "mass" [("value", "0.47")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00032900000000000003"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00032900000000000003"), ("iyz", "0"), ("izz", "0.0005875000000000001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_knee_qdd100_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_knee_stator")] [],
.text "\n    ",
.element "child" [("link", "left_knee_qdd100_stator")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_knee"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "left_knee_qdd100_stator")] [],
.text "\n    ",
.element "child" [("link", "left_knee_qdd100_rotor")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0292")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "16.0"), ("lower", "-2.51"), ("upper", "2.51"), ("velocity", "28.8")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_knee_qdd100_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_rotor.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.005"), ("radius", "0.023")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "mass" [("value", "0.015")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.0149999999999998e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "2.0149999999999998e-06"), ("iyz", "0"), ("izz", "3.9675e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_knee_horn")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_horn.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.09"), ("radius", "0.025")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "mass" [("value", "0.05267")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.37819375e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.37819375e-05"), ("iyz", "0"), ("izz", "1.6459375000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_knee_horn_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_knee_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "left_knee_horn")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "left_tibia")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.25"), ("radius", "0.011")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.26"), ("radius", "0.012")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.056")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.170666666666667e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "5.170666666666667e-06"), ("iyz", "0"), ("izz", "4.0320000000000005e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_tibia_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_knee_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "left_tibia")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0.07 0.025")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "left_ankle_base")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/ankle_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "chalky_blue")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.002 0.0275")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.092 0.068 0.056")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.002 0.0275")] [],
.text "\n      ",
.element "mass" [("value", "0.07863")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.084740000000002e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "7.6009e-05"), ("iyz", "0"), ("izz", "8.575912e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ankle_base_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_tibia")] [],
.text "\n    ",
.element "child" [("link", "left_ankle_base")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.034 -0.105")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ankle_plate")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.08 0.045 0.003")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_gray")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.09 0.046 0.004")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.02")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.5533333333333333e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.3526666666666667e-05"), ("iyz", "0"), ("izz", "1.7026666666666667e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ankle_plate_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ankle_base")] [],
.text "\n    ",
.element "child" [("link", "left_ankle_plate")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0015")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ankle_mj5208_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/mj5208_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "mj5208_stator")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.018"), ("radius", "0.03")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01")] [],
.text "\n      ",
.element "mass" [("value", "0.1721")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.3369200000000005e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.3369200000000005e-05"), ("iyz", "0"), ("izz", "7.7445e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_ankle_mj5208_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ankle_plate")] [],
.text "\n    ",
.element "child" [("link", "left_ankle_mj5208_stator")] [],
.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 0 0"), ("xyz", "0 0 -0.0015")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_anchor")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_anchor_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ankle_mj5208_stator")] [],
.text "\n    ",
.element "child" [("link", "left_anchor")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0.0545 0.05")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_ankle_mj5208_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/mj5208_rotor.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "mj5208_rotor")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.016"), ("radius", "0.034")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.551666666666667e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.551666666666667e-05"), ("iyz", "0"), ("izz", "2.8900000000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_wheel"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "left_ankle_mj5208_stator")] [],
.text "\n    ",
.element "child" [("link", "left_ankle_mj5208_rotor")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "1.7"), ("velocity", "111.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "left_wheel_hub")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/wheel_hub.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0125")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.025"), ("radius", "0.039")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0125")] [],
.text "\n      ",
.element "mass" [("value", "0.0454")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.9627933333333332e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.9627933333333332e-05"), ("iyz", "0"), ("izz", "3.45267e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_wheel_hub_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_ankle_mj5208_rotor")] [],
.text "\n    ",
.element "child" [("link", "left_wheel_hub")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0251")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_wheel_tire")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/wheel_tire/wheel_tire.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark_gray")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.04"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.08715")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.608875000000002e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "6.608875000000002e-05"), ("iyz", "0"), ("izz", "0.00010893750000000003")] [],
.text "\n    "],
.text "\n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "rolling_friction" [("value", "0.01")] [],
.text "\n      ",
.element "stiffness" [("value", "30000")] [],
.text "\n      ",
.element "damping" [("value", "1000")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_wheel_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_wheel_hub")] [],
.text "\n    ",
.element "child" [("link", "left_wheel_tire")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0209")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_contact")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_contact_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_wheel_tire")] [],
.text "\n    ",
.element "child" [("link", "left_contact")] [],
.text "\n    \n    \n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.047 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "left_wheel_center")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "left_wheel_center_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "left_wheel_tire")] [],
.text "\n    ",
.element "child" [("link", "left_wheel_center")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "right_hip_qdd100_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.03"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "mass" [("value", "0.47")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00032900000000000003"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00032900000000000003"), ("iyz", "0"), ("izz", "0.0005875000000000001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hip_qdd100_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 3.141592653589793 0"), ("xyz", "0.0 -0.085 -0.064")] [],
.text "\n    ",
.element "parent" [("link", "torso")] [],
.text "\n    ",
.element "child" [("link", "right_hip_qdd100_stator")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hip_qdd100_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_rotor.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.005"), ("radius", "0.023")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "mass" [("value", "0.015")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.0149999999999998e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "2.0149999999999998e-06"), ("iyz", "0"), ("izz", "3.9675e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hip"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "right_hip_qdd100_stator")] [],
.text "\n    ",
.element "child" [("link", "right_hip_qdd100_rotor")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0292")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "16.0"), ("lower", "-1.26"), ("upper", "1.26"), ("velocity", "28.8")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_hip_horn")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_horn.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.09"), ("radius", "0.025")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "mass" [("value", "0.05267")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.37819375e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.37819375e-05"), ("iyz", "0"), ("izz", "1.6459375000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_hip_horn_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_hip_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "right_hip_horn")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "right_femur")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.25"), ("radius", "0.011")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.26"), ("radius", "0.012")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.056")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.170666666666667e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "5.170666666666667e-06"), ("iyz", "0"), ("izz", "4.0320000000000005e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_femur_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_hip_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "right_femur")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.07 0.025")] [],
.text "\n  "],
.text "\n  \n  ",
.element "joint" [("name", "right_knee_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_femur")] [],
.text "\n    ",
.element "child" [("link", "right_knee_stator")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 -1.5707963267948966"), ("xyz", "0 0.042 -0.098")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_knee_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/knee_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0.03 0 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.06"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0.03 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.09874")] [],
.text "\n      ",
.element "inertia" [("ixx", "9.133450000000001e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "9.133450000000001e-05"), ("iyz", "0"), ("izz", "0.000123425")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_knee_qdd100_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.03"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "mass" [("value", "0.47")] [],
.text "\n      ",
.element "inertia" [("ixx", "0.00032900000000000003"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0.00032900000000000003"), ("iyz", "0"), ("izz", "0.0005875000000000001")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_knee_qdd100_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_knee_stator")] [],
.text "\n    ",
.element "child" [("link", "right_knee_qdd100_stator")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.5707963267948966 0 1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_knee"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "right_knee_qdd100_stator")] [],
.text "\n    ",
.element "child" [("link", "right_knee_qdd100_rotor")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0292")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "16.0"), ("lower", "-2.51"), ("upper", "2.51"), ("velocity", "28.8")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_knee_qdd100_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_rotor.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.005"), ("radius", "0.023")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0025")] [],
.text "\n      ",
.element "mass" [("value", "0.015")] [],
.text "\n      ",
.element "inertia" [("ixx", "2.0149999999999998e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "2.0149999999999998e-06"), ("iyz", "0"), ("izz", "3.9675e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_knee_horn")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/qdd100_horn.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.09"), ("radius", "0.025")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 1.5707963267948966 0"), ("xyz", "0 0 0.025")] [],
.text "\n      ",
.element "mass" [("value", "0.05267")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.37819375e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.37819375e-05"), ("iyz", "0"), ("izz", "1.6459375000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_knee_horn_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_knee_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "right_knee_horn")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 1.5707963267948966"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "right_tibia")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.25"), ("radius", "0.011")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.26"), ("radius", "0.012")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_wood")] [],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.056")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.170666666666667e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "5.170666666666667e-06"), ("iyz", "0"), ("izz", "4.0320000000000005e-06")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_tibia_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_knee_qdd100_rotor")] [],
.text "\n    ",
.element "child" [("link", "right_tibia")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0.07 0.025")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "right_ankle_base")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/ankle_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "chalky_blue")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.002 0.0275")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.092 0.068 0.056")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.002 0.0275")] [],
.text "\n      ",
.element "mass" [("value", "0.07863")] [],
.text "\n      ",
.element "inertia" [("ixx", "5.084740000000002e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "7.6009e-05"), ("iyz", "0"), ("izz", "8.575912e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ankle_base_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_tibia")] [],
.text "\n    ",
.element "child" [("link", "right_ankle_base")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.034 -0.105")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ankle_plate")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.08 0.045 0.003")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "light_gray")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0.09 0.046 0.004")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.02")] [],
.text "\n      ",
.element "inertia" [("ixx", "3.5533333333333333e-06"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.3526666666666667e-05"), ("iyz", "0"), ("izz", "1.7026666666666667e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ankle_plate_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ankle_base")] [],
.text "\n    ",
.element "child" [("link", "right_ankle_plate")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.0015")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ankle_mj5208_stator")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/mj5208_stator.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "mj5208_stator")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.018"), ("radius", "0.03")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.01")] [],
.text "\n      ",
.element "mass" [("value", "0.1721")] [],
.text "\n      ",
.element "inertia" [("ixx", "4.3369200000000005e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "4.3369200000000005e-05"), ("iyz", "0"), ("izz", "7.7445e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_ankle_mj5208_stator_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ankle_plate")] [],
.text "\n    ",
.element "child" [("link", "right_ankle_mj5208_stator")] [],
.text "\n    ",
.element "origin" [("rpy", "3.141592653589793 0 0"), ("xyz", "0 0 -0.0015")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_anchor")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_anchor_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ankle_mj5208_stator")] [],
.text "\n    ",
.element "child" [("link", "right_anchor")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.0545 0.048")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_ankle_mj5208_rotor")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/mjbots/mj5208_rotor.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "mj5208_rotor")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.016"), ("radius", "0.034")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.015")] [],
.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.551666666666667e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.551666666666667e-05"), ("iyz", "0"), ("izz", "2.8900000000000005e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_wheel"), ("type", "revolute")] [.text "\n    ",
.element "parent" [("link", "right_ankle_mj5208_stator")] [],
.text "\n    ",
.element "child" [("link", "right_ankle_mj5208_rotor")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n    \n    ",
.element "axis" [("xyz", "0 0 -1")] [],
.text "\n    ",
.element "limit" [("effort", "1.7"), ("velocity", "111.0")] [],
.text "\n  "],
.text "\n  \n  ",
.element "link" [("name", "right_wheel_hub")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/wheel_hub.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "terracotta_light")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0125")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.025"), ("radius", "0.039")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0125")] [],
.text "\n      ",
.element "mass" [("value", "0.0454")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.9627933333333332e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "1.9627933333333332e-05"), ("iyz", "0"), ("izz", "3.45267e-05")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_wheel_hub_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_ankle_mj5208_rotor")] [],
.text "\n    ",
.element "child" [("link", "right_wheel_hub")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0251")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_wheel_tire")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "package://upkie_description/meshes/wheel_tire/wheel_tire.stl")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "dark_gray")] [],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.04"), ("radius", "0.05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "mass" [("value", "0.08715")] [],
.text "\n      ",
.element "inertia" [("ixx", "6.608875000000002e-05"), ("ixy", "0"), ("ixz", "0"), ("iyy", "6.608875000000002e-05"), ("iyz", "0"), ("izz", "0.00010893750000000003")] [],
.text "\n    "],
.text "\n    ",
.element "contact" [] [.text "\n      ",
.element "lateral_friction" [("value", "1.0")] [],
.text "\n      ",
.element "rolling_friction" [("value", "0.01")] [],
.text "\n      ",
.element "stiffness" [("value", "30000")] [],
.text "\n      ",
.element "damping" [("value", "1000")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_wheel_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_wheel_hub")] [],
.text "\n    ",
.element "child" [("link", "right_wheel_tire")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.0209")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_contact")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_contact_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_wheel_tire")] [],
.text "\n    ",
.element "child" [("link", "right_contact")] [],
.text "\n    \n    \n    ",
.element "origin" [("rpy", "1.5707963267948966 0 0"), ("xyz", "0 0.047 0")] [],
.text "\n  "],
.text "\n  ",
.element "link" [("name", "right_wheel_center")] [.text "\n    \n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", "0 0 0")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.001")] [],
.text "\n      ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "\n      ",
.element "inertia" [("ixx", "0"), ("ixy", "0"), ("ixz", "0"), ("iyy", "0"), ("iyz", "0"), ("izz", "0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "right_wheel_center_fix"), ("type", "fixed")] [.text "\n    ",
.element "parent" [("link", "right_wheel_tire")] [],
.text "\n    ",
.element "child" [("link", "right_wheel_center")] [],
.text "\n    ",
.element "origin" [("rpy", "1.5707963267948966 3.141592653589793 0"), ("xyz", "0 0 0")] [],
.text "\n  "],
.text "\n"],
[],
[],
"d15965215067276203599a850e5c7ebb319ed6815506f0a2721dae78abac2483"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
