import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "anymal"), ("xmlns:xacro", "http://www.ros.org/wiki/xacro")] [.text "  \n      \n    ",
.element "material" [("name", "anymal_material")] [.text "    \n        ",
.element "color" [("rgba", "0.7 0.7 0.7 1.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "base")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_base.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0.08")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.531 0.27 0.24")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.227 0.116 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.05")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.227 -0.116 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.05")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.227 0.116 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.05")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.227 -0.116 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.05")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.2155 0.0 -0.09")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.1 0.1 0.07")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.2155 0.0 -0.09")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.1 0.1 0.07")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.09")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.531 0.02 0.07")] [],
.text "      \n            "],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "base_to_base_inertia"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "base")] [],
.text "    \n        ",
.element "child" [("link", "base_inertia")] [],
.text "    \n        ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "base_inertia")] [.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.001960558279 -0.001413217745 0.050207125344")] [],
.text "      \n            ",
.element "mass" [("value", "16.793507758")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.217391101503"), ("ixy", "-0.00132873239126"), ("ixz", "-0.00228200226173"), ("iyy", "0.639432546734"), ("iyz", "-0.00138078263145"), ("izz", "0.62414077654")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "LF_HIP")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_hip_l.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0635 -0.009 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.08")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0635 -0.074 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.03"), ("radius", "0.045")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.064516258147 -0.003787101702 -0.000152184388")] [],
.text "      \n            ",
.element "mass" [("value", "1.42462064")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00243023349564"), ("ixy", "-1.53023971e-05"), ("ixz", "-2.1819095354e-05"), ("iyy", "0.00230257239103"), ("iyz", "2.6473021273e-05"), ("izz", "0.0019806759227")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LF_HAA"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "base")] [],
.text "    \n        ",
.element "child" [("link", "LF_HIP")] [],
.text "    \n        ",
.element "origin" [("xyz", "0.277 0.116 0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "LF_THIGH")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_thigh_l.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0.145 0 0"), ("xyz", "0 0.035 -0.125")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.04 0.25")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0 0.069 -0.25")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.06")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.71579632679 0 0"), ("xyz", "0 -0.005 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.066")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003897968082 0.054226618537 -0.214583373795")] [],
.text "      \n            ",
.element "mass" [("value", "1.634976467")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0120367944369"), ("ixy", "6.762065206e-05"), ("ixz", "0.000287806340448"), ("iyy", "0.0120643637939"), ("iyz", "-0.00140610131218"), ("izz", "0.00249422574881")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LF_HFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "LF_HIP")] [],
.text "    \n        ",
.element "child" [("link", "LF_THIGH")] [],
.text "    \n        ",
.element "origin" [("xyz", "0.0635                    0.041                    0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "LF_SHANK")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_shank_l.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.065 -0.015 0.01")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.07 0.13")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.030816858139 -0.004617229294 0.000893125713")] [],
.text "      \n            ",
.element "mass" [("value", "0.207204302")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0002104880248"), ("ixy", "-5.6750980345e-05"), ("ixz", "1.0127699391e-05"), ("iyy", "0.000676270210023"), ("iyz", "-8.22869024e-07"), ("izz", "0.000545032674924")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LF_KFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "LF_THIGH")] [],
.text "    \n        ",
.element "child" [("link", "LF_SHANK")] [],
.text "    \n        ",
.element "origin" [("xyz", "0.0 0.109 -0.25")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LF_SHANK_TO_ADAPTER"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "LF_SHANK")] [],
.text "    \n        ",
.element "child" [("link", "LF_ADAPTER")] [],
.text "    \n        ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.1 -0.02 0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "LF_ADAPTER")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0.032")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_foot.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.160625")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.32125"), ("radius", "0.015")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-8.66e-10 -1.472e-09 -0.244345749188")] [],
.text "      \n            ",
.element "mass" [("value", "0.140170767")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00159938741862"), ("ixy", "-9.32e-13"), ("ixz", "1.039e-11"), ("iyy", "0.00159938741932"), ("iyz", "1.7563e-11"), ("izz", "5.4423177329e-05")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LF_ADAPTER_TO_FOOT"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "LF_ADAPTER")] [],
.text "    \n        ",
.element "child" [("link", "LF_FOOT")] [],
.text "    \n        ",
.element "origin" [("rpy", "0.0 0.0 0.0"), ("xyz", "0.0 0.0 -0.32125")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "LF_FOOT")] [.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("xyz", "0 0 0.02325")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "sphere" [("radius", "0.031")] [],
.text "      \n            "],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "gazebo" [("reference", "LF_FOOT")] [.text "    \n        ",
.element "kp" [] [.text "1000000.0"],
.text "    \n        ",
.element "kd" [] [.text "100.0"],
.text "    \n        ",
.element "mu1" [] [.text "0.8"],
.text "    \n        ",
.element "mu2" [] [.text "0.8"],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "RF_HIP")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_hip_r.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0635 0.009 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.08")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0635 0.074 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.03"), ("radius", "0.045")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.064516258147 0.003787101702 -0.000152184388")] [],
.text "      \n            ",
.element "mass" [("value", "1.42462064")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00243023349564"), ("ixy", "1.53023971e-05"), ("ixz", "-2.1819095354e-05"), ("iyy", "0.00230257239103"), ("iyz", "-2.6473021273e-05"), ("izz", "0.0019806759227")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RF_HAA"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "base")] [],
.text "    \n        ",
.element "child" [("link", "RF_HIP")] [],
.text "    \n        ",
.element "origin" [("xyz", "0.277 -0.116 0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "RF_THIGH")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_thigh_r.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-0.145 0 0"), ("xyz", "0 -0.035 -0.125")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.04 0.25")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0 -0.069 -0.25")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.06")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-1.71579632679 0 0"), ("xyz", "0 0.005 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.066")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.003897968082 -0.054226618537 -0.214583373795")] [],
.text "      \n            ",
.element "mass" [("value", "1.634976467")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0120367944369"), ("ixy", "-6.762065206e-05"), ("ixz", "0.000287806340448"), ("iyy", "0.0120643637939"), ("iyz", "0.00140610131218"), ("izz", "0.00249422574881")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RF_HFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "RF_HIP")] [],
.text "    \n        ",
.element "child" [("link", "RF_THIGH")] [],
.text "    \n        ",
.element "origin" [("xyz", "0.0635                    -0.041                    0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "RF_SHANK")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_shank_r.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "0.065 0.015 0.01")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.07 0.13")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.030816858139 0.004617229294 0.000893125713")] [],
.text "      \n            ",
.element "mass" [("value", "0.207204302")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0002104880248"), ("ixy", "5.6750980345e-05"), ("ixz", "1.0127699391e-05"), ("iyy", "0.000676270210023"), ("iyz", "8.22869024e-07"), ("izz", "0.000545032674924")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RF_KFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "RF_THIGH")] [],
.text "    \n        ",
.element "child" [("link", "RF_SHANK")] [],
.text "    \n        ",
.element "origin" [("xyz", "0.0 -0.109 -0.25")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RF_SHANK_TO_ADAPTER"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "RF_SHANK")] [],
.text "    \n        ",
.element "child" [("link", "RF_ADAPTER")] [],
.text "    \n        ",
.element "origin" [("rpy", "-0.0 0.0 -0.0"), ("xyz", "0.1 0.02 0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "RF_ADAPTER")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0.0"), ("xyz", "0 0 0.032")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_foot.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.160625")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.32125"), ("radius", "0.015")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-8.66e-10 -1.472e-09 -0.244345749188")] [],
.text "      \n            ",
.element "mass" [("value", "0.140170767")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00159938741862"), ("ixy", "-9.32e-13"), ("ixz", "1.039e-11"), ("iyy", "0.00159938741932"), ("iyz", "1.7563e-11"), ("izz", "5.4423177329e-05")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RF_ADAPTER_TO_FOOT"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "RF_ADAPTER")] [],
.text "    \n        ",
.element "child" [("link", "RF_FOOT")] [],
.text "    \n        ",
.element "origin" [("rpy", "-0.0 0.0 -0.0"), ("xyz", "0.0 -0.0 -0.32125")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "RF_FOOT")] [.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("xyz", "0 0 0.02325")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "sphere" [("radius", "0.031")] [],
.text "      \n            "],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "gazebo" [("reference", "RF_FOOT")] [.text "    \n        ",
.element "kp" [] [.text "1000000.0"],
.text "    \n        ",
.element "kd" [] [.text "100.0"],
.text "    \n        ",
.element "mu1" [] [.text "0.8"],
.text "    \n        ",
.element "mu2" [] [.text "0.8"],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "LH_HIP")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_hip_r.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "-0.0635 -0.009 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.08")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "-0.0635 -0.074 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.03"), ("radius", "0.045")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.064516258147 -0.003787101702 -0.000152184388")] [],
.text "      \n            ",
.element "mass" [("value", "1.42462064")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00243023349564"), ("ixy", "1.53023971e-05"), ("ixz", "2.1819095354e-05"), ("iyy", "0.00230257239103"), ("iyz", "2.6473021273e-05"), ("izz", "0.0019806759227")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LH_HAA"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "base")] [],
.text "    \n        ",
.element "child" [("link", "LH_HIP")] [],
.text "    \n        ",
.element "origin" [("xyz", "-0.277 0.116 0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "LH_THIGH")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_thigh_r.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "0.145 0 0"), ("xyz", "0 0.035 -0.125")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.04 0.25")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0 0.069 -0.25")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.06")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.71579632679 0 0"), ("xyz", "0 -0.005 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.066")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.003897968082 0.054226618537 -0.214583373795")] [],
.text "      \n            ",
.element "mass" [("value", "1.634976467")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0120367944369"), ("ixy", "-6.762065206e-05"), ("ixz", "-0.000287806340448"), ("iyy", "0.0120643637939"), ("iyz", "-0.00140610131218"), ("izz", "0.00249422574881")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LH_HFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "LH_HIP")] [],
.text "    \n        ",
.element "child" [("link", "LH_THIGH")] [],
.text "    \n        ",
.element "origin" [("xyz", "-0.0635                    0.041                    0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "LH_SHANK")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_shank_r.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.065 -0.015 0.01")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.07 0.13")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.030816858139 -0.004617229294 0.000893125713")] [],
.text "      \n            ",
.element "mass" [("value", "0.207204302")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0002104880248"), ("ixy", "5.6750980345e-05"), ("ixz", "-1.0127699391e-05"), ("iyy", "0.000676270210023"), ("iyz", "-8.22869024e-07"), ("izz", "0.000545032674924")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LH_KFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "LH_THIGH")] [],
.text "    \n        ",
.element "child" [("link", "LH_SHANK")] [],
.text "    \n        ",
.element "origin" [("xyz", "-0.0 0.109 -0.25")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LH_SHANK_TO_ADAPTER"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "LH_SHANK")] [],
.text "    \n        ",
.element "child" [("link", "LH_ADAPTER")] [],
.text "    \n        ",
.element "origin" [("rpy", "0.0 -0.0 -0.0"), ("xyz", "-0.1 -0.02 0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "LH_ADAPTER")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0.032")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_foot.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.160625")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.32125"), ("radius", "0.015")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-8.66e-10 -1.472e-09 -0.244345749188")] [],
.text "      \n            ",
.element "mass" [("value", "0.140170767")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00159938741862"), ("ixy", "-9.32e-13"), ("ixz", "1.039e-11"), ("iyy", "0.00159938741932"), ("iyz", "1.7563e-11"), ("izz", "5.4423177329e-05")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "LH_ADAPTER_TO_FOOT"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "LH_ADAPTER")] [],
.text "    \n        ",
.element "child" [("link", "LH_FOOT")] [],
.text "    \n        ",
.element "origin" [("rpy", "0.0 -0.0 -0.0"), ("xyz", "-0.0 0.0 -0.32125")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "LH_FOOT")] [.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("xyz", "0 0 0.02325")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "sphere" [("radius", "0.031")] [],
.text "      \n            "],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "gazebo" [("reference", "LH_FOOT")] [.text "    \n        ",
.element "kp" [] [.text "1000000.0"],
.text "    \n        ",
.element "kd" [] [.text "100.0"],
.text "    \n        ",
.element "mu1" [] [.text "0.8"],
.text "    \n        ",
.element "mu2" [] [.text "0.8"],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "RH_HIP")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_hip_l.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "-0.0635 0.009 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.1"), ("radius", "0.08")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-1.57079632679 0 0"), ("xyz", "-0.0635 0.074 0.0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.03"), ("radius", "0.045")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.064516258147 0.003787101702 -0.000152184388")] [],
.text "      \n            ",
.element "mass" [("value", "1.42462064")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00243023349564"), ("ixy", "-1.53023971e-05"), ("ixz", "2.1819095354e-05"), ("iyy", "0.00230257239103"), ("iyz", "-2.6473021273e-05"), ("izz", "0.0019806759227")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RH_HAA"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "base")] [],
.text "    \n        ",
.element "child" [("link", "RH_HIP")] [],
.text "    \n        ",
.element "origin" [("xyz", "-0.277 -0.116 0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "1 0 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "RH_THIGH")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_thigh_l.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-0.145 0 0"), ("xyz", "0 -0.035 -0.125")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.04 0.25")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "1.57079632679 0 0"), ("xyz", "0.0 -0.069 -0.25")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.06")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n                  \n            ",
.element "origin" [("rpy", "-1.71579632679 0 0"), ("xyz", "0 0.005 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.12"), ("radius", "0.066")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.003897968082 -0.054226618537 -0.214583373795")] [],
.text "      \n            ",
.element "mass" [("value", "1.634976467")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0120367944369"), ("ixy", "6.762065206e-05"), ("ixz", "-0.000287806340448"), ("iyy", "0.0120643637939"), ("iyz", "0.00140610131218"), ("izz", "0.00249422574881")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RH_HFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "RH_HIP")] [],
.text "    \n        ",
.element "child" [("link", "RH_THIGH")] [],
.text "    \n        ",
.element "origin" [("xyz", "-0.0635                    -0.041                    0.0")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n    ",
.element "link" [("name", "RH_SHANK")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_shank_l.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 1.57079632679 0"), ("xyz", "-0.065 0.015 0.01")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "box" [("size", "0.08 0.07 0.13")] [],
.text "      \n            "],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-0.030816858139 0.004617229294 0.000893125713")] [],
.text "      \n            ",
.element "mass" [("value", "0.207204302")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.0002104880248"), ("ixy", "-5.6750980345e-05"), ("ixz", "-1.0127699391e-05"), ("iyy", "0.000676270210023"), ("iyz", "8.22869024e-07"), ("izz", "0.000545032674924")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RH_KFE"), ("type", "revolute")] [.text "    \n        ",
.element "parent" [("link", "RH_THIGH")] [],
.text "    \n        ",
.element "child" [("link", "RH_SHANK")] [],
.text "    \n        ",
.element "origin" [("xyz", "-0.0 -0.109 -0.25")] [],
.text "    \n        ",
.element "axis" [("xyz", "0 1 0")] [],
.text "    \n        ",
.element "limit" [("command_effort", "40"), ("current", "10"), ("effort", "80"), ("gear_velocity", "10"), ("lower", "-9.42"), ("upper", "9.42"), ("velocity", "15.0")] [],
.text "    \n        ",
.element "dynamics" [("damping", "0.0"), ("friction", "0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RH_SHANK_TO_ADAPTER"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "RH_SHANK")] [],
.text "    \n        ",
.element "child" [("link", "RH_ADAPTER")] [],
.text "    \n        ",
.element "origin" [("rpy", "-0.0 -0.0 0.0"), ("xyz", "-0.1 0.02 0.0")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "RH_ADAPTER")] [.text "    \n        ",
.element "visual" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 -3.14159265359"), ("xyz", "0 0 0.032")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "mesh" [("filename", "package://anymal_b_simple_description/meshes/anymal_foot.dae"), ("scale", "0.001 0.001     0.001")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0 -0.160625")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "cylinder" [("length", "0.32125"), ("radius", "0.015")] [],
.text "      \n            "],
.text "      \n            ",
.element "material" [("name", "anymal_material")] [],
.text "    \n        "],
.text "    \n        ",
.element "inertial" [] [.text "      \n            ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "-8.66e-10 -1.472e-09 -0.244345749188")] [],
.text "      \n            ",
.element "mass" [("value", "0.140170767")] [],
.text "      \n            ",
.element "inertia" [("ixx", "0.00159938741862"), ("ixy", "-9.32e-13"), ("ixz", "1.039e-11"), ("iyy", "0.00159938741932"), ("iyz", "1.7563e-11"), ("izz", "5.4423177329e-05")] [],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "joint" [("name", "RH_ADAPTER_TO_FOOT"), ("type", "fixed")] [.text "    \n        ",
.element "parent" [("link", "RH_ADAPTER")] [],
.text "    \n        ",
.element "child" [("link", "RH_FOOT")] [],
.text "    \n        ",
.element "origin" [("rpy", "-0.0 -0.0 0.0"), ("xyz", "-0.0 -0.0 -0.32125")] [],
.text "  \n    "],
.text "  \n      \n    ",
.element "link" [("name", "RH_FOOT")] [.text "    \n        ",
.element "collision" [] [.text "      \n            ",
.element "origin" [("xyz", "0 0 0.02325")] [],
.text "      \n            ",
.element "geometry" [] [.text "        \n                ",
.element "sphere" [("radius", "0.031")] [],
.text "      \n            "],
.text "    \n        "],
.text "  \n    "],
.text "  \n      \n    ",
.element "gazebo" [("reference", "RH_FOOT")] [.text "    \n        ",
.element "kp" [] [.text "1000000.0"],
.text "    \n        ",
.element "kd" [] [.text "100.0"],
.text "    \n        ",
.element "mu1" [] [.text "0.8"],
.text "    \n        ",
.element "mu2" [] [.text "0.8"],
.text "  \n    "],
.text "  \n"],
[],
[],
"8e037a1da8d76cdd81b3aa530b05f2e0a7e582d9895abc114f7ff6fb2f252b75"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
