import FluxKernel.UrdfDocument
open FluxKernel.UrdfDocument
set_option maxRecDepth 16384
set_option maxHeartbeats 16000000
def robotDocument : Document := ⟨
.element "robot" [("name", "quadruped")] [.text "\n  ",
.element "link" [("name", "base_chassis_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".33 0.10 .07")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.3 0.3 0.3 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "visual" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.10 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".17 0.10 .05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.3 0.3 0.3 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n\t\t",
.element "visual" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.10 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".17 0.10 .05")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "black")] [.text "\n        ",
.element "color" [("rgba", "0.3 0.3 0.3 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".33 0.10 .07")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.10 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".17 0.10 .05")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.10 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".17 0.10 .05")] [],
.text "\n      "],
.text "\n    "],
.text "\n\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "3")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "chassis_right")] [.text "\n    ",
.element "visual" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n\t\t\t",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "    "],
.text "\n    ",
.element "visual" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n\t\t\t",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "    "],
.text "\n    ",
.element "collision" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "chassis_right_center"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "base_chassis_link")] [],
.text "\n    ",
.element "child" [("link", "chassis_right")] [],
.text "\n    ",
.element "origin" [("rpy", "-0.0872665 0 0"), ("xyz", "0.0 -0.10 0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n  ",
.element "link" [("name", "chassis_left")] [.text "\n    ",
.element "visual" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n\t\t\t",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "    "],
.text "\n    ",
.element "visual" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n\t\t\t",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "    "],
.text "\n    ",
.element "collision" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n\t\t\t",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0 -0.035 0")] [],
.text "\n      ",
.element "geometry" [] [.text "\n       ",
.element "box" [("size", ".34 0.01 .04")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", ".1")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n\n  ",
.element "joint" [("name", "chassis_left_center"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "base_chassis_link")] [],
.text "\n    ",
.element "child" [("link", "chassis_left")] [],
.text "\n    ",
.element "origin" [("rpy", "0.0872665 0 0"), ("xyz", "0.0 0.10 0.0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n  \n  \n  ",
.element "link" [("name", "motor_front_rightR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_front_rightR_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_right")] [],
.text "\n    ",
.element "child" [("link", "motor_front_rightR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 0"), ("xyz", "0.21 -0.025 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\t",
.element "link" [("name", "motor_front_rightL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_front_rightL_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_right")] [],
.text "\n    ",
.element "child" [("link", "motor_front_rightL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 3.141592"), ("xyz", "0.21 0.04 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "motor_front_leftL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_front_leftL_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_left")] [],
.text "\n    ",
.element "child" [("link", "motor_front_leftL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 3.141592"), ("xyz", "0.21 0.025 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\t",
.element "link" [("name", "motor_front_leftR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_front_leftR_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_left")] [],
.text "\n    ",
.element "child" [("link", "motor_front_leftR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 0"), ("xyz", "0.21 -0.04 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "motor_back_rightR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_back_rightR_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_right")] [],
.text "\n    ",
.element "child" [("link", "motor_back_rightR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 0"), ("xyz", "-0.21 -0.025 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\t",
.element "link" [("name", "motor_back_rightL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_back_rightL_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_right")] [],
.text "\n    ",
.element "child" [("link", "motor_back_rightL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 3.141592"), ("xyz", "-0.21 0.04 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  \n  \n  ",
.element "link" [("name", "motor_back_leftL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_back_leftL_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_left")] [],
.text "\n    ",
.element "child" [("link", "motor_back_leftL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 3.141592"), ("xyz", "-0.21 0.025 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\t",
.element "link" [("name", "motor_back_leftR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "mesh" [("filename", "tmotor3.obj"), ("scale", "1 1 1")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "white")] [.text "\n        ",
.element "color" [("rgba", "1 1 1 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "cylinder" [("length", "0.026"), ("radius", "0.0434")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.25")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_back_leftR_joint"), ("type", "continuous")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "chassis_left")] [],
.text "\n    ",
.element "child" [("link", "motor_back_leftR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "1.57075 0 0"), ("xyz", "-0.21 -0.04 0")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\t",
.element "link" [("name", "upper_leg_front_rightR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "hip_front_rightR_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_front_rightR_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_front_rightR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\t",
.element "link" [("name", "lower_leg_front_rightR_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_front_rightR_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_front_rightR_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_front_rightR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n    \n  ",
.element "link" [("name", "upper_leg_front_rightL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_front_rightL_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_front_rightL_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_front_rightL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n  \n\n  \n  ",
.element "link" [("name", "lower_leg_front_rightL_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .198")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .198")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_front_rightL_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_front_rightL_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_front_rightL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\t",
.element "link" [("name", "upper_leg_front_leftR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "hip_front_leftR_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_front_leftR_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_front_leftR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\t",
.element "link" [("name", "lower_leg_front_leftR_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0.0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0.0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_front_leftR_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_front_leftR_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_front_leftR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\n   ",
.element "link" [("name", "upper_leg_front_leftL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_front_leftL_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_front_leftL_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_front_leftL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n  ",
.element "link" [("name", "lower_leg_front_leftL_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0.0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .198")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0.0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .198")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_front_leftL_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_front_leftL_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_front_leftL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  \n\t",
.element "link" [("name", "upper_leg_back_rightR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "hip_rightR_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_back_rightR_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_back_rightR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\t",
.element "link" [("name", "lower_leg_back_rightR_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2032")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2032")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_back_rightR_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_back_rightR_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_back_rightR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n    \n  ",
.element "link" [("name", "upper_leg_back_rightL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_back_rightL_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_back_rightL_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_back_rightL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n  \n\n  \n  ",
.element "link" [("name", "lower_leg_back_rightL_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n  \n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_back_rightL_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_back_rightL_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_back_rightL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n\n\n\t",
.element "link" [("name", "upper_leg_back_leftR_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "hip_leftR_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_back_leftR_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_back_leftR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n",
.element "link" [("name", "lower_leg_back_leftR_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2032")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2032")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_back_leftR_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_back_leftR_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_back_leftR_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n  \n   ",
.element "link" [("name", "upper_leg_back_leftL_link")] [.text "\n    ",
.element "visual" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .11")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "motor_back_leftL_link"), ("type", "fixed")] [.text "\n    ",
.element "axis" [("xyz", "0 0 1")] [],
.text "\n    ",
.element "parent" [("link", "motor_back_leftL_link")] [],
.text "\n    ",
.element "child" [("link", "upper_leg_back_leftL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "-1.57075 0 0"), ("xyz", "0.0 0.06 -0.015")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n\n \n  ",
.element "link" [("name", "lower_leg_back_leftL_link")] [.text "\n\t",
.element "contact" [] [.text "\n\t\t",
.element "stiffness" [("value", "10000")] [],
.text "\n\t\t",
.element "damping" [("value", "10")] [],
.text "\n\t\t",
.element "lateral_friction" [("value", "1")] [],
.text "\n  "],
.text "\n\n    ",
.element "visual" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n      ",
.element "material" [("name", "grey")] [.text "\n        ",
.element "color" [("rgba", "0.65 0.65 0.75 1")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "collision" [] [.text "\n    \t",
.element "origin" [("rpy", "0.0 0 0"), ("xyz", "0 0 .1")] [],
.text "\n      ",
.element "geometry" [] [.text "\n        ",
.element "box" [("size", ".01 0.01 .2")] [],
.text "\n      "],
.text "\n    "],
.text "\n    ",
.element "inertial" [] [.text "\n      ",
.element "mass" [("value", "0.05")] [],
.text "\n      ",
.element "inertia" [("ixx", "1.0"), ("ixy", "0.0"), ("ixz", "0.0"), ("iyy", "1.0"), ("iyz", "0.0"), ("izz", "1.0")] [],
.text "\n    "],
.text "\n  "],
.text "\n  ",
.element "joint" [("name", "knee_back_leftL_link"), ("type", "revolute")] [.text "\n    ",
.element "axis" [("xyz", "0 1 0")] [],
.text "\n    ",
.element "parent" [("link", "upper_leg_back_leftL_link")] [],
.text "\n    ",
.element "child" [("link", "lower_leg_back_leftL_link")] [],
.text "\n    ",
.element "origin" [("rpy", "0 0 0"), ("xyz", "0.0 0.01 .055")] [],
.text "\n    ",
.element "limit" [("effort", "100"), ("velocity", "100")] [],
.text "\n    ",
.element "joint_properties" [("damping", "0.0"), ("friction", "0.0")] [],
.text "\n  "],
.text "\n \n"],
[],
[],
"ad71189162e6ff6d889c32dd4d982dfba3569170da85d087861b13d8904fdba7"
⟩
def main : IO Unit := IO.print (render robotDocument.root)
